### ISSUE TITLE
Replace bottom navigation bar icons

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client-anc#132]
Just seeing now that they look a bit pixelated. I'm referring to the clients, register, and library icons specifically.

**Comment by dubdabasoduba** [comment]
This is now done

**Comment by dubdabasoduba** [comment]
@cagulas the Initials do not use icons or svg's since its dynamic text and we have to draw an Icon dynamically on code. I will check it out and try to make it better.

**Comment by dubdabasoduba** [comment]
@rowo  yes we can use svg's for Icons. We might need to decide which method we are to use for devices below API level 20 but other than that, yes they are usable. https://developer.android.com/studio/write/vector-asset-studio

**Comment by faith-mutua** [comment]
lgtm.

**Comment by rowo** [comment]
Is this better now? Providing SVGs was on my list of to-do's

**Comment by rowo** [comment]
[SVG-tab-icons.zip](https://github.com/OpenSRP/opensrp-client-anc/files/2700144/SVG-tab-icons.zip) @dubdabasoduba

**Comment by cagulas** [comment]
Closing this issue and condensing all similar issues to here: https://github.com/OpenSRP/opensrp-client-anc/issues/163
