### ISSUE TITLE
Implement contact save and exit functionality

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client-anc#133]
This issue can be completed once the rest of the contact containers are finished.

- [x] The Save Changes option saves all of the data entered so far in the contact form and takes the user back to where she was before she entered the contact (either main register page or woman's profile view). On the main register page, the contact button changes to the orange status. If the user presses the orange contact button again, they are taken back to the main contact page to continue where the user left off.
- [x] The close without saving option clears all data the user has entered so far in the contact and takes the user back to where she started the contact from (main register page or woman's profile view). The contact button reverts to the status it was before the contact started.

**Comment by faith-mutua** [comment]
QA 20th Dec

lgtm

**Comment by cagulas** [comment]
Closing.
