### ISSUE TITLE
Start using the Android native barcode api instead of invoking another app

### ISSUE THREAD

**Issue by dubdabasoduba** [OpenSRP/opensrp-client-anc#137]
Currently in most on the OpenSRP apps we use the barcode services from another app. We have noticed that this fails at times. We need to start using the native barcode api provided by android. 

- [x] Change the anc toolbar scan QR functionality to use the native barcode api 
- [x] Change the native forms barcode scan in the registration page to also use the native barcode api

**Comment by dubdabasoduba** [comment]
This was close after the function was moved to core.

**Comment by cagulas** [comment]
QA 14 Dec 2018:

- [ ] This seems to prefix "http://" to the beginning of the ID when I use https://www.qr-code-generator.com/# tool, so it's failing to search the woman. Can you look into this? It should be reading  only the ID number.

**Comment by faith-mutua** [comment]
QA 20 Dec 2018: 
Got the same error as reported by @cagulas above.

**Comment by cagulas** [comment]
This is fixed now.
