### ISSUE TITLE
Implement side menu

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client-anc#14]
<img width="354" alt="screen shot 2018-07-06 at 11 10 27 am" src="https://user-images.githubusercontent.com/3488986/42367549-47006d32-810d-11e8-9c7a-b8a30b870c21.png">

- [x] Logged in user's first and last name
- [x] Logout button logs user out without clearing data
- [x] ANC clients opens the register list
- [x] Swiping from the right closes the side menu and takes the user back to the register list page
- [ ] Counseling resources is placeholder for counseling module
- [ ] Site characteristics is placeholder for site characteristics workflow
- [ ] (not shown) Population characteristics is placeholder for pop characteristics viewing
- [ ] Sync button does a manual sync in between automatic attempts, it should also show last successful sync date and time

**Comment by cagulas** [comment]
@rowo to finalize styling and format.

**Comment by cagulas** [comment]
@rowo I think you were thinking of removing the ANC clients from the side menu to support the new interaction with less clicks?

**Comment by rowo** [comment]
@cagulas I have a recommendation in the [initial walkthrough question issue](https://github.com/OpenSRP/opensrp-client-anc/issues/19#issuecomment-407564522) that will impact this one.

**Comment by rowo** [comment]
It's not final what items go in here yet (see discussion started in previous comment), but styling is similar to the ZEIR app:

![menu](https://user-images.githubusercontent.com/1584163/43278344-d8208df8-90d8-11e8-99d9-da9ab99b6eb1.png)

**Comment by cagulas** [comment]
@rowo So I think this won't be implemented anymore, right? Since we are moving to the bottom register menu.

**Comment by rowo** [comment]
@cagulas yes correct, I updated the marvel app where the bottom links are now: https://marvelapp.com/project/2823817/screen/46121628
