### ISSUE TITLE
Implement advanced search results

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client-anc#16]
<img width="414" alt="screen shot 2018-08-02 at 2 29 10 pm" src="https://user-images.githubusercontent.com/3488986/43603267-7288ae16-9660-11e8-919f-e23145da8811.png">

- [x] The advanced search results page shows the results from the advanced search page (https://github.com/OpenSRP/opensrp-client-anc/issues/15)
- [x] The back button (or tapping back button on the device) takes you back to the advanced search screen (https://github.com/OpenSRP/opensrp-client-anc/issues/15)
- [x] The grey results summary bar shows the number of results returned and the search criteria - similar to ZEIR where each search criteria is semi-colon separated (if more than one).
- [x] For all women, `first_name`, `last_name`, `age`, `gest_age`, and `anc_id` are displayed.
- [x] For in-area women (i.e. records are on the device) the `wom_image` is also shown. Tapping on this row opens the woman's profile view.
- [x] For out of area women, you cannot tap on the row, only the sync button that is displayed. Tapping sync will sync the woman's entire ANC record to the device. We do not need to un-sync the woman's record from the other health facility for this project. We can discuss if this will be an issue.
- [x] Unit Tests

**Comment by rowo** [comment]
@cagulas can you share some thoughts on why you'd like results to go into the main view?

**Comment by cagulas** [comment]
@rowo You actually said that. You said you didn't think there was a need to build a new view to display the search results and they would appear just as any search results in the main register view. Just going by what you said.

**Comment by rowo** [comment]
@cagulas Ok cool. I don't remember if I did mean it at the time or if it was a miscommunication. The extent I remember is about the QR code in this way and not needing to do that via Advanced Search. I don't think any decision on that was finalized. I'll just assign this to me and reassign when done since I don't think the results can show up in the register list with the filer stuff accessible (I mean it could but seems like more work).

**Comment by cagulas** [comment]
@rowo Ok cool. For the QR code search, we decided that we'd just re-use the flow from ZEIR, since it worked well, and we can recycle it easily. The important thing we emphasized was that they should be able to scan the QR code from the main register page no matter if it's an in or out of area search (i.e. same first step for every woman), and if it is out of area search, then it would automatically continue with an out of area search if no local results were found.

**Comment by cagulas** [comment]
QA 11th Oct build:

I have combined all QA results for this into the advanced search issue here: https://github.com/OpenSRP/opensrp-client-anc/issues/15

I still need to QA:
For out of area women, you cannot tap on the row, only the sync button that is displayed. Tapping sync will sync the woman's entire ANC record to the device. We do not need to un-sync the woman's record from the other health facility for this project. We can discuss if this will be an issue.

Waiting to be able to create another record on a different device with other user login.

**Comment by cagulas** [comment]
Closing this issue and creating a separate issue to implement support for the server-side support needed to sync out of area records.
