### ISSUE TITLE
Replace blurry icons throughout app

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client-anc#163]
I'm combining everything into this one issue, so it's easier to track what's left. @dubdabasoduba Please get what you need directly from @rowo 

- [ ] User's initials in the bottom navigation menu
- [x] OpenSRP logo on the main register page looks blurred
- [x] The red, yellow, blue and green info icons within the contact data entry forms are very blurry
- [x] Woman's pink avatar looks blurry
- [x] Done, ordered, and not done icons in the Tests container

**Comment by rowo** [comment]
@dubdabasoduba do you still need the other stuff on this list? Did we discuss just using an image instead of the bottom nav user initials?

**Comment by dubdabasoduba** [comment]
@rowo We did not discuss about having an image instead of the initials on the bottom nav. A for the other info icons we were to use the new info icon you sent and change its color when creating the drawables from the icon

**Comment by cagulas** [comment]
@dubdabasoduba and what about the OpenSRP logo? Let's get these all fixed in the next release.

**Comment by dubdabasoduba** [comment]
@cagulas We are working on fixing this UI issues so all this are currently being worked on

**Comment by dubdabasoduba** [comment]
@rowo What were your thoughts on using an image instead on the user initials on the bottom nav

**Comment by cagulas** [comment]
QA 28 January:

This looks great. I'm ok leaving the initials as is if it's a lot of work to fix.
