### ISSUE TITLE
QA fixes for PE contact container

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client-anc#167]
I'm condensing all QA for PE contact container here to make it easier, since #74 was getting too long.

**All sections:**
- [x] Move PE title closer to the left hand contact icon
- [x] Fix all cells highlighted in bright pink in the data dictionary which were not done correctly or missed.
- [x] Info icons are appearing higher than the question label in all of the contact containers. They should be even.

**Maternal Exam:**
- [x] Add space between each abnormal reason. Also, can we somehow get the abnormal reasons to go to the next line right underneath Abnormal instead of all right-aligned? See screenshot below:

![screenshot_20181227-161036](https://user-images.githubusercontent.com/3488986/50481504-f0e84400-09f2-11e9-9c11-aa8653f74a75.png)

- [x] As soon as the user selects "abnormal", can the pop-up with abnormal reasons pop-up immediately (for all of these questions)? Right now, the user has to select Abnormal and then select specify to open it.
- [x] The Cancel and Done buttons on these pop-ups should be larger font and don't need to be bolded. 
- [x] The abnormal reasons selected do not persist when you re-open the popup. Same goes for cm dilated.
- [x] The page jumps around a bit when you close the popups and when you answer the questions, and you have to scroll back to where you left off, which is a bit disorienting.
- [x] If possible, the popup should shift upwards when the keypad pops up, so the cancel and done buttons are still shown.
- [x] I can't move on to the fetal assessment section, because I keep getting an error message about the cervical dilation

**Fetal Assessment:**
- [ ] Is it possible to include the constraint messages in line with the popup widgets? E.g. heartbeat rate constraint isn't shown until you're trying to move on from the page instead of right after you enter it.
- [x] When showing fetal heart rate in parentheses, can we include "bpm" after the number so they know the unit?
- [x] No. of fetuses unknown checkbox is too close to the No. of fetuses question.
- [x] Same issues with the select a number widget as reported in the obstetric history section. I assume if you change the widget in one place, it changes in other places, but let me know if otherwise.

**Comment by cagulas** [comment]
**QA 14 Jan release:**

- [ ] The Cancel and Done buttons on the abnormal pop-ups should be medium font, not bolded.
- [ ] The specify, specify type, specify cm cervix dilated, and tap to change italic labels appear to be sitting lower than the answer choice label they are associated with; Can we try to make them more aligned?
- [ ] Can we add a bit more space between the temp, pulse rate, bp boxes, etc. and the question labels? They look to be only just barely not touching.
- [ ] Can we align the abnormal reasons with the Abnormal answer choice label? Right now the reasons appear to be ever so slightly more indented.
- [ ] When you select the tap to change option, the Abnormal answer choice briefly becomes un-selected. If this will improve when we try to optimize performance, that's fine.
- [ ] Let's add more spacing between the answer choices and the question labels as well. See https://github.com/OpenSRP/opensrp-client-anc/issues/74 for guidance on how much spacing is good to use. An example of good spacing in this section is Fetal presentation. No. of fetuses is an example of not enough spacing.
- [ ] At some point after selecting "abnormal" for any of the woman's exams, if you revisit the screen, the "Abnormal" answer choice label disappears, but the radio button and the tap to change and any selected reasons remain.
- [ ] None of the abnormal toaster messages are appearing for maternal exam questions.
- [ ] For number of cms dilated, can we include "cm" (the unit) in the label that appears? Right now it's just a number.
- [ ] I've rechecked the data dictionary and updated the pink highlighting. Pls check out the highlighting for fields that still have issues.
- [ ] When a dialog re-opens with the answer pre-filled, it would be helpful if the cursor is at the end of the data input. Right now, it's at the beginning, and you need to adjust the cursor before you can edit the field.
- [ ] I'm still getting the constraint message about the cervix dilated and it's not alloowing me to continue to fetal assessment page.

**Also moving all previous QA, from above that is not finished yet, into this comment, so everything is here in this one comment:**

- [ ] Is it possible to include the constraint messages in line with the popup widgets? E.g. heartbeat rate constraint isn't shown until you're trying to move on from the page instead of right after you enter it.
- [ ] When showing fetal heart rate in parentheses, can we include "bpm" after the number so they know the unit?

**Comment by dubdabasoduba** [comment]
@cagulas `* When you select the tap to change option, the Abnormal answer choice briefly becomes un-selected. If this will improve when we try to optimize performance, that's fine.` The reason for the un-select is to re-trigger the popup launch. This is due to the  requirement for the `tap to change` text click to also select the radio button. We made the `tap to change` to use the radio button's click events, so in-case a radio button was selected before we need to  un-select it then perform a click for the popup to launch.

**Comment by cagulas** [comment]
Done.
