### ISSUE TITLE
Implement site characteristic configuration walkthrough on first login

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client-anc#18]
There are a list of 4 site characteristics that the first user to log in from a facility will need to set before they can start using the app. These characteristics are binary (1 = yes, 0 = no) and need to be available for calculations and logic in the contact workflow, whether the user is online or offline.

- [x] Screen that the first user from a health facility to log in will see (this appears right after login page):
<img src="https://user-images.githubusercontent.com/1584163/43215474-3f0610d0-900a-11e8-9e5e-c0abaa34c9c0.png" width="400">

- [x] Image is placeholder only for now. @rowo will provide an image sometime in mid-August.
- [x] Pressing continue takes the user to the next screen, below.
- [x] All questions are required, so the user must answer all questions for the Save button to be active and clickable.

<img src="https://user-images.githubusercontent.com/1584163/43215479-43c7dbbc-900a-11e8-93f3-fcf3241f38a1.png" width="400">

- [x] All questions are answered, so the Save button is active and clickable.
<img src="https://user-images.githubusercontent.com/1584163/43215529-6316f368-900a-11e8-9694-37876a227eb9.png" width="400">

- [x] Once the site characteristics are initially set for the health facility by the first user from that facility to log in, the site characteristics need to be synced to the server and then downloaded to every new device that a health worker from that facility logs in to. So, in other words, each time a new health worker logs in to the app, an internet connection will be required to check which facility they belong to and whether the site characteristics for that facility have been set already. If already set, they should be downloaded to the device; if not already set, they should get the above welcome screen to set the site characteristics.
- [x] In the event that two different health workers from the same health facility are able to set the site characteristics separately (e.g. the first health worker sets them but isn't able to sync them to the server before the 2nd health worker logs in), then the last site characteristics to be synced should be used.
- [x] Please use the exact wording and content from the [data dictionary (Site Charact. tab)](https://docs.google.com/spreadsheets/d/1dRYeuq8rPXNcAmqFfXlSeMC1gm_ejsvl76gQM39zxm8/edit#gid=1796677713) instead of what's shown in the mockup. Use the content that is in the Info icon column.
- [x] After they press Save, they'll be redirected to a confirmation page (see below)

<img width="409" alt="screen shot 2018-08-23 at 9 39 22 am" src="https://user-images.githubusercontent.com/3488986/44508856-7b710d80-a6b8-11e8-8c07-7df95c8fa976.png">

- [x] Pressing back button on top left or device back button takes the user back to site charact. page.
- [x] Facility name should be populated with that user's health facility name
- [x] Continue to your client list takes user to the main register page.
- [x] The site characteristics can be edited at anytime from the bottom menu bar, Me profile page.
- [x] Unit tests

**Comment by rowo** [comment]
@keymane @cagulas I've updated this here: https://marvelapp.com/project/2823817/screen/44913704. 

<img src="https://user-images.githubusercontent.com/1584163/43215474-3f0610d0-900a-11e8-9e5e-c0abaa34c9c0.png" width="400">

<img src="https://user-images.githubusercontent.com/1584163/43215479-43c7dbbc-900a-11e8-93f3-fcf3241f38a1.png" width="400">

<img src="https://user-images.githubusercontent.com/1584163/43215529-6316f368-900a-11e8-9694-37876a227eb9.png" width="400">

Using this single page form means even if you come from the [side menu summary](https://marvelapp.com/project/2823817/screen/44915817), we can use the same form as above for editing.

**Comment by cagulas** [comment]
Lgtm

**Comment by rowo** [comment]
Cool please just use placeholder for the image if you start building I will get that drawing done in mid-August

**Comment by cagulas** [comment]
@rowo Ok cool, great. I'll leave you assigned to the issue though, but also assigned @ndegwamartin to start working on it.

**Comment by cagulas** [comment]
QA 16th Oct build:

- [ ] One is able to click "Save" on the site characteristics page without answering any of the questions. Save should be disabled and not clickable until all questions are answered. When I clicked save without answering any questions then went back to the site charact. page, all of the questions were auto-filled to No.
- [ ] On the confirmation page, do not bold "Go back to site characteristics."
- [ ] Period missing on the end of sentence after "time".
- [ ] Let's enlarge "Continue to your client list". This is the primary action for the user on this page, so it should be more prominent and definitely larger than the go back to site charact. button, which is a secondary action.

**Comment by cagulas** [comment]
Let's fix up the IPV indentation, each lettered part should be on a new, indented line:

![screenshot_20181019-082543](https://user-images.githubusercontent.com/3488986/47199383-04838880-d37a-11e8-8747-d6cbaab21004.png)

**Comment by rowo** [comment]
@ndegwamartin does this work?

<img src="https://user-images.githubusercontent.com/1584163/49986118-9f44b180-ff3c-11e8-8e0b-ecb730368ba6.png" width="500">

![artboard 1 copy](https://user-images.githubusercontent.com/1584163/49986120-a10e7500-ff3c-11e8-928b-6ad2c70cb004.png)

**Comment by faith-mutua** [comment]
QA 20 Dec 2018: 

- [ ] First user from a health facility to log into the app for the very first time is not being redirected to the Site Characteristics page.  They are being taken to the main register page instead.

**Comment by faith-mutua** [comment]
QA 21 Dec 2018

The placeholder images shared by @rowo haven't been implemented yet.

**Comment by dubdabasoduba** [comment]
@cagulas for validation you can not move forward without selecting all required items since the validation is enforced by native forms.

**Comment by cagulas** [comment]
@dubdabasoduba Ok cool, I'll take another look. When I QA'ed this a long time ago now, it was allowing SAVE without answering any of the questions.

**Comment by dubdabasoduba** [comment]
![xters](https://user-images.githubusercontent.com/4817531/55627226-4b452d80-57b6-11e9-934b-045d6d43d9eb.png)

**Comment by cagulas** [comment]
lgtm
