### ISSUE TITLE
Implement login filter workflow

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client-anc#19]
Initial login filter for the user to select what action they want to do when they first login. This was based on user feedback.

**Comment by rowo** [comment]
This is blocked and don't think the client signed off on anything in particular.

**Comment by rowo** [comment]
<img width="278" alt="screen shot 2018-07-24 at 5 51 29 pm" src="https://user-images.githubusercontent.com/1584163/43168187-58403198-8f6a-11e8-9db4-bc19165aaeac.png">

@cagulas @keymane I wonder if something like this is a better solution than a first step question. It can disappear on scroll and "Register" and "Library" can still be full screen dialogs you "X" out of.

**Comment by cagulas** [comment]
Update: We are switching to the bottom menu approach on the main register page, so this issue isn't relevant anymore. Closing.
