### ISSUE TITLE
Fix bug on advanced search qr code

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client-anc#198]
When I scan a qr code on the advanced search page, it should populate the ANC ID field on the page (so that the user can continue to enter other search parameters if needed and then search for the woman). Right now, if you scan a qr code, it closes the advanced search and takes you back to the main register.

**Comment by dubdabasoduba** [comment]
@cagulas what version of the app are you using to test

**Comment by cagulas** [comment]
This is working.
