### ISSUE TITLE
Fix qr code no results popup bug

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client-anc#199]
https://github.com/OpenSRP/opensrp-client-anc/issues/44 - The popup about wanting to go to advanced search page is not appearing anywhere. Think something broke.

**Comment by dubdabasoduba** [comment]
@dubdabasoduba What version of the app are you using to test

**Comment by dubdabasoduba** [comment]
@cagulas What version of the app are you using to test

**Comment by cagulas** [comment]
This is working as expected.
