### ISSUE TITLE
Implement record birth popup

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client-anc#20]
At GA 41 weeks, the contact button on the main register page changes to a blue Due Delivery button. When you click on this button, the below widget pops up:

<img src="https://user-images.githubusercontent.com/1584163/43165519-17386222-8f62-11e8-9f4a-4411ab7b3968.png" width="400px">

- [x] Display `gest_age` from the woman's record.
- [x] Display woman's `edd`. Calculate and display how many days ago it was.
- [x] Replace Charity with woman's `first_name`.
- [x] The Record birth button opens the ANC Close form (https://github.com/OpenSRP/opensrp-client-anc/issues/3)
- [x] The Cancel button (or tapping device back button or tapping anywhere outside the widget) closes the widget.

**Comment by rowo** [comment]
@cagulas what do you think of the below discussion? 

Here is the dialog as we discussed before:

<img src="https://user-images.githubusercontent.com/1584163/43165318-981c0b60-8f61-11e8-987b-58d014936be0.png" width="400px">

However, I thought it was a little complex (the two options for action aren't a simple decision) for something that is not routine.

So here is another approach that supposes a user is trying to record birth when GA is is >40 weeks. If not, the user can always Cancel this dialog and click the row if they do want to go to the profile for some reason:

<img src="https://user-images.githubusercontent.com/1584163/43165519-17386222-8f62-11e8-9f4a-4411ab7b3968.png" width="400px">

**Comment by cagulas** [comment]
QA results from 23 August 2018 build:

- [ ] Don't capitalize "Birth"
- [ ] The GA is incorrect. I did this for Ann Karembo, whose GA is 12 weeks, but the popup is showing 17 weeks.
- [ ] The schedule isn't correct yet. Ann is 12 weeks, but when I tap on her Contact button, this widget pops up. This should change to due delivery button and pop up at 41 weeks only.

**Comment by cagulas** [comment]
@ndegwamartin how to test this again? It's no longer popping up.

**Comment by cagulas** [comment]
Closing this - remaining functionality moved to new issue https://github.com/OpenSRP/opensrp-client-anc/issues/134
