### ISSUE TITLE
Responsively resize contact container icons to appear on single screen

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-anc#207]
From Roger: On the main contact page, is there a way to make all of the contact section buttons responsively resize to always appear on a single screen? This consistency is important to build muscle memory.

**Comment by dubdabasoduba** [comment]
![Peek 2020-01-10 15-50](https://user-images.githubusercontent.com/4817531/72154206-11e2c380-33c1-11ea-9a48-c5f2461fd63c.gif)
@cafootitt if we made the page uncontrollable then it would look distorted for very small screens. To avoid this we created a recycler view which creates the contact buttons dynamically resizing them to fit each screen and adding the scroll to avoid distortion.

**Comment by cafootitt** [comment]
Great, thanks Ben.
