### ISSUE TITLE
UI clean up on the due delivery popup

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client-anc#209]
- [x] Remove the extra space before Belinda
- [x] Remove the period (full stop) at end of EDD row

![screenshot_20190308-120943](https://user-images.githubusercontent.com/3488986/54019173-96f6be00-419b-11e9-805f-58c18f521e90.png)

**Comment by ellykits** [comment]
![DueAlert](https://user-images.githubusercontent.com/26865532/55157718-29bcc400-516e-11e9-9ae0-a73204a8a9e5.png)

**Comment by cagulas** [comment]
lgtm
