### ISSUE TITLE
Implement site characteristics in "Me" menu and ability to edit

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client-anc#21]
From the "Me" page in the bottom register page menu, the user can open the site characteristics that were originally set at first login (https://github.com/OpenSRP/opensrp-client-anc/issues/18) and review and/or edit them.

![onboarding02-verify](https://user-images.githubusercontent.com/1584163/43221045-a31d99d0-9019-11e8-982d-fc31ccf446b3.png)

- [x] The X or Cancel button (or tapping the device back button) takes the user back to the main register page.
- [x] Use the short label field to display here. And the answers they set at first login (yes or no) and the longer description goes in the info icon popup. See data dictionary.
- [x] If you click edit, you go to the same full screen dialog form as used during the initial setting of the site characteristics (#18). Since all of the fields are already filled out for this scenario, I think it's okay for the Save button to be active even if the user hasn't changed anything.
- [x] After pressing save, the user is taken back to the main register page.
- [x] If they press device back button while on the edit page, show a widget to confirm they want to go back (to site charact. page above) and all changes would be lost.
- [x] If they do make any changes and save, the changes should sync to the server and then sync to any other user's device from the same health facility.

**Comment by rowo** [comment]
@cagulas can you update the data dictionary with the content you think should appear here? I had drawn up the initial login sequence just as an idea of what could appear but I don't think the content has been vetted or finalized.

**Comment by cagulas** [comment]
@rowo As you've said before, the exact content doesn't matter, because they'll just copy from the data dictionary. Can you explain why you need the exact content? I think what you have is good. There is a sequence of 4 questions and they're all yes or no. I was just wondering if what you have right now is finalized, or whether you were planning to go back to it at a later point and change it.

**Comment by rowo** [comment]
@cagulas Just wondering how much content there will be and if yes/no for all questions is okay since I pretty much made it all up and it's still a v1 whereas everything else is up to about a v15. I didn't know if that was final since it wasn't in the data dictionary and it wasn't described in the issue's comment — so that's why I was asking above for some sort of verification beyond high level agreement in the weekly call notes.

**Comment by cagulas** [comment]
The pop and site characteristics have been pretty finalized (with the exception of the removal of most of the site characteristics) since the initial workshop in WHO earlier this year. I'm not sure what you mean by it wasn't in the data dictionary. The content in the data dictionary is pretty final (maybe some small wording tweaks remain yet, but as you say, it shouldn't matter for your work). It's the list of questions there, and they are binary, so yes/no works well. We walked through the sequence on Thursday's call, and WHO was fine with it. The only remaining part is whether or not they will want this to be password-protected, but I also don't think this would block your work.

**Comment by rowo** [comment]
From the side menu, you'd open up the site characteristics and get a short description of each characteristics with a info icon that opens a dialog with the full question label:

<img src="https://user-images.githubusercontent.com/1584163/43216132-1b36bf2c-900c-11e8-84bc-ac5f544aee99.png" width="400">

If you click edit, you go to the same full screen dialog form as used the initial setting of site characteristics. Since all of the fields are already filled out for this scenario, I think it's okay for the Save button to be active even fi the user hasn't changed anything.

<img src="https://user-images.githubusercontent.com/1584163/43216082-f15d6cdc-900b-11e8-8786-015f05f35f10.png" width="400">

**Comment by cagulas** [comment]
QA 11th October build:

- [ ] The info icon for IPV assessment has the quotes around the description. I think this might be because it was copy-pasted. For some reason they add the quotes. Please remove.
- [ ] Also for IPV assessment info icon, can we indent the listed items? And change from numbers to letters?
- [ ] Confirm form close confirmation should be the "all changes will be lost" variety, not all data will be lost.

Still need to test propagation of edited site characteristics to another team member's device.

**Comment by cagulas** [comment]
QA 16th Oct build:

The first two QA points above were not included in this app update:

- [ ] The info icon for IPV assessment has the quotes around the description. I think this might be because it was copy-pasted. For some reason they add the quotes. Please remove.
- [ ] Also for IPV assessment info icon, can we indent the listed items? And change from numbers to letters?

**Comment by ndegwamartin** [comment]
this must have broken again when we reset the data, the settings are dynamic so it must be that the old un-updated data was used. If I reset again on the server with the correct data, it should be able to sync back again for testing

**Comment by cagulas** [comment]
QA 18th Oct build:

- [ ] Can we make the entire sub-points indented? Right now, it indents the first line, but the subsequent lines aren't

**Comment by faith-mutua** [comment]
QA 21 Dec 2018
lgtm

**Comment by cagulas** [comment]
QA 27th December 2018:

- [ ] IPV numbering is still off. Right now it goes 1. then a. b. c. etc.  Number 1 should be the main question label, then the bullets should be lettered.
- [ ] The required red asterisk shows up in the first question label and again after the last item in the list. It should only appear once.

**Comment by cagulas** [comment]
Looks great!
