### ISSUE TITLE
Clean up on main register page

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client-anc#211]
The attention flag icon needs to get smaller, as it's almost touching the 
The interpunct looks like it's bolder than the other text

@rowo can you advise here?

![screenshot_20190308-121049](https://user-images.githubusercontent.com/3488986/54020230-5187c000-419e-11e9-9330-9fc8c0a21143.png)

**Comment by rowo** [comment]
<img width="853" alt="screen shot 2019-03-08 at 12 28 56 pm" src="https://user-images.githubusercontent.com/1584163/54044773-c9091f80-419d-11e9-8fe2-f922cf241a98.png">

Left is in app, right is an updated mockup.

The idea was the flag button would match the line height (not letter height) of the third line, or  slightly taller.

The type goes like this:

Name: regular, size 13pt, #212121
Subtext: regular, size 12, #757575
Flag number: regular, size 11, #757575

Originally the flag number text was defined as medium, ~10, but I think the above works fine.

**Comment by dubdabasoduba** [comment]
Fix the toolbar scan icon & the sync icon alignment with the rest of the page.

**Comment by cagulas** [comment]
Latest screenshot from March 29 release:

![Screenshot_20190402-120042](https://user-images.githubusercontent.com/3488986/55315908-03509e80-5476-11e9-9a68-be78260184c7.png)

@rowo Still looks like the alignment is not what you specified.

**Comment by rowo** [comment]
@cagulas Correct. The image on the left shows the most recent compared to the prior spec image. It looks like the flag button got moved down to the third line baseline, but the button and alert icon itself are tall so pushing in the line above.

![Untitled-1](https://user-images.githubusercontent.com/1584163/55401733-a7daeb00-551f-11e9-80a6-ee817981b382.png)

**Comment by cagulas** [comment]
This wasn't included in the latest release, but I am able to see from ben's computer that this is fixed, closing.
