### ISSUE TITLE
Negative contact number shows if you skip the contact due to danger sign

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client-anc#213]
This is something we haven't discussed and specified what should show up when you skip a contact visit by selecting refer and close contact from the quick check page after checking a danger sign.

See below, it's showing a negative number in the contact summary pages and then contact 0 completed on the main register page:

![screenshot_20190711-122717](https://user-images.githubusercontent.com/3488986/54022836-77b05e80-41a4-11e9-8e23-a69c835e01d6.png)
![screenshot_20190711-122854](https://user-images.githubusercontent.com/3488986/54022839-78e18b80-41a4-11e9-92db-4cb9fccd646f.png)
![screenshot_20190711-123618](https://user-images.githubusercontent.com/3488986/54022843-7a12b880-41a4-11e9-9564-acf36fb4bbcf.png)

**Comment by cagulas** [comment]
@dubdabasoduba or @ellykits Can you weigh in here on what's happening on the rules engine side that's resulting in this?

**Comment by dubdabasoduba** [comment]
This is tied to a bug I am working on. Essentially it should just have the same schedule as before and just save the Event with a negative contact number to showed that the contact was referred. It should not change the contact status or update the GA & EDD in any way.

**Comment by cagulas** [comment]
Linked to https://github.com/OpenSRP/opensrp-client-anc/issues/242

**Comment by cagulas** [comment]
18 April release:

@dubdabasoduba I'm not seeing the changes that we discussed this week, i.e. hide the "Contact -1 recorded" row completely and just show the upcoming contact visit dates. Don't show that message explaining why a negative number is shown.

**Comment by dubdabasoduba** [comment]
This has been fixed and verified today.
