### ISSUE TITLE
Add constraint logic to select preferred GA

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-anc#214]
We need some way to prevent the user from selecting a preferred GA/EDD that isn't even calculated. I spoke with @dubdabasoduba about this previously. If SFH isn't calculated and shows zero, somehow we need to de-activate that answer choice to prevent the user from selecting it and having an illogical GA/EDD. If we can't remove the answer choice from the list, we should ideally grey it out and make it un-tappable. Best case scenario though, we implement constraint logic, so that the answer choices don't even show up until they are calculated.

**Comment by dubdabasoduba** [comment]
@cagulas Disabling the specific items in the radio buttons might take some time as it means tweaking the current relevance logic to also take into consideration radio button widgets that require their items disabled or enabled.

**Comment by dubdabasoduba** [comment]
We have an option of having the preferred GA radio button items created as different radio buttons widget then just use the current relevance logic to disable|hide and enable|show them

**Comment by cagulas** [comment]
@dubdabasoduba Cool, appreciate the input. This is in the icebox column for now, so we don't have to worry about it yet, but your feedback will be helpful if we get to it at a later phase of work.

**Comment by dubdabasoduba** [comment]
@cafootitt Do we need to implement the same for the TESTS container?
Please test the Profile container bit of this with a bit of keenness just to make sure we didn't break anything with the form rules.

**Comment by cafootitt** [comment]
lgtm
