### ISSUE TITLE
Fix numeric widget cut-off

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client-anc#216]
This was marked as complete in the last QA but I'm still seeing it in the March 7th release:

![screenshot_20190308-155905](https://user-images.githubusercontent.com/3488986/54030398-873ba180-41bc-11e9-891a-486f6caafada.png)

**Comment by ellykits** [comment]
**Snapshot taken from a screen of resolution 720 by 1280 xhdpi** 
![Screenshot_1558613298](https://user-images.githubusercontent.com/26865532/58251674-ded5bc00-7d6c-11e9-97c4-53e23c549cf6.png)

**Snapshot taken from a screen of resolution 240 by 320 ldpi** 
![Screenshot_1558613375](https://user-images.githubusercontent.com/26865532/58251675-ded5bc00-7d6c-11e9-9685-23e360793873.png)

**Comment by cagulas** [comment]
lgtm
