### ISSUE TITLE
Implement pop characteristics screen (view only)

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client-anc#22]
The population characteristics are similar to the site characteristics (#18) in that they are binary (yes = 1, no = 0) and impact the calculations and decision support logic in the ANC contact flow. The difference is that these are set in the back-end and cannot be set or changed by anybody on the device. Once set in the back-end (in a configuration file for the project), the pop characteristics need to sync to each device on first time login and be stored on the device. The pop characteristics can be edited over time (although this would be rarely, if ever done), so we can discuss how any edits to the pop characteristics would need to sync to the devices.

<img src="https://user-images.githubusercontent.com/1584163/43221265-64134ee6-901a-11e8-802b-1e5c88b21705.png" width="375">

Please use the exact wording and content from the data dictionary (Pop Charact. tab) instead of what's shown in the mockup. The label or the short name is what's shown in the above mockup, while the content in the info icon column would appear in a pop-up widget when the user taps the info icon next to each one.

These cannot be edited, so this page is view only. Clicking the X or cancel button or the back button on the device takes the user back to the main register page.

The user can open this page by selecting pop characteristics from the "Me" screen in the main register bottom menu.

- [x]  User Interface Layout
- [x]  UI render / exit Functionality
- [x]  Unit tests

**Comment by rowo** [comment]
@cagulas are there any requirements around this? What mixture of short name and long name should appear? Should positive/true items show up or everything? Any other actions or content besides titles and the characteristics?

**Comment by cagulas** [comment]
@rowo Just what we discussed. View-only in the side menu. If you look in the data dictionary, there already is a short name for them. All of them would show up, no matter whether they're yes or no. The longer description can be in an info icon.

**Comment by rowo** [comment]
@cagulas Yes, I definitely saw the short name. I was just asking about further detail. Below is my understanding — does it sound correct?

Requirements
1. Both the short name and long name need to appear in some way, with openness to using an info icon (or user interaction) to access the long name.
2. All characteristics need to show up — meaning it can't be just a list of positive/true's for that area, it will need to be a list of all characteristics and the associated "yes" or "no". If it is all "no", the entire list is still required to show up.
3. Continuing on the above, then the pop characteristics will be a 14-item list items similar to: "Low dietary calcium intake (i) - Yes"
4. The yes/no values are not editable.

**Comment by cagulas** [comment]
@rowo Correct

**Comment by rowo** [comment]
Using same styling as Site characteristics except no Edit button:

<img src="https://user-images.githubusercontent.com/1584163/43221205-312e5aca-901a-11e8-8053-288c7c11288d.png" width="375">

**Comment by cagulas** [comment]
Lgtm

**Comment by rowo** [comment]
@cagulas great, removed label and me from assignee

**Comment by cagulas** [comment]
QA results from 23 August 2018 build:
- [ ] Let's add more padding on the left hand side. The text is too close to the edge.
- [ ] Let's capitalize Characteristics in "Population Characteristics"
- [ ] Make the OK bigger in the info icon popups
- [ ] Capitalize "info" in the info icon popup

**Comment by cagulas** [comment]
QA 11th Oct build:

- [ ] "higher" on TB prevalence charact. gets cut off to "high."
- [ ] "National Hep B ANC routine screening program established" is missing.

**Comment by cagulas** [comment]
QA 16th Oct build:

- [ ] Remove the period after "higher" on the TB one
- [ ] National Hep B screening program is still missing.

**Comment by cagulas** [comment]
QA 18th Oct build:

LGTM!
