### ISSUE TITLE
Bugs on Tests container

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client-anc#220]
We need to re-look at the Tests container again. There are a lot of issues occurring here.

- [x] When I save blood type test results, nothing happens on the Due section page. It doesn't show a check that the blood type test was recorded, nor does it show the results. When I open blood type test again and select done today, no other questions appear. Same thing happens with Blood glucose test. Same thing happens with the Blood haemoglobin test.
- [x] When I enter urine test results, only the urine test type appears, not the date nor the results. 
- [x] The Undo and Record buttons are also missing now

Let's try to re-look at this section again and figure out the major issues that are causing no data to be saved and displayed. I can't finish QA on this until this is resolved.

**Comment by dubdabasoduba** [comment]
- [ ] Update the expansion panel in order to disable scroll of the selected values display area

**Comment by cagulas** [comment]
I'll add QA to the individual test issues.
