### ISSUE TITLE
Implement attention flag popup

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client-anc#24]
![dialog-risklist](https://user-images.githubusercontent.com/1584163/43219854-74513074-9016-11e8-8942-803df3762f0f.png)

- [x] The attention flag widget opens when the user taps the attention flag button for the woman on the main register page (https://github.com/OpenSRP/opensrp-client-anc/issues/1)
- [x] The number displayed on the button and the flag color (yellow or red) changes for each woman and is based on the list of attention flag issues calculated for the woman during her pregnancy.
- [x] If there are no attention flags, the button isn't shown.
- [x] If there are only yellow attention flags, the button flag color is yellow, else it is red (i.e. has both red and yellow it is red or just red flags it is red as well).
- [x] The number is the total number of red and/or yellow attention flags she has.
- [x] In the widget, split the list into red and yellow as shown in the mockup.
- [x] Pressing the device back button or the X cancel button or tapping anywhere outside the widget closes the widget.

I will create a separate issue for the attention flag calculations. This issue is just for the UI. (CG update: separate issue created here: https://github.com/OpenSRP/opensrp-client-anc/issues/82)

**Comment by cagulas** [comment]
@rowo This is no longer blocked, since they finalized the category names today. Can you let me know if the https://marvelapp.com/3aj9f30/screen/41196679 mockup is finalized, and I'll expand on this implementation issue?

**Comment by cagulas** [comment]
Lgtm.

**Comment by rowo** [comment]
@cagulas cool I removed label and me as assignee

**Comment by cagulas** [comment]
QA results from 23 August 2018 build:

- [ ] The flag icon is really blurry. Do you need the proper file size from @rowo?

**Comment by rowo** [comment]
![icon-flag-128](https://user-images.githubusercontent.com/1584163/44585903-d586d700-a77b-11e8-947c-7a4aeba24852.png)
![icon-flag-256](https://user-images.githubusercontent.com/1584163/44585904-d586d700-a77b-11e8-9936-ddb05a1e7681.png)
![icon-flag-512](https://user-images.githubusercontent.com/1584163/44585905-d586d700-a77b-11e8-8ee7-a68c7d470e0d.png)

**Comment by ndegwamartin** [comment]
@rowo we probably need these in yellow too. but maybe just the first one, its big enough

**Comment by rowo** [comment]
![icon-ylflag-128](https://user-images.githubusercontent.com/1584163/46429799-53dc7e80-c715-11e8-9969-1665fbd4144b.png)
![icon-ylflag-256](https://user-images.githubusercontent.com/1584163/46429800-53dc7e80-c715-11e8-8c0a-ebb159722ddf.png)
![icon-ylflag-512](https://user-images.githubusercontent.com/1584163/46429801-53dc7e80-c715-11e8-9ffd-bacb7cb8b224.png)

**Comment by cagulas** [comment]
QA results 11th Oct build:

- [ ] The attention flag icon on the main register page is still blurry.

**Comment by ndegwamartin** [comment]
@rowo I think we should probably go the reverse on this. My guess is it becomes blurry once we programmatically shrink it. Would it be possible to have a very small high quality version of this for testing?

**Comment by ndegwamartin** [comment]
thanks @rowo , let me try this

**Comment by ndegwamartin** [comment]
could I get it in red too please

**Comment by cagulas** [comment]
Done. Closing.
