### ISSUE TITLE
[Discussion] Change BP to not be required

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client-anc#240]
WHO is requesting that we make BP not required in the app. This is because some places may not have a proper BP cuff to take it. They also want us to make the health worker record the reason s/he is not capturing BP (WHO will be providing this list of reasons shortly, but I imagine it will be reasons like BP cuff broken, etc.).

I see one of two options:
1) We implement a check box (similar to DOB unknown) that says something like "Unable to record BP". Either entering BP or checking this box is required. If they check this box, the list of reasons appears.
2) We automatically show the list of reasons for not recording BP if the BP fields are empty. This means this is the default view they'd see when navigating to the BP page in the app. If they record a BP measurement, the list of reasons for not recording BP disappears.

I think both options are already supported elsewhere in the contact workflow, so I think the technical implications are about the same for either option.

Pls provide feedback on which of the two options is preferred or if another option is possible and would be better.

**Comment by rowo** [comment]
Requirements are still being changed? I guess the first would be the least confusing and also most common in the contact workflow. What fields are that second option used on? It's kind of a grouped section where you have one field then have a "-OR-" field below it. 

A third option used elsewhere is an initial question about if something is available and then showing the resulting followup fields.

**Comment by cagulas** [comment]
To be fair, this came up only in the context of finalizing reporting requirements and the realization that how we currently have it implemented doesn't support the indicator that they need to support for BP. Reporting indicators are still within the scope of this first phase of work.

> What fields are that second option used on?
This is just simple skip logic used throughout the workflow already.

Thanks

**Comment by rowo** [comment]
@cagulas I have a feeling anything done here will involve skip logic in some form. I was wondering 
 — do we have any situation where we show all inputs and hide them if one of the items is filled in. Which fields does that happen on?

**Comment by cagulas** [comment]
@rowo I'd have to comb through the data dictionary to look. Is this really helpful or are you just curious?

**Comment by cagulas** [comment]
Creating separate implementation issue. Will close this issue if @rowo is satisfied with implementation plan.

**Comment by rowo** [comment]
@rowo I was curious (with project quality questions) since you mentioned it. The problem is "showing all inputs then hiding after one input" doesn't immediately sound like a conventional flow and could be confusing, so I wanted to check out where it happens to make sure. It's a separate issue.

**Comment by cagulas** [comment]
Ok cool, I'll flag anything I come across.
