### ISSUE TITLE
Order the selected values on the Expansion panel widget 

### ISSUE THREAD

**Issue by dubdabasoduba** [OpenSRP/opensrp-client-anc#243]
Currently the selected items in the expansion panel are not order in any way. Fix the ordering to the selection order

**Comment by cagulas** [comment]
@dubdabasoduba I'm also noticing that the test results scroll. Instead of showing all test results, only the first 2-3 lines seem to show, and you have to scroll to see the rest. The user should see all test results and not have to scroll. Is this something you can look into in this issue as well?

**Comment by cagulas** [comment]
lgtm
