### ISSUE TITLE
[Discussion] Make IFA prescription fields show up each visit

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client-anc#247]
The client is asking if we can update the logic slightly to ensure that IFA prescription fields in the C&T page show up (if relevant) each contact visit. Beforehand, the instruction was to show this each visit, if relevant, only until the user marks the service as "Done". 

Flagged this to @ellykits in the data dictionary for feedback and to see how it's currently implemented.

**Comment by ellykits** [comment]
We implemented this to show up whenever it is relevant

**Comment by hmakandi** [comment]
SCN01: Gweta Tweta, 22weeks, contact 2, set Pallor yes,Shows Anaemia & IFA Counseling, on Click done record is stored, On Click Not done, 3 options for Reasons as referred instead, Side effects prevent.. and other. OK
SCN02 Cruiz Pruiz, GA not calculated, First Contact, Pallor NO,Anaemia prevention is not visible OK
SCN03 Draki Praki GA 0 weeks, No Pallor option selected, Anaemia Prevention is not visible OK
SCN04 Sepetu Wema,GA 13weeks, Pallor not marked Anaemia Prevention is not visible OK
SCN05:Pretatwi Kwetatwi, GA 14 weeks, Pallor not marked, Anaemia Prevention not visible OK

Observations:
