### ISSUE TITLE
Create woman avatar for when no picture is taken

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client-anc#25]

**Comment by rowo** [comment]
Placeholder until a pregnant woman is created:

![artboard 1](https://user-images.githubusercontent.com/1584163/43142112-a3a1d2bc-8f25-11e8-97a7-19685cadd11c.png)

**Comment by cagulas** [comment]
@rowo Closing this issue. Is her head supposed to be cut off like that though?

**Comment by cagulas** [comment]
Talked to @rowo. Ok to close this issue.
