### ISSUE TITLE
Add more room between rows in C&T container to prevent cut offs

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client-anc#255]
Let's do this across all C&T rows.

![Screenshot_20190402-110431](https://user-images.githubusercontent.com/3488986/55386150-88e85300-5537-11e9-962c-1724438e8028.png)

**Comment by ellykits** [comment]
![Screenshot_1554983855](https://user-images.githubusercontent.com/26865532/55955476-365f1300-5c6a-11e9-9e89-d55ce7e3c62b.png)

**Comment by cagulas** [comment]
Lgtm
