### ISSUE TITLE
Fix bugs on specify cm cervix dilated

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client-anc#271]
Something broke here in the 12 April release.

When I enter the integer for specify cm cervix dilated for the cervical exam done question, the integer I enter does not get recorded and does not appear once the pop-up dialog closes.

Also, I notice that when I do input an integer for this field, the page jumps back up to the Pulse rate field, and you are forced to scroll back to the cm dilated question.

Let's address this as a priority, since it's a reverted bug. Let's also write tests to make sure this doesn't break again.

**Comment by cagulas** [comment]
18 April release:

I can record the number now, and it displays, but the alert logic is broken again now. If you enter 2 or greater, an alert message should show.

The part where the page jumps back up to pulse rate wasn't addressed. @dubdabasoduba Pls let me know if this can be addressed quickly. If not, I'll move it to a new issue.

**Comment by cagulas** [comment]
Everything I reported in the 18 April release in the comment above is still not working.

**Comment by dubdabasoduba** [comment]
This has just been fixed today. We move the cards immediately to avoid forgetting what was changed.
![device-2019-05-02-152924](https://user-images.githubusercontent.com/4817531/57075313-1e216780-6cef-11e9-8a8a-76dfd5a8a3d8.png)

**Comment by cagulas** [comment]
Great, thank yoou.
