### ISSUE TITLE
Edit registration form

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client-anc#28]
The user can re-open the woman's ANC registration form and edit certain fields.

- [x] Clicking on the [Registration info](https://github.com/OpenSRP/opensrp-client-anc/issues/27) in the top portion of profile view launches form
- [x] See the data dictionary, ANC Reg tab, Editable column for the list of fields that can be edited in the form.
- [x] Saving the form will save the changes and update the relevant fields in the woman's profile and sync changes to the server. 
- [x] User can also exit the form without saving by hitting a cancel button or the back button on the phone.
- [x] A confirmation message when canceling changes should be added to say all changes will be lost.
- [x] Unit testing

**Comment by cagulas** [comment]
QA results from 23 August 2018 build:

- [ ] The confirm form close popup - can we change this slightly to say any "changes" you make will be lost?

**Comment by cagulas** [comment]
@ndegwamartin Ok, is there any way to have these two options? It will always be either all data will be lost or any changes you make will be lost. Can we support two options and we can specify which of the two will be used?

**Comment by ndegwamartin** [comment]
thats a good idea @cagulas , I can update the native library with and implementation to support setting the closing message dynamically such that any implementation can use their own custom one

**Comment by cagulas** [comment]
QA 11th Oct build:

- [ ] The confirm form close popup - can we change this slightly to say any "changes" you make will be lost? **CG: Not done yet**

**Comment by cagulas** [comment]
Lgtm

**Comment by cagulas** [comment]
Reopening this. In the 14th Dec build, there are edit icons next to some of the form fields in the edit registration form, which shouldn't be there.

**Comment by cagulas** [comment]
Lgtm
