### ISSUE TITLE
Implement view-only registration form

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client-anc#29]
The user can view the registration form from the woman's profile view to reference information in the form.

- [ ] Tapping on the [Registration info button](https://github.com/OpenSRP/opensrp-client-anc/issues/26) in the profile view launches a view-only registration form for the woman
- [ ] There should be a back or exit button for the health worker to return to the woman's profile
- [ ] View only. If the user needs to make edits, they should go to the top right profile menu edit registration info option instead.

**Comment by cagulas** [comment]
@rowo I noticed that you removed the Edit Registration info option in the top right profile dropdown, which means, this is out of date now. Am closing the issue and rephrasing the other one.

**Comment by rowo** [comment]
@cagulas yes I think if we are just showing the registration info like a completed contact form section, we can treat it the same way using an Edit button in the top right of the registration information view.
