### ISSUE TITLE
Hide/disable View ANC History button in contact page

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client-anc#293]
Tied to https://github.com/OpenSRP/opensrp-client-anc/issues/95. Until we implement issue 95, let's disable or hide this button.

![Screenshot_20190529-094544](https://user-images.githubusercontent.com/3488986/58535514-deb73f80-81f6-11e9-985a-8fef31ef9862.png)

**Comment by ellykits** [comment]
![Screenshot_1559112842](https://user-images.githubusercontent.com/26865532/58535917-bed44b80-81f7-11e9-9517-e81d13afc224.png)

**Comment by cagulas** [comment]
lgtm
