### ISSUE TITLE
Should we hide the Filter button?

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client-anc#294]
Since we are unable to implement sort/filter parameters in the first phase of work for the user testing, should we hide this button? If we hide it, will the search bar look odd on its own or should we attempt to expand it?

![Screenshot_20190529-094933](https://user-images.githubusercontent.com/3488986/58535785-60a76880-81f7-11e9-8c75-66da4ad03c7c.png)

**Comment by rowo** [comment]
@cagulas How long will it be hidden and who will be seeing it? It'll look a little weird but not a big deal if there's nobody really using it and judging it. If first phase means this entire project.. I would say yes please make the search bar full width.

**Comment by cagulas** [comment]
I can't foresee us doing this until we get another SOW, so I would venture that it will take a while. We'll also need to revise the sort/filter parameters down. Thanks for the input. I think we should hide it and then expand the search bar.

@ellykits can you do this ahead of the next release? Let me know if this is a quick job to do.

**Comment by ellykits** [comment]
![Screenshot_1559218266](https://user-images.githubusercontent.com/26865532/58632044-2cae6f00-82ed-11e9-8848-491e60394b39.png)

**Comment by cagulas** [comment]
Great, thanks!
