### ISSUE TITLE
Tests & C&T containers wrongly show Complete status when you exit

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-anc#295]
I can open Tests container and immediately exit, and it shows Complete status instead of the number of required fields. Same goes for C&T container. When I open the container and then exit immediately, it shows the complete status.

If it is difficult to show the number of required fields if no data input has been made yet in the container, a workaround is that we don't show either Complete or the required number of fields if the user doesn't input anything before they exit the container, i.e. the starting state of the contact container remains until they input something.

@ellykits What are your thoughts on this?

**Comment by ellykits** [comment]
@cagulas after consideration the fix has been implemented based on this workaround.

>  if no data input has been made yet in the container, a workaround is that we don't show either Complete or the required number of fields if the user doesn't input anything before they exit the container, i.e. the starting state of the contact container remains until they input something.

**Comment by cafootitt** [comment]
This is working as expected based on discussion above.
