### ISSUE TITLE
HIV diagnosis date should be a required field with an asterisk

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-anc#296]
See row 129-130 in Profile. Either HIV diagnosis date or unknown check mark is required. Right now, I can exit profile container and it doesn't show that they are required if I leave them both blank. HIV diagnosis date should have the red required asterisk. This functionality exists in WCARO, so please check with that team if not existing already in our app.

**Comment by ellykits** [comment]
![Screenshot_1559548370](https://user-images.githubusercontent.com/26865532/58785216-c4fa6b80-85ed-11e9-91c0-656153fcd64d.png)

**Comment by cafootitt** [comment]
lgtm
