### ISSUE TITLE
Add more padding between back arrow row and avatar

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client-anc#298]
![Screenshot_20190531-140210](https://user-images.githubusercontent.com/3488986/58709491-f6432380-83c2-11e9-9147-6df041bcd6f9.png)

Let's try to shift the entire avatar plus demographics info in the top blue section further down to add more space between it and the back arrow row (where it says Contact 1 in the screenshot).

**Comment by ellykits** [comment]
![Screenshot_1559652905](https://user-images.githubusercontent.com/26865532/58880703-3404bc80-86e1-11e9-9ac2-e1d3910f6d57.png)

**Comment by cagulas** [comment]
lgtm
