### ISSUE TITLE
Other gyn procedure missing from yellow attention flag

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client-anc#299]
{surgeries_other_gyn_proced} is not getting populated in yellow attention flag note.

Should appear in attention flag icon as well as contact summary in contact tab.

**Comment by ellykits** [comment]
I specified **Colposcopy** as other gynecological procedure and **Cholecystectomy** as Other surgeries
![Screenshot_1559636220](https://user-images.githubusercontent.com/26865532/58863049-b0d07000-86ba-11e9-9464-c4a884542a43.png)
![Screenshot_1559636376](https://user-images.githubusercontent.com/26865532/58863084-c2197c80-86ba-11e9-9d17-33093b543b9c.png)

**Comment by cagulas** [comment]
Perfect, closing this.
