### ISSUE TITLE
Respiratory distress abnormal reasons not appearing in yellow attention flag

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client-anc#300]
Respiratory distress: {repiratory_exam_abnormal}, {repiratory_exam_abnormal_other}

Should appear in attention flag icon and in contact summary in contact tab.

**Comment by ellykits** [comment]
@cagulas Should this appear in the yellow flag section or the red attention flag section. In the data dictionary its under **Red** attention flag section.

**Comment by ellykits** [comment]
![Screenshot_1559569779](https://user-images.githubusercontent.com/26865532/58807670-3273bf80-8621-11e9-874c-abf6cdb53940.png)
![Screenshot_1559569435](https://user-images.githubusercontent.com/26865532/58807678-37d10a00-8621-11e9-9a63-3b43af042939.png)

**Comment by cagulas** [comment]
@ellykits Yes, thanks for catching that. My mistake. Should be in red.

**Comment by ellykits** [comment]
@cagulas I updated the screenshots above you can see the Respiratory Exam now being shown in both **Contact Summary** and **Attention flags**

**Comment by cagulas** [comment]
great, thanks
