### ISSUE TITLE
Fix remaining bugs on the data dictionary 

### ISSUE THREAD

**Issue by ellykits** [OpenSRP/opensrp-client-anc#302]
- [x] Symptoms and Followup
- [x] Physical Exam
- [x] Tests
- [x] Counselling and Test
- [x] Contact Summary
- [x] Attention flags

**Comment by ellykits** [comment]
To save time on QA for **Contact summary** here are some screen shots on the highlighted section in the data dictionary

<br/>**OBSTETRIC SECTION** <br/>
![contact_summary obstetric section](https://user-images.githubusercontent.com/26865532/59198251-f0f09080-8b9b-11e9-909d-5f4fc3e0b813.png)

<br/>**MEDICAL HISTORY SECTION** <br/>
![contact_summary_medical_history](https://user-images.githubusercontent.com/26865532/59198334-29906a00-8b9c-11e9-86c5-f84795e522e4.png)

<br/>**MEDICATIONS SECTION** <br/>
![contact_summary_medications](https://user-images.githubusercontent.com/26865532/59198359-39a84980-8b9c-11e9-93e3-fb8bd09ab413.png)

 <br/>**WOMAN'S BEHAVIOR SECTION** <br/>
![contact_summary_woman_behavior](https://user-images.githubusercontent.com/26865532/59198436-6a887e80-8b9c-11e9-9da1-eb8c61235b78.png)

<br/>**PHYSIOLOGICAL SYMPTOMS SECTION** <br/>
![contact_summary_physiological_symptoms](https://user-images.githubusercontent.com/26865532/59198489-868c2000-8b9c-11e9-8d7c-c16607c7ff7e.png)

<br/>**HEIGHT AND WEIGHT SECTION** <br/>
![contact_summary_height_and_weight](https://user-images.githubusercontent.com/26865532/59198523-9b68b380-8b9c-11e9-95ed-f3efe73b8a10.png)

**Comment by ellykits** [comment]
**BLOOD PRESSURE SECTION**
![contact_summary_blood_pressure](https://user-images.githubusercontent.com/26865532/59199159-f8b13480-8b9d-11e9-8470-8e1462fb6b69.png)

**Comment by cafootitt** [comment]
Thanks @ellykits These all look good and I have resolved the comments in the data dictionary for the above screens. This is really helpful and saves me a lot of time, so I really appreciate it.

**Comment by ellykits** [comment]
**MORE SCREENSHOT FOR NOT DONE FOR TESTS**<br/>

![Uploading contact_summary_hepatitits_b_not_done.png…]()
![contact_summary_tb_screen_notdone](https://user-images.githubusercontent.com/26865532/59275735-96bc0200-8c65-11e9-82dc-4b1e0ecf8f53.png)
![contact_summary_ultrasoun_not_done](https://user-images.githubusercontent.com/26865532/59275736-96bc0200-8c65-11e9-841b-424407c024ca.png)
![contact_summary_urine_notdone](https://user-images.githubusercontent.com/26865532/59275738-97549880-8c65-11e9-9fe7-bdc1f644a650.png)

**Comment by ellykits** [comment]
**MORE SCREENSHOTS FOR ORDERED OPTIONS**<br/>

![contact_summary_ordered_hepb png](https://user-images.githubusercontent.com/26865532/59276450-fd8deb00-8c66-11e9-8579-4bea509ea60b.png)
![contact_summary_ordered_tb png](https://user-images.githubusercontent.com/26865532/59276453-fd8deb00-8c66-11e9-82b4-e09fca46b891.png)
![contact_summary_ordered_ultrasound](https://user-images.githubusercontent.com/26865532/59276456-fe268180-8c66-11e9-9a44-c17bc1afb336.png)
![contact_summary_ordered_urine png](https://user-images.githubusercontent.com/26865532/59276457-fe268180-8c66-11e9-8794-e7c77df816ac.png)

**Comment by ellykits** [comment]
[Seven-day antibiotic not done not being shown](https://docs.google.com/a/ona.io/spreadsheets/d/1dRYeuq8rPXNcAmqFfXlSeMC1gm_ejsvl76gQM39zxm8/edit?disco=AAAAC-XdrCc)

![contact_summary_asb_notdone](https://user-images.githubusercontent.com/26865532/59277104-3aa6ad00-8c68-11e9-93ac-509f0bb68039.png)

**Comment by ellykits** [comment]
**Fix for IFA ANAEMIA NOT DONE NOT BEING SHOWN**
![contact_summary_ifa_anemianotdone](https://user-images.githubusercontent.com/26865532/59280367-22399100-8c6e-11e9-94ba-bb1748ae5e57.png)

**Comment by ellykits** [comment]
**PRE-ECLAMPSIA RISK SECTION**</b>
>Not done was not being shown. Change pop characteristic to test both
![contact_summary_preeclampsia_risk](https://user-images.githubusercontent.com/26865532/59281174-7abd5e00-8c6f-11e9-9104-b955a2e41b4c.png)

**Comment by ellykits** [comment]
**BIRTH PREPAREDNESS & BREAST FEEDING SECTION** <br/>
> Both were not being shown. Fixed as in the screenshot. Not done should work the same way. You can test
![contact_summary_birthprep](https://user-images.githubusercontent.com/26865532/59282150-1b604d80-8c71-11e9-82d5-c448cd56d2e9.png)

**Comment by ellykits** [comment]
**DEWORMING & MALARIA PROPHYLAXIS**
> Fixed IPTp-SP not done reasons not showing plus replaced the character **||** that was being shown instead of **or**
![Screenshot_1560264742](https://user-images.githubusercontent.com/26865532/59282706-02a46780-8c72-11e9-9e73-238668189833.png)

**Comment by ellykits** [comment]
**VITAMIN A SUPPLEMENTATION FIXES**
![contact_summar_vita](https://user-images.githubusercontent.com/26865532/59283155-c4f40e80-8c72-11e9-8298-e164d565340e.png)

**Comment by cafootitt** [comment]
Great, all looks good.

**Comment by cafootitt** [comment]
@ellykits Feel free to keep sending screenshots for the remaining fields that are still highlighted in the data dictionary!

**Comment by cafootitt** [comment]
Closing this and creating new issue with remaining bugs
