### ISSUE TITLE
Remaining data dictionary bugs

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-anc#308]
Remaining Data Dictionary Bugs:

Quick Check: All done
- [x] Profile: Just the HIV diagnosis as chronic health condition not being picked up in C&T to show HIV pos counseling
- [x] S&F: Just the IFA compliance and side effects relevance not working
PE: All done
Tests: All done
**C&T:**
- [x] HIV positive counseling is required if woman is HIV positive from the chronic health conditions question
- [x] Syphilis positive counseling not appearing
- [x] Birth plan "Woman should plan to give birth at a facility due to risk factors" info icon should appear in the widget not on the expansion panel
- [x] Anaemia prevention (couldn't test because IFA side effects was not working)
- [x] Specify other for wheat bran isn't working
- [x] Hep B dose 2 not working
- [x] IPTp-SP dose 2 not working
- [x] Deworming still showing up even after it was marked as given
- [x] Flu immunization still showing up even after it was marked as given
- [x] Contact Summary: See what's still highlighted

**Comment by ellykits** [comment]
**Showing IFA Compliance**


![Screenshot_1560943045](https://user-images.githubusercontent.com/26865532/59761365-4532f900-929d-11e9-8994-fa10747e1cc8.png)

**Comment by ellykits** [comment]
![Screenshot_1561364308](https://user-images.githubusercontent.com/26865532/60002721-dd502a00-9671-11e9-9150-6708a20a8e7f.png)

**Comment by ellykits** [comment]
![Screenshot_1561365223](https://user-images.githubusercontent.com/26865532/60003728-f954cb00-9673-11e9-9e65-eda6fb75e3ff.png)

**Comment by ellykits** [comment]
**GA now shown in weeks and days for ultrasound**
![Screenshot_1561366136](https://user-images.githubusercontent.com/26865532/60004880-17232f80-9676-11e9-802c-3aa8c646e19b.png)

**Comment by ellykits** [comment]
**3rd and 4th degree tear now shown**

![Screenshot_1561366234](https://user-images.githubusercontent.com/26865532/60004983-53569000-9676-11e9-8ddb-34488e76197d.png)

**Comment by ellykits** [comment]
**IFA Compliance and IFA Side effects now displayed under medication in Contact Summary page**

![Screenshot_1561366324](https://user-images.githubusercontent.com/26865532/60005218-bc3e0800-9676-11e9-99cc-da41b1f4ac51.png)

**Comment by ellykits** [comment]
**FIXES FOR ANAEMIA PREVENTION SECTION CONTACT SUMMARY**

![Screenshot_1561366608](https://user-images.githubusercontent.com/26865532/60005564-6fa6fc80-9677-11e9-9096-b158b8216a62.png)

**Comment by ellykits** [comment]
**Fix for Vitamin A supplementation section Contact Summary**


![Screenshot_1561367030](https://user-images.githubusercontent.com/26865532/60006022-5488bc80-9678-11e9-92b4-947c0d896122.png)

**Comment by ellykits** [comment]
**HEPB dose 2 and Iptp  dose 2**

![Screenshot_1561378188](https://user-images.githubusercontent.com/26865532/60017858-798a2900-9692-11e9-9210-30cfc552fb51.png)
![Screenshot_1561378268](https://user-images.githubusercontent.com/26865532/60017864-7d1db000-9692-11e9-9802-dd4b83dfff37.png)

**Comment by ellykits** [comment]
**IPTP-sp 3 dose now showing.**

![Screenshot_1561378880](https://user-images.githubusercontent.com/26865532/60018345-cc181500-9693-11e9-8a86-56a486bf1d42.png)

**Comment by ellykits** [comment]
**TT Dose 3 and  HepB dose 3 now being shown**

![Screenshot_1561380382](https://user-images.githubusercontent.com/26865532/60019854-82c9c480-9697-11e9-8ecd-e94686ff0a34.png)

**Comment by ellykits** [comment]
@cafootitt For the above here are my test cases: 

**MALARIA PROPHYLAXIS**

| FIELD        | DATE EXPECTED |
| ------------- |:-------------:| 
| IPTp-SP dose 1  | 24-06-2019|
| IPTp-SP dose 2     |  22-07-2019     | 
| IPTp-SP dose 3 |  19-08-2019     |  

**TT IMMUNISATION**

| FIELD        | DATE EXPECTED |
| ------------- |:-------------:| 
| TT dose 1  | 24-06-2019 |
| TT dose 2   |  22-07-2019     | 
| TT dose  3 |  09-12-2019     |  


**HEP B IMMUNISATION**

| FIELD        | DATE EXPECTED |
| ------------- |:-------------:| 
| Hep B dose 1  | 24-06-2019 |
| Hep B dose 2     |  22-07-2019     | 
| Hep B dose 3 |  09-12-2019     |  

> NOTE: This worked when in offline mode only since server would not allow syncing with a future date. So once you have logged in, disable internet connectivity and then adjust the dates while offline.

**Comment by cafootitt** [comment]
QA 25 June:

- [ ] Syphilis counseling still not working


All else looks good to me!

**Comment by cafootitt** [comment]
V1.2.2 - lgtm
