### ISSUE TITLE
Change EDD calculation for LMP

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-anc#310]
Current calculation:

lmp + 7 days + 9 calendar months

Change to:

lmp + 280 days

This is an improved calculation that WHO is recommending we use to calculate EDD based on LMP. One improvement is that with this new calculation, it takes into account leap years.

This is updated in the data dictionary, Profile tab, row 29. See highlighted cell.

**Comment by ellykits** [comment]
I used lmp date of **15 November, 2018** , the new EDD is as shown in the screenshot: **22nd August 2019**. Hope this calculation is correct. 


I compared against the result from this site [Date calculator Site](https://www.timeanddate.com/date/dateadded.html?d1=15&m1=11&y1=2018&type=add&ay=&am=&aw=&ad=280&rec=)
![Screenshot_1560952055](https://user-images.githubusercontent.com/26865532/59771500-7ff35c00-92b2-11e9-8c6d-8cfc9dd9a603.png)

**Comment by cafootitt** [comment]
Can you test today's date for LMP? the EDD should be 25 March 2020 (which accounts for leap year in 2020). If you get 25 March 2020, then we're all set.

**Comment by ellykits** [comment]
There you go. Today's date (19th June 2019) gives **25th March 2020**
![Screenshot_1560953186](https://user-images.githubusercontent.com/26865532/59772604-c2b63380-92b4-11e9-9454-7f131aa8ab3b.png)

**Comment by cafootitt** [comment]
Brilliant!

**Comment by cafootitt** [comment]
lgtm
