### ISSUE TITLE
Change EDD calculation for ultrasound

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-anc#311]
Based on WHO's request, we need to add back the field for ultrasound in number of days. This affects the EDD calculation from ultrasound in the Profile and Tests tabs.

See data dictionary, Profile tab, rows 37-40, and Tests tab, rows 14-18.

Current:
{ultrasound_date} + (280 - ({ultrasound_gest_age_wks} * 7)

Change to:
{ultrasound_date} + (280 - ({ultrasound_gest_age_wks} * 7 + {ultrasound_gest_age_days})

**Comment by ellykits** [comment]
![Screenshot_1561296228](https://user-images.githubusercontent.com/26865532/59976899-5187c080-95d3-11e9-96ee-23bd508c13ca.png)

**Comment by cafootitt** [comment]
Awesome!

**Comment by cafootitt** [comment]
lgtm
