### ISSUE TITLE
Change {reminders} question to radio instead of spinner

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-anc#312]
Change {reminders} field in ANC Reg form from spinner to select one radio button question type and change the label to "Woman wants to receive reminders during pregnancy". Keep the info icon as is. Data dictionary is updated, see ANC Reg tab.

**Comment by ellykits** [comment]
We have these two options with the label bold and normal label: 
![Screenshot_1560944462](https://user-images.githubusercontent.com/26865532/59762608-46b1f080-92a0-11e9-9986-30336b1c63e3.png)
![Screenshot_1560944540](https://user-images.githubusercontent.com/26865532/59762736-955f8a80-92a0-11e9-8953-b2aa02b2cea5.png)

**Comment by cafootitt** [comment]
Normal label pls

**Comment by cafootitt** [comment]
lgtm
