### ISSUE TITLE
Implement ANC client-server data sync

### ISSUE THREAD

**Issue by ndegwamartin** [OpenSRP/opensrp-client-anc#33]
- [x] Sync data from client to server
- [x] Sync Images from client to server
- [x] Sync data from server to client
- [x] Sync Images from server to client
- [x] Unit testing

**Comment by cagulas** [comment]
@ndegwamartin Someone else will have to QA this.

**Comment by ndegwamartin** [comment]
@thats ok

**Comment by ndegwamartin** [comment]
but it basically involves using two devices when testing and seeing if the data created in one reflects in the other. Or just one device after which one clears the data and sees if it syncs back.

**Comment by faith-mutua** [comment]
QA 21 Dec 2018
I can't create a new client. Tapping on the register icon throws the error "No unique ids found"
