### ISSUE TITLE
Hep B routine screening pop characteristic is not displaying

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-anc#337]
![Screenshot_20190913-105137_WHO_ANC](https://user-images.githubusercontent.com/3488986/64846522-87a67080-d615-11e9-9add-09054acc997b.jpg)

National Hep B ANC routine screening program established 
{pop_hepb_screening}

Pls refer to data dictionary, Pop Charact. tab

**Comment by cafootitt** [comment]
QA Sept 30 build:

I'm not seeing this in the app. The screen appears the same way as in the first screenshot.

**Comment by dubdabasoduba** [comment]
![device-2019-09-30-204346](https://user-images.githubusercontent.com/4817531/65902494-37743000-e3c3-11e9-8948-eb53551eed24.png)
Its the second last option

**Comment by cafootitt** [comment]
Great, lgtm. I can see this now in the app update you shared.
