### ISSUE TITLE
Hep B immunization status relevance logic is not working

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-anc#338]
Hep B immunisation status relevance logic doesn't seem to be working:

`{pop_hepb} = 1 OR {pop_hepb_screening} = 1 OR {hiv_positive} = 1 OR {alcohol_substance_use} = "Injectable drugs" OR {occupation} = "Informal employment (sex worker)"`

See data dictionary, Profile tab, row 146.

Does this have something to do with the pop charact. not displaying: https://github.com/OpenSRP/opensrp-client-anc/issues/337?

Also, question: The `{alcohol_substance_use} = "Injectable drugs"` clause of the relevance logic actually appears after the Hep B immunisation status question in the contact workflow. Does this matter? I.e. if the user selects injectable drugs later on, would it make the Hep B immunisation status field active even without visiting the page? I.e. would it show there is one more required field not answered in Profile section?

**Comment by dubdabasoduba** [comment]
@cafootitt if the `{alcohol_substance_use} = "Injectable drugs"` is selected later, when saving it would actually show that one required questions not answered.

**Comment by dubdabasoduba** [comment]
The relevance on Hep B immunisation status is fixed.

**Comment by cafootitt** [comment]
QA 30 Sept build:

This doesn't pass QA. I put in all three of these conditions: {hiv_positive} = 1,  {alcohol_substance_use} = "Injectable drugs",  {occupation} = "Informal employment (sex worker), yet the Hep B immunization status field doesn't show up on the Immunisation Status section of Profile.

**Comment by cafootitt** [comment]
QA 30 Sept app update.

Ok, this is working in the app update that was shared. Thanks.

**Comment by dubdabasoduba** [comment]
@cafootitt I have fixed this do you need a new apk today or we can have this on the 3rd October release
