### ISSUE TITLE
[Discussion] Improvements to the expansion panel

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-anc#341]
We want to talk about the design of the expansion panel in WHO ANC. This was a point of feedback so far from the Brazil and Indonesia teams. Esp. in the C&T container, it doesn't seem efficient to have an expansion panel (which requires 2 more taps) for single questions. As an example, see the "ANC contact schedule counseling" question on the Counseling section in the C&T container. 

Options:
1) Put more time into making the expansion panel a widget that pops up instead of a full page form (like the original design)
2) Put the counseling message (if there is one) into the expansion panel popup instead of hidden in an info icon). Not all questions have an info icon though.
3) Make some of these sections, such as the Counseling section, a scrolling form instead of an expansion panel.

**Comment by cafootitt** [comment]
16 Sept call discussion:

- We'll go with option 3 for C&T, we'll keep the expansion panel in Tests
- Case by case basis for showing the contents of the info icon in the form itself
- This won't have any impact on the Profile Tasks workflow, where we'll still use the expansion panel (as is right now).

**Comment by rowo** [comment]
For the C&T content, I don't think it really requires any changes since the format shouldn't break anything that was working before. Two things do come to mind:
1. Would it help to differentiate the tasks from normal forms fields with some sort of beginning word (like "Task:"?
2. If the task list still behaves as an expansion panel, it would be good to keep the content similar enough so they can be recognizes as matching. I know we talked about combining info icon content and sometimes we used a question format ("Did you..") instead of a task item ("Alcohol counseling") format.

**Comment by cafootitt** [comment]
>> Would it help to differentiate the tasks from normal forms fields with some sort of beginning word (like "Task:"?

I agree it would be helpful to distinguish the high level tasks from the other form fields. 
In addition to your suggestion, I can also think of another one where we bold the high level task or we introduce in-form headings for the task topics.

### Options:

#### A) Main tasks are bolded. Secondary questions are not:

**Postpartum family planning counseling**
- Done
- Not done

FP method accepted
- Oral contraceptive
- Injectable
- Implant
- IUD
- Vaginal ring
- Tubal ligation
- Sterilization (partner)
- None

#### B) Prepend the high level task with "Task"

Task: Postpartum family planning counseling
- Done
- Not done

FP method accepted
- Oral contraceptive
- Injectable
- Implant
- IUD
- Vaginal ring
- Tubal ligation
- Sterilization (partner)
- None

#### C) Add in-form headings for the task topics

**`Birth Plan`**

Planned birth place
- Facility
- Facility (elective C-section)
- Home
- Other

Birth preparedness and complications readiness counseling
- Done
- Not done

**`Family Planning`**

Postpartum family planning counseling
- Done
- Not done

FP method accepted
- Oral contraceptive
- Injectable
- Implant
- IUD
- Vaginal ring
- Tubal ligation
- Sterilization (partner)
- None

Thoughts?

**Comment by cafootitt** [comment]
@rowo Any feedback on the different options? @dubdabasoduba is saying these are all feasible technically.

**Comment by rowo** [comment]
I don't understand C given the examples in A and B. Is that group header the task or a group of tasks?

**Comment by cafootitt** [comment]
@rowo The headers are those found in the data dictionary. So the tasks were initially organized into those categories, but during implementation, we didn't use them when we added the expansion panels.

**Comment by rowo** [comment]
Ok gotcha. I think they can all work fine together. For C, I think that's more about the content (which you have looked at closely), so if you think it'll add enough value for worth the work of defining a new style, that seems okay to me. Do you know what styling constraints we have for doing this "h1" within the form? What is the best data dictionary section I can use to demonstrate all of these changes in one view?

**Comment by cafootitt** [comment]
### PHYSIOLOGICAL SYMPTOMS COUNSELING (row 62 of C&T tab) would be a good example of where the page heading would suffice, and all the questions in that section would be a normal form (no form headings required).

Current app:
![Screenshot_20190924-085246_WHO ANC](https://user-images.githubusercontent.com/3488986/65485004-43cf2900-dea9-11e9-8069-a08495484282.jpg)

### DIAGNOSES (row 163 of C&T tab) would be a good example of where we might want to sub-categorize the different diagnoses, like Hypertension, HIV, etc.

Current app:
![Screenshot_20190924-085610_WHO ANC](https://user-images.githubusercontent.com/3488986/65485020-50538180-dea9-11e9-923a-bdd214adff1d.jpg)


### COUNSELING (row 256 of C&T tab) would be a good example of where the form headings might be helpful.

Current app:
![Screenshot_20190924-085319_WHO ANC](https://user-images.githubusercontent.com/3488986/65485016-4a5da080-dea9-11e9-8b7d-5371a3d948e0.jpg)


>> Do you know what styling constraints we have for doing this "h1" within the form? 

@dubdabasoduba Can you help answer that question ^

**Comment by rowo** [comment]
@cafootitt Sorry — so just to clarify, are you suggesting we apply all of the changes consistently?

**Comment by cafootitt** [comment]
@rowo I think my opinion would be to go with one scrolling form, with the main tasks in bold font, while the sub-tasks/questions would be in normal font (for all sections of C&T, except for Services & Treatments, see last paragraph below)

Just looking through the data dictionary again, I'd have to change the text for anaemia (row 202) if we go in this direction, because the iron/folic acid prescription question doesn't refer to anaemia diagnosis in the main label (it's kind of different from the other diagnosis tasks in that respect). For that same reason, I'd need to change the labels for pre-eclampsia risk (rows 217, 226). I would need to re-arrange birth plan counseling questions as well, maybe moving the birth plan preparedness question to be first.

For the time being, I think it might be good to leave Services & Treatments as is (keep the expansion panels). We could change it, but I think it would take a little focus off of the treatments that need to be given. I think I like how all the major treatment categories, like TT immunization, Malaria prophylaxis, are listed on the expansion panels, and then you click into it to see the dose that is due. If these were all listed together in one scrolling form, you would just have questions like TT dose 1, IPTp-SP dose 1, which might take focus away from the main goal of that treatment. I don't know if this is a good explanation or not though.

**Comment by cafootitt** [comment]
With the exceptions of pre-eclampsia risk counseling and anaemia counseling (both of which are more than just counseling in that they have a medication prescribed), everything else in all sections (apart from Services & Treatments) is just counseling done/not done. 

Services & Treatments (the entire section) and PE risk and anaemia counseling are the only things in the whole C&T container that have something physically given to the woman, like a medicine or a supplement. Everything else is just counseling.

**Comment by cafootitt** [comment]
Cool, so I'm suggesting approach A with the exception of Services & Treatment section, which we would leave as is.

carolyn  3 days ago
You can search for the Services & Treatment section in the data dictionary (row 302)

carolyn  3 days ago
For content to use for mockup, any of the sections I linked to in this comment would be good to use: https://github.com/OpenSRP/opensrp-client-anc/issues/341#issuecomment-534402432

**Comment by rowo** [comment]
Here's a look at A. Seems sufficient. In this case the secondary question only shows up when the first question is answered "done", but you get the idea.


<img width="333" alt="Contact - labs copy 2" src="https://user-images.githubusercontent.com/1584163/66182656-fdfe2780-e643-11e9-83c7-6e51440f3d89.png">

<img width="333" alt="Contact - labs copy" src="https://user-images.githubusercontent.com/1584163/66182658-00608180-e644-11e9-97b9-3a57d78fc6f0.png">

**Comment by cafootitt** [comment]
@rowo Thanks for this. @dubdabasoduba Let's pick this up for further discussion when I get back.

**Comment by cafootitt** [comment]
- All C&T sections a single scrolling form
- Do not make sub-tasks a lighter font. Keep everything consistent.
- Change the text for anaemia (row 202)
- change the labels for pre-eclampsia risk (rows 217, 226)
- re-arrange birth plan counseling questions as well, maybe moving the birth plan preparedness question to be first.

**Comment by cafootitt** [comment]
Closing this and will create a new implementation issue.
