### ISSUE TITLE
Create assets for posting the app to the Play Store

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-anc#342]
- [ ] A short description of the app (up to 80 characters):

Reference software for the 2016 WHO Antenatal Care guidelines

- [ ] Full description of the app (up to 4000 characters):

The WHO ANC reference application was developed for the World Health Organization (WHO). It digitizes WHO’s antenatal care (ANC) guidelines, which were revised in 2016. The app is used by healthcare providers at the facility level to register all pregnant women and record all of their services and treatments during routine pregnancy care. The clinical algorithm provides decision support to the healthcare provider, ensuring they adhere to the guidelines. Women can consent to be contacted via SMS for appointment reminders and messages.

- [ ] Hi-res app icon (512x512 pixels) @rowo 

- [ ] Feature graphic for the app. More info on the feature graphic [here](https://support.google.com/googleplay/android-developer/answer/1078870?hl=en) (1024x500 pixels) @rowo 

- [ ] 3 screenshots of the app

**Comment by cafootitt** [comment]
Deadline to post to the Play Store: October 4th

**Comment by rowo** [comment]
@cafootitt what is the final app title?

**Comment by cafootitt** [comment]
Just confirming with WHO now that it will remain "WHO ANC" for the Play Store posting. Thanks.

**Comment by cafootitt** [comment]
Closing this for now. We're not posting to the Play Store yet.
