### ISSUE TITLE
Fix Anaemia diagnosis alert logic in Haemoglobin test expansion panel

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-anc#348]
See below. The Anaemia diagnosis alert is displayed when it shouldn't be shown. There is no anaemia diagnosis, because the Hb test result is not yet answered. I have also selected "No pallor" as well.

To replicate:
- Register a new ANC woman
- Start Contact 1
- In PE container, record woman has no pallor (Maternal Exam section)
- In Tests container, go to Hemoglobin test and select done today, complete blood count test. You'll see the Anaemia diagnosis alert show up.

The alert should show up if `{anaemic} = 1`
The Anaemic calculation is as follows: `if(({hb_result} < 11 AND ({gest_age} <= 12 OR {gest_age} >= 28)) OR ({hb_result} < 10.5 AND ({gest_age} > 12 AND {gest_age} < 28)) OR ({hb_results} = '' AND {pallor} = "Yes"), 1, 0)`

In this case, Hb results are blank, because they haven't been entered yet, but pallor is "No", so no alert should show up.

![Screenshot_20190924-085147_WHO ANC](https://user-images.githubusercontent.com/3488986/65485197-d374d780-dea9-11e9-87f6-edadfd4da7d2.jpg)

**Comment by cafootitt** [comment]
QA 30 Sept release:

lgtm

**Comment by cafootitt** [comment]
Sorry, I closed this too soon. I tested another condition, where this is not working.

If the user selects Pallor, but afterwards enters a *normal* Hb level under Hb test, then the woman is not anaemic and therefore, the alert and the diagnosis and counseling should not appear. 

Please refer to this part of the calculation: `({hb_results} = '' AND {pallor} = "Yes")`
So, pallor is only used to diagnosis anaemia in the absence of an Hb test result. So, if you enter a normal Hb test result, then the pallor condition should not result in an anaemia diagnosis.

To pass QA:

- Register a new woman, then open Contact 1
- Under PE tab, mark that the woman has pallor (anaemia diagnosis should appear)
- Under Haemoglobin (Hb) test in Tests container, enter a normal Hb test result, e.g. 12. The anaemia alert still appears when it shouldn't.

**Comment by dubdabasoduba** [comment]
@cafootitt I have fixed this do you need a new apk today or we can have this on the 3rd October release

**Comment by cafootitt** [comment]
3rd October release is fine. Thanks for checking.

**Comment by cafootitt** [comment]
lgtm
