### ISSUE TITLE
Add additional attention flag logic for one of the pelvic exam reasons

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-anc#364]
- [x] See PE tab, row 146. If {pelvic_exam_abnormal} has "Evidence of amniotic fluid" selected as one of the reasons, then we display a new red alert with the label: 
"Evaluate labor. Urgent referral if GA is less than 37 weeks."

To pass QA:
- Register a new woman and open Contact 1
- in PE tab, select amniotic fluid as an abnormal pelvic exam reason
- The red flag should appear beneath with the correct label.

**Comment by dubdabasoduba** [comment]
@cafootitt I am not sure whether this should appear in the main form or on the popup form. I have currently added it to appear on the popup form where the question is.

**Comment by cafootitt** [comment]
That is fine, I think. Thanks.

**Comment by cafootitt** [comment]
V1.2.2 - lgtm
