### ISSUE TITLE
Update all the ANC servers versions to something >= 1.5.0-SNAPSHOT

### ISSUE THREAD

**Issue by dubdabasoduba** [OpenSRP/opensrp-client-anc#400]
Due the compression of data being uploaded to OpenSRP update made by the reveal team, we need to update our servers so as to use this functionality

- Stage Server : - this can be updated any time - LOE (3 - 4 hours). This is because we need to update staging inventories to match the current format we have of the other deployments. 

- ANC default Preview Server : - This we be updated on a day the Brasil team not using the server. LOE (1-2 hours) to allow for testing that all the data sync back to the client app as required. 

- ANC Indonesian Server : - This will be updated on a day the Indonesian team in not using the server.  LOE ( 1 hour max).

**Note : -** After the testing on either of the preview servers depending on which is deployed first i.e (Brasil or Indonesia) the testing done on the first server will be proof that the update works well with ANC so the LOE might even be less than and hour for the second server update. 

@cafootitt could you talk to the respective teams on the days they can spare for this update? It would be nice if you can get them to agree to the same day. 

This update will also be used with the client core version >= `opensrp-client-core:1.8.0-SNAPSHOT`,  this means we will need to send new APK's to the teams after the updates.

**Comment by cafootitt** [comment]
@dubdabasoduba Let's do the stage and preview (Brazil) servers before the end of this week. Brazil is going to start user testing again start of next week, so let's upgrade it before end of week. Still waiting to hear back from Indonesia.

**Comment by dubdabasoduba** [comment]
- [ ] Stage server update

- [ ] Brasil Preview server update 

- [ ] Brasil APK update

- [ ] Indonesian preview server update

- [ ] Indonesian APK update
