### ISSUE TITLE
Workflow for post-registration [UAT feedback response]

### ISSUE THREAD

**Issue by rowo** [OpenSRP/opensrp-client-anc#401]
Summary: This splits off of https://github.com/OpenSRP/opensrp-client-anc/issues/399. It concerns feedback for "[It is not clear what we have to do after registering.](https://docs.google.com/document/d/1FqEfbpxFeDQ2BiFY1-ZUQ0gMvbFFIiGfgFiGTz0Cazg/edit#bookmark=id.eastyuo7i6kk) It does not continue to the next step, which would be starting a new visit. How to include information of the new visit? More difficult than should be."

### Current:
Immediately after the registration form is saved, it goes to the unfiltered register list view with the person who was added as the top row (and a "contact 1" button in that row). 

When that profile is tapped, it shows this seemingly empty profile:
<img src="https://user-images.githubusercontent.com/3488986/69057500-0e673780-0a23-11ea-8a2a-7f57fcc4ba9c.jpg" width="300">

### Updates:
- [ ] 1. Immediately after the registration form is saved, it should go to the profile of the person that was just created.
- [ ] 2. This profile needs to be updated so the button of the contact appears at the bottom. Currently, the button appears below the fold even though there is no data for that person pushing the content down.
- [ ] 3. This empty state should include instructional text and an arrow to indicate the next step:
<img src="https://user-images.githubusercontent.com/1584163/69095980-761c8300-0a21-11ea-821d-191fa8dab3f0.png" width="300">

**Comment by cafootitt** [comment]
Blocked until I get final go-ahead from WHO.

**Comment by rowo** [comment]
I will need to update the empty state arrow graphic as well before this actually gets made.

**Comment by cafootitt** [comment]
@rowo Ok, thanks for the heads up. WHO just gave the ok for these changes. When do you think you can get to this?

**Comment by rowo** [comment]
Before eod Thursday my time

**Comment by rowo** [comment]
Here are the specs: https://marvelapp.com/9j1277a/screen/63920582/handoff
