### ISSUE TITLE
Implement changes to the button statuses on main register list page

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-anc#402]
- [x] Text for orange in progress button: CONTACT {0} IN PROGRESS
- [x] Make sure the "IN PROGRESS" part fits on one line
- [x] Text for upcoming contact due: CONTACT {0} DUE {date}
- [x] Make sure the "DUE" and "DATE" go on separate lines
- [x] Text for red overdue button: "START CONTACT {0} {date}"
- [x] Make sure Contact 2 and date fit on separate lines
- [x] Text for blue due contact: "START CONTACT {0} {date}"

![image](https://user-images.githubusercontent.com/3488986/69213352-da039080-0b74-11ea-8fe4-7bada88d71f3.png)

**Comment by dubdabasoduba** [comment]
@cafootitt What do you think about this? 
![device-2019-12-05-164122](https://user-images.githubusercontent.com/4817531/70240378-2d353000-177e-11ea-8f61-3934832917ce.png)

**Comment by dubdabasoduba** [comment]
![device-2019-12-05-171457](https://user-images.githubusercontent.com/4817531/70242993-d8e07f00-1782-11ea-88af-bd3a5a075dc9.png)

**Comment by cafootitt** [comment]
looks perfect!

**Comment by cafootitt** [comment]
lgtm
