### ISSUE TITLE
Test results are wiped if you navigate to other tests and press save

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-anc#414]
Steps to replicate:

- Open Contact 1 for a new woman
- In Tests container, enter test results for all tests in the Due tab
- after entering the last test on the page (should be TB screening), click on the next button at the bottom
- then tap on the SAVE button in the top right on the Other Tests page (don't submit any test results on this page)
- Re-open the Tests container. You'll see that all of the Test results you entered are cleared and you have to start over.

**Comment by dubdabasoduba** [comment]
@cafootitt checking this out. Let me confirm if it affects the other contact container too.

**Comment by dubdabasoduba** [comment]
@cafootitt This now fixed. This affected all the contact containers.

**Comment by cafootitt** [comment]
@dubdabasoduba Awesome, thanks for quick work on this.

**Comment by cafootitt** [comment]
lgtm
