### ISSUE TITLE
Implement main contact page

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client-anc#42]
~~@rowo Pls replace with the actual mockup. It was scrolling, so wasn't able to capture all of it. Also, please post the assets for this issue.~~ Replaced mockup

<img src="https://user-images.githubusercontent.com/1584163/44241647-3e29ee80-a193-11e8-9631-74cf614e50d8.png" width="480">
<img src="https://user-images.githubusercontent.com/1584163/44241648-3e29ee80-a193-11e8-9afc-fed86cbcb621.png" width="480">

- [x] You land on this page after you complete the [quick check flow](https://github.com/OpenSRP/opensrp-client-anc/issues/40), or when you open a saved contact (orange button status) on the main register page.
- [x] Woman's `first_name` `last_name` appears in top bar.
- [x] X button in top left takes user to the contact save widget (https://github.com/OpenSRP/opensrp-client-anc/issues/43) before returning to the page she was on before she started the contact (i.e. main register page or woman's profile page)
- [x] Finalize button in top right is greyed out and cannot be selected until all required fields in the contact containers are filled (see both statuses above).
- [x] View ANC History button at the bottom opens up a full dialog widget for the user to review the woman's profile during the contact (issue to be created)
- [x] The 6 contact containers shown are the final ones, @rowo to provide color codes and images for these. Each contact container opens that section of the contact (issues to be created)
- [x] Each contact container shows how many required fields are still not answered. The actual number of required fields will vary, random numbers were chosen for the mockup.
- [x] When all required fields are answered, the Complete status is shown.

**Comment by rowo** [comment]
Icon graphics in 1024 and 512:

![counseling-512](https://user-images.githubusercontent.com/1584163/44113183-432de41e-9fd5-11e8-9082-8946ad389b6c.png)
![counseling-1024](https://user-images.githubusercontent.com/1584163/44113184-43374b94-9fd5-11e8-9d92-1a91074f517c.png)
![physical-512](https://user-images.githubusercontent.com/1584163/44113185-4340726e-9fd5-11e8-93d0-e7aa98f3b07e.png)
![physical-1024](https://user-images.githubusercontent.com/1584163/44113186-434a4870-9fd5-11e8-8e7c-19cb49e27b70.png)
![profile-512](https://user-images.githubusercontent.com/1584163/44113187-43539d8a-9fd5-11e8-990a-5475dcffcdde.png)
![profile-1024](https://user-images.githubusercontent.com/1584163/44113188-435e1e86-9fd5-11e8-95f6-d44857c322ad.png)
![quickcheck-512](https://user-images.githubusercontent.com/1584163/44113189-4367085c-9fd5-11e8-8cc3-3540c47f409b.png)
![quickcheck-1024](https://user-images.githubusercontent.com/1584163/44113190-43708f80-9fd5-11e8-9556-3cffb5808176.png)
![symptoms-512](https://user-images.githubusercontent.com/1584163/44113191-437af6fa-9fd5-11e8-91df-76c1ea586f2b.png)
![symptoms-1024](https://user-images.githubusercontent.com/1584163/44113193-43b67ba8-9fd5-11e8-84de-874f5394797a.png)
![tests-512](https://user-images.githubusercontent.com/1584163/44113194-43c2dcc2-9fd5-11e8-89f9-e9a7d85a16a7.png)
![tests-1024](https://user-images.githubusercontent.com/1584163/44113195-43d4a3c6-9fd5-11e8-8f7f-54118b2fc713.png)

**Comment by cagulas** [comment]
QA 11th October build:

- [ ] There is too much white space around the containers, which is causing "Physical Exam" to roll over to the next line, among others. Let's expand the contact containers width and height until they are just barely not touching, as you can see in Roger's mockups above.
- [ ] This might be a nice-to-have for now, but it would be nice for the contact container icons to adjust in size automatically so that they never overlap with any of the wording.

**Comment by cagulas** [comment]
QA 18th Oct build:

- [ ] Sorry, I forgot to include this in the last QA round, but let's increase the font size for the woman's name and the Finalize button at the top. Both look very small now. Also, let's add a couple more spaces or so between the top X button and the woman's name.

**Comment by cagulas** [comment]
QA;

- [ ] On the main contact screen, please put back the top left X. It was swapped out with the contact container icon. The contact container icon only goes in the sub-forms, not on the main contact container page.

**Comment by cagulas** [comment]
lgtm!
