### ISSUE TITLE
Show contact button on ANC profile page without needing to scroll

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-anc#422]
Please refer to original issue: https://github.com/OpenSRP/opensrp-client-anc/issues/403

The ANC profile needs to be updated so the button of the contact appears at the bottom. Currently, the button appears below the fold even though there is no data for that person pushing the content down.

**Comment by dubdabasoduba** [comment]
![Peek 2020-01-13 13-05](https://user-images.githubusercontent.com/4817531/72247215-75f5c980-3605-11ea-9af1-54d491db9e7e.gif)
@cafootitt I tried the GIZ way but that affects the collapsible tool bar.

**Comment by dubdabasoduba** [comment]
![Peek 2020-01-13 15-03](https://user-images.githubusercontent.com/4817531/72254676-dab92000-3615-11ea-81f1-1a0f909bdb6d.gif)
@cafootitt What do you think about this?

**Comment by cafootitt** [comment]
lgtm
