### ISSUE TITLE
Fix calculation/relevance logic in C&T

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-anc#428]
After the fix to add back all relevance logic (https://github.com/OpenSRP/opensrp-client-anc/issues/424), I'm noticing some relevance errors in C&T:

- pre-eclampsia diagnosis not appearing when it should
- pre-eclampsia risk diagnosis appearing when it shouldn't.

**Comment by dubdabasoduba** [comment]
@cafootitt is this on the toaster notes?

**Comment by cafootitt** [comment]
Yes, on the toasters.
