### ISSUE TITLE
Implement contact save widget

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client-anc#43]
<img width="410" alt="screen shot 2018-08-02 at 10 03 31 am" src="https://user-images.githubusercontent.com/3488986/43597857-43c58284-9651-11e8-9c5f-ca4870c114ff.png">

- [x] This widget pops up when the user presses the cancel (X) button on the [main contact page](https://github.com/OpenSRP/opensrp-client-anc/issues/42) (or the device back button)
- [x] Replace {name} with the woman's `first_name` and `last_name`
- [ ] The Save Changes option saves all of the data entered so far in the contact form and takes the user back to where she was before she entered the contact (either main register page or woman's profile view). On the main register page, the contact button changes to the orange status. If the user presses the orange contact button again, they are taken back to the main contact page to continue where the user left off.
- [ ] The close without saving option clears all data the user has entered so far in the contact and takes the user back to where she started the contact from (main register page or woman's profile view). The contact button reverts to the status it was before the contact started.
- [x] The Cancel button (or tapping anywhere outside the widget) closes the widget (they see the contact page again)

**Comment by cagulas** [comment]
@rowo Feedback from project showcase was about these buttons not looking like buttons. Flagging the issue for you if you want to take a look.

**Comment by ndegwamartin** [comment]
![image](https://user-images.githubusercontent.com/10017086/46399444-66988880-c700-11e8-8480-8802fe36d34c.png)
@rowo what do yo think? ideas?

**Comment by rowo** [comment]
@ndegwamartin  what do you think about this?

<img width="493" alt="dialog-closecontact" src="https://user-images.githubusercontent.com/1584163/46428268-884e3b80-c711-11e8-8ddf-fcab695b8aa3.png">

**Comment by ndegwamartin** [comment]
@rowo this looks great! thanks

**Comment by cagulas** [comment]
QA 18th Oct build:

- [ ] Don't capitalize "Contact"
- [ ] Can we slightly increase the width of the widget and the buttons so that "time" fits on the same line?

**Comment by cagulas** [comment]
Closing this and the remaining functionality moved to a new issue https://github.com/OpenSRP/opensrp-client-anc/issues/133
