### ISSUE TITLE
Fix regression bugs in V1.2.9 release (build date 10 Jan 2020)

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-anc#439]
- [ ] Woman's name is missing in the contact container page (screenshot 1)
- [ ] Unable to open Profile container in subsequent contacts (screenshot 1)
- [ ] Woman's details are missing on profile top nav bar after scroll (screenshot 2)
- [ ] All contact buttons are showing Contact 1 done after the release update (screenshot 3) instead of the accurate contact status
- [ ] Contact 1 done button shows non-human readable text (screenshot 3)
- [ ] Profile page avatar and demographic info is missing (screenshot 4)
- [ ] Every single profile is showing Charity Otala as the woman's name instead of the actual woman's name and details (screenshot 4)

## Screenshot 1
![Screenshot_20200115-091026_WHO_ANC](https://user-images.githubusercontent.com/3488986/72410210-eec96280-3778-11ea-8835-8404981805c3.jpg)

## Screenshot 2
![Screenshot_20200115-090818_WHO_ANC](https://user-images.githubusercontent.com/3488986/72410287-1fa99780-3779-11ea-8331-ae407b605fd8.jpg)

## Screenshot 3
![Screenshot_20200115-090823_WHO_ANC](https://user-images.githubusercontent.com/3488986/72410399-60a1ac00-3779-11ea-8d8e-b5d3817c34a9.jpg)

## Screenshot 4
![Screenshot_20200115-090813_WHO_ANC](https://user-images.githubusercontent.com/3488986/72410523-90e94a80-3779-11ea-8ab1-9ea322c756b4.jpg)

**Comment by dubdabasoduba** [comment]
@cafootitt which device are you using?

**Comment by dubdabasoduba** [comment]
I might haven't noticed all this on my emulator

**Comment by cafootitt** [comment]
Samsung Galaxy A10. You can borrow it when you get in.

**Comment by dubdabasoduba** [comment]
![device-2020-01-15-114401](https://user-images.githubusercontent.com/4817531/72418699-65bc2680-378c-11ea-8936-a0d17763fc7e.png)
![device-2020-01-15-114351](https://user-images.githubusercontent.com/4817531/72418700-65bc2680-378c-11ea-880e-2d3ccc0375cb.png)
![device-2020-01-15-114316](https://user-images.githubusercontent.com/4817531/72418701-65bc2680-378c-11ea-8dc3-4e9a379c3d4b.png)
![device-2020-01-15-114304](https://user-images.githubusercontent.com/4817531/72418702-6650-378c-11ea-86ac-a58723f9bd8f.png)
![device-2020-01-15-114225](https://user-images.githubusercontent.com/4817531/72418703-6654bd00-378c-11ea-9662-e3884ae71ed3.png)
@cafootitt I can't seem to replicate the bugs mentioned above. I will add the can't replicate tag and  move this back to in progress just in case we can replicate it in future.
