### ISSUE TITLE
Implement search by QR code and results

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client-anc#44]
Note: no mockup for this issue.

- [x] On the main register page (https://github.com/OpenSRP/opensrp-client-anc/issues/1), the QR code button launches the barcode scanner app (if no scanner app is installed, direct the user to install it from the play store).
- [x] This is an in area search only. So if there is a match, display the record in the list. To cancel this search, the user can X the ANC ID from the search bar, which should display the ANC ID from the QR code search.
- [x] If there is no match, display a widget like from zeir where it asks if they want to continue with an advanced search, see below from zeir:

<img width="266" alt="screen shot 2018-08-02 at 2 53 52 pm" src="https://user-images.githubusercontent.com/3488986/43604560-151d26b8-9664-11e8-8ba0-06551554436e.png">

- [x] In the above widget, instead of "No matching person..." say "No matching woman found on this device. "
- [x] Remove the two buttons. Instead, two options should be shown below: "Cancel" and "Go to advanced search"
- [x] If they hit Cancel (or tap the device back button or tap anywhere outside the widget) it closes.
- [x] The Go to advanced search button opens the advanced search dialog with the ANC ID pre-filled from the QR code.

@rowo Can you review this, since we didn't specifically discuss the layout and wording of this, and there's no mockup for it?

@ndegwamartin Note this is a slight expansion of the original issue (https://github.com/OpenSRP/opensrp-client-anc/issues/17).

**Comment by cagulas** [comment]
QA results from 23 August 2018 build:

- [ ] The functionality is correct, but the popup widget needs to be cleaned up:

![screenshot_20180824-175425](https://user-images.githubusercontent.com/3488986/44591646-fb859900-a7c6-11e8-817d-55ab1afa5ed8.png)

@rowo Can you advise please? Should the advanced search be a button like above in the snapshot from ZEIR?

**Comment by rowo** [comment]
@ndegwamartin @cagulas yes we can use the same styling if it's there already. I'm not exactly sure about the wording and if the user will understand what records will be on the device versus being able to search out of facility records on advanced search (since that's only an option on advanced search and if they don't do it, they'll get the same result).

**Comment by cagulas** [comment]
@rowo This will have to be part of training, definitely. I don't think we got feedback from Zambia that this was confusing, but I don't know if it was used as intended, either. I think let's go with what's proposed, and we'll see during user testing if there's any confusion.

**Comment by cagulas** [comment]
QA 11th Oct build:

- [ ] Don't capitalize every word in "Go to advanced search". Only capitalize Go.
- [ ] If you hit cancel on the no matching woman pop-up (or back button or anywhere outside the widget), it should cancel the search. Right now, it just closes the pop-up widget, but the ID remains in the search bar and you have to cancel that as well.
- [ ] There is a notable 1-2 second delay for the no matching pop-up to appear after scanning the QR code. This didn't happen on the first attempt but subsequent attempts only. Not sure why this is.
- [ ] I'm getting the below error message a couple of times I am using the QR search. I have to restart my device to be able to use the QR scanner app again. Do we think this is related to the app? I have never seen this before in the QR scanner app for any other OpenSRP app before.

![screenshot_20181012-091502](https://user-images.githubusercontent.com/3488986/46851213-69316700-cdff-11e8-99f8-c75bf0e90c3f.png)

**Comment by cagulas** [comment]
Closing and moving the last issue to a new one: https://github.com/OpenSRP/opensrp-client-anc/issues/131
