### ISSUE TITLE
Performance improvements

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-anc#444]
Please profile the performance of these really slow actions in the ANC reference app:

- Tapping the NEXT button to advance to the Current Pregnancy page in Profile
- Entering pre-gestational weight in Physical Exam, Height & Weight section
- Tapping on urine test in Tests container
- Tapping on Blood Haemoglobin test in Tests container and filling out the fields in the expansion panel
- In general, filling out the fields in the Tests expansion panels is really slow
- Tapping on NEXT to advance to the Immunizations section in the C&T section

**Comment by ndegwamartin** [comment]
@cafootitt  from our analysis, appears with the current architecture we might not achieve a better experience for effort ratio, It might be better to re-architect the the library to implement some of the recommendations that came out of our discussions in 2019 and are documented [here](https://docs.google.com/document/d/125JIFL09oyGRg8V8e2IduhsYHeSZxEySc92hH_8MyAo/)

**Comment by cafootitt** [comment]
Performance issues were addressed during the Malawi project and changes merged back to master. Closing this.
