### ISSUE TITLE
Add counseling pdf materials to Library

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-anc#448]
We need to load the below 3 counseling pdfs into the "Library" menu in the app.

Names to appear in the menu:

Balanced Nutrition
Physical Activity
Birth and Emergency Plan

Pdfs:
[BIRTH AND EMERGENCY PLAN.pdf](https://github.com/OpenSRP/opensrp-client-anc/files/4128992/BIRTH.AND.EMERGENCY.PLAN.pdf)
[PHYSICAL ACTIVITY.pdf](https://github.com/OpenSRP/opensrp-client-anc/files/4128995/PHYSICAL.ACTIVITY.pdf)
[Balancednutrition.pdf](https://github.com/OpenSRP/opensrp-client-anc/files/4128996/Balancednutrition.pdf)

**Comment by dubdabasoduba** [comment]
@cafootitt do you have a design idea of how this page should look like? @rowo your input on how this page might look would be helpful

**Comment by rowo** [comment]
This could look the same as the Guidebooks in the CHW app (no download/play button though).. just rows that go to the documents.

Also, was there any discussion on not using PDFs? I feel like reading PDFs on devices suck since they have rigid formatting.

**Comment by dubdabasoduba** [comment]
@cafootitt How often will the content on these PDF's change?

**Comment by cafootitt** [comment]
@rowo There wasn't a discussion on not using pdfs. What alternatives are there? We have the content in a google document.

@dubdabasoduba Not often for the reference app.

**Comment by rowo** [comment]
@cafootitt Alternatives to PDFs is probably a question for @dubdabasoduba. I think since we have the unformatted content, it's just about what's easiest to develop so we can render at the correct readable sizes no matter the device. Something like .txt, or .md or .html file if it needs italics/bolds.

**Comment by cafootitt** [comment]
Decision: Android views will allow us to add MLS, it will also reformat to screen size.

**Comment by dubdabasoduba** [comment]
- [ ] Add the material selection page. Will have a look that's almost as the image attached
![Screenshot_1580715408](https://user-images.githubusercontent.com/4817531/73634235-cba41b80-4671-11ea-8288-8daef806b329.png)

- [ ] Create the content page which will hold the library content.

**Comment by cafootitt** [comment]
LGtm

**Comment by rowo** [comment]
@cafootitt what is MLS?

**Comment by cafootitt** [comment]
multi-language support
