### ISSUE TITLE
Contact info does not update right away in the Profile

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-anc#464]
Steps to replicate:

- Register a woman
- Fill out Contact 1 for a woman
- Finalize & close the contact
- The Overview, Contacts tab are still blank, instead of showing the filled out contact info
- To see the contact info, you must go back to the register page then open the profile page again.

**Comment by dubdabasoduba** [comment]
@cafootitt I could not replicate this with the current release. Please retest it again.

**Comment by cafootitt** [comment]
V1.2.13 - no longer an issue.
