### ISSUE TITLE
Syphilis test is missing in Tests tab even though it was skipped in Tasks

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-anc#477]
Steps to replicate:

- Register a woman and fill in Contact 1
- In Tests, mark all tests as not done
- Submit the contact visit and go to Tasks
- Fill in test results for TB, Blood Type, and Blood Hemoglobin only (leave Urine, Syphilis, Hep C, and Ultrasound blank)
- Wait a day
- Go back to the woman and start a new contact
- Go to Tests container. 

Expected result:
- TB, Blood Type, and Blood Hemoglobin should not appear in the due list
- Urine, Syphilis, Hep C, and Ultrasound should appear in the due list

Actual result:
- Blood Type, Blood Hemoglobin do not appear
- TB appears at first, but if you exit the contact and then re-open it, it disappears
- Urine, Hep C, and Ultrasound appear
- Syphilis does not appear when it should

**Comment by dubdabasoduba** [comment]
@cafootitt does the due logic for syphilis allow it to be shown for that contact?

**Comment by cafootitt** [comment]
Yes

**Comment by dubdabasoduba** [comment]
@cafootitt 
`      {
        "key": "accordion_syphilis",
        "openmrs_entity_parent": "",
        "openmrs_entity": "",
        "openmrs_entity_id": "",
        "text": "Syphilis test",
        "accordion_info_text": "A syphilis test is recommended for all pregnant women at the first contact and again at the first contact of 3rd trimester (28 weeks). Women who are already confirmed positive for syphilis do not need to be tested.",
        "accordion_info_title": "Syphilis test",
        "type": "expansion_panel",
        "content_form": "tests_syphilis_sub_form",
        "container": "anc_test",
        "relevance": {
          "rules-engine": {
            "ex-rules": {
              "rules-file": "tests_expansion_panel_relevance_rules.yml"
            }
          }
        },
        "is_visible": false
      }`
The relevance & is setting due logic is making it invisible. I am re-checking the rules to make sure they are well defined.

**Comment by dubdabasoduba** [comment]
`"is_visible": false` this part shows its hidden due to relevance of due logic

**Comment by cafootitt** [comment]
@dubdabasoduba There is no expiry for syphilis test, so if it's not given in the first contact, it's due until it's done. After it's done, it becomes due again at 28 weeks.

Unless there is a specific expiry mentioned, i.e. TT vaccine, then all services are due until given.

**Comment by cafootitt** [comment]
V1.2.14

Syphilis test is appearing, but now Blood Haemoglobin test is appearing when it shouldn't be.

Steps to replicate:
- Register a new woman
- Complete Contact 1
- In Tests, mark Blood Haemoglobin test is ordered (I also marked every other test as ordered - not sure if that makes a difference)
- Submit the contact
- In Tasks tab, fill in the Blood Haemoglobin result
- Wait a day
- Start Contact 2, go to Tests and you see Blood Haemoglobin test is showing, even though it was recorded in Tasks.

**Comment by cafootitt** [comment]
V1.2.14 - lgtm
