### ISSUE TITLE
Implement Profile contact container of contact

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client-anc#48]
The Profile contact container is the dark purple section of the contact (next to Quick Check). All content, logic, calculations, etc. should come from the data dictionary, Profile tab. This section is different from all the other sections in the contact, in that all of the questions in this section are asked during the **first** contact only. In subsequent contacts, the user can still review this section and make edits if desired.

![contact-profile-demo](https://user-images.githubusercontent.com/3488986/44215272-c5b73380-a17a-11e8-8dc4-f76ab2fbd51b.png)

- [x] The top left icon takes the user back to the main contact menu, saving automatically all the progress made so far in the contact container. This will be the behavior for every contact container. 
- [x] Name of the contact container the user is currently in, i.e. "Profile"
- [ ] The hamburger menu on the top right is another shortcut that allows the user to quickly navigate between sections within the contact container and also quickly jump to another contact container (see mockup below)

![subnav-profile](https://user-images.githubusercontent.com/3488986/44215726-e8961780-a17b-11e8-853f-d0946c001f7e.png)
*Note in the mockup above, the contact number appears at the top and also the names of the containers have changed since this mockup was created. Please use the contact container names in the main contact menu (https://github.com/OpenSRP/opensrp-client-anc/issues/42), not what you see here.

- [x] The different sections of the contact container are separate pages that the user can flip through using the right and left arrows at the top, the top right hamburger menu, or the previous and next buttons at the bottom. The different sections are marked in the data dictionary within the Profile tab in dark pink highlighting. Within a section, you can scroll up and down to view all the questions.

Some other screens below showing question styling:

![contact-profile-current](https://user-images.githubusercontent.com/3488986/44252724-cea11700-a205-11e8-8343-0ec55d7a601a.png)

- [x] Red asterisk denotes a required field
- [x] Note styling (see https://github.com/OpenSRP/opensrp-client-anc/issues/50)
- [x] Tapping the grey info icon opens up a small popup window with content from "Info icon" column in data dictionary - not all fields have an info icon though, see data dictionary for exact content. Tapping X or anywhere outside the info icon popup closes it (no mockup provided, but similar to https://github.com/OpenSRP/opensrp-client-anc/issues/24)
- [x] In the mockup above, there is a new question style for some date questions. Asking a yes/no question first, then if yes selected, a date widget popup appears, where they select the date. Once date is selected and popup closes, the date selected appears in the question in the "yes" row and a "tap to change" hint appears (see mockup below for that state).

![contact-profile-current02](https://user-images.githubusercontent.com/3488986/44253281-c649db80-a207-11e8-9362-036abfdf42fb.png)

- [x] For no. of pregnancies integer field, we're trying a new styling for integer question (see below). 

![contact-profile-ob01](https://user-images.githubusercontent.com/3488986/44253604-cdbdb480-a208-11e8-97d6-cf48c06861b4.png)

- [x] Tapping 5+ opens an integer widget, where they can select a higher number (see below mockup - but note, the data constraint allows user to select up to 15, not 20 as is shown)

![contact-profile-preg-dropdown](https://user-images.githubusercontent.com/3488986/44253764-4a509300-a209-11e8-9cf2-e57d7e8f7ed2.png)

- [x] After selecting a number higher than 4 above:

![contact-profile-ob02](https://user-images.githubusercontent.com/3488986/44253895-c5b24480-a209-11e8-9853-34457ddb187f.png)

- [x] Medical History section:

![contact-profile-med](https://user-images.githubusercontent.com/3488986/44253949-fa260080-a209-11e8-957f-52e9f21f9d26.png)

- [x] Immunisation status section:

![contact-profile-imm](https://user-images.githubusercontent.com/3488986/44254006-217ccd80-a20a-11e8-87df-693180e08bcb.png)

- [x] Medications in use, Woman's behaviour, Partner's HIV status sections (no mockups for these, but follows same format as above)
- [ ] If there's not going to be a screen space issue, instead of "Previous" and "Next" options at the bottom, it would be good to show the name of the section as well (see Obstetric History mockup above as an example). We can shorten the names to make this work, i.e. "Medications in use" --> "Medications". I can add the short-hand name in the data dictionary.

**Comment by cagulas** [comment]
QA 17th Oct build:

- [ ] Capitalize "i" in "Demographic info"
- [ ] Replace the top left X with the contact page icon
- [ ] "Profile" can be closer to the left hand side, see mockups - it is near to the contact page icon
- [ ] When you tap the top left contact page icon, you should be taken back to the main contact page without having to confirm form close. Saving the data entered should be automatic when you leave a sub-form
- [ ] Let's hide the top right navigation option for now. We may or may not implement this, so let's hide it for now.
- [ ] Don't capitalize "Level" or "School" in first question. Please copy-paste exactly what's in the data dictionary.
- [ ] First two questions should be required - please carefully follow what's in the data dictionary
- [ ] Other specify text field not implemented yet.
- [ ] I'm noticing that there is a "calculation" in red font appearing instead of performing the actual calculation field. Is this not implemented yet? Is this something we need to put in the release notes that's not working yet?
- [ ] Don't capitalize "Known" in LMP known
- [ ] Specify date on LMP known not working yet
- [ ] Don't capitalize "Done" in ultrasound done
- [ ] Logic for the notes are not working yet
- [ ] don't capitalize "Tap to Change" - all lowercase please
- [ ] In general I think we can reduce the font size a bit in these sub-forms. Even small lines are getting cut off to the next line.
- [ ] Pls check and implement the constraint logic from the data dictionary - for e.g. GA from ultrasound - days does not have the constraint logic added. Pls double-check that it's added for all fields if indicated in the data dictionary.
- [ ] Pls check the skip logic in the profile. I don't think it's been implemented yet. For e.g. GA from SFH shouldn't be asked unless LMP is unknown and ultrasound GA is >= 24 weeks. Check the "Relevance" column in the data dictionary.
- [ ] The GA and EDD are not displaying for the select preferred gest. age question.
- [ ] Increase the left hand margin on the numeric pop-up widget (i.e. the widget that pops up when you select 5+ for no. of pregs)
- [ ] Partner HIV status missing "negative" answer choice

**Comment by cagulas** [comment]
QA 18th Oct build:

- [ ] Let's increase the spacing between the questions and the answer choices. They are too close together right now on all of the pages except Obstetric History and Current Pregnancy pages.
- [ ] I'm seeing red "0"'s at the bottom of each page now. These seem to have replaced the red calculations.
- [ ] As soon as you tap "yes" for LMP and ultrasound, the date widget should open. Right now, after you tap yes, you also have to tap on the "specify date" to open it.
- [ ] If you tap on the date to select the date, it should automatically select yes as the answer choice. Right now, you can select no, then enter a date, and the answer remains on no.
- [ ] The logic for displaying the notes doesn't seem to be working yet. See ultrasound-related notes.
- [ ] Required fields don't have to be answered until you try to finalize the form. So you can leave the page without answering all required fields. Right now, I can't move past current pregnancy page unless I enter GA from SFH.

**Comment by faith-mutua** [comment]
QA 20th Dec 

The first two issues have been fixed.  The following are yet to be fixed. 

- [ ] As soon as you tap "yes" for LMP and ultrasound, the date widget should open. Right now, after you tap yes, you also have to tap on the "specify date" to open it.
- [ ] If you tap on the date to select the date, it should automatically select yes as the answer choice. Right now, you can select no, then enter a date, and the answer remains on no.
- [ ] The logic for displaying the notes doesn't seem to be working yet. See ultrasound-related notes.
- [ ] Required fields don't have to be answered until you try to finalize the form. So you can leave the page without answering all required fields. Right now, I can't move past current pregnancy page unless I enter GA from SFH.

**Comment by cagulas** [comment]
Closing this issue, compiling all remaining QA into https://github.com/OpenSRP/opensrp-client-anc/issues/165
