### ISSUE TITLE
Fix `Key Not found` Exception in case a key is not found on a language specific property file

### ISSUE THREAD

**Issue by dubdabasoduba** [OpenSRP/opensrp-client-anc#492]
Currently the application will force close in case a key is not found on the language specific property file. In this scenario we need to display what the default property file holds for that key. 

In case the default property file does not have the key we should skip this interpolation and display this  raw key on the form. 

- [ ] Update the translation functionality to always revert to using the default language in case something doesn't exist in the language specific property files. 

- [ ] Display the interpolated key on the form in case its property is missing for all the language translations including the default ones.

**Comment by cafootitt** [comment]
This was fixed already by @vincent-karuri some time back. Closing.
