### ISSUE TITLE
Update the GET settings endpoint.

### ISSUE THREAD

**Issue by dubdabasoduba** [OpenSRP/opensrp-client-anc#502]
We have to divide the settings endpoint to return both global & location/team/provider settings separately. 

- [ ] Return global settings when only the `serverVersion` is provided as a parameter

- [ ] Return location/team/provider settings when either if the three are parameters. make sure the global settings are not returned too.

**Comment by vincent-karuri** [comment]
@dubdabasoduba as part of this deliverable no specific role is needed to access the global settings, right?

**Comment by dubdabasoduba** [comment]
Yes. for now no role it should just be like the current endpoint.

**Comment by vincent-karuri** [comment]
Thanks

**Comment by vincent-karuri** [comment]
And to be clear, global settings are those not tagged with `location/team/provider` etc. ?

**Comment by dubdabasoduba** [comment]
Yes.
