### ISSUE TITLE
Implement Symptoms & Follow-up contact container

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-anc#52]
All content, logic, calculations, styling please take from the data dictionary, S&F tab. The mockups for this section, especially, are out of date, so please use styling from the mockup below, but all sections, content, etc. please take from data dictionary. There are 4 sections in total: MEDICATION FOLLOW-UP, PREVIOUSLY REPORTED BEHAVIOUR, PREVIOUSLY REPORTED SYMPTOMS, and PHYSIOLOGICAL SYMPTOMS.

![contact - behavior01](https://user-images.githubusercontent.com/3488986/44255673-871f8880-a20f-11e8-9457-a5788a07c148.png)

- [x] UI Layout and Rendering
- [x] Skip Logic (partially as some conditions are from latter containers)

**Comment by cagulas** [comment]
QA 18th Oct build:

- [ ] Some of the questions don't have enough spacing between the question label and answer choices, while others are ok. For e.g. "Which medications is she still taking" is fine, but the rest of the questions on the page are not.
- [ ] Make sure the info icon does not overlap with the question text or the red asterisk for the required field.
- [ ] Syphilis compliance is missing a space in "upto"
- [ ] Change "Physiologic Symptoms" to "Physiological Symptoms" I think this is fine to fit in.

**Comment by faith-mutua** [comment]
QA 20th Dec

lgtm
