### ISSUE TITLE
Implement Tests contact container

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client-anc#53]
The Tests contact container contains all of the test results that a user can record for a woman and is split into two sections: Due and Other (disregard the Due later section in the mockups).

![subnav-tests](https://user-images.githubusercontent.com/3488986/44260594-855cc180-a21d-11e8-8850-82b463e60b71.png)

Due section:

![elly-contact-tests 1](https://user-images.githubusercontent.com/3488986/44262995-dcff2b00-a225-11e8-8db1-0791d407b546.png)

- [ ] Due contains all the tests that are currently due for the woman. The user must respond to all of these before she can submit the contact, i.e. they're required (the mockup doesn't show the required red asterisk, so please add). Importantly, see the logic in the "Due" column in the data dictionary, Tests tab to determine when tests show up in the Due section or the Other section.
- [ ] Tests should be ordered by most due, then alphabetically

Other section:
- [ ] The Other section contains all the other test results (i.e. tests that are not due right now). The user can submit the contact without responding to any of the tests in the Other section. 
- [ ] Tests are ordered by when they become due later on, and then alphabetically.
- [x] Same look as the Due section, but please add the due date underneath the test, if there is one, i.e. similar to this screen: https://marvelapp.com/3aj9f30/screen/43671168

**Comment by dubdabasoduba** [comment]
I just designed the form like the other contact forms. Need to discuss with @ndegwamartin @ellykits on how to implement the actual look and feel on the marvel mockups

**Comment by cagulas** [comment]
QA 28th December:

**Overall QA for Tests contact container:**
- [ ] We don't need the dropdown carrot action. When you tap on the circle or anywhere in the row, the test page should open. Right now, you need to tap the row, which opens the dropdown to reveal an Undo and Record buttons. So the user has to tap twice to open the test page. They should only have to tap once to open it. The Undo shouldn't be there, because there's no test result recorded yet.
- [ ] The info icon is also missing. See above mockup. Basically, if you tap anywhere in the row, the tests page should open. The info icon should open the info popup for that test type.
- [ ] I'm asking @rowo to take a look at the styling. I'm not sure the grey font color makes sense here. The margins are a bit wide as well.

**Comment by cagulas** [comment]
Screenshots from the app for reference:

![screenshot_20181228-092758](https://user-images.githubusercontent.com/3488986/50506350-8b936200-0a89-11e9-95c1-a5c73039d816.png)
![screenshot_20181228-101453](https://user-images.githubusercontent.com/3488986/50506351-8c2bf880-0a89-11e9-9f62-7fff76d40628.png)

**Comment by cagulas** [comment]
Closing this and creating a new issue for remaining QA
