### ISSUE TITLE
Hide "Automated BP assessment tool" site characteristic for the reference app launch

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-anc#541]
The BP assessment tool has not been integrated yet into the reference app, so is there a way to hide this or comment this one out of the UI? As a reminder, this site characteristic does not dictate any logic in the contact workflow at all, so there is nothing further to do once we hide it.

**Comment by dubdabasoduba** [comment]
- [ ] Involves updating the site characteristics on the server.

**Comment by cafootitt** [comment]
Form release v0.0.35 - lgtm, thanks!
