### ISSUE TITLE
Add Portuguese translations to Brazil version of the app

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-anc#542]
The Brazil team has added Portuguese translations in Transifex for the ANC reference app libraries. They are gearing up to pilot test the app in a couple of locations at the start of the new year and would like to test the app in Portuguese beforehand.

Can we deploy a Brazil-specific version or flavor of the app on the current stage/testing server (anc-stage.smartregister.org) that has the Portuguese translation files and the Portuguese language dropdown option? WHO wants to keep the Portuguese translations out of the reference app flavor prior to the official launch happening later this year.

Please advise on any other approaches that meet the same goal that might be better.

**Comment by dubdabasoduba** [comment]
- [ ] Download the Portuguese translations from Transifex
- [ ] Update the language switcher on the reference app. Remember to disable all the other language for this APK.

**Comment by dubdabasoduba** [comment]
Fix #538 too here.

**Comment by cafootitt** [comment]
This was done, closing.
