### ISSUE TITLE
Client registration creates duplicate clients 

### ISSUE THREAD

**Issue by dubdabasoduba** [OpenSRP/opensrp-client-anc#551]
Currently creating a client creates 2 duplicate clients instead of one. This only happens on the optimization branch

Please test this with the following branch https://github.com/OpenSRP/opensrp-client-anc/tree/feature/zambia-demo

**Comment by dubdabasoduba** [comment]
Fixed by removing the call to `super` in the `onactivityresult` method on the `homeregisteractivity`

**Comment by madrinekariuki** [comment]
There is a recurrence of this issue
`apk reference-app-debug`
user `demo`
android 11

steps.

- login and sync data
- click on create a new profile
- fill in the ANC registration form and save
- wait for profile to load then  go back and observe how we have another profile of the same client created.


screenshot
![image](https://user-images.githubusercontent.com/84722169/147086154-dcb8b62f-b097-4b30-872b-5b36b637b009.png)
