### ISSUE TITLE
Unable to upload new anc_register.json file

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-anc#556]
Steps to replicate:

- Download previous version from latest release
- Make changes offline
- Click on the Upload/edit button
- Select file from computer
- Nothing happens when you click the blue "Upload file" button. It's completely non-responsive.

It was working earlier, but when I went to make another change and upload it again, it became unresponsive.

Do you need to upload the properties file first, even if you're not making any changes to it?

**Comment by dubdabasoduba** [comment]
- It might have been blocked by validation. Was the form valid? 
- Please share the exact form you tried to upload

**Comment by cafootitt** [comment]
Yes, I ran it through the json editor first. I can't attached json form here, so let me share on slack.

**Comment by dubdabasoduba** [comment]
This is fixed. Dependant forms validation was blocking it. This is also the issue for the other forms.

**Comment by cafootitt** [comment]
Replaced by https://github.com/OpenSRP/opensrp-client-anc/issues/573
