### ISSUE TITLE
Update content/logic for select fields on the Contact Summary page

### ISSUE THREAD

**Issue by cafootitt** [opensrp/opensrp-client-anc#570]
Please see all cells highlighted in bright green in the "Contact Summary" tab in the DD: https://docs.google.com/spreadsheets/d/1XVy-9JyTU-Ot6ndV-lbV053WZCC1jU3HKcbJPpXYasc/edit#gid=163602729

**Comment by cafootitt** [comment]
Unable to QA due to #586

**Comment by cafootitt** [comment]
V1.6.1 - lgtm apart from rows 52-24 and row 56 in Contact Summary tab.

- [ ] Labels not updated, and the answer choices are still showing the previous answer choices.
- [ ] TT dose and flu dose should be showing today's date, because I selected "Done today" for each vaccine, but instead it's repeating the field label.

![Screenshot_20210219-151806_WHO ANC](https://user-images.githubusercontent.com/3488986/108524012-967a6380-729c-11eb-9104-853e1d4885b8.jpg)

**Comment by cafootitt** [comment]
V1.6.3, build date 12 March 2021

![Screenshot_20210312-142259_WHO_ANC](https://user-images.githubusercontent.com/3488986/110953316-1dbc7380-833f-11eb-8d49-18260cac95fd.jpg)

**Comment by cafootitt** [comment]
V1.6.5 - fails qa. The Flu dose date is still not appearing. Else, looks good.

![Screenshot_20210322-105629_WHO ANC](https://user-images.githubusercontent.com/3488986/111979740-56a5d680-8afd-11eb-93f7-24076419e3ad.jpg)

**Comment by dubdabasoduba** [comment]
https://drive.google.com/file/d/1cQoEk0NsyRS1B_UxGFNHfS8etKApLwCf/view?usp=sharing this works on v1.6.5

**Comment by cafootitt** [comment]
@dubdabasoduba what type of file did you upload? I'm not able to play it on my machine.
