### ISSUE TITLE
Update content/logic for select fields on the Profile Overview page

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-anc#571]
Please see all cells highlighted in bright green in the "Profile Overview" tab in the DD: https://docs.google.com/spreadsheets/d/1XVy-9JyTU-Ot6ndV-lbV053WZCC1jU3HKcbJPpXYasc/edit#gid=163602729

**Comment by cafootitt** [comment]
Unable to QA due to #586

**Comment by cafootitt** [comment]
QA v1.6.1 on 19 Feb 2021:

- [ ] Row 5 - {occupation} = "Employment that puts woman at increased risk for HIV (e.g. sex worker) - this is not appearing in the Overview page, even though this was selected during the contact.
- [ ] Row 20 - {prev_preg_comps} = Pre-eclampsia or eclampsia; Convulsions; Gestational Diabetes; Tobacco use; Alcohol or illicit substance use; Heavy bleeding (during or after delivery); Baby died within 24 hrs of birth; Macrosomia; Forceps; Vacuum delivery; Perineal tear (3rd or 4th degree); Other (specify) - I think the key values for the modified answer choices are displaying instead of the label from the property file.
- [ ] Row 21 - Label should be "Past alcohol / substances used". Right now it's showing "Past alcohol used"
- [ ] Row 26 - again I think this is showing the key values of the edited answer choices instead of the label from the property file
- [ ] Row 53 - same issue, not showing updated label
- [ ] Row 63 - same issue, not showing updated label
- [ ] Row 70 - same issue
- [ ] Row 74 - logic doesnt' seem to be working. I selected "Cocaine" for this question in the contact, but this field is not appearing in the profile overview
- [ ] Rows 105-107 and row 113-114 - Same issue, the labels haven't been updated, revised answer choices not appearing, and the tt dose and flu dose date fields are not appearing.

**Comment by cafootitt** [comment]
V1.6.3 build 12 Marhc 2021

3 QA failures - see above comment - rows 21, 74, and rows 105-107

**Comment by dubdabasoduba** [comment]
@muchuri row 105-107 has a bug that I just noticed and fixing. I Will share an APK soon

**Comment by cafootitt** [comment]
- [ ] Row 21 - Label should be "Past alcohol / substances used". Right now it's showing "Past alcohol used" Fails QA - we seem to have added a new field instead of correcting the existing field. I'm seeing both a "Past alcohol used" and a "Past substances used" field - there should just be one field.

- [ ] Row 74 - logic doesnt' seem to be working. I selected "Cocaine" for this question in the contact, but this field is not appearing in the profile overview Fails qa - check row 74 again. I think we might be confusing the alcohol_substance_use and the substances_used fields.

- [ ] Rows 105-107 and row 113-114 - Same issue, the labels haven't been updated, revised answer choices not appearing, and the tt dose and flu dose date fields are not appearing. Fails QA - not seeing the updated labels yet, but the revised answer choices are appearing and the dates are appearing, so please just update the labels for TT to TTCV
