### ISSUE TITLE
Fix special character in pop_hiv_generalized pop characteristic

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-anc#579]
- [x] Special character not rendered correctly in Generalized HIV epidemic pop characteristic. It should be a ">" sign.

![Screenshot_20210212-133326_WHO ANC](https://user-images.githubusercontent.com/3488986/107774591-3409ec00-6d0d-11eb-8be5-1ef48d6d588e.jpg)

**Comment by dubdabasoduba** [comment]
@cafootitt can we switch this to greater than in words?

**Comment by cafootitt** [comment]
16 Feb 2021 release - V1.6.1 - lgtm
