### ISSUE TITLE
Implement blood type test result flow

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client-anc#59]
Blood type test is due at first contact and remains due until it's done. After blood type test is done, blood type test goes under the Other optional tests section in future contact visits.

See data dictionary, Tests tab, Blood Type section, for the content.

**Comment by cagulas** [comment]
QA 29 March release:

- [ ] Please see row 49 and 58 (pink highlighting) in data dictionary.
- [ ] I noticed an issue whereby if I fill in the blood type info and then switch the answer to Blood type test Not done, then save it, the blood type test results are still shown. To replicate, record a blood type test result but then, before saving, change the first answer to Not done and save. The test results will still be shown. Let's make sure the other inputs are erased when the first answer is changed.
- [ ] Also, when I undo the test result, then record it again, I see that answers from the previous test result are shown, creating a duplicate. See below:

![Screenshot_20190402-143029](https://user-images.githubusercontent.com/3488986/55324477-e4103c00-548a-11e9-83fc-74fe7c303991.png)

**Comment by ellykits** [comment]
Content for Rhesus negative toaster
![Screenshot_1554294275](https://user-images.githubusercontent.com/26865532/55478570-afd08300-5624-11e9-9908-0133e9232856.png)

**Comment by cagulas** [comment]
lgtm
