### ISSUE TITLE
Modify info icon text for syphilis test

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-anc#592]
See [DD](https://docs.google.com/spreadsheets/d/1XVy-9JyTU-Ot6ndV-lbV053WZCC1jU3HKcbJPpXYasc/edit#gid=1375357718), row 143 in Tests tab.

**Comment by cafootitt** [comment]
@dubdabasoduba Think this was missed, not seeing the change in V1.6.3

![Screenshot_20210312-135711_WHO_ANC](https://user-images.githubusercontent.com/3488986/110949945-23b05580-833b-11eb-8022-88faa5f4defd.jpg)

**Comment by muchuri** [comment]
This is fixed closing the issue
![Screenshot_2021-03-15-12-12-54-231_org smartregister anc](https://user-images.githubusercontent.com/10526420/111130881-c14c9480-8588-11eb-8174-d4dd22361a3f.png)
