### ISSUE TITLE
BP measurement type recording

### ISSUE THREAD

**Issue by dubdabasoduba** [opensrp/opensrp-client-anc#600]
**Question**
Which BP measurement method are you using. 
1. OptiBp 
2. Other

**Relevance**
If OptiBp is selected then show the OptiBP widget and  set the `diastolic` & `systolic` questions to read only this is because the BP will be added automatically from the OptiBP widget. 

If Other is selected then, hide the OptiBP widget and remove the read-only constraint on the `diastolic` & `systolic` questions.

**Comment by SebaMutuku** [comment]
@dubdabasoduba  was this resolved?

**Comment by dubdabasoduba** [comment]
@SebaMutuku not sure please go ahead and test the app. I haven't looked at it for a while now

**Comment by SebaMutuku** [comment]
@dubdabasoduba  I do not see the issue description and pass criterion.

**Comment by dubdabasoduba** [comment]
@SebaMutuku This is a documentation issue. The text above explains how relevance should work. You or QA should test the app to see if it works as explain above
