### ISSUE TITLE
PT app crash on login

### ISSUE THREAD

**Issue by dubdabasoduba** [opensrp/opensrp-client-anc#608]
- [ ] follow up on what device the user is using to see if the crashes much with what we have on crashlytics

**Comment by dubdabasoduba** [comment]
https://github.com/opensrp/opensrp-client-anc/releases/tag/v1.6.7

**Comment by muchuri** [comment]
I was able to install the app on Samsung Galaxy A02s running on Android version 10. A quick check of Samsung J6+ Android version, it supports 8.1 (upgradable to 9). Highly suspecting it's an Android OS version. We might need to reproduce it using a device running this android version (emulator perhaps)

**Comment by Naima-Bashir** [comment]
Closing this. Please reopen if issue still persists.
