### ISSUE TITLE
WHO ANC - Partner HIV logic not working correctly

### ISSUE THREAD

**Issue by joyce-x-chen** [opensrp/opensrp-client-anc#622]
I'm entering training case #12 (Layla). I entered her partner's HIV test status (negative) at contact 1. While filling out the Counseling and Treatment form for contact 2, it is saying "partner HIV test recommended."It is not pulling the relevant information from the test info entered at contact #1.

**Comment by dubdabasoduba** [comment]
Tested this with the team and couldn't replicate
