### ISSUE TITLE
Blank population characteristics activity

### ISSUE THREAD

**Issue by hilpitome** [opensrp/opensrp-client-anc#629]
## Issue description
The population characteristics page is blank in the SID Indonesia app created from [this](https://github.com/sid-indonesia) forked repo
### How to recreate the issue
Login to the app then go to:
`Home->me->Population Characteristics`

**Comment by dubdabasoduba** [comment]
@Naima-Bashir This is the same issue.

**Comment by Naima-Bashir** [comment]
Closing this https://github.com/opensrp/opensrp-client-anc/issues/635 @junaidwarsivd cc

**Comment by Naima-Bashir** [comment]
Closing this, can be reopened if issue occurs again
