### ISSUE TITLE
[OptiBP] Error occurs when client tries to access the OptiBp app that is linked to the WHO ANC App

### ISSUE THREAD

**Issue by Naima-Bashir** [opensrp/opensrp-client-anc#632]
The client(SID) is getting an error in which they cant access the ObtiBP app that is linked with WHO ANC App. 
They downloaded the ObtiBP app but couldn't open the app through WHO ANC App.

The error they are getting occurs after they click  the "measure" button and they can't open the ObtiBP app
Find the image below
![image](https://user-images.githubusercontent.com/61143692/132338223-ef374ac1-abdf-4809-b9a7-df8e6cc46845.png)

**Comment by hamza-vd** [comment]
@Naima-Bashir 
As per the error in the above image, the user did not have the OptiBP app installed on the device. The app needs to be **"Downloaded and Installed"** before starting the BP measurement from the ANC app. As you mentioned above that the app was downloaded, can you confirm if the OptiBP app was also **installed** on that device or not? 
[
Optibp App Download Link](https://drive.google.com/file/d/1Ms2WdY3wtE5IuXeDjok8dqKZBvCMw2Wc/view?usp=drivesdk)

**Comment by dubdabasoduba** [comment]
> @Naima-Bashir
> As per the error in the above image, the user did not have the OptiBP app installed on the device. The app needs to be **"Downloaded and Installed"** before starting the BP measurement from the ANC app. As you mentioned above that the app was downloaded, can you confirm if the OptiBP app was also **installed** on that device or not?
> [ Optibp App Download Link](https://drive.google.com/file/d/1Ms2WdY3wtE5IuXeDjok8dqKZBvCMw2Wc/view?usp=drivesdk)

@hamza-vd did the optibp app start up what you tested it?

**Comment by hamza-vd** [comment]
> > @Naima-Bashir
> > As per the error in the above image, the user did not have the OptiBP app installed on the device. The app needs to be **"Downloaded and Installed"** before starting the BP measurement from the ANC app. As you mentioned above that the app was downloaded, can you confirm if the OptiBP app was also **installed** on that device or not?
> > [ Optibp App Download Link](https://drive.google.com/file/d/1Ms2WdY3wtE5IuXeDjok8dqKZBvCMw2Wc/view?usp=drivesdk)
> 
> @hamza-vd did the optibp app start up what you tested it?

@dubdabasoduba yes it is working for me.

**Comment by Naima-Bashir** [comment]
Closing this issue
