### ISSUE TITLE
Fix breaking tests on ANC. 

### ISSUE THREAD

**Issue by dubdabasoduba** [opensrp/opensrp-client-anc#637]
This [PR](https://github.com/opensrp/opensrp-client-anc/pull/634) has a few breaking tests. We might need more time to work on them 

**To Reproduce:**
- Check out the `master` branch
- Run the tests locally e.g. `./gradlew opensrp-anc:clean opensrp-anc:jacocoTestReport --stacktrace`

**Comment by SebaMutuku** [comment]
On progress...

**Comment by Naima-Bashir** [comment]
All tests have been completed on ANC by @SebaMutuku . Closing this
