### ISSUE TITLE
Search Page - Searching by the EDD does not work as expected

### ISSUE THREAD

**Issue by Naima-Bashir** [opensrp/opensrp-client-anc#645]
**Steps:**
Login to the app
Go the search tab
Click on Outside and inside my health facility options
Search by EDD
Observe the results that are shown.

**Results:**
Did not work for 'Outside and inside my health facility' options. The search result page said '1 matches', but none of the clients appeared. Also, the answer field can be filled by alphabet or number, not always the date.

How is this feature expected to work?
It can be improved to:

Remove the option of alphabets and remain with the select date option
The search filter should work when one searches via EDD
Link to Excel Spreadsheet is [here](https://docs.google.com/spreadsheets/d/1U8e3NYO_AStHxdXZUd2tEP-AHguNGUZU/edit#gid=1219538130)

**Comment by hamza-vd** [comment]
The EDD date selection and incorrect input bug is fixed. Will create another issue for incorrect count of matching results. Marking this issue as done.

**Comment by Mstjamush** [comment]
Fixed
