### ISSUE TITLE
Search Page - Searching by the DoB does not work as expected

### ISSUE THREAD

**Issue by Naima-Bashir** [opensrp/opensrp-client-anc#646]
**Steps:** 
1. Login to the app
2. Go the search tab 
3. Click on Outside and inside my health facility options
4. Search by DoB 
5. Observe the results that are shown.

**Results:** 
Did not work for 'Outside and inside my health facility' options. The search result page said '1 matches', but none of the clients appeared. Also, the answer field can be filled by alphabet or number, not always the date.

### How is this feature expected to work?
It can be improved to: 
1. Remove the option of alphabets and remain with the select date option 
2. The search filter should work when one searches via DoB 

Link to Excel Spreadsheet is [here](https://docs.google.com/spreadsheets/d/1U8e3NYO_AStHxdXZUd2tEP-AHguNGUZU/edit#gid=1219538130)

**Comment by SebaMutuku** [comment]
@dubdabasoduba @AngelaKabari I have debugged the issue and I am receiving response {"message":"The server encountered an error processing the request.","status":"500 INTERNAL_SERVER_ERROR","data":null,"success":false} from anc labs opensrp-server-web backend. I am working on getting access to see what the logs print on the K8S service.

**Comment by SebaMutuku** [comment]
Created an issue here https://github.com/opensrp/opensrp-server-web/issues/1091

**Comment by Naima-Bashir** [comment]
Closing this with client approval
