### ISSUE TITLE
 Library Page - Accessing information of Birth and Emergency Plan -  Loaded a blank black page

### ISSUE THREAD

**Issue by Naima-Bashir** [opensrp/opensrp-client-anc#647]
### How do we replicate the bug?

Library Page - Accessing information of Birth and Emergency Plan -  Loaded a blank black page

### How is this feature expected to work?

Library Page - Accessing information of Birth and Emergency Plan -  Loaded a blank black page

**Comment by Mstjamush** [comment]
Fixed
