### ISSUE TITLE
There are some missing forms(Counselling and Treatment - Display of the form and questions)

### ISSUE THREAD

**Issue by Naima-Bashir** [opensrp/opensrp-client-anc#649]
### How do we replicate the bug?

Missing 2 forms: Nutrition Supplementation (Step 9) and  Deworming & Malaria Prophylaxis (Step 10)
Missing 2 forms: Nutrition Supplementation (Step 9) and  Deworming & Malaria Prophylaxis (Step 10)

### How is this feature expected to work?

Missing 2 forms: Nutrition Supplementation (Step 9) and  Deworming & Malaria Prophylaxis (Step 10)
Missing 2 forms: Nutrition Supplementation (Step 9) and  Deworming & Malaria Prophylaxis (Step 10)

**Comment by dubdabasoduba** [comment]
> ### How do we replicate the bug?
> Missing 2 forms: Nutrition Supplementation (Step 9) and Deworming & Malaria Prophylaxis (Step 10)
> Missing 2 forms: Nutrition Supplementation (Step 9) and Deworming & Malaria Prophylaxis (Step 10)
> 
> ### How is this feature expected to work?
> Missing 2 forms: Nutrition Supplementation (Step 9) and Deworming & Malaria Prophylaxis (Step 10)
> Missing 2 forms: Nutrition Supplementation (Step 9) and Deworming & Malaria Prophylaxis (Step 10)
> 
> ### Please Share other relevant information about the bug
> _No response_

@Naima-Bashir I am not sure I understand what this means

**Comment by Naima-Bashir** [comment]
This has been resolved; closing this
