### ISSUE TITLE
Implement urine test result flow

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client-anc#65]
A urine test is required at the first contact AND last contact in 2nd trimester AND 2nd contact in 3rd trimester OR anytime the woman reports pain during urination. 

Additionally, a urine test (specifically a dipstick protein test) is required if a woman's blood pressure reading is over 140/90.

When the urine test is done and not currently due, it should be available in the Other Tests section until it becomes due again.

There are 3 different types of urine tests, and each test type has different types of results recorded, see data dictionary, Tests tab, Urine section for specific content and logic.

Urine test due:
<img width="403" alt="screen shot 2018-08-20 at 4 42 14 pm" src="https://user-images.githubusercontent.com/3488986/44343962-07f0b580-a498-11e8-8d30-cffeaa54bf6c.png">

Clicking on urine test, you can select done today, done earlier, ordered, or not done (not pictured, but please add):
<img width="464" alt="screen shot 2018-08-20 at 4 43 54 pm" src="https://user-images.githubusercontent.com/3488986/44344024-3ff7f880-a498-11e8-9ba0-efaf7bd2cd93.png">

If selected done today, done earlier, or ordered, select which urine test was done or ordered (note this is a select multiple):
<img width="417" alt="screen shot 2018-08-20 at 4 44 47 pm" src="https://user-images.githubusercontent.com/3488986/44344094-6f0e6a00-a498-11e8-8839-ab1cdaa6f188.png">

If selected done today or done earlier, and after selecting test type(s), record the result(s) and select done:
<img width="427" alt="screen shot 2018-08-20 at 4 46 17 pm" src="https://user-images.githubusercontent.com/3488986/44344150-a2e98f80-a498-11e8-9701-6d2ff8075a01.png">

**Comment by rowo** [comment]
Update here, spoke to @dubdabasoduba and we are trying to do full screen dialogs since breaking up the form is too complicated. So that first question becomes a simple select one like below:

<img src="https://user-images.githubusercontent.com/1584163/50261755-069aaf80-03dc-11e9-8b80-a5a92a9db520.png" width="450">

<img src="https://user-images.githubusercontent.com/1584163/50261757-08647300-03dc-11e9-87a9-ed56fed954f2.png width="450">

**Comment by rowo** [comment]
<img src="https://user-images.githubusercontent.com/1584163/50622959-5ea6db00-0edf-11e9-803e-cf3ba0f8c0cb.png" width="300px">

@cagulas @dubdabasoduba @ndegwamartin Just reviewing latest APK (one screengrab above) — not sure if it's meant to be complete — but just wanted to add more detail on the Test row interaction. Follow along the click through here: https://marvelapp.com/3aj9f30/screen/40006364

A blank, or Tests screen without anything filled out, looks like this:

<img width="395" alt="screen shot 2019-01-02 at 10 35 27 pm" src="https://user-images.githubusercontent.com/1584163/50622940-2ef7d300-0edf-11e9-9d2a-14dac95dfbfc.png">

After tapping on the Urine test row (which could have a tooltip), it goes to the first screen in the previous comment, https://github.com/OpenSRP/opensrp-client-anc/issues/65#issuecomment-448845309. 

After you finish the form, each row updates as shown in https://marvelapp.com/3aj9f30/screen/43671169, or:

<img width="395" alt="screen shot 2019-01-02 at 10 43 43 pm" src="https://user-images.githubusercontent.com/1584163/50623019-e391f480-0edf-11e9-924d-8eb015e960e4.png">

1. The left row circle shows the categorical result
2. a line is added with the detailed result
3. the tooltip is still shown
4. the buttons to Undo and Record are added to the row and are not in an accordion

**Comment by cagulas** [comment]
QA 29th March release:

- [ ] Please see all pink-highlighted cells in the data dictionary.
- [ ] Due date doesn't seem to be working yet

**Comment by cagulas** [comment]
lgtm
