### ISSUE TITLE
Search Page: Searching by Phone number does not work as expected

### ISSUE THREAD

**Issue by Naima-Bashir** [opensrp/opensrp-client-anc#653]
### How do we replicate the bug?

"Steps to check:
1. Login to the app
2. Click on one of the client's name, it will navigate you to the client's profile
3. Click on Registration info button
4. Copy the client's phone number
5. Press the back button until you get to the client's page
6. Go to search tab by clicking the search bottom navigation
7. Click on the Outside and inside my health facility option in the client's facility question
8. Paste the phone number on the phone number's field
9. Click search on the top right of the page
10. Observe the result. It will show all clients registered in the user"

### How is this feature expected to work?

Did not work  for 'Outside and inside my health facility' options. The search result showed all clients' names. It should work

**Comment by Naima-Bashir** [comment]
Excel link here https://docs.google.com/spreadsheets/d/1U8e3NYO_AStHxdXZUd2tEP-AHguNGUZU/edit#gid=1219538130

**Comment by SebaMutuku** [comment]
issue completed

**Comment by madrinekariuki** [comment]
Tested on
Android 11 Samsung A12
user `demo`

Steps:
Followed the steps highlighted [here](https://github.com/opensrp/opensrp-client-anc/issues/653#issue-1004191284)

Observations:
- One is able to search by phone number and clients not by that phone number is shown
- Important to note that one as to sync the data first to be able to search and get the clients names


Screenshot:
![image](https://user-images.githubusercontent.com/84722169/177534649-7493f69a-c5cb-43cf-89b3-61c0ec85eddb.png)

**Comment by Naima-Bashir** [comment]
Closing this with client approval
