### ISSUE TITLE
Register Page: The name of the client can be filled with blanks

### ISSUE THREAD

**Issue by Naima-Bashir** [opensrp/opensrp-client-anc#655]
### How do we replicate the bug?

"Steps to check:
1. Login to the app
2. Click on the register button
3. Fill in the first name with space character only
4. Fill in the last name with space character only
5. Fill out all other information
6. Click on save button on the top right of the page
7. Observe the result on the client page, it will show you blank name in the client page"

### How is this feature expected to work?

Name of the client can be filled by space characters only, so it will make the client's name looked blank

### Please Share other relevant information about the bug

Link to excel sheet : https://docs.google.com/spreadsheets/d/1U8e3NYO_AStHxdXZUd2tEP-AHguNGUZU/edit#gid=1219538130

**Comment by AngelaKabari** [comment]
@junaidwarsivd please send the apk with this fix to Madrine for QA.

**Comment by madrinekariuki** [comment]
@junaidwarsivd 
I note that one cannot put blanks as the name now. However one can put special character specifically `.` see below example
![image](https://user-images.githubusercontent.com/84722169/168817672-49225af7-1fe1-4470-bd16-e8ad638b637f.png)
