### ISSUE TITLE
Search Page: Accessing client's profile from the search result page gives you blank page and causes crash

### ISSUE THREAD

**Issue by Naima-Bashir** [opensrp/opensrp-client-anc#656]
### How do we replicate the bug?

"Steps to check:
1. Login to the app
2. Go to search tab by clicking the search bottom navigation
3. Search the client by any category (could be first name, last name, etc)
4. Click search on the top right of the page, it will show the search result with the client's name
5. Click on the client's name

Note:
If you tried it for the first time, it sometimes will navigate you successfully to the client's profile page. However, most often, it will navigate you the blank page and eventually give you crashes."

### How is this feature expected to work?

One should be able to search for clients and not have a blank page or an app crash. 
See video here: https://drive.google.com/file/d/19LD3kaUF3R8XLgyIQTQgC4EI2MZT3Ch-/view?usp=sharing

**Comment by ellyasafaa** [comment]
Hi @Naima-Bashir, I think this issue has not been closed yet.

**Comment by ellyasafaa** [comment]
I corrected the title of the issue since it is not represented the real issue described.

cc: @elwinameylentia

**Comment by Naima-Bashir** [comment]
thanks @ellyasafaa , I have reopened it

**Comment by Naima-Bashir** [comment]
Out engineer @junaidwarsivd is working on this one that i created https://github.com/opensrp/opensrp-client-anc/issues/713

**Comment by ellyasafaa** [comment]
Okay, noted. Thanks @Naima-Bashir
