### ISSUE TITLE
Register Page: When adding the mobile phone number and alternate phone number is shown instead

### ISSUE THREAD

**Issue by Naima-Bashir** [opensrp/opensrp-client-anc#657]
### How do we replicate the bug?

"Steps to check:
1. Login to the app
2. Click on the register button
3. Fill in the mobile phone number with 123456
4. Fill in the alternate contact phone number with 987654
5. Fill out all other information
6. Click on save button on the top right of the page
7. Click on the client's name that you have just made, you will then be navigated to the client's profile page
8. Click on the Registration Info
9. Observe the alternate contact phone number and the mobile phone number field, they will have the same number, and it will follow the number of alternate contact number"

### How is this feature expected to work?

There should be two different phone numbers shown in the mobile and the alternate phone number

### Please Share other relevant information about the bug

Video can be found here https://drive.google.com/file/d/1954cviBwhJ6kRAXBDtJL-OH_TuePtUMe/view

**Comment by Mstjamush** [comment]
Fixed
