### ISSUE TITLE
Register Page - Editing register page after the form has been saved

### ISSUE THREAD

**Issue by Naima-Bashir** [opensrp/opensrp-client-anc#658]
### How do we replicate the bug?

"Steps to check:
1. Login to the app
2. Click on one of the client's name, it will navigate you to the client's profile page
3. Click on the Registration info button
4. Scroll down until the end of the page, the cohabitant question does not appear

Please kindly check on several clients. Sometimes the question showed up, but most of them are not. Only the cohabitant question that appears, the options do not appear.

On the Indonesia version, the question does not appear."

### How is this feature expected to work?

For some clients, co-habitants question does not show up in the register page as it should 

### Please Share other relevant information about the bug

Excel link can be found here: https://docs.google.com/spreadsheets/d/1U8e3NYO_AStHxdXZUd2tEP-AHguNGUZU/edit#gid=1219538130

**Comment by Mstjamush** [comment]
Fixed
