### ISSUE TITLE
Profile Page (Tasks Tab) - Missing translations on client tasks page

### ISSUE THREAD

**Issue by hamza-vd** [opensrp/opensrp-client-anc#664]
### How do we replicate the bug?

1. Launch the WHO ANC app
2. Login to the app
3. Click on the settings tab and convert app language to Portuguese
4. Click on one client, it will navigate you to the client's profile 
5. Navigate to Tasks Tab
5. Look if client has task
6. If client has 0 task go to step 4 and search client with tasks or create task for her
7. If Client has task observe the untranslated task names
7. Click on it to open the form
8. The test options are not translated

### How is this feature expected to work?

When app is in Portuguese, all the labels on Tasks page should be translated into the Portuguese language.the 

### Please Share other relevant information about the bug

Including some screenshots from the missing translations.
<img src="https://user-images.githubusercontent.com/70560433/135992352-0a937b50-f820-4ebb-8f63-790c8ac7456a.png" width="500" height="800">
<img src="https://user-images.githubusercontent.com/70560433/135992363-1b3b6bde-8af3-45a9-8011-f6b4c44cb620.png" width="500" height="800">
<img src="https://user-images.githubusercontent.com/70560433/135992368-e3a4f64b-499d-46fa-ad1a-12f3bf3de7b7.png" width="500" height="800">

**Comment by Naima-Bashir** [comment]
Hi @hamza-vd has this ticket been worked on? Can we close this?

**Comment by hamza-vd** [comment]
@Naima-Bashir 
Yes, I fixed this issue earlier. But some translations for test names were missing in the `strings.xml` file at that time. If those translations are added now, then this issue can be marked as done.

**Comment by Naima-Bashir** [comment]
@hamza-vd Where/ who can we get this information from: some translations for test names were missing in the strings.xml file at that time

**Comment by hamza-vd** [comment]
@junaidwarsivd  cc: @Naima-Bashir 

Please can you please confirm if the following strings
```
    <string name="accordion_ultrasound">Ultrasound test</string>
    <string name="accordion_blood_type">Blood Type test</string>
    <string name="accordion_hepatitis_b">Hepatitis B test</string>
    <string name="accordion_hepatitis_c">Hepatitis C test</string>
    <string name="accordion_syphilis">Syphilis test</string>
    <string name="accordion_urine">Urine test</string>
    <string name="accordion_blood_haemoglobin">Blood Haemoglobin test</string>
    <string name="accordion_hiv">HIV test</string>
    <string name="accordion_tb_screening">TB Screening</string>
    <string name="accordion_partner_hiv">Partner HIV test</string>
    <string name="accordion_blood_glucose">Blood Glucose test</string>
    <string name="accordion_other_tests">Other test</string>
```
and subforms for each of these tests are fully translated or not. Thanks

**Comment by junaidwarsivd** [comment]
@hamza-vd  on which branch this needs to be checked?

**Comment by junaidwarsivd** [comment]
@hamza-vd  cc @Naima-Bashir  
i've checked the translations under optibp/merge-general-app-updates  + merge/general-app-updates branch 
the translations dont exist
