### ISSUE TITLE
Highlight an Allergy when describing Allergenic medicine

### ISSUE THREAD

**Issue by Naima-Bashir** [opensrp/opensrp-client-anc#666]
### Feature Use Case

Need to highlight an allergy when prescribing the allergenic medicine. The module currently recommends treatment with penicillin with no additional information regarding the allergy linked to this prescription and/or alternatives to manage the condition.

### Acceptance criteria

- We should indicate if there any any allergies that were recorded in the profile 

- Alert/flag if allergy is not empty

- See Data Dictionary (https://docs.google.com/spreadsheets/d/1XVy-9JyTU-Ot6ndV-lbV053WZCC1jU3HKcbJPpXYasc/edit#gid=722570350) for clarity

-  Eg give an alert for row 176, 179, 360, 367, 399,  etc of the CT section of the Data Dictionary 
 

### Relevant Information
[Data Dictionary](https://docs.google.com/spreadsheets/d/1XVy-9JyTU-Ot6ndV-lbV053WZCC1jU3HKcbJPpXYasc/edit#gid=722570350) 
_No response_

**Comment by Mstjamush** [comment]
Not fixed

**Comment by Naima-Bashir** [comment]
Hi @Mstjamush could you clarify for the engineers what you mean by not fixed? cc @junaidwarsivd

**Comment by Mstjamush** [comment]
Despite indicating that a client is allergic to Penicillin, Penicillin is the recommended medication for syphilis
