### ISSUE TITLE
Data Dictionary Updates

### ISSUE THREAD

**Issue by Naima-Bashir** [opensrp/opensrp-client-anc#671]
### Feature Use Case

"Data Dictionary Updates
OBSTETRIC HISTORY
MEDICAL HISTORY
IMMUNISATION STATUS
MATERNAL EXAM
TESTS - ULTRASOUND
TESTS - SYPHILIS
TOXOPLASMOSIS
COVID-19"

**Comment by hamza-vd** [comment]
[Data dictionary link](https://docs.google.com/spreadsheets/d/1MFx7FN2L0c_dsDZYaDasMjmHUBVYmhXP/edit#gid=536690820)

**Comment by hamza-vd** [comment]
@Naima-Bashir 
In the [Data dictionary](https://docs.google.com/spreadsheets/d/1MFx7FN2L0c_dsDZYaDasMjmHUBVYmhXP/edit#gid=536690820), the MATERNAL EXAM section has `anaemia_suspect`  calculation and a `toaster` defined. But in the code, it has already been implemented with some other condition as well. Does this needs to be implemented separately or the current implementation is okay?

**Data Dictionary**
<img width="1460" alt="Screenshot 2021-11-15 at 5 13 04 PM" src="https://user-images.githubusercontent.com/70560433/141784107-93cac579-7e5d-4329-b614-3be1ab83883d.png">

**Current Implementation**
<img width="500" alt="Screen 1" src="https://user-images.githubusercontent.com/70560433/141784216-b0fdbe81-5591-4569-93d9-7a2f2167f7f7.png">
<img width="500" alt="Screen 2" src="https://user-images.githubusercontent.com/70560433/141784252-cd6a73c3-f4c7-4b58-9277-9d40d6f94b9b.png">

**Comment by hamza-vd** [comment]
@dubdabasoduba  cc @Naima-Bashir 
In the [Data dictionary](https://docs.google.com/spreadsheets/d/1MFx7FN2L0c_dsDZYaDasMjmHUBVYmhXP/edit#gid=536690820), the OBSTETRIC EXAM (row 3) section has  a `toaster` defined. It's relevance section is a bit confusing. Should {gravida} be less than or grater than {1+ ({previous_pregnancies}+{miscarriages_abortions}+{live_births}+{stillbirths})} value ?

**Sreenshot**
<img width="1455" alt="Screenshot 2021-11-15 at 5 49 25 PM" src="https://user-images.githubusercontent.com/70560433/141785423-a7879108-d43e-4cf0-9c44-089189f031a5.png">

**Comment by Naima-Bashir** [comment]
Hi @hamza-vd so updates from the client: 
Question1 : The rationale is: {gravida} is the sum of the current pregnancy and all of the previous pregnancies (including those wich ended in stillbirth, abortion and live birth). So, we need to have a rule to advise the user to input the correct number of obstetric events.



Question 2 answer: The rationale is: here in Brazil, we will only consider the woman to be {anaemic} if she has (({hb_result} < 11 AND ({gest_age} <= 12 OR {gest_age} >= 28)) OR ({hb_result} < 10.5 AND ({gest_age} > 12 AND {gest_age} < 28)), 1, 0).
If ({hb_results} = '' AND {pallor} = "Yes"), she has {anaemia_suspected} and the toaster message is: Note displaying that the woman has great risk of anaemia and she should be counseled.
The flag should be yellow: Anaemia suspected! Haemoglobin test (Hb) recommended.

**Comment by hamza-vd** [comment]
@Naima-Bashir 
I'm still unclear about what should be the relevance condition for {gravida} toaster message. The relevance defined in the **Relevance** column is 

> {gravida} < or > 1+ ({previous_pregnancies}+{miscarriages_abortions}+{live_births}+{stillbirths})

The condition here is unclear. Should this toaster be shown when {gravida} will be less than or greater than `1+ ({previous_pregnancies}+{miscarriages_abortions}+{live_births}+{stillbirths})`? What should be the exact relevance here?

**Comment by Naima-Bashir** [comment]
@hamza-vd response from client: 
The "check message" should be displayed if {gravida} is different than the sum of all the obstetric occurrences plus the current pregnancy (1).

**Comment by SebaMutuku** [comment]
issue resolved.
How to test
Register a new ANC client or use an existing one.
Create contact and fill in the details.
Choose start contact, fill in details and click proceed to normal contact
Choose profile and fill in required details under Demographic info and current pregnancy
Under Obstetric History, choose a number greater than 2 for No. of pregnancies, live births, lost and still births. If all is greater than 1, then the toast will appear.

**Comment by SebaMutuku** [comment]
Just wanted to confirm one last about obstetric toast message. The mentioned toast message on excel-sheet, is it an info or a warning toast?

**Comment by Naima-Bashir** [comment]
It's for information @SebaMutuku

**Comment by SebaMutuku** [comment]
Thank you.I  will generate an apk tomorrow once it's updated to info toast.

**Comment by madrinekariuki** [comment]
This has been tested on` reference-app-debug`

Followed these test [steps](https://github.com/opensrp/opensrp-client-anc/issues/671#issuecomment-994729771)

Observation:
`under No. of pregnancies lost/ended (before 22 weeks/5 months)`.
- when you select 1 or more the toast message on top appears showing (check for the number of previous pregnancies lost,            live births and stillbirths.)
- for the question was the last question `NO. of live births` if you select  1 or more then another pop up shows indicating to        select `was the last live birth preterm?`and  also a prompt to confirm if one has had any past problems. 


@SebaMutuku @hamza-vd  cc @Naima-Bashir 
Kindly confirm what is the success criteria for this item?..

screenshot shared below.
![image](https://user-images.githubusercontent.com/84722169/146903690-3e230abb-c234-4629-a8cf-9c8e26763b3b.png)

**Comment by SebaMutuku** [comment]
Hi @Naima-Bashir @madrinekariuki  below is the success criteria is {gravida} < or > 1+ ({previous_pregnancies}+{miscarriages_abortions}+{live_births}+{stillbirths}) .i.e if previous_pregnancies +miscarriages_abortions+live_births+stillbirths is greater than 1, show toast message.

**Comment by madrinekariuki** [comment]
This has been tested on `reference-app-debug`
user `demo`
android 11



when you select 2 or more on  `no of pregnancies including this one` the toast message on top appears showing (check for the number of previous pregnancies lost, live births and stillbirths.)

screenshot
![image](https://user-images.githubusercontent.com/84722169/147090917-83f2d29a-39d1-41e7-8aef-f207d45e5282.png)
