### ISSUE TITLE
Hepatitis B Updates 

### ISSUE THREAD

**Issue by Naima-Bashir** [opensrp/opensrp-client-anc#672]
### Feature Use Case

"Hep B Updates
Maintaining Hep B on the Test Tab
Hep B recommendations - under Profile --> Immunization status"

### Acceptance criteria

![image001](https://user-images.githubusercontent.com/61143692/141112957-e027c220-eaaa-43df-b8bc-dc8e699f1324.png)

**Comment by junaidwarsivd** [comment]
@Naima-Bashir  @dubdabasoduba  i assume we have to add  hepatitis B immunization status in immunization status section of the Profile for that i need openMrs id for the hepatitis B immunization status
Second question is where does the reults in the Output section apply 
do we need to show the results as we show it on the on flu or covid19 immunization update?
or the other way

**Comment by madrinekariuki** [comment]
This has been tested on `reference-app-debug`
user` demo`
android 11

@junaidwarsivd cc @Naima-Bashir 

Observation:
 - under Profile --> Immunization status the `hepatitis B immunization status` is missing. so we are unable to record this.

see screenshot below that shows the available immunizations.
Also kindly update the ticket with the success criteria 
![image](https://user-images.githubusercontent.com/84722169/146906285-7a40370a-e9e9-4d69-84cc-20a4a0f25b48.png)

**Comment by SebaMutuku** [comment]
@madrinekariuki  this has been updated. An APK will be shared with you.

**Comment by madrinekariuki** [comment]
retested on 
apk: `reference-app-debug`
user: `demo`

observation. 
on the profile-> immunization part,  Hepatitis B has been added correctly.

see screenshot below:
![image](https://user-images.githubusercontent.com/84722169/148519959-3f4c25a9-5532-4d77-946f-66097f855e22.png)
