### ISSUE TITLE
Covid Updates

### ISSUE THREAD

**Issue by Naima-Bashir** [opensrp/opensrp-client-anc#673]
### Feature Use Case

"Covid Updates
Under Quick Check tab, Flu like symptoms. (COVID-19 suspected). It should to be under the attention flag
Under Profile tab/container Include COVID-19 under immunization status "

### Acceptance criteria
Add the option in the quick check tab: Include COVID-19 under immunization status
In the quick check tab, when one clicks on Flu Like symptoms, the Attention Flag should show "COVID- 19 suspected"

**Comment by hamza-vd** [comment]
Add COVID-19 test from data[-dictionary](https://docs.google.com/spreadsheets/d/1MFx7FN2L0c_dsDZYaDasMjmHUBVYmhXP/edit#gid=536690820)

**Comment by madrinekariuki** [comment]
This has been tested on `reference-app-debug`
user `demo`
android 11

@hamza-vd 

observation:
- under the immunization status the` covid-19 immunisation status` is there.
- under quick check tab on clicking flu symptoms, there is no Attention Flag to show "COVID- 19 suspected"

Also note that on quick check tab, `flu symptoms` is only showing when you click `Health concern`

see screenshot below:
![image](https://user-images.githubusercontent.com/84722169/146909780-d715d3bc-7b76-488b-982b-836b2638a8de.png)

**Comment by SebaMutuku** [comment]
@madrinekariuki For this to appear under Attention Flag, you need to complete all required contact tabs (Under profile, Symptoms,Physical exam ,Tests,Counselling) then finalize the form.

**Comment by madrinekariuki** [comment]
@SebaMutuku 
This has been retested and the covid-19 updates are available on the attention flags. 

see attached screenshot.
user `demo`
![image](https://user-images.githubusercontent.com/84722169/148056476-ff9429f6-2118-4243-9d8a-544e132cbd5b.png)
