### ISSUE TITLE
Problem with Opensrp-web service on docker;  All Services and Containers startup perfectly except opensrp-web

### ISSUE THREAD

**Issue by chobela** [opensrp/opensrp-client-anc#674]
### Affected App or Server Version

v1.1.12 Server

### What kind of support do you need?

We still have a problem with opensrp-web service on docker. All Services and Containers startup perfectly except opensrp-web.

### What is the acceptance criteria for your support request?

We have Setup opensrp-server-web, keycloak, postgres, redis, mybatis. They all work fine.

### Relevant Information

We have followed the exact steps on docker hub for Opensrp web setup.

**Comment by Naima-Bashir** [comment]
Hi @chobela can I close this ticket? Has your team gotten the support requested?

**Comment by Naima-Bashir** [comment]
@chobela closing this ticket. Kindly reopen if issue still persists.
