### ISSUE TITLE
[Ona Support Request]: 

### ISSUE THREAD

**Issue by chobela** [opensrp/opensrp-client-anc#677]
### Affected App or Server Version

Image : opensrp/web:v1.1.12

### What kind of support do you need?

Getting the following error when trying to open OpenSRP Web. : {"message":"Unable to connect to localhost:28080","status":"error","statusCode":500}  Or {"message":"Unable to connect to 127.0.0.1:28080","status":"error","statusCode":500}

### What is the acceptance criteria for your support request?

All other containers running

**Comment by Naima-Bashir** [comment]
Hi @chobela can I close this ticket? 

cc @Naima-Bashir

**Comment by Naima-Bashir** [comment]
Hi @chobela I am closing this ticket, kindly reopen if there is support required
