### ISSUE TITLE
Implement blood haemoglobin test result flow

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client-anc#68]
The blood haemoglobin test is due at the first contact and last contact in 2nd trimester (13 to 27 weeks, inclusive) and the middle contact in 3rd trimester (28 weeks to pregnancy end) -- upper middle, meaning closer to the delivery date in the event it is an even number of contacts in the 3rd trimester.

In between, the Hb test should be available and optional in the Other Tests section. 

There are three types of Hb tests, see data dictionary, Tests tab, Blood Haemoglobin section for content and logic, etc.

**Comment by cagulas** [comment]
29th March release:

- [ ] For the test result decimal fields, can we see if the numeric keypad can be launched? The alphabet keypad is getting launched, which is not very user-friendly.
- [ ] See all pink-highlighted fields in the data dictionary.

**Comment by cagulas** [comment]
Looking good, but please check the anaemia calculation in row 270.

**Comment by hmakandi** [comment]
SCN01: First Contact Gweta Tweta ->Blood Haemoglobin test visible, numeric keyboard is displayed,  Record done with Complete blood count test.result values 0-10.9 show Anaemia diagnosis, 10.4 and below show Heamocrit levels low,16001 WBC count shoes WBC count too high,Platelet count too low at 99999 Results displayed under contact. OK
SCN02: Second Contact Pretatwi Kwetatwi, ->Set date to 15/09 GA 30 weeks, Blood Haemoglobin test visible,Record done with Hb Test(haemoglobinometer), test result 0-10.9 show Anaemia diagnosis,  Results displayed under contact. OK
SCN03: Second Contact Pwani Kwani,->Set date 15/07, GA 17 weeks, Record done with Hb Test(haemoglobin colour scale), test result 0-10.49 shows Anaemia diagnosis above does not, Results displayed under contact. OK

Overall:
Test passed

Observations:
-In Test container, performance testing is recommended across various devices.
