### ISSUE TITLE
Test container Updates - 1

### ISSUE THREAD

**Issue by Naima-Bashir** [opensrp/opensrp-client-anc#680]
### Feature Use Case

"Test container Updates:
Syphilis test type Add the option: ""VDRL"", 
Syphilis_positive name, add OR {vdrl_test} diferent than ""Negative"" as part of the calculation, 
Midstream urine culture, If positive, we need to open a field to describe the agent name,
Blood glucose test type, should be changed to multiselect control,
Add COVID-19 test,
"

### Acceptance criteria

..

**Comment by hamza-vd** [comment]
Duplicate of issue #681
