### ISSUE TITLE
Test container updates 2

### ISSUE THREAD

**Issue by Naima-Bashir** [opensrp/opensrp-client-anc#681]
### Feature Use Case

Test container Updates:
1) Syphilis test type Add the option: ""VDRL"", 
2) Syphilis_positive name, add OR {vdrl_test} different than ""Negative"" as part of the calculation, 
3) Midstream urine culture, If positive, we need to open a field to describe the agent name,
4) Blood glucose test type, should be changed to multiselect control,
5) Add COVID-19 test

### Acceptance criteria
1. We have two types of Syphilis tests. Add the second(missing test) "VDRL"
2. When the test is sometimes positive, it may not be active positive(meaning you can't say a person has syphilis). It would be easier to separate previously recorded positive test and a recent test.  Change the wording from **positive** to **reactive**
3. When the midstream urine culture is positive, we need to open up a field to type the name of the micro organism. 
4. The health worker may perform more than one type of test. This means that the multi select option(checkbox) would be ideal. 
5. Include the type of Covid test, the date and the result of the test. 
The three types of Covid tests that should be listed are: 
1. PCR test
2. Antigen test 
3. Serology

**Comment by hamza-vd** [comment]
@Naima-Bashir 
The following points are unclear in the above description.
- The proper specifications in data-dictionary for "VDRL" option in `syph_test_type` needs to be defined (openmrs_entity/openmrs_entity_id)
- Point 2 above is unclear as to what is needed to be done.
- The data-dictionary for the COVID-19 is needed

**Comment by Naima-Bashir** [comment]
Hi @hamza-vd ,
1.  I have made the Data Dictionary changes here: https://docs.google.com/spreadsheets/d/1Zh38B873ohVCbmO5R1sUn9OF2SMca4vP/edit?usp=sharing&ouid=110412449922271073551&rtpof=true&sd=true
Line 6 of the Quick check section

2. Change the wording from positive to reactive
3.

**Comment by hamza-vd** [comment]
COVID-19 test will be added in issue #673

**Comment by Naima-Bashir** [comment]
Hi @hamza-vd some updates from the clients:
 Point 2: Syphilis_positive name, add OR {vdrl_test} different than ""Negative"" as part of the calculation.
The calculation to consider syphilis positive was:
if({rapid_syphilis_test} = "Positive" OR {rpr_syphilis_test} = "Positive" OR {lab_syphilis_test} = "Positive", 1, 0)

I have added one point to the calculation, to include in the logic the VDRL test result:
if({rapid_syphilis_test} = "Positive" OR {rpr_syphilis_test} = "Positive" OR {lab_syphilis_test} = "Positive", 1, 0) OR {vdrl_test} <> Negative

3. The proper specifications in data-dictionary for "VDRL" option in syph_test_type needs to be defined (openmrs_entity/openmrs_entity_id)
The technical description to VDRL is: Venereal disease research laboratory (VDRL) test is a nontreponemal test, used for screening of syphilis, titration, and follow-up of positive cases.
However, I don't know how to define the openmrs_entity/openmrs_entity_id value.

**Comment by madrinekariuki** [comment]
This has been tested on` reference-app-debug`
user `demo`
android 11

Steps to test for syphilis VDRL:
- login to the apk and sync data
- create a new profile/or use and existing one
- go to tests tab
- scroll to syphilis
- click on done today or done earlier
- observe if the VDRL has been added. (should show on the list)
- select  VDRL observe the new pop up and select one of the options that is not` negative`
- Observe how a Red message pops up showing `Syphilis test positive`

Steps to test for Midstream urine culture:
- login to the apk and sync data
- create a new profile/or use and existing one
- go to tests tab
- scroll to urine
- click on done today or done earlier
- observe how Urine test type pop up and select Midstream urine culture.
- select positive.
- observe how the `agent name` field pop up. 
- fill it.


Steps to test for Add COVID-19 test:
- login to the apk and sync data
- create a new profile/or use and existing one
- go to tests tab
- scroll down and click NEXT
- check covid-19 test and click on done today or done earlier
- observe how an option to select Covid-19 test type is shown


observations:
- For syphilis VDRL has been added and when on selects it you are able to select the test details and for a positive test a pop message appears.
- For urine tests  Midstream urine culture has been added and selecting it then select positive on is prompted to insert the Agent Name.
- For covid tests, the 3 covid test types have been added. 

Find screenshots below.
Covid tests:
![image](https://user-images.githubusercontent.com/84722169/146935377-c0a019be-dec1-4c26-8fb0-4b748da0d650.png)


Midstream urine culture:
![image](https://user-images.githubusercontent.com/84722169/146935693-b6dd5a66-ad8b-4eef-8074-c7f496722cdb.png)

Syphilis VDRL:
![image](https://user-images.githubusercontent.com/84722169/146935720-d06aa5b1-e261-45d8-ba21-5712cd187032.png)
