### ISSUE TITLE
Test Screen Updates

### ISSUE THREAD

**Issue by Naima-Bashir** [opensrp/opensrp-client-anc#682]
### Feature Use Case

"Tests Screen Updates
Enabling tests to be opened on the same screen, one below the other / in list form. 
Reducing the number of clicks. "

### Acceptance criteria
Having to open each and every page of the tests can be long and tiresome. It would be ideal to have a drop down form of the tests that are clickable. 
Section 1 has the active tests that were done 
Section 2 has the next tests that will be done

### Relevant Information
This may affects the tasks tab in the Patient Profile 
Ensure the data is saved in real time so that data is not loss* @dubdabasoduba to verify

**Comment by hamza-vd** [comment]
**As per discussion:**
- There will be no expansion panel and the test sub-form will be displayed below the test.
- The form will be a 2 step form with Step 1 (Section 1) for due and Step 2 (Section 2) for others.

**Comment by madrinekariuki** [comment]
This has been tested on` reference-app-debug`
user `demo`
android 11

Steps:
login to the pk and sync
create a new profile
fill in information
on the Tests tab, check how the tests are arranged.

Expectations:
- The form will be a 2 step form with Step 1 (Section 1) for due and Step 2 (Section 2) for others.
- Tests shall be opened on the same screen, one below the other / in list form


Observations.
- on clicking the tests tab, on is presented with a blank page with the Tab NEXT
- on clicking next, tests are presented in the same form as expected (Step 1 (Section 1) for due and Step 2 (Section 2) for others.)
- However, the response on this page is very slow. i.e when you click on a test e.g for HIV click ordered, the app is taking approx 20 secs  before responding.
- trying to scroll down to record the other tests its also very slow.
- on clicking submit the app crashes and you have to login again
- when you login again no data is lost.

Sharing the video shortly

**Comment by Naima-Bashir** [comment]
The page is taking too long to execute. 
The app is crashing as well 
This has been raised on a separate [issue ](https://github.com/opensrp/opensrp-client-anc/issues/742)affecting the other countries including the OptiBP apk. It is a native form issue. @dubdabasoduba @ndegwamartin @SebaMutuku and @bennsimon to have a session

**Comment by Naima-Bashir** [comment]
This can be closed as we have a separate issue for it
