### ISSUE TITLE
Unable to register new pregnant woman[Bug Report]: 

### ISSUE THREAD

**Issue by TigestT** [opensrp/opensrp-client-anc#686]
### How do we replicate the bug?

Try to register a new pregnant woman using the demo version that has been setup for us to test the app with the Demo/Amani login credentials. I believe the app is using the staging server as I have not done any server setup when testing the app. 
Pasting below the error message I get when i try to register a new client

![20210810_144551 (003)](https://user-images.githubusercontent.com/12300872/137896675-a607c20e-d67a-4ab0-81ba-48d45b04f7ca.png
![20210810_144551 (003)](https://user-images.githubusercontent.com/12300872/137896758-8f078096-8095-47b3-b99e-0b40ff13eb2f.png)
)

### How is this feature expected to work?

Be able to register a pregnant woman, be directed to a new screen to enter the details

**Comment by dubdabasoduba** [comment]
@TigestT what server is the app using. 

This documentation helps set up the unique ids https://smartregister.atlassian.net/wiki/spaces/Documentation/pages/2899345409/How+to+Configure+Unique+IDs+sources+on+OpenSRP

**Comment by TigestT** [comment]
I believe it is using the stage server--whatever the Ona team provides when emailing the apk for WHO team to test
