### ISSUE TITLE
Non-stop Saving Pop-up Message and The Same Client Replicated After Creating New Register

### ISSUE THREAD

**Issue by ellyasafaa** [opensrp/opensrp-client-anc#687]
### How do we replicate the bug?

Device: Samsung A21s
OS: Android 10

1. Login to the app
2. Sync all the clients
3. Click the + Register button to add new register
4. Fill in all information needed
5. Click Save button, you will be navigated to the client profile page
6. Press the back button
7. Observe the error (Non-stop saving pop-up message will appear). This will continuously happen.
8. Terminate the session from the background (Close the background apps of WHO ANC Apps)
9. Find the WHO ANC Apps on the menu in the device
10. Login to the app
11. Observe another error: the client that has just created will be replicated.

Note:
The replicated client will disappear if we clear the data before relogging in to the apps

Please kindly check @Naima-Bashir 

### How is this feature expected to work?

The apps is supposed to be back in the client apps if we press the back button although the visit data has not been entered yet. Also, the client that is created should be only one.

### Please Share other relevant information about the bug

The video of the error can be seen [here](https://drive.google.com/file/d/1-tREwiJxGPvtrXs5Z-sJ_V5JOZoBGewh/view?usp=sharing) from the minutes of 05.16 until the end of the video.

**Comment by ellyasafaa** [comment]
As additional information, if the apps continued to be used to record the data, the data can't be synced unless the apps get the data cleared on the setting (after the error occurred, the user should clear the data if they want to proceed to fill in the data). If not, this will lead to lose the data that have been entered by the user. Happened frequently during user testing.

@Naima-Bashir

**Comment by Naima-Bashir** [comment]
Hi @hamza-vd , kindly pick this ticket after you are done with the one you are working on. 
cc @dubdabasoduba
