### ISSUE TITLE
Unable to save the register if the user takes the picture of the client

### ISSUE THREAD

**Issue by ellyasafaa** [opensrp/opensrp-client-anc#688]
### How do we replicate the bug?

Device: Samsung A21s
OS: Android 10

1. Login to the app
2. Sync all the clients
3. Click the + Register button to add new register
4. Click 'Take A Picture of The Woman' button, it can't be saved at first, for the second try or third try, it can be saved
5. Fill in all information needed
6. Click Save button
7. Observe the error: it will go to the splash screen and the data is not saved

Please kindly check @Naima-Bashir 

### How is this feature expected to work?

The apps is supposed to save the client and navigate the user into the client's profile page after clicking the 'Save' button.

### Please Share other relevant information about the bug

The video of the whole process on how to reproduce the bugs can be seen [here](https://drive.google.com/file/d/1-tREwiJxGPvtrXs5Z-sJ_V5JOZoBGewh/view?usp=sharing) from the beginning until the minutes of 04.41

**Comment by hamza-vd** [comment]
@ellyasafaa does this issue only appear on Samsung A21s? Or were you able to reproduce it on other devices as well?

**Comment by ellyasafaa** [comment]
Hi @hamza-vd, we don't try it on the other devices since we planned to deploy it on Samsung A21s. However, there might be any change in the device we would like to deploy. Is there any issue with the device?
