### ISSUE TITLE
Clicking right-arrow button in the library cause crashes

### ISSUE THREAD

**Issue by ellyasafaa** [opensrp/opensrp-client-anc#689]
### How do we replicate the bug?

Device: Samsung A21s
OS: Android 10 and 11

1. Login to the app
2. Go to library page
3. Click the right-arrow button besides either 'Birth and Emergency Plan' or 'Balanced Nutrition' or 'Physical Activity'
4. Observe the crashes

Please kindly check @Naima-Bashir 

### How is this feature expected to work?

The screen should be navigated to the information page of each section.

### Please Share other relevant information about the bug

The video on how to replicate the bugs can be seen [here](https://drive.google.com/file/d/10KZCXxTRz4rN32tn1Y1RqbGnYU2d3-Dp/view?usp=sharing)

**Comment by Naima-Bashir** [comment]
Passed QA
