### ISSUE TITLE
There is no button to navigate the users to the OptiBP apps if the BP measurement needs to be measured again

### ISSUE THREAD

**Issue by ellyasafaa** [opensrp/opensrp-client-anc#697]
### How do we replicate the bug?

If the blood pressure is abnormal, the apps will ask the user to measure again the blood pressure after 10-15 mins rest. If we pick the OptiBP to measure the blood pressure, there is no widget available that can direct the user to use the OptiBP to measure again the blood pressure of the mother. It needs to be created.

Steps to replicate:
1. Login to the apps
2. Start the visit on one of the clients
3. Click Physical Exam page
4. Fill in the information until you get to the page of Blood Pressure
5. Pick 'OptiBP' in the BP measurement method question
6. Measure your BP, you should get your blood pressure considered high in order to see the question.
7. If you get blood pressure high, then the apps will ask you to measure again.
8. There is no widget to navigate to the OptiBP apps again.

Please kindly check @Naima-Bashir 

### How is this feature expected to work?

If the method chosen is OptiBP then the widget should appear if it asked to re-measure the blood pressure.

**Comment by Naima-Bashir** [comment]
This is an enhancement . It is not a high priority for the team. @elwinameylentia @ellyasafaa

**Comment by Naima-Bashir** [comment]
To be picked up later after the main priority tickets have been worked on. cc @elwinameylentia

**Comment by junaidwarsivd** [comment]
![Screenshot_1641466910](https://user-images.githubusercontent.com/81764603/148373331-9676d168-28e0-42f1-9b50-5329fa390466.png)
![Screenshot_1641466875](https://user-images.githubusercontent.com/81764603/148373354-34a1482f-e4ea-4286-bb72-2c2926418e15.png)
@ellyasafaa  it is implemented in this way if the blood pressure exceeds the acceptable level widget prompt changes from get started to remeasure

**Comment by madrinekariuki** [comment]
@junaidwarsivd 
Tested this on `optibp-reference-app-debug-v1.6.10` apk
user: `demo`

steps:
Followed the steps mentioned [here](https://github.com/opensrp/opensrp-client-anc/issues/697#issue-1044369334) .

observations:
-when you input a high BP, prompt to remeasure appears down below.
-when you click remeasure you get an error. (see screenshot below.) and video shared on slack here
-user cannot proceed to the next page until the BP is remeasured.

![image](https://user-images.githubusercontent.com/84722169/148376517-fd4fe99e-5b67-4475-a2bf-056b51fe1be6.png)

**Comment by junaidwarsivd** [comment]
@madrinekariuki  please install the optibp apk in order to launch the optibp app

**Comment by madrinekariuki** [comment]
@junaidwarsivd 
This is noted. 

Please find below details after installing the APK to launch the optibp app:
- when you input a high BP, prompt to remeasure appears down below.
- when you click remeasure you are redirected to the optibp app and your BP measurements are taken. 
- Let the app scan your BP.
- Then you click return to ANC  and the Values from the optibp app results autofill (screenshot attached below.) in the `SBP after 10-15 minutes rest `and `DBP after 10-15 minutes rest`
- Then you are able to click next to proceed to the next page.

screenshots:
![image](https://user-images.githubusercontent.com/84722169/148385993-14dfee18-2187-4fef-9911-a7c3bcd31274.png)

**Comment by Naima-Bashir** [comment]
This has been fixed. APK will be shared shortly.

**Comment by madrinekariuki** [comment]
Retested on the  apk:` optibp-reference-app-debug-v1.6.13`
user: demo

observation:
The app behaves as described above [here](https://github.com/opensrp/opensrp-client-anc/issues/697#issuecomment-1006566587)
