### ISSUE TITLE
Toaster message "HIV risk counseling" popped up when Partner HIV Status is selected as Negative, but did not pop up when selected as Positive

### ISSUE THREAD

**Issue by elwinameylentia** [opensrp/opensrp-client-anc#703]
### How do we replicate the bug?

Steps to replicate:

1. Log in to the apps
2. Start the visit on one of the clients
3. Click the Profile page
4. Fill in the information until you get to the page of Partner's HIV Status
5. Choose Positive
6. "HIV risk counseling" message does not show up
7. Choose Negative
8. "HIV risk counseling" message will show up instead

Please kindly check @Naima-Bashir

### How is this feature expected to work?

The "HIV risk counseling" message should show up when Partner's HIV Status is Positive, and it should not show up if Partner's HIV Status is Negative.

### Please Share other relevant information about the bug

Documentation can be seen [here](https://drive.google.com/file/d/1WtFmRGFKss8GLSBMMtYmh8bP4hSbCbz6/view?usp=sharing) and [here](https://drive.google.com/file/d/1X0K94ypgh0zIzdkgq-Vjq55rbkopYYxV/view?usp=sharing)

**Comment by Naima-Bashir** [comment]
This is noted @elwinameylentia . I'll assign @junaidwarsivd to pick it up from Friday onwards.

**Comment by dubdabasoduba** [comment]
@junaidwarsivd Please make this a general app update. 

The [Data dictionary](https://docs.google.com/spreadsheets/d/1Zh38B873ohVCbmO5R1sUn9OF2SMca4vP/edit#gid=1562301016) defines it as so. 

`if({partner_hiv_status} = "Positive" OR {hiv_test_partner_result} = "Positive", 1, 0)`

**Comment by Naima-Bashir** [comment]
Passed QA
