### ISSUE TITLE
App is crashing

### ISSUE THREAD

**Issue by Naima-Bashir** [opensrp/opensrp-client-anc#707]
### How do we replicate the bug?

This was raised by the QA team. cc @Mstjamush 
Crash logs:
`11-15 11:03:16.858 13032 13032 E AndroidRuntime: FATAL EXCEPTION: main
11-15 11:03:16.858 13032 13032 E AndroidRuntime: Process: org.smartregister.anc, PID: 13032
11-15 11:03:16.858 13032 13032 E AndroidRuntime: java.lang.RuntimeException: Unable to resume activity {org.smartregister.anc/org.smartregister.anc.library.activity.MainContactActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'int java.lang.CharSequence.length()' on a null object reference
11-15 11:03:16.858 13032 13032 E AndroidRuntime: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4907)
11-15 11:03:16.858 13032 13032 E AndroidRuntime: 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4944)
11-15 11:03:16.858 13032 13032 E AndroidRuntime: 	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
11-15 11:03:16.858 13032 13032 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
11-15 11:03:16.858 13032 13032 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
11-15 11:03:16.858 13032 13032 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2325)
11-15 11:03:16.858 13032 13032 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
11-15 11:03:16.858 13032 13032 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:246)
11-15 11:03:16.858 13032 13032 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8633)
11-15 11:03:16.858 13032 13032 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-15 11:03:16.858 13032 13032 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
11-15 11:03:16.858 13032 13032 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
11-15 11:03:16.858 13032 13032 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'int java.lang.CharSequence.length()' on a null object reference
11-15 11:03:16.858 13032 13032 E AndroidRuntime: 	at org.joda.time.format.DateTimeFormatterBuilder$CharacterLiteral.parseInto(DateTimeFormatterBuilder.java:1225)
11-15 11:03:16.858 13032 13032 E AndroidRuntime: 	at org.joda.time.format.DateTimeFormatterBuilder$Composite.parseInto(DateTimeFormatterBuilder.java:2516)
11-15 11:03:16.858 13032 13032 E AndroidRuntime: 	at org.joda.time.format.InternalParserDateTimeParser.parseInto(InternalParserDateTimeParser.java:52)
11-15 11:03:16.858 13032 13032 E AndroidRuntime: 	at org.joda.time.format.DateTimeFormatterBuilder$MatchingParser.parseInto(DateTimeFormatterBuilder.java:2610)
11-15 11:03:16.858 13032 13032 E AndroidRuntime: 	at org.joda.time.format.DateTimeFormatter.parseDateTime(DateTimeFormatter.java:925)
11-15 11:03:16.858 13032 13032 E AndroidRuntime: 	at org.joda.time.DateTime.parse(DateTime.java:160)
11-15 11:03:16.858 13032 13032 E AndroidRuntime: 	at org.joda.time.DateTime.parse(DateTime.java:149)
11-15 11:03:16.858 13032 13032 E AndroidRuntime: 	at org.smartregister.util.Utils.getAgeFromDate(Utils.java:676)
11-15 11:03:16.858 13032 13032 E AndroidRuntime: 	at org.smartregister.anc.library.activity.MainContactActivity.onResume(MainContactActivity.java:74)
11-15 11:03:16.858 13032 13032 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1456)
11-15 11:03:16.858 13032 13032 E AndroidRuntime: 	at android.app.Activity.performResume(Activity.java:8353)
11-15 11:03:16.858 13032 13032 E AndroidRuntime: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4897)
11-15 11:03:16.858 13032 13032 E AndroidRuntime: 	... 11 more
11-15 11:03:16.874   798  1033 D connsyslogger: SD_LOG_ROOT is /data/debuglogger/connsyslog/fw.
11-15 11:03:16.874   798  1033 D connsyslogger: systemReady:1
`
@Mstjamush kindly provide steps on how to replicate this bug. Thank you

### How is this feature expected to work?

App should not crash

**Comment by Mstjamush** [comment]
Steps

1. Login with the user demo/Amani123
2. Click on client before the sync process ends

**Comment by Naima-Bashir** [comment]
@madrinekariuki kindly retest this in the next apk and reopen if issue persists
