### ISSUE TITLE
Search Page: Searching and clicking on a user causes an app crash 

### ISSUE THREAD

**Issue by Naima-Bashir** [opensrp/opensrp-client-anc#713]
### Affected App or Server Version

Latest apk: 1.6.11 rc1

### What kind of support do you need?

Login to the app
Click on the search page
Search for a patient eg Test 
Notice how all the patients have 12 weeks. This is a bug 
Click on a patient and observe how the app crashes 

### What is the acceptance criteria for your support request?

1. The search page should return the correct number of gestational weeks
2. The app should not crash when a user is clicked after searching

Video can be found [here](https://drive.google.com/file/d/1kmxOBUE_vRuMttlndx5ywqLLkhIPYpL7/view)

**Comment by Naima-Bashir** [comment]
Crash occurred in android 11 only. 
Could be a data related issue from the server side
Dev work as been done, it requires Clearance of Data.

**Comment by Naima-Bashir** [comment]
Data has been cleared by @dubdabasoduba . @junaidwarsivd retest this ticket

**Comment by Naima-Bashir** [comment]
Issue is complete. Data needs to be cleared once more. @dubdabasoduba @junaidwarsivd

**Comment by madrinekariuki** [comment]
APK used:` optibp-reference-app-debug-v1.6.11.apk`
user : `demo`

steps

- login and sync data
- click on search
- input the client first or last name
- click on search
- click on the profile that shows
- confiim the correct GA shows and also that the app does not crash

observations:
-the correct GA shows. used client `lynn nduta`
-the app DOES NOT crash on clicking the clients profile
