### ISSUE TITLE
[Ona Support Request]: How to generate Task in Contact Summary page

### ISSUE THREAD

**Issue by elwinameylentia** [opensrp/opensrp-client-anc#714]
### Affected App or Server Version

v1.6.11-rct1

### What kind of support do you need?

The WHO-ANC app from ONA in this version has successfully generated Task based on the undone test. However, the SID IT team hasn't been able to replicate it. A demonstration to show the way to do it would be helpful. 

### What is the acceptance criteria for your support request?

SID IT Team is able to generate Task based on undone/unfinished tests

### Relevant Information
Examples of 'Task' referred to in this ticket can be seen here 
https://drive.google.com/file/d/1Bim1P8n-zxsdSHRGCY3-mMHtpdniY94S/view?usp=sharing https://drive.google.com/file/d/1Bm0P5Q-4wzM8qAoFm37Ou5N6Gj_XoH_3/view?usp=sharing
_No response_

**Comment by Naima-Bashir** [comment]
Naima to setup a pairing session this week with @elwinameylentia @SebaMutuku @junaidwarsivd 
cc @dubdabasoduba

**Comment by Naima-Bashir** [comment]
The SID team have successfully generated the task
