### ISSUE TITLE
[Ona Support Request]: How to generate expected future contact date shown in Client Page and after saving ANC contact

### ISSUE THREAD

**Issue by elwinameylentia** [opensrp/opensrp-client-anc#715]
### Affected App or Server Version

v1.6.11-rct1

### What kind of support do you need?

Due to the local adaptation from 8 contacts to 6 contacts ANC visit, the SID IT team needs to modify the expected future contact date according to Indonesian health regulation. A demonstration to show the way to do it would be helpful.

### What is the acceptance criteria for your support request?

SID IT Team is able to modify expected future contact date to suit 6 contacts adaption

**Comment by Naima-Bashir** [comment]
Hi @dubdabasoduba , how do you suppose we can support the SID team on this?

**Comment by Naima-Bashir** [comment]
Setting up a pairing session next week @elwinameylentia @ellyasafaa @dubdabasoduba

**Comment by Naima-Bashir** [comment]
Pairing session will take place next week Thursday 12:00 - 1.00 pm EAT
