### ISSUE TITLE
[Ona Support Request]: WHO-ANC client app mixed translation issue

### ISSUE THREAD

**Issue by elwinameylentia** [opensrp/opensrp-client-anc#716]
### Affected App or Server Version

v1.6.11-rct1

### What kind of support do you need?

SID IT team has been able to translate most of the WHO-ANC client app to the local language. However, some values cannot be translated from English because it will break the logic or cause the logic to fail. This particular issue has been demonstrated in a call with @junaidwarsivd and @Naima-Bashir. It would be helpful if ONA can help find the reason why this translation difficulty happens and show the way to solve it.

### What is the acceptance criteria for your support request?

SID IT team understands why the translation difficulty happened and is able to translate the whole WHO-ANC client app to Bahasa Indonesia (local language)

### Relevant Information

Mixed translation:
https://drive.google.com/file/d/11PbMo7frTLrS0eUgaGWGU9HPp4AXsvD2/view?usp=sharing 
https://drive.google.com/file/d/11VO45ZljbOe9CB2Cvpkn0DHivKpHVpRz/view?usp=sharing
https://drive.google.com/file/d/136BKolI9PT1Ez4OOFxUxQXQIuQO_TJcI/view?usp=sharing 
https://drive.google.com/file/d/12zzsXE_zHrX6WgLfbohtAW1-4Mw7VJ6l/view?usp=sharing

**Comment by Naima-Bashir** [comment]
Connected to this ticket https://github.com/opensrp/opensrp-client-anc/issues/728. Currently in progress
