### ISSUE TITLE
Mother GA from search feature is all set at 12 weeks

### ISSUE THREAD

**Issue by elwinameylentia** [opensrp/opensrp-client-anc#717]
### How do we replicate the bug?

Steps to replicate:
1. Log in to the WHO-ANC app
2. Go to the search page
3. Chose either "Outside and inside my health facility" or "My health facility only"
4. Input mother's first name
5. Click Search
6. All mother's profiles show GA: 12 weeks

This issue has been demonstrated in a call with @Naima-Bashir 

### How is this feature expected to work?

When being searched with the search feature, the mother's profile should show the correct GA weeks based on LPM or USG

### Please Share other relevant information about the bug
Screenshots of bug referred to in this issue can be seen here
https://drive.google.com/file/d/18Hf6zQjkKgS-h2wse79zqOb-uxA-gYtH/view?usp=sharing 
https://drive.google.com/file/d/18FVXQDcgZqB5LuxibJOVQWVKzsgiGIKz/view?usp=sharing 
_No response_

**Comment by Naima-Bashir** [comment]
Hi @junaidwarsivd kindly pick this up after #713

**Comment by Naima-Bashir** [comment]
The data has to be cleared (tables that hold the patient data/ events and clients) for a fix of this ticket. This cannot be done at the moment as the SID team is actively testing the app.
SID have agreed that this will be paused until the other high priority tickets are worked on.

**Comment by Naima-Bashir** [comment]
Data has been cleared. @Naima-Bashir @junaidwarsivd to retest this ticket 
How to test: Create new users and test to see if the GA is returning 12 weeks

**Comment by Naima-Bashir** [comment]
This ticket is complete. Awaiting QA

**Comment by madrinekariuki** [comment]
Tested on `optibp-reference-app-debug-v1.6.11`
user `demo` 

steps:

- login to the apk
- sync data 
- add different clients with different GA based on LPM or USG
- fill in all the forms and finalize
- click on search select either "Outside and inside my health facility" or "My health facility only"
- search using the first or last name for the different mothers and check their GA

Expected.
The GA should be different for the mothers depending on the correct LPM or USG input.

Observation.
The GA differs for every mother and It is correctly calculated depending on the LPM or USG inserted.

see screenshot below:

![image](https://user-images.githubusercontent.com/84722169/146165513-3ff9abba-13bc-40f2-b1a8-ae3329a5e941.png)
