### ISSUE TITLE
Options for number of live births and number of stillbirths don't show up

### ISSUE THREAD

**Issue by elwinameylentia** [opensrp/opensrp-client-anc#718]
### How do we replicate the bug?

Steps to replicate:
1. Register a new client
2. Fill in the quick check
3. Fill in the profile form until reaching the Obstetric History page
4. Enter no. of pregnancies more than 1 (in the video example, it's 3)
5. No. of pregnancies lost/ended 0 or 1
6. No. of live births and No. of stillbirths options do not show up

### How is this feature expected to work?

No. of live births and No. of stillbirths options should show up

### Please Share other relevant information about the bug

Video for issue referred to in this ticket can be seen here:
https://drive.google.com/file/d/18aZUXx0xlVUJ6Ki4TGmwCIPxCMBQxLa9/view?usp=sharing

**Comment by Naima-Bashir** [comment]
Hi @elwinameylentia , this ticket is a new feature that is currently being worked in the Brazil Updates here: [https://github.com/opensrp/opensrp-client-anc/issues/671#issuecomment-968882372] 
This ticket has been paused as the team is working on SID bug fixes. Once that is complete, the team will pick it up and merge with the optibp branch

**Comment by Naima-Bashir** [comment]
This has been solved, it is related to the native forms. @madrinekariuki kindly test on the latest apk

**Comment by madrinekariuki** [comment]
Tested on 
optibp-reference-app-debug-v1.6.13
user: `demo`
android version : Android 11

Steps:
Followed the steps highlighted [here](https://github.com/opensrp/opensrp-client-anc/issues/718#issue-1066934237).
tested using clients `Re Tests` ID `3198801 `and `Don Pat `ID `3198793`

Observation:
- the No. of live births and No. of stillbirths options are showing up.

see below screenshot.
![image](https://user-images.githubusercontent.com/84722169/148761983-27c1abaa-9b58-428b-8333-438550829e8b.png)
