### ISSUE TITLE
Sync button takes more than 10s after being clicked to start spinning and syncing

### ISSUE THREAD

**Issue by elwinameylentia** [opensrp/opensrp-client-anc#719]
### How do we replicate the bug?

Steps to replicate:
1. Log in to the WHO-ANC app
2. Tap the sync button on the client page
3. The sync button will only start spinning and syncing after more than 10s. This causes the user to think that the button is unresponsive and will tap the button multiple times.

### How is this feature expected to work?

The sync button should start spinning and syncing right after being clicked

### Please Share other relevant information about the bug

This issue has been raised on August 30, 2021, on this sheet https://docs.google.com/spreadsheets/d/1U8e3NYO_AStHxdXZUd2tEP-AHguNGUZU/edit#gid=1219538130&range=B2

Video for issue referred to on this ticket can be seen here https://drive.google.com/file/d/1XdAHuETyawyDXOoBuUz-jmk4AvGGp8Ez/view

**Comment by Naima-Bashir** [comment]
This is a nice to have feature and not a high priority. We shall pick it up once the other high priority tickets are complete. @elwinameylentia @dubdabasoduba

**Comment by Naima-Bashir** [comment]
Will be picked up this sprint
