### ISSUE TITLE
Gestational Age and EDD are incorrect 

### ISSUE THREAD

**Issue by elwinameylentia** [opensrp/opensrp-client-anc#720]
### How do we replicate the bug?

Steps to replicate the bug:
1. Register a new client
2. Fill in the form until the Current Pregnancy page (Profile form)
3. Fill in the LMP and USG date
4. The generated GA and EDD calculation is incorrect

### How is this feature expected to work?

Generated GA and EDD calculation should be correct based on the LMP and USG date

### Please Share other relevant information about the bug

Screenshot of the incorrect GA and EDD year can be seen here https://drive.google.com/file/d/1VuR23npmj8wdjQPfaf1MH-y-0aY8lQNz/view

The video process of the issue can be seen here on minute 03.00 - 03.25 https://drive.google.com/file/d/1-MJN3pooMTY6qkxVqm2RNH97c4qA4_cW/view?usp=sharing

**Comment by junaidwarsivd** [comment]
this issue is completed

**Comment by Naima-Bashir** [comment]
Related to #717

**Comment by madrinekariuki** [comment]
tested on `optibp-reference-app-debug-v1.6.11.apk`
user : `madrineqa`

observed: newly added clients:
```
Doris Tee
Bernice Mumbi
lucia mwikali
```

their GA and EDD are correctly calculated. 

![image](https://user-images.githubusercontent.com/84722169/146187313-cb7ad33f-4b96-458a-a5a9-e09ca9eff4e7.png)

**Comment by elwinameylentia** [comment]
this issue is still replicated in client Eve Siii ID 3023819
https://docs.google.com/spreadsheets/d/1DiEzVsPlZqu8IbL3hRvQnH1ucM4K4fGcTQDPJEHvycM/edit?usp=sharing

**Comment by Naima-Bashir** [comment]
Kindly clear your cache and test again @elwinameylentia . If it persists, we will reopen it

**Comment by elwinameylentia** [comment]
hi, we've cleared the cache and data, then we registered a new patient name Ny Q Ny Q. As you can see here, her GA and EDD are still incorrect
https://drive.google.com/file/d/1-g9S2wJFA8k1DDju_sGl5jwIOHggBr5F/view?usp=sharing
https://drive.google.com/file/d/1-i38ED7nuy-Ejd9z70NM0J2xbS_aWmMz/view?usp=sharing 
https://drive.google.com/file/d/1-udzvVQ2057r3ze7bZ9dSce4c1naTkuC/view?usp=sharing

**Comment by madrinekariuki** [comment]
This is noted. seems not all clients are getting incorrect GA and EDD. I have added  a new client whose details are showing correctly.
`Mules June`
![image](https://user-images.githubusercontent.com/84722169/146873150-d239ef5d-4470-47d1-817a-ae5e9f2d9786.png)

**Comment by junaidwarsivd** [comment]
hi @madrinekariuki  the case for replication of this issue is you start the contact of the patient > go to profile > select LMP known or Ultrasound done to  yes  when the date popup opens do not select any date  and cancel the date picker by tapping anywhere other than the date dialog ..... once its done proceed to complete the contact required details then finish and finalize the profile

**Comment by madrinekariuki** [comment]
Testing from: `optibp-reference-app-debug-v1.6.11`
user: `demo`

From the instructions above its not clear what details to put on` GA from ultrasound` and also on the part for` select preferred gestational age`. 
these 2 are mandatory values...

I have put a random value 4 for `GA from ultrasound`  and for  `select preferred gestational age` I have selected using LMP. for client `Mueni Kamau`.



see screenshots below for the GA and EDD of the client.
![image](https://user-images.githubusercontent.com/84722169/147101704-d579e9cf-92c0-4073-8f03-429afd421bb6.png)

**Comment by madrinekariuki** [comment]
@junaidwarsivd 
Testing from: [optibp-reference-app-debug-v1.6.12](https://onaio.slack.com/archives/CETQ18XL3/p1640183475094000?thread_ts=1640176651.093300&cid=CETQ18XL3)
user: `demo`

I have added a new client `Just Lion`

see screenshots below:
![image](https://user-images.githubusercontent.com/84722169/147112263-9c99709d-6437-4613-942f-15012fe35180.png)

**Comment by Naima-Bashir** [comment]
This issue has been fixed, APK can be found on slack. APK will be shared with the client this week

**Comment by madrinekariuki** [comment]
This has been retested. 
`optibp-reference-app-debug-v1.6.13`
`user`
android version: 11

steps:
- Followed the steps highlighted [here](https://github.com/opensrp/opensrp-client-anc/issues/720#issuecomment-999545667)
- Added clients. `mumbi witu` and` wangu w`


observation:
The Gestational Age and EDD are updating correctly.

screenshot. 

![image](https://user-images.githubusercontent.com/84722169/148765135-839fc405-6804-44d8-85d0-2c58a379f00f.png)

**Comment by Naima-Bashir** [comment]
Hi @junaidwarsivd 
For this ticket. We shall do the following:
1. Do not display the GA of a patient who has passed 42 weeks. 
2. If a patient has passed 42 weeks: a) Follow up with the woman b) Close out form(remove the woman from the list). 

Kindly let me know if this is clear. cc @dubdabasoduba

**Comment by Naima-Bashir** [comment]
This ticket has been worked on by @junaidwarsivd . Will be tested in the next release

**Comment by Naima-Bashir** [comment]
This has passed QA. Kindly reopen if it persisits @elwinameylentia
