### ISSUE TITLE
Upcoming contact date is not showing the right year

### ISSUE THREAD

**Issue by elwinameylentia** [opensrp/opensrp-client-anc#721]
### How do we replicate the bug?

Steps to replicate:
1. Register a new client
2. Fill in all the forms until Counselling and Treatment
3. Click finalize
4. Click save + finish
5. Upcoming contact dates will appear. The date and month are correct, but the year is 0002

### How is this feature expected to work?

The upcoming contact dates should show the correct date, month, and year

### Please Share other relevant information about the bug

Video process for this issue can be seen here, especially in minutes 16.35-16.50
https://drive.google.com/file/d/1-MJN3pooMTY6qkxVqm2RNH97c4qA4_cW/view?usp=sharing

**Comment by Naima-Bashir** [comment]
Currently in progress. The app device language is set to English and the device local language is either bahasa or german, causing the bug to appear.

**Comment by junaidwarsivd** [comment]
@Naima-Bashir  @elwinameylentia   i've switched device language to  Indonesia (bahasa) also tried on German language but was unable to replicate the issue

**Comment by madrinekariuki** [comment]
This has been tested on the apk  `optibp-reference-app-debug-v1.6.11` 
test user `demo`
Language english

observation:
-A newly registered client, the upcoming contact dates show the correct date, month, and year see the screenshot below:

![image](https://user-images.githubusercontent.com/84722169/146135507-04d79ec4-9371-43ba-8145-32e8efd3a99f.png)
