### ISSUE TITLE
Multiple same statements appear in the site characteristics menu

### ISSUE THREAD

**Issue by elwinameylentia** [opensrp/opensrp-client-anc#722]
### How do we replicate the bug?

Steps to replicate the bug:
1. Log in to WHO-ANC app
2. Tap 'Me' (Demo User)
3. Tap Site Characteristics
4. The page will show multiple lines for each characteristics 

### How is this feature expected to work?

Each characteristic should only be written once

### Please Share other relevant information about the bug

Screenshot of the issue can be seen here https://drive.google.com/file/d/1Wq7Uf0kWMC2ndFqCBPDTai-XXfcftLtu/view?usp=sharing

**Comment by madrinekariuki** [comment]
Tested on `optibp-reference-app-debug-v1.6.11`
user : `demo`

steps:

- login to the device
- sync data
- click on 'me' on bottom right
- click on site characteristics.


observations:
It is noted that  each site characterisitic appears in its own line. 

screenshot:
![image](https://user-images.githubusercontent.com/84722169/146150244-3960b309-f27c-4d6a-93d5-ae0ca94810e0.png)
