### ISSUE TITLE
Pop-up info of Generalized HIV shows "&amp;amp;gt; 1%"

### ISSUE THREAD

**Issue by elwinameylentia** [opensrp/opensrp-client-anc#723]
### How do we replicate the bug?

1. Log in to WHO-ANC app
2. Tap 'Me' (Demo User)
3. Tap Site Characteristics
4. Tap the info (I) for Generalized HIV epidemic
5. The pop-up info will show "is the HIV prevalence consistently &amp;amp;gt; 1% in pregnant women attending antenatal clinics at your facility?"

### How is this feature expected to work?

The pop-up info should show "is the HIV prevalence consistently 1% in pregnant women attending antenatal clinics at your facility?"

### Please Share other relevant information about the bug

Screenshot of the issue can be seen here https://drive.google.com/file/d/1Wm8VuwvlFA_bGgBjxkRz0GzFmf768enp/view?usp=sharing

**Comment by hamza-vd** [comment]
@dubdabasoduba 
After you updated the `site_characteristics` this is what im getting in response:
``` 
[
  {
    "identifier": "site_characteristics",
    "settings": [
      {
        "settingMetadataId": "163",
        "serverVersion": 0,
        "description": "\"Are all of the following in place at your facility: \r\n1. A protocol or standard operating procedure for Intimate Partner Violence (IPV); \r\n2. A health worker trained on how to ask about IPV and how to provide the minimum response or beyond;\r\n3. A private setting; \r\n4. A way to ensure confidentiality; \r\n5. Time to allow for appropriate disclosure; and\r\n6. A system for referral in place. \"",
        "label": "Minimum requirements for IPV assessment",
        "type": "Setting",
        "value": "true",
        "uuid": "bba96687-e0c6-419b-aae6-fc7b9201a5c3",
        "metadataVersion": 1066,
        "key": "site_ipv_assess",
        "settingIdentifier": "site_characteristics"
      },
      {
        "settingMetadataId": "164",
        "serverVersion": 0,
        "description": "Is an ultrasound machine available and functional at your facility and a trained health worker available to use it?",
        "label": "Ultrasound available",
        "type": "Setting",
        "value": "false",
        "uuid": "19adbf84-fa8a-4456-9db6-d3888a242a8e",
        "metadataVersion": 1067,
        "key": "site_ultrasound",
        "settingIdentifier": "site_characteristics"
      }
    ],
    "serverVersion": 62,
    "providerId": "demo",
    "locationId": "44de66fb-e6c6-4bae-92bb-386dfe626eba",
    "teamId": "ca2d2f3f-573d-4b99-b060-b1ac1bad3104",
    "_rev": "v1",
    "team": "Bukesa",
    "_id": "e30e6360-02cc-4ba0-82c3-1b390e9ac4e3",
    "type": "SettingConfiguration"
  }
]
```

There is No Generalized HIV in settings:
![Screenshot_1638791740](https://user-images.githubusercontent.com/70560433/144842648-b38ffe12-9d41-4071-b9c9-57eac3a5af34.png)

Is this how it is supposed to be?

**Comment by dubdabasoduba** [comment]
@hamza-vd @Naima-Bashir Yes, the site characteristics were updated to 2 by the WHO team https://github.com/opensrp/opensrp-client-anc/blob/master/opensrp-anc/src/main/assets/anc_site_characteritics.json

**Comment by Naima-Bashir** [comment]
Hi @elwinameylentia @ellyasafaa Kindly retest this. It is not showing on our end. See image below.

**Comment by elwinameylentia** [comment]
yes it's also not showing anymore on our end due to the site characteristics being updated

**Comment by Naima-Bashir** [comment]
closing this

**Comment by madrinekariuki** [comment]
tested on : `optibp-reference-app-debug-v1.6.11`
user` demo`

observation:
observed the  pop-up info is not showing anymore as indicated above the site characteristics  were updated and thats why it is not showing.

see screenshot below of how the site characteristics page currently looks like:
![image](https://user-images.githubusercontent.com/84722169/146161042-5affecc4-b476-44ec-91ca-350cb751ed45.png)
