### ISSUE TITLE
Task list is showing a blank list

### ISSUE THREAD

**Issue by elwinameylentia** [opensrp/opensrp-client-anc#724]
### How do we replicate the bug?

For the next contact (contact after contact 1), tasks list on the profile page will add up with blank lists 

Steps to replicate:

1. Log in to WHO-ANC app
2. Go to Client Lucia Zulu (ID 2489797) profile
3. Go to the Task tab
4. The Task list will show Urine test, Syphilis test, followed by a blank list, then Ultrasound test and Hepatitis B test

### How is this feature expected to work?

The Task list should display all the unfinished tests and measurements correctly

### Please Share other relevant information about the bug

Screenshot of the issue can be seen here https://drive.google.com/file/d/1WqBIdwq0bRbnurDxETDP_N7xVFG-EDMD/view?usp=sharing

**Comment by SebaMutuku** [comment]
Issue resolved.
How to test.
1. Clone the code 
2. Checkout on branch merge/general-app-updates
3. Build/generate and apk and test.

**Comment by Naima-Bashir** [comment]
@Naima-Bashir to retest this and respond.

**Comment by Naima-Bashir** [comment]
This has been fixed and is working now. @elwinameylentia Kindly retest.

**Comment by elwinameylentia** [comment]
can I test this now or do I wait until the new APK is built?

**Comment by Naima-Bashir** [comment]
Which apk are you using? The data was cleared by @dubdabasoduba so it shouldn't show the old users @elwinameylentia

**Comment by Naima-Bashir** [comment]
Tested this with @elwinameylentia. Closing this

**Comment by madrinekariuki** [comment]
Tested this using` optibp-reference-app-debug-v1.6.11 apk`
user `demo`
mentioned user is not showing show I used client `Bernice mumbi `

steps:

- Log in to WHO-ANC app
- Go to Client Bernice mumbi id(3023827) profile
- Go to the Task tab


Observations:
- The Task list shows:
  blood type test
  hepatitis B test
  syphilis test
  urine test
  blood hemoglobin test

There is no blank list shown. 
see below screenshot.
![image](https://user-images.githubusercontent.com/84722169/146159183-daf8ceae-3d49-43a4-9670-c542dded75d8.png)
