### ISSUE TITLE
Pdf download message appeared but cannot be located

### ISSUE THREAD

**Issue by elwinameylentia** [opensrp/opensrp-client-anc#725]
### How do we replicate the bug?

The PDF downloaded message appears, but there is not known where the location of the file downloaded, and there seems no file downloaded
1. Register a new client
2. Fil in all the forms
3. Tap finalize
4. Pdf saved successfully message will pop up but the file cannot be found in the device

### How is this feature expected to work?

The pdf file can be found inside the device. It would be better if when the pop-up message is tapped, it can open the pdf file for the user to see

### Please Share other relevant information about the bug

screenshot of the message can be seen here https://drive.google.com/file/d/1WNe57VJeZ7TDO0VWPA6BsueT5AEK5OUt/view?usp=sharing

**Comment by Naima-Bashir** [comment]
Hi @shoaibmushtaq25 @junaidwarsivd , can you help answer this ticket? The SID team is trying to locate the PDF document

**Comment by junaidwarsivd** [comment]
its saved under the app local storage file which is storage/emulated/0/Android/org.smartregister.anc/files/WHO ANC/ targetfile.pdf

**Comment by Naima-Bashir** [comment]
cc @elwinameylentia @ellyasafaa : its saved under the app local storage file which is storage/emulated/0/Android/org.smartregister.anc/files/WHO ANC/ targetfile.pdf
it can be seen under file explorer

**Comment by elwinameylentia** [comment]
@Naima-Bashir @junaidwarsivd yes I'm aware that that's what was written in the pop-up message
However, I cannot find that saved file in the app local storage
here's a video of me registering a new client and trying to find the saved pdf of that client https://drive.google.com/file/d/1Ci2HrgKEo46SdyROT6PQ9x6nwS1p2H3g/view?usp=sharing

Perhaps I'm looking at the wrong place. It'd be helpful if you can share a screen recording video for the process of locating the pdf in your android phone. Thanks!

**Comment by junaidwarsivd** [comment]
@elwinameylentia  i've attached the recording of the pdf file access https://drive.google.com/file/d/1S3ytSlHddXYwdbabanteN-0sh36simM7/view?usp=sharing

**Comment by elwinameylentia** [comment]
@junaidwarsivd thank you for the video. But as I've shown you in the gmeet, no file was found in the Samsung device (we are most likely to deploy the app with Samsung phone due to the OptiBP feature). Kindly try to use the app on a Samsung phone (not an emulator) to ensure: 1) that the contact summary file is truly downloaded, 2) where the file is located.
This feature is actually very useful for the health workers for their reporting needs, that's why we want to make sure that it works. Thanks!

**Comment by Naima-Bashir** [comment]
Hi @junaidwarsivd , have you had a follow up call/ session with @elwinameylentia on this ticket?

**Comment by junaidwarsivd** [comment]
hi @Naima-Bashir  @elwinameylentia  can we have a call session for this issue today ?

**Comment by Naima-Bashir** [comment]
Ticket has been reopened for further investigations on the specific Samsung A21 phone

**Comment by elwinameylentia** [comment]
i'm available for a call session with the usual time, on any day

**Comment by madrinekariuki** [comment]
This has been tested on a Samsung A12 device.
profile created: Bernice mumbi

Observation:
- when you create  a profile and finalize a report path is generated and shows on the screen However when you click on it is not opening. Path indicated is  `storage/emulated/0/Android/org.smartregister.anc/files/WHO ANC/ targetfile.pdf`
- However on the physical device the path is different.
- For one to view the report, you have to go to `/internal storage/WHO AN`C (observed in my physical device)
- when you click the file from there you are able to see it. 

see screenshot below:
![image](https://user-images.githubusercontent.com/84722169/146148272-2cbfb513-9256-4c52-a77b-926f07d5b25c.png)

**Comment by elwinameylentia** [comment]
hi @madrinekariuki, just want to make sure, which APK version did you use to test this? is it the latest one released yesterday? thanks!

**Comment by madrinekariuki** [comment]
> hi @madrinekariuki, just want to make sure, which APK version did you use to test this? is it the latest one released yesterday? thanks!

I have updated the details @elwinameylentia

**Comment by elwinameylentia** [comment]
hi @Naima-Bashir @junaidwarsivd @madrinekariuki 
yes this function is working and i can find the pdf on the phone. but indeed the data is overwritten every time we register a new client and there's no mother's name/ID/registration info that allows us to identify whom the report belongs to. 
is this intentional?
https://drive.google.com/file/d/1I9USgCMhD8HK-Nx2UD-ndqFnFPxrJNZG/view?usp=sharing
