### ISSUE TITLE
Incorrect information on the summary page before finalizing the visit data

### ISSUE THREAD

**Issue by elwinameylentia** [opensrp/opensrp-client-anc#726]
### How do we replicate the bug?

Some information on the summary page did not appear and showed the repeated question instead (e.g. Tobacco cessation counseling done: Tobacco cessation counseling done:)

Steps to replicate:
1. Register a new client
2. Fill in all the forms and click finalize
3. On the contact summary page, notice that some information in answer/value is missing and being replaced by the questions

### How is this feature expected to work?

All the answers/values on the summary page should appear beside the questions/keys

### Please Share other relevant information about the bug

screenshot of the issues can be seen here:
https://drive.google.com/file/d/1WTXT7CZtyHPPyZV4nE-0zMAwnObeOFjf/view?usp=sharing
https://drive.google.com/file/d/1VkXY1SXa8gOojPSyz6WDE5NvscXB-GhK/view?usp=sharing

**Comment by Naima-Bashir** [comment]
Issue is done, Fix will be created with the next apk for QA

**Comment by madrinekariuki** [comment]
tested on `optibp-reference-app-debug-v1.6.11.apk`
user `demo`

Observations:
This was observed on the added client` lynn nduta`
on the summary page, one is able to see  correct data of answer-value details. 

see screenshot below
![image](https://user-images.githubusercontent.com/84722169/146190763-98f7369d-3e32-4a4f-a3d7-a7f775fa9f85.png)
