### ISSUE TITLE
Sync failed error occurs when a newly created user tries to login to the app

### ISSUE THREAD

**Issue by Naima-Bashir** [opensrp/opensrp-client-anc#727]
### Affected App or Server Version

Latest apk: 1.6.11 rc1

### What kind of support do you need?

1. Create a new user on the https://web.anc-stage.smartregister.org/admin/users 
2. Assign it to a team (Bukesa)
3. Ensure that it is active and has credentials 
4. On the app, clear the data and login with the new user (demo2  and sidtestuser)
5. After you login to the app, observe how the loaded clients are 47/48. 
6. Click on the sync button and observe a sync failed error(image below)
7. If you clear the cache and login again, the app will lead you to the site characteristics page and when you click next, you will see a black page (image below)

### What is the acceptance criteria for your support request?

When one creates a user to the same team as demo, it should load similar clients and not have a sync failed error. 
![image](https://user-images.githubusercontent.com/61143692/144182484-fe075fb5-056a-4fbf-a32f-3fd55c637e79.png)
![image](https://user-images.githubusercontent.com/61143692/144182492-ae371e27-eeab-41df-8748-ef5cb32432a4.png)

**Comment by junaidwarsivd** [comment]
@dubdabasoduba @Naima-Bashir  it fails to fetch the default location id in the new user that might be causing the issue .
![Screenshot from 2021-12-01 11-30-02](https://user-images.githubusercontent.com/81764603/144183985-b13fa59a-956f-4c5c-800c-74f3b1ebb01f.png)
``

**Comment by dubdabasoduba** [comment]
@Naima-Bashir How is this assignment done?

**Comment by Naima-Bashir** [comment]
@dubdabasoduba I checked the demo user and noticed he was assigned to Bukesa 
So I did the same for the two new users I created like this 
![image](https://user-images.githubusercontent.com/61143692/144211529-a542a4c0-96ba-4992-8017-023088395f20.png)

**Comment by Naima-Bashir** [comment]
This ticket has been fixed: 
1. We ensured that the teams assigned to the user was Bukesa
2. We also ensured that the users created are provider(similar to demo user)
3. These two users should work and sync correctly 
4. cc @ellyasafaa @elwinameylentia

**Comment by madrinekariuki** [comment]
tested on :` optibp-reference-app-debug-v1.6.11`
users: `demo` and `madrineqa`

steps:

- logged in using user `demo` and created clients.
- synced data and logged out.
- logged into the app using a new user `madrineqa`
- click on sync.

observations:
-I was able to login to the app with the new user 
-Sync worked and all data associated with demo sync successfully and showed` sync completed`

screenshot:
![image](https://user-images.githubusercontent.com/84722169/146181215-6f9f2096-c6c0-4210-b5c2-d88ef91986b3.png)
