### ISSUE TITLE
Failed to sync the contact summary and overview

### ISSUE THREAD

**Issue by elwinameylentia** [opensrp/opensrp-client-anc#729]
### How do we replicate the bug?

After finalizing the care data for Contact 3 of the client named "Lucia Zulu", the information won't get updated on the APK for the overview and contact summary. When it is synced, other devices have different data from what has been entered.

Steps to replicate:
1.  Log in to WHO-ANC app with "demo" username
2. Go to mother profile named Lucia Zulu ID 2489797
3. Go to the "Overview" tab
4. According to the Ultrasound date under the Current Pregnancy header, the contact date should be on or after 26 November 2021 (ultrasound date cannot be entered after the contact date)
5. Go to the "Contacts" tab
6. Information under the Last Contact header shows that Contact 3 dated 16 November 2021, which is inaccurate
7. Go to Previous Contacts
8. Date under each contact (Contact 1, 2, 3) will show the same date which is 16 November 2021
9. This inaccurate date might not be replicated in all devices as we have checked it from two devices using the same username and same mother. It shows the different date of contacts between devices. Please refer to the video attached.

### How is this feature expected to work?

We expect accurate information on contacts date (and other contact summary) that synced properly across username and devices

### Please Share other relevant information about the bug

Video of the issue explanation can be seen here https://drive.google.com/file/d/12rElXfOsMIM_8bcPKorIG9arqrPN9owa/view?usp=sharing
Picture and explanation of the issue can be seen here
https://drive.google.com/file/d/12zpZyyBWb5f7-1POjiRfQ3dDpVpUZq5Z/view?usp=sharing

**Comment by dubdabasoduba** [comment]
@Naima-Bashir Please test this on the app

**Comment by madrinekariuki** [comment]
Tested on optibp-reference-app-debug-v1.6.13
user demo
Devices:
```
android 11 physical device
android 10 emulated device
```

Steps taken.

- installed the apk on both devices
- logged in and synced data on both devices.
- opened a client profile `cok Iwan` and `Deepa Rachel`
- note that there were no clients with more that 1 contact so I registered another contact for these clients using the physical device (they became 2 contacts).
- synced data on both devices
- opened the clients overview data and also the contact data.


Observations:
` cok Iwan`
- We have different overview data for the same client i.e
GA and EDD in the physical device changed to GA O weeks
GA and EDD in the emulated device GA is 11 weeks 2 days.
- on the emulated device the date of the last contact is incorrect. It is showing `18th Dec 2021` instead of `10th Jan 2022`

`Deepa Rachel`
-we have discrepancies in data i.e
      i)  On overview in weight, on total weight gain in pregnancy so far, it show, 3kgs in one device and 5kgs in the other.
     ii)  On tasks viw, it shows 14 in one device and 13 in the other device
     iii) On contacts, in one device it shows the last contact was on `10th January 2022 ` (this is correct )and in the other it shows `4th January 2022` .



see screenshots below:

Deepa Rachel

![image](https://user-images.githubusercontent.com/84722169/148779652-ec37ec3a-f978-4c82-8942-cbd2c5161655.png)



`Cok Iwan`

![image](https://user-images.githubusercontent.com/84722169/148780691-f6a0fbfd-3291-41d7-a95a-4e0e621b2aa4.png)

**Comment by Naima-Bashir** [comment]
Hi @SebaMutuku Kindly pick this up after you are done with your current tasks. Thank you

**Comment by SebaMutuku** [comment]
@elwinameylentia kindly grand my email access to the video. I have requested it.

**Comment by SebaMutuku** [comment]
@elwinameylentia this has been shared with me on email by @ellyasafaa

**Comment by Naima-Bashir** [comment]
Will be picked up today cc @SebaMutuku

**Comment by madrinekariuki** [comment]
This has also been noted when testing using the apk shared [here](https://onaio.slack.com/archives/C0E2558SH/p1643202839058800)

explanation:
There is data discrepancy on the Tasks tab when you compare data between 2 devices.
This has been noted on the client `Last born` , `story zakale`  and `wool write` where tasks on one device are more by 1.
It has been noted that the task that is being repeated on all these instances is the `HIV test`.

**Comment by madrinekariuki** [comment]
apk:` reference-app-debug-v1.6.12`
user demo

Devices:
android 11 physical device
android 10 emulated device

Steps taken:

installed the apk on both devices
logged in and synced data on both devices.
Added new clients` Retha Arms`, `Patience P` and `Terry Ann`.
Filled in the first contact for the clients.
On some clients `Patience P `and `Terry Anne` partner's HIV status was marked as unknown.
Left some tests not done and for `patience p` all her tests were marked as` ordered`.
synced data on both devices
opened the clients overview data -> tasks.


Observation.
The double tests that were appearing on the tasks tab e.g` HIV `appearing twice have disappeared.

However we still have some issues noted. 
1. when you record a test that is on the tasks tab and sync data, it is not showing on the other device. 
2. Partners HIV is not showing under the tasks tab (This is how it should be according to data dictionary). However under tests if partners HIV status was `unknown` it shows as a test to be done, if you select `ordered`, it does not show under Tasks tab. @naima please confirm if we should raise this as an issue.


screenshots:
#`1`
![image](https://user-images.githubusercontent.com/84722169/153560229-0658650d-4460-45b2-903d-1d61f01e7dd4.png)

#`2`
![image](https://user-images.githubusercontent.com/84722169/153561642-951b5dd7-ecf1-4626-bbb7-cb2904b79615.png)

**Comment by junaidwarsivd** [comment]
@madrinekariuki  for the point 1 when you record a test that is on the tasks tab and sync data, it is not showing on the other device. did you just recorded only the test before syncing or also filled a contact form along with that test ?

**Comment by madrinekariuki** [comment]
@junaidwarsivd 
for` 1`
- yes,  when I record a test that is on the tasks tab, it is not showing on the other device (even after syncing severally).
-  _did you just recorded only the test before syncing or also filled a contact form along with that test ?_ this is not very clear. However, I tested this with newly added clients after completing their contact, and then I check the tasks tab for the tests , and then I fill them then sync.

**Comment by Naima-Bashir** [comment]
@junaidwarsivd kindly add this to the next release

**Comment by junaidwarsivd** [comment]
![Screenshot_1646208886](https://user-images.githubusercontent.com/81764603/156322628-4816a173-78b0-4dd6-a074-769d275caf95.png)
![Screenshot_1646208890](https://user-images.githubusercontent.com/81764603/156322650-e0ee866f-ceb3-4771-a235-2000968d9975.png)
AS tested with @madrinekariuki  yesterday we found that test are now being synced and working corretly but we found out the few data discrepancies in the overview section  @Naima-Bashir

**Comment by madrinekariuki** [comment]
This has been tested on [this](https://onaio.slack.com/archives/CETQ18XL3/p1646986949773349) APK 

tested on `kituo kikuu `and `Bobs rest.`
recorded contact 4 for both clients and synced data.

Observation:
Contact summary and overview data is matching in both devices.
