### ISSUE TITLE
Implement Record another test result flow

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client-anc#73]
For tests where there are multiple types (i.e. Hep B, Hep C, Syphilis, Urine, Blood glucose, and Blood haemoglobin), the user can record multiple test types in the same contact visit. Furthermore, the status of multiple test types of the same kind can be different, i.e. urine culture test done today, urine gram-stain test ordered. The user can do this one of two ways:

1) If both test types are of the same status (i.e. urine culture done today and urine gram-stain done today), then they can multi-select the test types done, and the results are asked for each one separately.
2) If both test types are of a different status (i.e. urine culture done today and urine gram-stain done earlier (or even urine gram stain ordered)), then they have to select RECORD in the screen below in order to record a test type with a different status.

![tests-due02-multiple 1](https://user-images.githubusercontent.com/3488986/44384152-e5a47980-a523-11e8-934c-c8def4827376.png)

**Comment by cagulas** [comment]
QA 29th March release:

- [ ] When you select "Record" to record another test result status, the test result page should be cleared of the previous inputs. Right now, it shows what you entered in the previous test result you entered.
- [ ] When you record another test result, the 2nd recorded test results override the 1st recorded results. Read through the issue again to see how the results should get added on top of each other if more than one is recorded.

**Comment by cagulas** [comment]
Still not working as described, but in the interest of time, I think we can just hide the "Record" button for now. It's not high priority to implement.

Can we just hide or remove (whichever is easiest) the Record button after a test result is already recorded?

**Comment by dubdabasoduba** [comment]
All this tests all in the same popup dialog. With the popup functionality right now it wouldn't be possible to divide these questions unless we completely separate them in different expansion panels.

**Comment by cagulas** [comment]
After chatting with Ben today, we'll leave the functionality as is for now, since the Record button just reopens the widget that was already submitted.
