### ISSUE TITLE
"Overview" information does not appear on some device, even after clicking sync

### ISSUE THREAD

**Issue by elwinameylentia** [opensrp/opensrp-client-anc#730]
### How do we replicate the bug?

After the user finished entering contact 1 data, information on the Overview doesn't appear correctly across two devices (same phone type, same OS) with the same username, even after syncing the APK. Please refer to the first video attached to better understand how we identify this issue.

Steps to replicate:
1. Prepare two phones and follow the steps below with both of those phones
2. Log in to the WHO-ANC app with "demo" username
3. Sync the app
4. Go to the profile of Mentari Tiga ID 2654317
5. Go to the Overview tab
6. On one phone, the overview tab is showing the correct information. However, on another phone, information on the overview tab is missing (minute 1:27-1:40 of the first video link)

### How is this feature expected to work?

All contact information can be synced correctly across all devices with the same username

### Please Share other relevant information about the bug

Video explanation on the issue across different devices can be seen here https://drive.google.com/file/d/12WS3CHw8FXBDc34EFYqSIBZXFbBTS6TO/view?usp=sharing

The process of inputting the mother data can be seen here https://drive.google.com/file/d/14fWjeAM8DxrsWFbadmu0BYi2Mz9efw2F/view?usp=sharing

**Comment by dubdabasoduba** [comment]
@Naima-Bashir Please test this on the app

**Comment by Naima-Bashir** [comment]
cc @madrinekariuki

**Comment by madrinekariuki** [comment]
This has been tested on 
`optibp-reference-app-debug-v1.6.13`
user: `demo`
android: `11` and `6`

steps taken:

- prepare 2 phones
- Login to the apk using the same user on both
- sync data.
- search for a client profile
- click on the profile and proceed to the `overview` section.
- observe the data in the overview section  in both devices

Observation:
- Not all the clients have Overview data in both devices.
- same clients that have overview data in one device are missing overview data in other device.
- I have used client `Ela mai` as a test client

screenshots:
![image](https://user-images.githubusercontent.com/84722169/148772850-1f5f9503-3bef-454b-a857-f69107ab312d.png)

**Comment by Naima-Bashir** [comment]
Hi @junaidwarsivd Kindly pick this up after you are done with your current tasks. Thank you

**Comment by madrinekariuki** [comment]
@junaidwarsivd 
As requested as retest has been done on this. 
- A fresh install of the apk was done on the phones. android` 6 `and android `11`
- cleared cache
- logged in and synced data.

observation.
- I note that overview data is now showing on both phones.
- Good to note that the issue on data discrepancy reported in `729` is however still present. 

![image](https://user-images.githubusercontent.com/84722169/149287548-2e1232e1-1880-4e3e-9066-e7ae8f0834b5.png)

**Comment by Naima-Bashir** [comment]
@elwinameylentia kindly test this ticket
