### ISSUE TITLE
[Support Request] Translated OptiBP Intergration with the Bahasa WHO ANC apk

### ISSUE THREAD

**Issue by Naima-Bashir** [opensrp/opensrp-client-anc#738]
### Affected App or Server Version

Latest apk: 1.6.11 rc1

### What kind of support do you need?

The Biospectal team will share the translated OptiBP apk so that it can be integrated with the Bahasa apk. 
The support required is to have a pair session with the SID team and assist them with the integration process. 
JFK from Biospectal will share the apk via email either tomorrow or Monday(kindly ensure that the email includes @dubdabasoduba and @junaidwarsivd ) 

### What is the acceptance criteria for your support request?

To support the SID team with the integration process

**Comment by Naima-Bashir** [comment]
Ona already did the integration on the app and we sent it to the client. The SID team however translated the app to Bahasa(Indonesia), and now need our support on assisting them with integrating the translated optibp app with the translated WHO ANC app. 
Ona can share the codework/ how they integrated the app initially and SID can follow the steps. 
cc @dubdabasoduba

**Comment by Naima-Bashir** [comment]
Apk has been shared here: https://drive.google.com/file/d/1MS90lOB0YMQ1v_uoOOeGi51NVVD-N-Sv/view?usp=sharing

**Comment by elwinameylentia** [comment]
SID team is ready for a pairing session on this ticket this week on either Wednesday or Thursday
cc @dubdabasoduba @junaidwarsivd

**Comment by junaidwarsivd** [comment]
hi @elwinameylentia we've checked the translated optibp apk the tanslations are automatically picked from the device language if the code is not changed then no further integration is needed ANC will launch the optibp app video demonstration is added in this https://drive.google.com/file/d/14LaeEgCzTFcIV1teu_3eXpyTZopADzn7/view?usp=drivesdk link

**Comment by Naima-Bashir** [comment]
Support was provided by @junaidwarsivd and Ona team. @elwinameylentia Kindly let us know if we can close this ticket.

**Comment by elwinameylentia** [comment]
yes you can close it, thank you
