### ISSUE TITLE
Implement Physical Exam contact container

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client-anc#74]
The Physical Exam contact container has 4 sections in it: Height & Weight, Blood Pressure, Maternal Exam, and Fetal Assessment.

<img src="https://user-images.githubusercontent.com/3488986/44384726-cdcdf500-a525-11e8-9df5-17d585c9e182.png" width="460">

Follow the exact content and logic in the data dictionary (and order of the questions, which is not up to date in the mockups), PE tab, but a few mockups are provided below.

**Height & Weight:**
<img src="https://user-images.githubusercontent.com/3488986/44384835-269d8d80-a526-11e8-997f-d20bcd864149.png" width="460">

- [x] There should be an Pre-gestational weight unknown checkbox underneath the pre-gest weight input (see data dictionary). Either the checkbox or entering the pre-gest weight is required, but both cannot be inputted.
- [x] Instead of Continue to Blood Pressure, it should say "Next:" with the next section heading.
- [x] Assigning @rowo to this issue as well, to provide guidance on how to show first contact only fields on subsequent contacts (i.e. pre-gest weight and height).

**Blood Pressure:**
<img src="https://user-images.githubusercontent.com/3488986/44385216-5dc06e80-a527-11e8-8ed8-84ca7c689502.png" width="460">

- [x] For the time being, don't include the Automated BP measurement button. We will be adding the integration to the automated BP measurement tool early next year. For now, the user manually inputs the BP readings.
- [x] If the first BP reading is high, they are instructed to let the woman rest for 10-15 minutes and retake it, so this would be a good example where the health worker might want to exit the woman's contact and start other work and come back to this woman after several minutes, so this state needs to be saved for when she returns.
- [ ] If the woman's repeat BP is high, she is instructed to do a urine dipstick protein test. If this is already done from the Tests container, then pre-populate the result here. If it's not already done, and she does the urine test and enters the results here, the results should pre-populate that field in the Tests container.

**Maternal Exam:**
<img src="https://user-images.githubusercontent.com/3488986/44386261-b0e7f080-a52a-11e8-93b7-75056c585efe.png" width="460">

- [x] Note the question type here where, if exam is abnormal, it opens a small widget for the user to multi-select all abnormal conditions (no mockup provided). 

**Fetal Assessment:**
![physical-fetal](https://user-images.githubusercontent.com/3488986/44387306-d88c8800-a52d-11e8-9b8d-f678140f94ab.png" width="460">

- [ ] @rowo will provide guidance on how to display no. of fetuses after already answered in a previous contact. The user should be allowed to edit it in subsequent contacts though.
- [ ] No. of fetuses can be filled in here or the Tests container, ultrasound test result, so the answer here should populate the other (and vice versa). But please note, here, there is an unknown checkbox that can be checked instead of filling in the no. of fetuses answer.

- [x] User interface and Layout 
- [ ] Skip Logic

**Comment by ellykits** [comment]
Mock-up for Multicheck box widget
<img width="540" alt="cardiac-abnormal" src="https://user-images.githubusercontent.com/26865532/47711046-544d3400-dc45-11e8-95e1-f92835327897.png">
<img width="540" alt="specify" src="https://user-images.githubusercontent.com/26865532/47711049-54e5ca80-dc45-11e8-980d-c8c2bcef0e5c.png">

**Comment by rowo** [comment]
@ellykits @ndegwamartin For first contact only or similar answered-already questions (that can be edited), we (Ephraim, Carolyn and I) ended up on an inline "edit" button. But it's not really an edit button — it just enables a disabled field.

It would look like this:

<img width="309" alt="screen shot 2018-11-13 at 11 03 42 pm" src="https://user-images.githubusercontent.com/1584163/48459534-8196f780-e798-11e8-8114-f96191c8e1c4.png">
- Ultrasound done is an example of an active select one field
- GA from ultrasound - weeks is an active text entry field
- GA from SFH - weeks is disabled. If you tap the edit icon, it becomes like GA from ultrasound - weeks. 
- Select preferred gestational age is a disabled select one. If you click edit it becomes active
- Reactivated fields can be changed or not, doesn't matter. But if they were required, they'll be checked when the whole contact is submitted.
- This is how all answer-once fields will work, whether it's the only one in the view or whether it's the whole section.

**Comment by cagulas** [comment]
@rowo Moving the above into a new issue. And closing the original issue (https://github.com/OpenSRP/opensrp-client-anc/issues/51).

**Comment by cagulas** [comment]
Here it is: https://github.com/OpenSRP/opensrp-client-anc/issues/149

**Comment by cagulas** [comment]
Closing this and moving all remaining QA into #167
