### ISSUE TITLE
Delayed Response on Test Page

### ISSUE THREAD

**Issue by elwinameylentia** [opensrp/opensrp-client-anc#742]
### How do we replicate the bug?

The test page takes a while to respond to users' actions, sometimes showing a blank screen. This delayed response is consistently replicated across several devices, including flagship phones like Samsung S21 and Samsung Note 20 Ultra.

Video of this delayed response issue can be seen here
https://drive.google.com/file/d/1KLPkILibbhMTXH4bw_Ke4FWKibTCdWCO/view?usp=sharing

Steps to replicate:
1. Log in to the client app
2. Register a new client or continue contact
3. Go to the Test Form
4. Notice that when a user chose to record a test (e.g. Syphilis Test), the page consisting of details for that test (when the test was done, type of test, results) didn't immediately show up on the screen. It showed a blank page for a while first (look at video minute 0:02, minute 0:20, minute 1:02)
5. Next, when users switch their choice for test type (e.g. Urine Test: midstream urine culture, urine dipstick), the options of result for that test type didn't change and didn't show up. This causes the Test Form to look 'complete' but is actually not (look at video minute 0:39, compare to video minute 1:52)
6. Lastly, when users tried to type their answer, it didn't show up on screen immediately as well (look at video minute 1:27)

### How is this feature expected to work?

1. The form should show up right away on screen after being opened
2. Typed answers should show up right away on the screen after being entered by users

**Comment by SebaMutuku** [comment]
In progress.

**Comment by Naima-Bashir** [comment]
Hi @SebaMutuku how do you recommend we work on this? How can we manage to optimize the forms?

**Comment by madrinekariuki** [comment]
@SebaMutuku 
This has been tested on `optip-reference-app-debug-2022-1-12`
user `demo`

steps
I have followed the steps as explained [here](https://github.com/opensrp/opensrp-client-anc/issues/742#issue-1087414223).

Observations:
- the tests page  has reverted to the old form i.e (you click on a test and it opens another page)
- when you chose to record a test e.g syphilis and you click on the form. It is taking like 1/2 a second before it shows data (please advice if that's an okay duration.)
- when running tests e.g urine tests and you switch from midstream urine culture to urine dipstick, the options for the selected urine test type are showing and if you deselect for the other option i.e midstream urine culture its optons disappear and remain if you don't deselect.

Video of the test form behaviour
Shared here.

screenshots:
![image](https://user-images.githubusercontent.com/84722169/149274981-ad54ff0d-21f3-4cd5-bd11-16b7f1223828.png)

**Comment by SebaMutuku** [comment]
@madrinekariuki please note, this is OPTIBP tests page not Brazil updates. That's why the pages look different. 
Also confirm, is this a new issue on the app ,"when running tests e.g urine tests and you switch from midstream urine culture to urine dipstick, the options for the selected urine test type are showing and if you deselect for the other option i.e midstream urine culture its optons disappear and remain if you don't deselect."?

**Comment by madrinekariuki** [comment]
@SebaMutuku  No It is not a new issue, I was running the tests as highlighted on [this](https://github.com/opensrp/opensrp-client-anc/issues/742#issue-1087414223) `steps to replicate `number 5. Those are test results highlighted.

**Comment by SebaMutuku** [comment]
@madrinekariuki okay.

**Comment by Naima-Bashir** [comment]
Here is a video [https://drive.google.com/file/d/1wndasxQ0AkBVb0bbLoYA_ETJ_JiZQhdR/view?usp=sharing]

**Comment by SebaMutuku** [comment]
@Naima-Bashir can I generate an apk for this?

**Comment by Naima-Bashir** [comment]
This has been worked on. Will be released and tested in the next apk

**Comment by Naima-Bashir** [comment]
@junaidwarsivd when can we generate an apk?
