### ISSUE TITLE
Automatic Navigation to Empty Field

### ISSUE THREAD

**Issue by elwinameylentia** [opensrp/opensrp-client-anc#745]
### Feature Use Case

- Currently, users have to look at the field and pages one by one to find the empty ones, otherwise, they would not be able to save the form. According to users, this would waste their time, especially if they have to input data at the point of care and if they have to serve many patients.
- It would be helpful if the app could navigate the users directly to the obligatory fields that they missed. 

### Acceptance criteria

App should be able to navigate users directly to the obligatory fields that they missed, so they can save the form more quickly

**Comment by Naima-Bashir** [comment]
To be picked up after the main bugs are fixed

**Comment by ndegwamartin** [comment]
On the MainContact activity class we can populate a data structure with the `step identifier` and `field identifier` of the unpopulated required fields. Once we have that we can then implement navigation to a specific step and maybe field focus. 

For now the initial solution could just be navigation to the particular step. We can further iterate on this later.

**In summary:**
- [ ] Store the required fields navigation address e.g. as `<step_id>:<field_id>`
- [ ] Implement navigation to specific step in the form
