### ISSUE TITLE
[Ona Support Request]: Blank overview on profile and contacts after modifying json forms

### ISSUE THREAD

**Issue by Davidju97** [opensrp/opensrp-client-anc#748]
### Affected App or Server Version

v1.6.8

### What kind of support do you need?

Blank overview on profile and contacts after modifying json forms. After modifying the app to the Zambian context, Contacts are not saving and a blank overview in the profile is displayed after finalizing
![finalise](https://user-images.githubusercontent.com/46728226/148739906-6dffecce-774a-423d-9921-6f1797b589ab.png)
.

### What is the acceptance criteria for your support request?

Contacts are savable and overview of that particular contact is displayed in the client profile

**Comment by ndegwamartin** [comment]
@Davidju97 could you please link the code base with the form updates e.g. Github branch or PR? cc @Naima-Bashir  @junaidwarsivd

**Comment by Davidju97** [comment]
https://github.com/BlueCodeSystems/who-anc/tree/development @junaidwarsivd @ndegwamartin

**Comment by Naima-Bashir** [comment]
Hi @Davidju97 We are requesting the Oauth client Credentials you are using here https://github.com/BlueCodeSystems/who-anc/tree/development

**Comment by ndegwamartin** [comment]
@Davidju97 The issue can be solved by adding this translation string to the `contact_summary.properties` file cc @Naima-Bashir 

`contact_summary.reasons.reason_for_coming_to_facility = Reason for coming to facility`

**Comment by ndegwamartin** [comment]
I was able to narrow it down by following these steps:

1. Install the application from the code base above [(development branch)](https://github.com/BlueCodeSystems/who-anc/tree/development)
2. Run the app via IDE 
3. Check the Log Cat


I observed the following exception thrown

<img width="1433" alt="Screenshot 2022-01-12 at 13 26 48" src="https://user-images.githubusercontent.com/10017086/149125510-5d127560-2f4e-4503-8fc8-8ce71e9ea90b.png">

**Comment by ndegwamartin** [comment]
Perhaps in future we can discuss about propagating such exceptions to the UI for non-tech users to easily troubleshoot cc @dubdabasoduba

**Comment by chobela** [comment]
@ndegwamartin which branch have you committed to, so that e confirm?

**Comment by chobela** [comment]
@ndegwamartin thanks that works
