### ISSUE TITLE
No Unique IDs Found

### ISSUE THREAD

**Issue by elwinameylentia** [opensrp/opensrp-client-anc#751]
### How do we replicate the bug?

I cannot register new mothers due to 'no unique IDs found'. Even after clicking on the sync button, the error still persists

Steps to replicate:
1. Log in to APK version 1.6.12 (built on 12 Jan 2022)
2. Register new mothers
3. Pop up message will appear

### How is this feature expected to work?

Unique ID is supposed to be assigned automatically and user can register new client by clicking the register button

### Please Share other relevant information about the bug

video of explanation can be seen here https://drive.google.com/file/d/1MWCsA0XnjI-85GXXGlYW9bXDBbwzs3mm/view?usp=sharing

**Comment by Naima-Bashir** [comment]
I think we can close it and Incase it happens again we can reopen it
