### ISSUE TITLE
[Bug Report]: For the clients who's EDD is far past the current date app keeps calculating the GA and it is far past 42 weeks

### ISSUE THREAD

**Issue by junaidwarsivd** [opensrp/opensrp-client-anc#753]
### How do we replicate the bug?

Visit the Client with due delivery or EDD weeks ago 

### How is this feature expected to work?

GA should not be shown when the GA is past 42 weeks

### Please Share other relevant information about the bug

![screenshot_1642494383](https://user-images.githubusercontent.com/81764603/150505517-776f509f-a944-46a1-b6bc-e8916813d18a.png)

**Comment by Naima-Bashir** [comment]
Hi @junaidwarsivd any updates on this ticket?

**Comment by junaidwarsivd** [comment]
hi @Naima-Bashir  this issue is done and included in the last release v1.6.14
