### ISSUE TITLE
Adding P2P Module in WHO ANC Application

### ISSUE THREAD

**Issue by dodosi** [opensrp/opensrp-client-anc#754]
### Affected App or Server Version

v1.6.10

### What kind of support do you need?

We need to know how we can integrate P2P module in the WHO ANC application.
Documentation provided does not explain how it is integrated in WHO ANC, it only explain how it is integrate in CHW Application.

### What is the acceptance criteria for your support request?

Being able to sync data between devices using P2P

### Relevant Information

We suggest you to offer training sessions  to have deep understanding on how we can integrate in the application

**Comment by dubdabasoduba** [comment]
@dodosi https://github.com/opensrp/opensrp-client-anc/blob/master/reference-app/src/main/java/org/smartregister/anc/application/AncSyncConfiguration.java 

https://github.com/opensrp/opensrp-client-chw/blob/87eed43e7773e110c1cbc4637018bbbf4a16987e/opensrp-chw/src/main/java/org/smartregister/chw/application/LmhAuthorizationService.java#L20 copy this class and name it `ANCAuthorizationService`

**Comment by Naima-Bashir** [comment]
These classes are missing, We are getting errors
CoreAuthorizationService
CoreConstants
Constants

**Comment by Naima-Bashir** [comment]
some important links: @dodosi 
https://smartregister.atlassian.net/wiki/spaces/Documentation/pages/1139212418/Android+Peer-to-peer+sync+library
https://github.com/opensrp/opensrp-client-chw/blob/87eed43e7773e110c1cbc4637018bbbf4a16987e/opensrp-chw/src/main/java/org/smartregister/chw/application/LmhAuthorizationService.java#L20
https://github.com/opensrp/opensrp-client-anc/blob/master/reference-app/src/main/java/org/smartregister/anc/application/AncSyncConfiguration.java

**Comment by Naima-Bashir** [comment]
similar ticket: https://github.com/opensrp/opensrp-client-anc/issues/761

**Comment by Naima-Bashir** [comment]
Kindly find the attached P2P apk below. I have also included the Github branch [here](https://github.com/opensrp/opensrp-client-anc/pull/777), the meeting [recordings](https://drive.google.com/file/d/1FFJZWdmol7oj4VlG8q3ehgRv8kdJCwk7/view?usp=sharing) from today's session and the [documentation](https://docs.google.com/document/d/1XIj6yS8Qi1EjXJOwggVZSlwUYbnYbs9QrprrCDFOfF0/edit?usp=sharing).
