### ISSUE TITLE
[Ona Support Request]: MultiLanguge Support 

### ISSUE THREAD

**Issue by sanjit7** [opensrp/opensrp-client-anc#760]
### Affected App or Server Version

v 1.6.8

### What kind of support do you need?

How can we add Nepali fonts in a form ?
 Forms need to support Multi Language Support .
Generate forms in Nepali Language.

### What is the acceptance criteria for your support request?

Nepali  fonts ( Preeti font ) should be shown .

**Comment by dubdabasoduba** [comment]
@sanjit7 Just to confirm. I am I right to assume (from our last conversations) that this means adding form Nepalese form translations to WHO ANC app.

**Comment by sanjit7** [comment]
Yes , this ticket  is for  adding form Nepalese form translations to WHO ANC app  . 
Most of the things were clear on last meeting  . 
We will try this Multi Language support  after Client ANC's develop repo  works successfully  .

**Comment by sanjit7** [comment]
The issue "https://github.com/opensrp/opensrp-client-anc/issues/765"  has been solved . 
 Now our team will work on Multi language support of JSON forms.
 We will do as insisted on  meeting of 27th January .

**Comment by SebaMutuku** [comment]
Hi @sanjit7 any feedback on the Multi-Language of JSON forms you were to check?

**Comment by Naima-Bashir** [comment]
The Nepal team have translated properties file and used language switcher dialogue and it worked fine

**Comment by sanjit7** [comment]
Multi language issue is now resolved completely.Thank you for your support.
