### ISSUE TITLE
[Ona Support Request]: P2P Sync Configuration

### ISSUE THREAD

**Issue by chobela** [opensrp/opensrp-client-anc#761]
### Affected App or Server Version

Latest

### What kind of support do you need?

We are requesting a pairing session to understand the following clearly.

This is with reference to the following guide that was shared to us on how to integrate P2P Module. [(https://smartregister.atlassian.net/wiki/spaces/Documentation/pages/1139212418/Android+Peer-to-peer+sync+library)]

 - The guide says that the "P2P library has already been integrated into OpenSRP Client Core". It further says that we must include core library into our app. Is there a specific version of Core that we should include? 
 
 - The guide also says that we are to add cwac-saferoom maven repository. Where are we to include this repository? The guide is not clear whether to add it to the core library, or to the client build.gradle. Additionally, the guide does not explain the purpose of adding cwac-saferoom maven repository.
 
 - We would also like to confirm if step 3 of the documentation is the last step of Integration, because the documentation abruptly ends at step "3.a".
 
 - Finally, we would like you to demo to us how the Peer to Peer Sync works in a real time environment, i.e, with two devices. We would like to see how you setup a device as the Sender, and which one should be the Receiver. We would like to see how at-least 3 clients will move from the sender device to the receiver device using this method. We will like to see the clients appear in the recipient device. This will give us more confidence in knowing that this Library will work seamlessly.
 
 Thank you.
 
 

### What is the acceptance criteria for your support request?

WHO ANC Rference App must be installed.

**Comment by Naima-Bashir** [comment]
Some important links: @chobela 
https://smartregister.atlassian.net/wiki/spaces/Documentation/pages/1139212418/Android+Peer-to-peer+sync+library
https://github.com/opensrp/opensrp-client-chw/blob/87eed43e7773e110c1cbc4637018bbbf4a16987e/opensrp-chw/src/main/java/org/smartregister/chw/application/LmhAuthorizationService.java#L20
https://github.com/opensrp/opensrp-client-anc/blob/master/reference-app/src/main/java/org/smartregister/anc/application/AncSyncConfiguration.java

**Comment by dubdabasoduba** [comment]
@chobela 

> We would also like to confirm if step 3 of the documentation is the last step of Integration, because the documentation abruptly ends at step "3.a".

https://smartregister.atlassian.net/wiki/spaces/Documentation/pages/1139212418/Android+Peer-to-peer+sync+library the **How to use it in your project** section of this documentation links to the actual repo documentation.  

Here is the link https://github.com/OpenSRP/android-p2p-sync/blob/master/README.md

**Comment by dubdabasoduba** [comment]
> The guide says that the "P2P library has already been integrated into OpenSRP Client Core". It further says that we must include core library into our app. Is there a specific version of Core that we should include?

The latest core library already has this linked.  You only need this section

- Add the cwac-saferoom maven repository, as below
```
maven {
    url "https://s3.amazonaws.com/repo.commonsware.com"
}
```
Add the P2POptions as below when initializing the CoreLibrary:
```
P2POptions p2POptions = new P2POptions(true);
// Add the optional configurations to the P2POptions
p2POptions.setAuthorizationService(new ChwAuthorizationService());
CoreLibrary.init(context, new ChwSyncConfiguration(), BuildConfig.BUILD_TIMESTAMP, p2pOptions);
```

**Comment by dubdabasoduba** [comment]
> The guide also says that we are to add cwac-saferoom maven repository. Where are we to include this repository? The guide is not clear whether to add it to the core library, or to the client build.gradle. Additionally, the guide does not explain the purpose of adding cwac-saferoom maven repository.

p2p is an OpenSRP client module. This is integrated into the implementing app Gradle.  In this case WHO ANC.

**Comment by madrinekariuki** [comment]
@Naima-Bashir @hamza-vd 
I have tested this on 2 devices:
android 8.1 vivo 
android 6.01 samsung J5
for testing this item and #754 


Test steps:

- Login to the apk on both devices.
- sync data on both devices.
- Make a change(s) on one device.
- Switch bluetooth on for both devices.
- Go to the `me` section on the bottom right of the app and click on it.
- click on `Device-to-device sync`.
- observe the sync progress till it shows Transfer successful.
- observe the phone that was receiving data if all the data has been transferred successfully.


Observations:
- scenario 1 I logged in using `demo` user on both devices 
- Scenario 2 I logged in using` demo` user on one device and `madrineqa` user on the other device
- the Devices connected successfully.
- Transfer of data on both device showed that it was successful.
- However after the transfer the data does not show on the Receiving phone Immediately, it keeps showing the message` Currently processing transferred records. Do not edit client records until complete`. for a period of about 30 minutes 
- Later the data shows on both phones. 

Issues noted:
- Data is taking too long to show in the other phone after transfer is complete. (30 minutes)
- During the transfer,(if wifi is off, the phone prompts the wifi to be on ) if you manually put it back off, the message `Currently processing transferred records. Do not edit client records until complete` does not go away. @hamza-vd  is this expected?



Screenshots.
devices connecting and transferring data.
![image](https://user-images.githubusercontent.com/84722169/155502829-ce58d9b5-da9b-4694-8f89-6f9134280eb4.png)

message after transfer is complete before data shows
![image](https://user-images.githubusercontent.com/84722169/155503988-20bd244c-08f4-4209-acf2-03eb45da0a73.png)

**Comment by dubdabasoduba** [comment]
@madrinekariuki I think the time between data sync completion and data visibility is used in processing the data.  I am not sure how many records you synced? 30mins seems like a lot @hamza-vd please debug to see where we can enhance the functionality

**Comment by dubdabasoduba** [comment]
@hamza-vd The current p2p can use wifi (without network connectivity) and Bluetooth. Please debug and identify why the sync fails when the network is off

**Comment by hamza-vd** [comment]
@dubdabasoduba 
  - The data processing does not take much time at my end, it took me to process 1774 records in less than 15 mins with a 4GB RAM device. Maybe it's a device issue.
  - Current P2P is giving a connection lost error via Bluetooth, its only successful when data is transferred via WiFi.

**Comment by Naima-Bashir** [comment]
This has been completed. To be shared with the Technical partners.

**Comment by Naima-Bashir** [comment]
Kindly find the attached P2P apk below. I have also included the Github branch [here](https://github.com/opensrp/opensrp-client-anc/pull/777), the meeting [recordings](https://drive.google.com/file/d/1FFJZWdmol7oj4VlG8q3ehgRv8kdJCwk7/view?usp=sharing) from today's session and the [documentation](https://docs.google.com/document/d/1XIj6yS8Qi1EjXJOwggVZSlwUYbnYbs9QrprrCDFOfF0/edit?usp=sharing).
