### ISSUE TITLE
[Bug Report]:Missing phone number limit.

### ISSUE THREAD

**Issue by madrinekariuki** [opensrp/opensrp-client-anc#763]
### How do we replicate the bug?

Steps to replicate
- Login to the APK and sync data
- click on add a new client
- open the registration page and fill in the details till you get to the phone number part.
- Observe how one can input a number upto a 100 numbers.

### How is this feature expected to work?

Find out the phone number limt of the specific country and implement on the apk.

### Please Share other relevant information about the bug

Find below screenshot of the current phone number option value. 
![image](https://user-images.githubusercontent.com/84722169/151508529-bde5d298-df2d-4574-ad49-9b367d4bd195.png)

**Comment by SebaMutuku** [comment]
@Naima-Bashir @madrinekariuki  how many characters should the mobile number have?

**Comment by SebaMutuku** [comment]
I have added limit to 12 Characters

**Comment by madrinekariuki** [comment]
@SebaMutuku @Naima-Bashir 

This has been tested and has passed QA.
Tests done:

- Verify you cannot save a client's number that exceeds 12 digits.
- Verify that the mobile number limit is set to 12 digits.
- Verify that an error is thrown if you try to save a number that is more than 12 digits.
- Verify a number less thank 12 digits gets saved without an error.


screenshots:
![image](https://user-images.githubusercontent.com/84722169/153543170-13ea0a67-be24-4cf3-acde-963998798b2a.png)
