### ISSUE TITLE
[Ona Support Request]: Gradle Sync Failed for unknown reason

### ISSUE THREAD

**Issue by uzumakirex0000** [opensrp/opensrp-client-anc#765]
### Affected App or Server Version

v1.6.8

### What kind of support do you need?

![image](https://user-images.githubusercontent.com/95898994/151689159-c365a7f0-38dd-4f90-9e29-6399bdac7730.png)

Gradle project sync failed.  Build log is mentioned below : 

Starting Gradle Daemon...
Gradle Daemon started in 1 s 434 ms

> Configure project :opensrp-anc
PROJECT TASKS
SIZE : 1
task ':opensrp-anc:jacocoTestReport'
PROCESSING MAVEN LOCAL SNAPSHOT BUILD VERSION 2.1.0-SNAPSHOT at 2022-01-30 11:24:07...

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.5/userguide/command_line_interface.html#sec:command_line_warnings

### What is the acceptance criteria for your support request?

Project needs to be sync with gradle and installed in adb

**Comment by dubdabasoduba** [comment]
@uzumakirex0000 What android studio version is this?

**Comment by uzumakirex0000** [comment]
> @uzumakirex0000 What android studio version is this?

I was previously working through android studio version 2020.3.1 patch 4, so I ended with this error and my colleague was working on 2020.3.1 patch 3 and it was running there so i am currently installing patch 3 version and it still has same issue
