### ISSUE TITLE
[New Feature Request]: Date need to be generated in Bikram Sambat (BS)

### ISSUE THREAD

**Issue by sanjit7** [opensrp/opensrp-client-anc#766]
### Feature Use Case

In Json form , there is Datepicker widget.  It generates date in AD. 
Date need to be generated in Bikram Sambat(BS).

### Acceptance criteria

Date need to be generated in Bikram Sambat(BS) in datepicker widget.

**Comment by allan-on** [comment]
The `DatePicker` Widget should be able to show a date in a specified display format.
One needs only to specify the format e.g. `Form.setDatePickerDisplayFormat("dd-MM-YYYY");` 
Maybe an improvement is to have this be set as a widget config instead

**Comment by khadkadipesh** [comment]
We went through number of libraries in GitHub for Bikram Sambat as a Nepali date picker.
May be we can integrate one of the widget from following repo in the project.

1. https://github.com/keyrunHORNET/date_picker_converter

2. https://github.com/xyznaveen/pal

3. https://github.com/xyznaveen/nepali-calendar-library

**Comment by Naima-Bashir** [comment]
Next steps: 
Writing a convertor/ helper class that will convert dates in AD into BS -- Nepal team
Ona team; work on form widgets
LoE; next week Friday

**Comment by Naima-Bashir** [comment]
@junaidwarsivd to add this [https://github.com/keyrunHORNET/date_picker_converter](https://github.com/keyrunHORNET/date_picker_converter) to native forms and ANC.

**Comment by Naima-Bashir** [comment]
Nepal team to write the function that convert the BS to AD.

**Comment by Naima-Bashir** [comment]
@junaidwarsivd @SebaMutuku

**Comment by Naima-Bashir** [comment]
This has been finalized
