### ISSUE TITLE
[Ona Support Request]: Form Validation 

### ISSUE THREAD

**Issue by uzumakirex0000** [opensrp/opensrp-client-anc#767]
### Affected App or Server Version

v1.6.10

### What kind of support do you need?

until the form's values are not filled, even after clicking the NEXT button, the form should not go to the next form field. it should validate and until the forms are not filled it should throw an error and should not proceed

### What is the acceptance criteria for your support request?

Form validation error should be solved.

**Comment by junaidwarsivd** [comment]
hi @uzumakirex0000  in json form there is a property called "validate_on_submit" setting it to false in each form will activate the required scenario described above.
Note :  device cache needs to be cleared after the updates made on form.json
