### ISSUE TITLE
[Bug Report]: The timestamp (week and date) for Last Contact are all the same

### ISSUE THREAD

**Issue by madrinekariuki** [opensrp/opensrp-client-anc#768]
### How do we replicate the bug?

This has been tested on this [enable property apk](https://onaio.slack.com/archives/C0E2558SH/p1643274875068100?thread_ts=1643202839.058800&cid=C0E2558SH)
user: `demo`

steps:

- Login to the apk
- look for 2 clients who already have a contact done 
- record 2nd or 3rd contacts for each of them.
- click on the clients profile and go to contacts.
- click on previous contacts.
- observe how the contacts all show the same date.

### How is this feature expected to work?

The contacts should show the dates when the contacts were done.

Screenshot: clients `Sharon Sha`,`Re Tests`
![image](https://user-images.githubusercontent.com/84722169/152166472-28294a5a-7674-4fa8-af29-dc028c6da399.png)

**Comment by hamza-vd** [comment]
@madrinekariuki @Naima-Bashir 
This has been fixed in https://github.com/opensrp/opensrp-client-anc/pull/789 by @junaidwarsivd

**Comment by Naima-Bashir** [comment]
This was tested, closing this.
