### ISSUE TITLE
[Bug Report]:  OptiBP widget is still not integrated

### ISSUE THREAD

**Issue by madrinekariuki** [opensrp/opensrp-client-anc#769]
### How do we replicate the bug?

This Optip widget is missing. on this [enable property apk](https://onaio.slack.com/archives/C0E2558SH/p1643274875068100?thread_ts=1643202839.058800&cid=C0E2558SH)

steps:
- login to the app 
- go to the physical exam page.
- go to the Blood pressure form.
- we have the systolic blood pressure and diastolic blood pressure.
- we do not have the optiBP widget as we should.

### How is this feature expected to work?

The optiBP widget should be present so that when systolic blood pressure and diastolic blood pressure are high  we can use the optiBP widget to be redirected to the app to measure.

screenshot
![image](https://user-images.githubusercontent.com/84722169/152168689-dfca202c-afa9-4ebb-a29f-de98992cffb8.png)

**Comment by Naima-Bashir** [comment]
OptiBP widget was added. The next release will include it. @madrinekariuki to test

**Comment by Naima-Bashir** [comment]
This has been added
