### ISSUE TITLE
 Typo on 'Hiv test resultt'

### ISSUE THREAD

**Issue by madrinekariuki** [opensrp/opensrp-client-anc#773]
### How do we replicate the bug?

This has been tested on [this](https://onaio.slack.com/archives/C0E2558SH/p1643274875068100?thread_ts=1643202839.058800&cid=C0E2558SH) apk with the enabled property
user: demo
login to the apk and sync data
create a new client
start a contact
Ensure to put the value of `HIV Positive`
Finalize the contact.
click on the customers profile on the overview and scroll down.
Observe how the input detail has a typo as 'Hiv test resultt' instead of 'Hiv test result'
This can be observed on client Mary Janes

### How is this feature expected to work?

the Typo, `Hiv test resultt `should be corrected to `Hiv test result`
![image](https://user-images.githubusercontent.com/84722169/152326783-23d65327-fa76-4355-ae7f-00a4433f17bc.png)

**Comment by Naima-Bashir** [comment]
Hi @madrinekariuki kindly retest this on your latest apk to see if the issue still exists. The optiBP apk 1.6.12 to be specific

**Comment by SebaMutuku** [comment]
issue complete
