### ISSUE TITLE
Duplicated  'Syphilis test type'

### ISSUE THREAD

**Issue by madrinekariuki** [opensrp/opensrp-client-anc#774]
### How do we replicate the bug?

This has been tested on [this](https://onaio.slack.com/archives/C0E2558SH/p1643274875068100?thread_ts=1643202839.058800&cid=C0E2558SH) apk with the enabled property
user:` demo`

- login to the apk and sync data
- create a new client
- start a contact
- Ensure to put the value of syphilis test type
- Finalize the contact.
- click on the customers profile on the overview and scroll down.
- Observe how the input detail of syphilis test type is repeated.
- This can be observed on client Mary Janes

### How is this feature expected to work?

The syphilis test type should only show once.

screenshot.
![image](https://user-images.githubusercontent.com/84722169/152328066-c4412f04-49c0-49a6-abf0-088bde71cadf.png)

**Comment by Naima-Bashir** [comment]
@madrinekariuki closing this for now. Kindly reopen incase
