### ISSUE TITLE
Attention flag not updating.

### ISSUE THREAD

**Issue by madrinekariuki** [opensrp/opensrp-client-anc#775]
### How do we replicate the bug?

This has been tested on [this](https://onaio.slack.com/archives/C0E2558SH/p1643274875068100?thread_ts=1643202839.058800&cid=C0E2558SH) apk with the enabled property
user: `demo`

steps
1. Fill in only some of the test form and let some remains blank
2. Continue filling in other forms until the client can be finalized and saved
3. Check the attention flags
4. Go to client overview
5. Go to task tab
6. Pick any test and fill in with any results that should trigger a flag (As an example i pick Hepatitis B test positive and syphilis  positive as a result for client `Arthur Hannah`)
7. Go back to the clients page and sync (just in case)
8. Check the attention flags again. 

### How is this feature expected to work?

 The Hepatitis B test positive and syphilis  positive should be added into red flag on the attention flags.

see below details of client `Arthur Hannah` even after `Hepatitis B test positive` and `syphilis positive` have been added and data synced
![image](https://user-images.githubusercontent.com/84722169/152345053-f37bd328-f8a2-4c53-bdff-0bfe433311dc.png)

**Comment by madrinekariuki** [comment]
@SebaMutuku 
please note this is still occurring in the apk shared [here](https://onaio.slack.com/archives/C0E2558SH/p1646291253393939?thread_ts=1646232152.531119&cid=C0E2558SH). 

these are the observations:
- The attention flags are still not updating
- attention flags are not counting correctly we have 3 its showing 2 on the homepage for `Halsey heiley `and for `Julie Mu` its showing 6 but we have 3.
 - Attention flags are showing as a path.
 - Tests are not appearing on the attention flags. added` HIV +ve`, `Hep B +ve`, `syphillis +ve` for Halsey heiley `
 
screenshots.
![image](https://user-images.githubusercontent.com/84722169/156520852-104855e1-aab0-4df7-b5fa-2c96b9b54eff.png)
![image](https://user-images.githubusercontent.com/84722169/156521323-eecd11e9-3f06-4b53-ac21-e329c1a2a6df.png)

**Comment by Naima-Bashir** [comment]
Hi @madrinekariuki kindly confirm if this was fixed. Closing it for now

**Comment by madrinekariuki** [comment]
@Naima-Bashir This is still persistent. 
see this screenshot from The optiBP apk 1.6.12 apk on client `Gia Homu `who has 5 attention flags but when you count they are 6.
![image](https://user-images.githubusercontent.com/84722169/161242269-410dca91-62e8-4696-a0c8-5df8d4016d6d.png)

**Comment by Naima-Bashir** [comment]
Hi @SebaMutuku I am reopening this ticket

**Comment by SebaMutuku** [comment]
Hi @Naima-Bashir @madrinekariuki we were to open a new ticket for attention flags mismatch. This issue was mentioned by @madrinekariuki on slack and exists on the old app too. @madrinekariuki  can confirm this.

**Comment by Naima-Bashir** [comment]
Closing this one as I have opened a new ticket here https://github.com/opensrp/opensrp-client-anc/issues/811
