### ISSUE TITLE
[TEST] Test App to support Android 11 and 12

### ISSUE THREAD

**Issue by hamza-vd** [opensrp/opensrp-client-anc#778]
Upgrade and test the app on Android 11 and 12 to provide support for these OS versions.

- [ ] `buildToolsVersion` and `compileSdkVersion` needs to be updated to the latest

**Comment by Naima-Bashir** [comment]
can we close this @hamza-vd

**Comment by hamza-vd** [comment]
@dubdabasoduba can you update this?

**Comment by dubdabasoduba** [comment]
> 

I haven't tested this yet. @Naima-Bashir I think we can leave this open. It's more of tech debt and figuring out whether we can support the 2 android versions mentioned here.

**Comment by Naima-Bashir** [comment]
@SebaMutuku @junaidwarsivd to follow up with @hamza-vd on the status of this ticket

**Comment by Naima-Bashir** [comment]
Can I close this guys @hamza-vd @dubdabasoduba @AngelaKabari
