### ISSUE TITLE
[Ona Support Request]: App crashes: Previous Contact error

### ISSUE THREAD

**Issue by uzumakirex0000** [opensrp/opensrp-client-anc#784]
### Affected App or Server Version

v1.6.10

### What kind of support do you need?

when we change the language to nepali in the app.  under the profile of a woman in contact section, after we click in the previous contacts button app crashes.

### What is the acceptance criteria for your support request?

App should not crash

**Comment by Naima-Bashir** [comment]
Hello @uzumakirex0000 can we close this ticket or do you still need support on it?

**Comment by SebaMutuku** [comment]
@uzumakirex0000  write a function to convert BS date to AD date and save it on the database. The crash should disappear.
