### ISSUE TITLE
[Ona Support Request]: Setting up keycloak on public domain

### ISSUE THREAD

**Issue by khadkadipesh** [opensrp/opensrp-client-anc#785]
### Affected App or Server Version

Client anc 1.6.10 App version

### What kind of support do you need?

Keycloak is setup on local but stuck on forwarding keycloak to public ip.

### What is the acceptance criteria for your support request?

Keycloak web should be able to access from web browser publicly hosted from our AWS server.

### Relevant Information

https://smartregister.atlassian.net/wiki/spaces/Documentation/pages/2909995009/How+To+Setup+Opensrp+Server+Web+on+Kubernetes

We were following this documentation for keycloak setup.

**Comment by bennsimon** [comment]
@khadkadipesh Kindly setup a production ready cluster for this.

**Comment by Naima-Bashir** [comment]
Important links: https://docs.min.io/docs/generate-let-s-encypt-certificate-using-concert-for-minio.html
https://certbot.eff.org/
https://github.com/kubernetes/kops
