### ISSUE TITLE
[Ona Support Request]: Finalize button in the Dashboard doesn't activates until all the forms are filled 

### ISSUE THREAD

**Issue by sanjit7** [opensrp/opensrp-client-anc#790]
### Affected App or Server Version

v1.6.10

### What kind of support do you need?

When we start a Contact , the finalize button doesn't gets activated unless every details in the forms are filled.
Its not that mandatory requirement. But we want to learn ways to enable Finalize button of Dashboard , even if every details of forms are not filled.

### What is the acceptance criteria for your support request?

We want to learn ways  to activate finalize button  even if  every details in the forms are not filled.

**Comment by Naima-Bashir** [comment]
Is there a reason why you don't want to fill the activities? Just trying to understand the ticket better. @sanjit7

**Comment by uzumakirex0000** [comment]
ok !!! we will discuss with our team which forms we need to make required/optional. We will close this ticket now.
