### ISSUE TITLE
"Send Data" Button Not Working on Sender Device in P2P Sync Library

### ISSUE THREAD

**Issue by chobela** [opensrp/opensrp-client-anc#794]
### Affected App or Server Version

WHO ANC Reference App

### What kind of support do you need?

After completing the P2P Sync Setup, in the AncP2pModeSelectActivity activity, when we click on "SEND DATA" on the Sender Device, Nothing happens. Kindly help us to debug why this happens.

Also, we have noticed that we dont seem to have org.smartregister.anc.library.auth.AncCoreAuthorizationService in the library. So we cannnot import AncCoreAuthorizationService in our Application Class. Kindly shed more light on this too. 

Thanks.

### What is the acceptance criteria for your support request?

After Clicking Receive Data on the Recipient device, The Send data button on the sender device should also work.

### Relevant Information

We are using 2(Two) physical Tablet Devices. Samsung Tab A.

**Comment by dubdabasoduba** [comment]
@chobela Please add a title to this. Also, have you tested [this](https://github.com/opensrp/opensrp-client-anc/releases/tag/v.2.0.1) APK? It adds p2p to WHO ANC

**Comment by chobela** [comment]
@dubdabasoduba yes. But we are implementing the feature on our Instance because we have made several modifications to the App Forms, which are not in the APK you have shared.

**Comment by dubdabasoduba** [comment]
> @dubdabasoduba yes. But we are implementing the feature on our Instance because we have made several modifications to the App Forms, which are not in the APK you have shared.

The app form changes do not necessitate the change of how p2p works. I would like to understand the use case you are trying to add to the already done p2p work.

**Comment by dubdabasoduba** [comment]
The p2p code on this APK will be available by latest tomorrow on master so you don't need to rebuild it

**Comment by Naima-Bashir** [comment]
This has been resolved
