### ISSUE TITLE
[Ona Support Request]: The Date picker doesn't work well when Nepali language is selected.

### ISSUE THREAD

**Issue by sanjit7** [opensrp/opensrp-client-anc#797]
### Affected App or Server Version

v1.6.10

### What kind of support do you need?

In registration form , when we enter Date of Birth (date picker );
When language is selected as English , the date is properly shown after selection of a date .
When language " Nepali " is selected , date is not shown properly ( i.e age is calculated but date of birth field is empty )
[https://opensrp.slack.com/archives/C02V60H2KN1/p1646988698648869]

### What is the acceptance criteria for your support request?

 Date picker need to  work well when Nepali language is selected.

**Comment by junaidwarsivd** [comment]
hi @sanjit7  Please confirm weather this is working on your end cc @dubdabasoduba

**Comment by sanjit7** [comment]
Yes , we can close this ticket. This has been resolved partially.So we can continue this ticket in ticket number  #825.
