### ISSUE TITLE
[Ona Support Request]: The min date and max date is not working well in Date picker widget in BS(Bikram Sambat)

### ISSUE THREAD

**Issue by sanjit7** [opensrp/opensrp-client-anc#800]
### Affected App or Server Version

v1.6.10

### What kind of support do you need?

In registration form ,  when we enter date of birth .
The min date, and max date  is not working as mentioned in  code of  <anc_register.json> .

### What is the acceptance criteria for your support request?

The min date, and max date  need to  work as mentioned in  code of  <anc_register.json> .
If such condition are on other form , we will check from our side after the issue in registration form is resolved.

**Comment by AngelaKabari** [comment]
Hello @sanjit7 please confirm whether this has been satisfactorily resolved so we can close the issue?

**Comment by uzumakirex0000** [comment]
Yes its ok to close this issue

**Comment by uzumakirex0000** [comment]
Its solved in English language but when we change it to other language the issue still persisted But we can put it into less priority and focus first in other issue

**Comment by AngelaKabari** [comment]
Thanks for the feedback @uzumakirex0000. I've added a medium priority label so we can circle back to this once all the high priority issues are resolved.

**Comment by madrinekariuki** [comment]
This has been tested on this shared apk [reference-app-nepal-v1.6.16](https://onaio.slack.com/archives/CETQ18XL3/p1653646476035379)
user: `demo`

Observation:
- the min and Max date functionalities are working s expected

**Comment by sanjit7** [comment]
This feature is working  fine. 
We can close this ticket .
