### ISSUE TITLE
[Ona Support Request]: Translations in contact overview and contact tab not working when app language switched to French

### ISSUE THREAD

**Issue by neric1** [opensrp/opensrp-client-anc#802]
### Affected App or Server Version

v1.6.14 App

### What kind of support do you need?

Step: 1-login 
         2-perform contact while the app is switched in the English language and complete it.
         then move to the client profile.
         3- Results in the overview or contact tab are well displayed in English
         4- When the app is switched to French, data entered during contact remains in English while the app is translated to french.
![Captureoverview](https://user-images.githubusercontent.com/91191732/159282601-0bf013c7-0889-41d2-ae94-6a5d461c9f61.PNG)
![Capturecontact](https://user-images.githubusercontent.com/91191732/159282709-8dbeaba1-79b5-4916-9283-24fff290bf35.PNG)
        5-Also  during contact in physical exam->weight and height, while app switched in French some word won't be translated in  french (e.g in bmi calculation result “Underweight or normal weight ”)
![Capturephysical exam](https://user-images.githubusercontent.com/91191732/159283021-f6933a85-4c16-4801-b89b-859b55384b79.PNG)

### What is the acceptance criteria for your support request?

We need all app data in the overview and contact tab to be translated as app language changes.

**Comment by SebaMutuku** [comment]
Hi @neric1 can you share a screenshot of anc_register.json file and a screenshot of one client created after you added translation changes cc @Naima-Bashir

**Comment by neric1** [comment]
Hi @SebaMutuku it is not about creating a Client. it is about contact result displayed in overview and contact


![Captureoverview](https://user-images.githubusercontent.com/91191732/159448718-f5ccc144-7231-4d05-9c04-059e6d5033a2.PNG)

**Comment by SebaMutuku** [comment]
That's fine. I would like to see a few things and confirm whether you made those changes.

**Comment by SebaMutuku** [comment]
This issue was also explained during today's Location hierarchy call and documentation https://docs.google.com/document/d/1f0D8Ih4wNfGJr110aVD-NJyx13l8355ARKosXENQh9o shared with Rwanda team.

**Comment by Naima-Bashir** [comment]
Two issues:
1. Location Hierarchy
2. Translations

**Comment by neric1** [comment]
Hi @Naima-Bashir 
There is still a problem with the Location Hierarchy where the spinner is populated with locations only at the beginning when the app is syncing, but later when sync finished locations go away only a few of them appear.

**while syncing**

![Capturebeforesync](https://user-images.githubusercontent.com/91191732/160787250-f227d2a7-a5d7-4f77-9156-c85a5ea20d87.PNG)

**After sync**

![Capturelocationproblem](https://user-images.githubusercontent.com/91191732/160787432-32d7631c-b7cb-43e2-9ec2-230b353c88bf.PNG)

And on Translation, we completed all steps but the app won’t be translated in overview and all contact after contact is completed.

![Capturetranslation43](https://user-images.githubusercontent.com/91191732/160789060-a2d28932-dde3-4a5b-b0d2-a9af30a0043c.PNG)


cc @SebaMutuku

**Comment by SebaMutuku** [comment]
Hi @neric1 
1. Is there any error on the logcat when trying to sync the app?
2. What native-form version are you using? 
3. What ANC branch are you running your translations from? Can you kindly share a screenshots of:
a. Database once you do a contact
b. Version of native form on both opensrp-anc and reference app.

**Comment by neric1** [comment]
1.No error when I  try to sync 
2. native-form I am using 2.1.16-alpha-SNAPSHOT
3. and am using this branch https://github.com/opensrp/opensrp-client-anc/tree/merge/general-app-updates
which table do you want to see? am using  2.1.16-alpha-SNAPSHOT on both opensrp-anc and reference app.

**Comment by SebaMutuku** [comment]
@neric1 previous_contacts for a recently added user after you enabled translations

**Comment by SebaMutuku** [comment]
> 1.No error when I try to sync 2. native-form I am using 2.1.16-alpha-SNAPSHOT 
3. and am using this branch https://github.com/opensrp/opensrp-client-anc/tree/merge/general-app-updates which table do you want to see? am using 2.1.16-alpha-SNAPSHOT on both opensrp-anc and reference app.
Can you share a screenshot for the native-from?

**Comment by SebaMutuku** [comment]
> 1.No error when I try to sync 2. native-form I am using 2.1.16-alpha-SNAPSHOT 3. and am using this branch https://github.com/opensrp/opensrp-client-anc/tree/merge/general-app-updates which table do you want to see? am using 2.1.16-alpha-SNAPSHOT on both opensrp-anc and reference app.

Did you add native form on both opensrp-anc and reference app modules?

**Comment by neric1** [comment]
> > 1.No error when I try to sync 2. native-form I am using 2.1.16-alpha-SNAPSHOT 3. and am using this branch https://github.com/opensrp/opensrp-client-anc/tree/merge/general-app-updates which table do you want to see? am using 2.1.16-alpha-SNAPSHOT on both opensrp-anc and reference app.
> 
> Did you add native form on both opensrp-anc and reference app modules?

yes

**Comment by neric1** [comment]
> @neric1 previous_contacts for a recently added user after you enabled translations
![Capturedatabase](https://user-images.githubusercontent.com/91191732/160807430-b45a861d-cc3e-4cca-be82-02f8c0409b03.PNG)

**Comment by neric1** [comment]
> > 1.No error when I try to sync 2. native-form I am using 2.1.16-alpha-SNAPSHOT
> 
> 3. and am using this branch https://github.com/opensrp/opensrp-client-anc/tree/merge/general-app-updates which table do you want to see? am using 2.1.16-alpha-SNAPSHOT on both opensrp-anc and reference app.
>    Can you share a screenshot for the native-from?
![Capturenative](https://user-images.githubusercontent.com/91191732/160808312-b61ca288-b6b8-4c05-b2ff-637f26404c6c.PNG)

**Comment by SebaMutuku** [comment]
> > @neric1 previous_contacts for a recently added user after you enabled translations
> > ![Capturedatabase](https://user-images.githubusercontent.com/91191732/160807430-b45a861d-cc3e-4cca-be82-02f8c0409b03.PNG)

Translations have not been effected here.

**Comment by SebaMutuku** [comment]
> > > 1.No error when I try to sync 2. native-form I am using 2.1.16-alpha-SNAPSHOT
> > 
> > 
> > 
> > 3. and am using this branch https://github.com/opensrp/opensrp-client-anc/tree/merge/general-app-updates which table do you want to see? am using 2.1.16-alpha-SNAPSHOT on both opensrp-anc and reference app.
> >    Can you share a screenshot for the native-from?
> >    ![Capturenative](https://user-images.githubusercontent.com/91191732/160808312-b61ca288-b6b8-4c05-b2ff-637f26404c6c.PNG)

Also add the native form version on build.gradle of opensrp-anc module in opensrp-client-anc app

**Comment by neric1** [comment]
> > > > 1.No error when I try to sync 2. native-form I am using 2.1.16-alpha-SNAPSHOT
> > > 
> > > 
> > > 
> > > 3. and am using this branch https://github.com/opensrp/opensrp-client-anc/tree/merge/general-app-updates which table do you want to see? am using 2.1.16-alpha-SNAPSHOT on both opensrp-anc and reference app.
> > >    Can you share a screenshot for the native-from?
> > >    ![Capturenative](https://user-images.githubusercontent.com/91191732/160808312-b61ca288-b6b8-4c05-b2ff-637f26404c6c.PNG)
> 
> Also add the native form version on build.gradle of opensrp-anc module in opensrp-client-anc app

![Capturenative_opersrp_anc](https://user-images.githubusercontent.com/91191732/161011643-1cf977a5-804f-4a44-ace7-0d1bdc056a2c.PNG)

**Comment by Naima-Bashir** [comment]
Translation issue has been resolved. 
As for the location issue; Ona is waiting for an apk from the 1000 Hills team to troubleshoot.

**Comment by Naima-Bashir** [comment]
> Hi @Naima-Bashir There is still a problem with the Location Hierarchy where the spinner is populated with locations only at the beginning when the app is syncing, but later when sync finished locations go away only a few of them appear.
> 
> **while syncing**
> 
> ![Capturebeforesync](https://user-images.githubusercontent.com/91191732/160787250-f227d2a7-a5d7-4f77-9156-c85a5ea20d87.PNG)
> 
> **After sync**
> 
> ![Capturelocationproblem](https://user-images.githubusercontent.com/91191732/160787432-32d7631c-b7cb-43e2-9ec2-230b353c88bf.PNG)
> 
> And on Translation, we completed all steps but the app won’t be translated in overview and all contact after contact is completed.
> 
> ![Capturetranslation43](https://user-images.githubusercontent.com/91191732/160789060-a2d28932-dde3-4a5b-b0d2-a9af30a0043c.PNG)
> 
> cc @SebaMutuku

Hi @neric1 , The location issue is a sepaate ticket. Can we close this and you open another with the title Location hierarchy issues? cc @SebaMutuku

**Comment by neric1** [comment]
Hi @Naima-Bashir, You can close it.

**Comment by Naima-Bashir** [comment]
Okay @neric1 pleasw create a separate issue for location
