### ISSUE TITLE
[Ona Support Request]: All the mothers' age showed up the same on the database

### ISSUE THREAD

**Issue by elwinameylentia** [opensrp/opensrp-client-anc#803]
### Affected App or Server Version

Indonesian Local client app

### What kind of support do you need?

All the mothers' age showed up as 19 on the database, although we input various age and birth year on the client app. Could you please help us identify the source of the problem?
![image](https://user-images.githubusercontent.com/93704986/159461942-6c638b39-e823-4b38-b396-c572e31345f2.png)

### What is the acceptance criteria for your support request?

Mothers' ages showed up on the database according to the age and birth year that were entered through the client app

**Comment by Naima-Bashir** [comment]
do you have a screenshot of the app? @elwinameylentia

**Comment by Naima-Bashir** [comment]
@junaidwarsivd kindly take a look at this

**Comment by elwinameylentia** [comment]
@Naima-Bashir which part of the app would you like to see?

**Comment by Naima-Bashir** [comment]
the one that shows 19 @elwinameylentia

**Comment by elwinameylentia** [comment]
@Naima-Bashir here are two examples where the age doesn't match between the client app and the database screenshot above

1. Line 1 
first_name: Uji
last_name: Coba
age in database: 19
correct age (usia) in client app: 29
![image](https://user-images.githubusercontent.com/93704986/159466273-05f2714f-684a-41ac-97cb-3d0aaa08fdba.png)

2. Line 5
first_name: Angelina
last_name: Jolie
age in database: 19
correct age (usia) in client app: 31
![image](https://user-images.githubusercontent.com/93704986/159466479-48c3d0f7-aa06-4783-b389-2a24d6e28219.png)

**Comment by dubdabasoduba** [comment]
Next Steps
For SID 
- Does this happen while using the Bahasa language or happens in English too?

**Comment by Naima-Bashir** [comment]
The SID team to  check the rules engine calculations and a class called rules engine to see the edge that is calculated before saving. Then get back to the Ona team.

**Comment by SebaMutuku** [comment]
Issue resolved

**Comment by Naima-Bashir** [comment]
@elwinameylentia let us know if we can close this.

**Comment by elwinameylentia** [comment]
i will check and get back to you

**Comment by elwinameylentia** [comment]
we are still trying to implement it. will update you once it's been tested

**Comment by SebaMutuku** [comment]
Hi @elwinameylentia. Can we close this ticket?

**Comment by elwinameylentia** [comment]
Yes
