### ISSUE TITLE
[Ona Support Request]: Forms could not be finalized

### ISSUE THREAD

**Issue by elwinameylentia** [opensrp/opensrp-client-anc#804]
### Affected App or Server Version

Indonesian Local client app

### What kind of support do you need?

The 'Finalize' button on top right couldn't be clicked although all forms have been finished and there was no empty field anymore. Could you please help us identify the source of the problem?
![WhatsApp Image 2022-03-17 at 2 06 20 PM](https://user-images.githubusercontent.com/93704986/159462501-c58f82f9-b8d2-471b-b070-07be7d63fc7a.jpeg)

### What is the acceptance criteria for your support request?

'Finalize' button on the top right could be clicked when all forms have been finished and there was no empty field anymore

**Comment by dubdabasoduba** [comment]
Next steps
- Follow up with SID on the app version they are using. If it's a local build we need an APK from them for us to test.

**Comment by Naima-Bashir** [comment]
This can be closed as the SID team has fixed it
