### ISSUE TITLE
[Ona Support Request]: App Crash after selecting Location in settings

### ISSUE THREAD

**Issue by uzumakirex0000** [opensrp/opensrp-client-anc#806]
### Affected App or Server Version

v1.6.10

### What kind of support do you need?

need a location to be displayed in the settings.

### What is the acceptance criteria for your support request?

the app should not crash when opening the location. 

### STEPS:

1. Login to the Nepali local app
2. Click on the settings section
3. Select the location and observe how the app crashes

_No response_

**Comment by Naima-Bashir** [comment]
Ona and the tech partners had a pairing session, they noticed the location names are null from the app(they aren't being loaded from opensrp server)
The partners to check if they can get locations from postman then give Ona feedback.

**Comment by junaidwarsivd** [comment]
this issue is related to #826 @AngelaKabari

**Comment by uzumakirex0000** [comment]
This issue is solved. We can close this issue
