### ISSUE TITLE
[Bug Report]: Error on the Urine Test

### ISSUE THREAD

**Issue by elwinameylentia** [opensrp/opensrp-client-anc#809]
### How do we replicate the bug?

1. Log in to the client app
2. Register new client or continue contact
3. Go to the Test form
4. Fill in all the test results up until the urine test
5. Choose Urine Test, then pick a urine test type (i pick the dipstick test here)
6. The next question that should be asking for the test result, doesn't show up.
7. Click back on your phone
8. Urine test cannot be clicked again

https://user-images.githubusercontent.com/93704986/160751250-260c295d-01ba-4db2-b3b4-2b37cc934a18.mp4

### How is this feature expected to work?

After choosing the type of urine test, the app should ask for the result of the test

**Comment by madrinekariuki** [comment]
@elwinameylentia  I have tested this  and i am able to record the Urine test results. see below video shared here
https://drive.google.com/file/d/1YTz52nB43a65fkImrUgWUlcTVdxt63Q4/view?usp=sharing

**Comment by Naima-Bashir** [comment]
@elwinameylentia closing this; please feel free to reopen if it still occurs.
