### ISSUE TITLE
[Ona Support Request]: The drop down for selecting the location changes after sync

### ISSUE THREAD

**Issue by neric1** [opensrp/opensrp-client-anc#812]
### Affected App or Server Version

v1.6.14 App Rwanda

### What kind of support do you need?

-Login in reference app 
-Try to register a new client
-There is a problem with the Location Hierarchy where the spinner is populated with locations only at the beginning when the app is syncing, but later when sync finished locations go away only a few of them appear.

### What is the acceptance criteria for your support request?

The location Hierarchy should be displayed well according to what the user selected.

### Relevant Information

Before sync

![Capturprovincee](https://user-images.githubusercontent.com/91191732/161697172-83d8cab2-8016-4249-90e3-532ff03fe8a3.PNG)

After sync 

![location_appeb](https://user-images.githubusercontent.com/91191732/161697242-3957c564-1dfe-4e62-b14c-774e25548632.PNG)

**Comment by Naima-Bashir** [comment]
Their location endpoint returns a null point for jurisdiction. 
@SebaMutuku and @dubdabasoduba to look at it together

**Comment by AngelaKabari** [comment]
Hello @neric1 I'm following up on this: Did you try syncing? If yes, kindly share the logs of your opensrp-server-web backend?

**Comment by neric1** [comment]
Hi @AngelaKabari  we have already shared it on slack a few days ago.

**Comment by hamza-vd** [comment]
@dubdabasoduba I have tried debugging this issue and found that the locations are synced to the device on initial sync, but all the locations get deleted from the database on subsequent syncs. This is happening inside `ValidationAssignmentHelper` class's `processRemovedAssignments`  method. What could be the reason for this? Is there any configuration that we need to change?

**Comment by dubdabasoduba** [comment]
> @dubdabasoduba I have tried debugging this issue and found that the locations are synced to the device on initial sync, but all the locations get deleted from the database on subsequent syncs. This is happening inside `ValidationAssignmentHelper` class's `processRemovedAssignments` method. What could be the reason for this? Is there any configuration that we need to change?

@hamza-vd Does it remove the locations that are not assigned to any teams?

**Comment by hamza-vd** [comment]
@dubdabasoduba I'm not sure about that, @SebaMutuku can you verify which team assignments do the locations have?

**Comment by SebaMutuku** [comment]
@hamza-vd @dubdabasoduba below are screenshots for  assisgned locations for common users. What users were you using?
![Screenshot from 2022-05-18 14-44-43](https://user-images.githubusercontent.com/36365043/169031556-65d8beae-6c9a-4120-b2df-6e626669cd39.png)

**Comment by dubdabasoduba** [comment]
@SebaMutuku please troubleshoot this. Check whether the locations deleted are the ones not on the logged-in user hierarchy

**Comment by madrinekariuki** [comment]
This has been tested on `rw-reference-app-v1.6.14` shared apk

findings:
All the provinces are showing after sync is complete.
![image](https://user-images.githubusercontent.com/84722169/172177292-37ae10be-7a76-41ff-9f74-ce44aaadc367.png)

**Comment by AngelaKabari** [comment]
@neric1 Please find above the fix for the location issue. Kindly test it on your end to confirm whether it has been resolved satisfactorily?

**Comment by junaidwarsivd** [comment]
@neric1 i've updated the PR https://github.com/dodosi/opensrp_rw/pull/20 against the fix kindly check at your end if this has fixed cc @AngelaKabari

**Comment by neric1** [comment]
Hi @junaidwarsivd  @AngelaKabari , it is working fine now, Thank you
