### ISSUE TITLE
[Ona Support Request]: Cannot finalize after completing counselling and treatment form

### ISSUE THREAD

**Issue by elwinameylentia** [opensrp/opensrp-client-anc#813]
### Affected App or Server Version

Indonesia local apk

### What kind of support do you need?

Help in troubleshoot the error

Video of the mentioned error can be found in this drive link https://drive.google.com/file/d/1CHayhux0Dzv5pPlFE3usfQF1BJp2RKk9/view?usp=sharing

### What is the acceptance criteria for your support request?

Once completed, the counseling and treatment form shows "completed" and checkmark, then the ANC contact can be finalized.

**Comment by SebaMutuku** [comment]
@elwinameylentia  please share your repository and local.properties

**Comment by Naima-Bashir** [comment]
@SebaMutuku this has been shared on slack.

**Comment by SebaMutuku** [comment]
@Naima-Bashir  I haven't seen any local.properties files

**Comment by Naima-Bashir** [comment]
Updates from the SID team: They've identified the problem of why the checkmark on Counselling & Treatment box wasn't showing
Typo in MainContactActivity.java of "Counseling" as supposed to "Counselling" when using the setName() function

As for the finalise problem, there seems to be a mismatch of entries.size() [8 entries] and contactForms.length [7 entries] in the getRequiredCountTotal function

**Comment by Naima-Bashir** [comment]
Can we close this @elwinameylentia

**Comment by elwinameylentia** [comment]
yes this is okay to close
