### ISSUE TITLE
[New Feature Request]: Number of Fetal Heart Rate column follows the number of fetuses

### ISSUE THREAD

**Issue by elwinameylentia** [opensrp/opensrp-client-anc#817]
### Feature Use Case

As of now, users can only enter one fetal heart rate regardless of the number of fetuses. However, when there's more than one fetus, each fetus could have a different fetal heart rate. Therefore it requires more than one column for entering the fetal heart rate.

![Screenshot_20220407-172903_WHO ANC](https://user-images.githubusercontent.com/93704986/162176779-ae69fb95-738e-40a1-b9ac-05e3a2ae4fac.jpg)

### Acceptance criteria

The number of fetal heart rate columns appears according to the number of fetuses. For example: if there are two fetuses, then there would be two columns to enter two fetal heart rates, three fetuses means three columns, and so on

**Comment by Naima-Bashir** [comment]
#665 similar to this. Closing this one
