### ISSUE TITLE
[Ona Support Request]: Registration info : spinner, checkbox and native_radio values not populating after translation enabled 

### ISSUE THREAD

**Issue by neric1** [opensrp/opensrp-client-anc#818]
### Affected App or Server Version

v1.6.14 App

### What kind of support do you need?

1. Login in reference app 
2. Register a new Client 
3. Continue to Registration info on the client profile
4. Observe that reminder and cohabitant values are not populated, you can’t identify the chosen option 

### What is the acceptance criteria for your support request?

We want the app to show which option is chosen while registering the client

### Relevant Information

![WhatsApp Image 2022-04-08 at 12 04 30 PM](https://user-images.githubusercontent.com/91191732/162415102-0dd16ffe-d509-4aba-9ee6-6411ee171da7.jpeg)

**Comment by SebaMutuku** [comment]
Hi @neric1 what native form version are you using?

**Comment by neric1** [comment]
> Hi @neric1 what native form version are you using? Do you have translation_text attributes for the keys in the correct json form?

2.1.16-alpha

**Comment by neric1** [comment]
![Capturedhdhdhcohabitant](https://user-images.githubusercontent.com/91191732/162421661-96066a20-3424-4195-939b-f657ac9a42a9.PNG)

**Comment by SebaMutuku** [comment]
@neric1  what branch are you using?

**Comment by neric1** [comment]
> @neric1 what branch are you using? Update your current branch for me to use it.

https://github.com/dodosi/opensrp_rw/tree/develop

**Comment by SebaMutuku** [comment]
Hi @neric1 please share a user and local.property files associated with this endpoint on slack. I am getting login failed error when trying to log in

**Comment by SebaMutuku** [comment]
Dear @neric1 , translation_text attribute for native radios and checkboxes in anc_register.json are were not added. Below is a sample options array for key reminder [
  {
    "key": "yes",
    "text": "Yes",
    "openmrs_entity": "",
    "openmrs_entity_id": "1065AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
  },
  {
    "key": "no",
    "text": "No",
    "openmrs_entity": "",
    "openmrs_entity_id": "1066AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
  }
]

**Comment by SebaMutuku** [comment]
@neric1 add translation files to your json forms for the title widgets and use native form version 2.1.16-PREVIEW-SNAPSHOT

**Comment by neric1** [comment]
Hi, @SebaMutuku  I did it like this(in below snippet)  and I changed native form version to 2.1.16-PREVIEW-SNAPSHOT but the problem persists. is there anything I forgot?

         "type": "native_radio",
        "label": "{{anc_register.step1.reminders.label}}",
        "label_info_text": "{{anc_register.step1.reminders.label_info_text}}",
        "label_text_style": "normal",
        "text_color": "#000000",
        "options": [
          {
            "key": "yes",
            "text": "{{anc_register.step1.reminders.options.yes.text}}",
            "translation_text": "anc_register.step1.reminders.options.yes.text",
            "value": "false",
            "openmrs_entity": "",
            "openmrs_entity_id": "1065AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
          },
          {
            "key": "no",
            "text": "{{anc_register.step1.reminders.options.no.text}}",
            "translation_text": "anc_register.step1.reminders.options.no.text",
            "value": "false",
            "openmrs_entity": "",
            "openmrs_entity_id": "1066AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
          }
        ],

**Comment by SebaMutuku** [comment]
@neric1 Issue resolved. Please use core version 5.0.2-PREVIEW-SNAPSHOT and native version 2.1.18-PREVIEW-SNAPSHOT

**Comment by neric1** [comment]
> @neric1 Issue resolved. Please use core version 5.0.2-PREVIEW-SNAPSHOT and native version 2.1.18-PREVIEW-SNAPSHOT Also ensure the widgets you are testing with have translation_text

Hi, @SebaMutuku I see the problem solved only on spinners but not on checkbox and native_radio also relevance property has been broken after upgrading to this version. the hidden field is not shown when it is relevance

**Comment by SebaMutuku** [comment]
Hi @neric1 , please check on your end and advise. Native form version is 2.1.17-PREVIEW-SNAPSHOT . Core version is 5.0.1-SNAPSHOT

**Comment by neric1** [comment]
Hi @SebaMutuku, 
-Expansion of widget on native_radio when relevance solved but remains on spinner widget for instance you can check anc_close when you select reason no other thing shown.
-Data is not populated on reminder for edit when you open registration info
![Capturermminder](https://user-images.githubusercontent.com/91191732/165486887-29a18b2c-32fc-4a0a-af30-62eaa0b87463.PNG)
![Captureclose](https://user-images.githubusercontent.com/91191732/165486944-2d33ca47-3c11-40b4-8d71-2fd8842296db.PNG)

**Comment by SebaMutuku** [comment]
@neric1 please elaborate on anc_close issue. I didn't quite understand your issue

**Comment by neric1** [comment]
> @neric1 please elaborate on anc_close issue. I didn't quite understand your issue

HI @SebaMutuku , this is how is supposed tobe: when we choose livebirth
![Screenshot_2022-04-27-14-19-53-275_org smartregister anc](https://user-images.githubusercontent.com/91191732/165517441-cd5e09ce-b15e-447a-b663-3598225d36ce.jpg)

**Comment by SebaMutuku** [comment]
Do you have translation_text for  these spinners?

**Comment by neric1** [comment]
yes

> Do you have translation_text for these spinner keys? Especially livebirth key?

Yes, i think expansion rule on spinners was broken too

**Comment by SebaMutuku** [comment]
Hi @neric1 please check whether the anc form close has relevance and the rule's engine to call for those spinners
below is the json form I have seen while debugging
{
  "key": "anc_close_reason",
  "openmrs_entity_parent": "",
  "openmrs_entity": "concept",
  "openmrs_entity_id": "165245AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
  "openmrs_data_type": "select one",
  "type": "spinner",
  "hint": "Reason?",
  "options": [
    {
      "key": "live_birth",
      "text": "Live birth",
      "translation_text": "anc_close.step1.anc_close_reason.options.live_birth.text",
      "openmrs_entity_parent": "",
      "openmrs_entity": "concept",
      "openmrs_entity_id": "151849AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    },
    {
      "key": "stillbirth",
      "text": "Stillbirth",
      "translation_text": "anc_close.step1.anc_close_reason.options.stillbirth.text",
      "openmrs_entity_parent": "",
      "openmrs_entity": "concept",
      "openmrs_entity_id": "125872AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    },
    {
      "key": "miscarriage",
      "text": "Miscarriage",
      "translation_text": "anc_close.step1.anc_close_reason.options.miscarriage.text",
      "openmrs_entity_parent": "",
      "openmrs_entity": "concept",
      "openmrs_entity_id": "48AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    },
    {
      "key": "abortion",
      "text": "Abortion",
      "translation_text": "anc_close.step1.anc_close_reason.options.abortion.text",
      "openmrs_entity_parent": "",
      "openmrs_entity": "concept",
      "openmrs_entity_id": "50AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    },
    {
      "key": "woman_died",
      "text": "Woman died",
      "translation_text": "anc_close.step1.anc_close_reason.options.woman_died.text",
      "openmrs_entity_parent": "",
      "openmrs_entity": "",
      "openmrs_entity_id": "160034AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    },
    {
      "key": "moved_away",
      "text": "Moved away",
      "translation_text": "anc_close.step1.anc_close_reason.options.moved_away.text",
      "openmrs_entity_parent": "",
      "openmrs_entity": "concept",
      "openmrs_entity_id": "5240AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    },
    {
      "key": "false_pregnancy",
      "text": "False pregnancy",
      "translation_text": "anc_close.step1.anc_close_reason.options.false_pregnancy.text",
      "openmrs_entity_parent": "",
      "openmrs_entity": "concept",
      "openmrs_entity_id": "128299AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    },
    {
      "key": "lost_to_follow_up",
      "text": "Lost to follow-up",
      "translation_text": "anc_close.step1.anc_close_reason.options.lost_to_follow_up.text",
      "openmrs_entity_parent": "",
      "openmrs_entity": "concept",
      "openmrs_entity_id": ""
    },
    {
      "key": "wrong_entry",
      "text": "Wrong entry",
      "translation_text": "anc_close.step1.anc_close_reason.options.wrong_entry.text",
      "openmrs_entity_parent": "",
      "openmrs_entity": "concept",
      "openmrs_entity_id": "165246AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    },
    {
      "key": "other",
      "text": "Other",
      "translation_text": "anc_close.step1.anc_close_reason.options.other.text",
      "openmrs_entity_parent": "",
      "openmrs_entity": "concept",
      "openmrs_entity_id": "5622AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    }
  ],
  "v_required": {
    "value": "true",
    "err": "Please select one option"
  }
}

**Comment by neric1** [comment]
Hi @SebaMutuku, relevance exists and rules engine too.

      {
        "key": "delivery_place",
        "openmrs_entity_parent": "",
        "openmrs_entity": "concept",
        "openmrs_entity_id": "1572AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
        "openmrs_data_type": "select one",
        "type": "spinner",
        "hint": "{{anc_close.step1.delivery_place.hint}}",
        "options": [
          {
            "key": "health_facility",
            "text": "{{anc_close.step1.delivery_place.options.health_facility.text}}",
            "translation_text": "anc_close.step1.delivery_place.options.health_facility.text",
            "openmrs_entity_parent": "",
            "openmrs_entity": "concept",
            "openmrs_entity_id": "1588AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
          },
          {
            "key": "home",
            "text": "{{anc_close.step1.delivery_place.options.home.text}}",
            "translation_text": "anc_close.step1.delivery_place.options.home.text",
            "openmrs_entity_parent": "",
            "openmrs_entity": "concept",
            "openmrs_entity_id": "1536AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
          },
          {
            "key": "other",
            "text": "{{anc_close.step1.delivery_place.options.other.text}}",
            "translation_text": "anc_close.step1.delivery_place.options.other.text",
            "openmrs_entity_parent": "",
            "openmrs_entity": "concept",
            "openmrs_entity_id": "5622AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
          }
        ],
        "v_required": {
          "value": "true",
          "err": "{{anc_close.step1.delivery_place.v_required.err}}"
        },
        "relevance": {
          "rules-engine": {
            "ex-rules": {
              "rules-file": "anc_close_relevance_rules.yml"
            }
          }
        }
      },

rules 

![Capturerules](https://user-images.githubusercontent.com/91191732/165714175-16a54c78-5cb5-447c-84e7-2c2034b995eb.PNG)

**Comment by SebaMutuku** [comment]
Hi @neric1 please confirm both issues have been resolved here 2.1.17-ZAM-PREVIEW-SNAPSHOT

**Comment by neric1** [comment]
Hi @SebaMutuku , the issues are solved thank you!
