### ISSUE TITLE
Contact Downloaded pdf missing the Client's Name.

### ISSUE THREAD

**Issue by madrinekariuki** [opensrp/opensrp-client-anc#820]
### How do we replicate the bug?

tested on [this apk](https://drive.google.com/file/d/1X5IqZQGF6a0LMbVmRWOgI6VkFEeUuJqb/view)
user : `demo`

steps:

- Login to the apk
- register a client and start a contact.
- finish the contact and click finalize
- You will see a pop up showing contact summary pdf has been generated.
- take note of the path ()
- Save and finish the contact 
- Navigate to the pdf and open it
- See there is no client name of the pdf document.

### How is this feature expected to work?

The generated PDF document should have all the details of the contact including the clients name.

### Please Share other relevant information about the bug

screenshot with no name showing

![image](https://user-images.githubusercontent.com/84722169/162719386-25c1c060-adbe-4c1e-8024-658aa5abb0f1.png)

**Comment by Naima-Bashir** [comment]
Hi @junaidwarsivd kindly pick this up. 
cc @dubdabasoduba

**Comment by madrinekariuki** [comment]
@junaidwarsivd 

Kindly note that the clients name is now showing on the contact PDF Form.
see screenshot below.
![image](https://user-images.githubusercontent.com/84722169/165266548-d442955d-1cc5-4288-8fad-425296d7b7f6.png)

**Comment by AngelaKabari** [comment]
This has [passed QA](https://onaio.slack.com/archives/CETQ18XL3/p1650965000303219?thread_ts=1650871117.072899&cid=CETQ18XL3) and can therefore be closed
