### ISSUE TITLE
[Ona Support Request]: Adding new questions to forms

### ISSUE THREAD

**Issue by elwinameylentia** [opensrp/opensrp-client-anc#821]
### Affected App or Server Version

local Indonesian apk

### What kind of support do you need?

ONA team has shared related documentation but the SID team is facing problems in implementing it. The SID team will share the latest code used for it

### What is the acceptance criteria for your support request?

The SID team can add, remove, and modify questions on the client app

**Comment by SebaMutuku** [comment]
@elwinameylentia I left my comments here https://opensrp.slack.com/archives/C02FPRBPWCU/p1651144698103259?thread_ts=1650945430.884939&cid=C02FPRBPWCU

**Comment by SebaMutuku** [comment]
This has been resolved

**Comment by AngelaKabari** [comment]
SID Team have [asked for this issue to remain open](https://opensrp.slack.com/archives/C02FPRBPWCU/p1652264512068589?thread_ts=1651153598.277759&cid=C02FPRBPWCU) as it's still a work in progress and they may encounter another error that  requires support

**Comment by dubdabasoduba** [comment]
@elwinameylentia Please share the following items,

1. A link to the forms where the questions are added. 
2. Keys to the specific questions in the respective forms.
