### ISSUE TITLE
[Ona Support Request]: Extract some WHO ANC data in CSV files 

### ISSUE THREAD

**Issue by dubdabasoduba** [opensrp/opensrp-client-anc#822]
### Affected App or Server Version

lates

### What kind of support do you need?

- [ ] Get a data dump of the `client` & `client_metadata` tables 
- [ ] Get a data dump of the `event` & `event_metadata` tables
- [ ] Get a data dump of the `practitioner`, `practitioner_role` & `organization` tables. 

### What is the acceptance criteria for your support request?

- [ ] All the data dump in CSV files

**Comment by SebaMutuku** [comment]
@dubdabasoduba this has been provisioned from preview_stage database
