### ISSUE TITLE
[Ona Support Request]: after we login to the app the site characteristics popup and after we go past that the app crashes.

### ISSUE THREAD

**Issue by uzumakirex0000** [opensrp/opensrp-client-anc#823]
### Affected App or Server Version

v1.6.8

### What kind of support do you need?

2022-04-29 11:47:27.260 17013-17162/org.smartregister.anc E/HTTPAgent: Invalid credentials accessing: https://dhmira.dphcp.org/opensrp/security/authenticate using token null 

this is the error we are getting.

### What is the acceptance criteria for your support request?

the app should run when the server is changed to dhmira. it works fine with ona's server though

**Comment by junaidwarsivd** [comment]
this issue is the also related to #826

**Comment by uzumakirex0000** [comment]
we can close this issue too
