### ISSUE TITLE
[Ona Support Request]: Date Picker widget doesn't pop-up on ANC profile form , when language is switched from English to any other langauge 

### ISSUE THREAD

**Issue by sanjit7** [opensrp/opensrp-client-anc#825]
### Affected App or Server Version

v 1.6.15 BS_date_picker_changes 

### What kind of support do you need?

In Profile , when selecting dates from LMP & Ultrasound .It works well when language is selected as English . 
When switching to other language , i.e Nepali or French  . 
The date picker doesn't pop up on Profiles's LMP and Ultrasound date selection.

### What is the acceptance criteria for your support request?

Date picker widget should pop-up  in ANC_Profiles's LMP & Ultrasound date selection , when changing the language.

**Comment by madrinekariuki** [comment]
This has been tested on this shared apk [reference-app-nepal-v1.6.16](https://onaio.slack.com/archives/CETQ18XL3/p1653646476035379)
user: `demo`

observation:
- The date picker pops up. This was tested on French Language. under client `Alice Mun`
- The LMP button and ultrasound button  take long for the date picker to pop up.

**Comment by parajulisandip0000** [comment]
we can close this issue
