### ISSUE TITLE
[Ona Support Request]: App crashes after location info has been filled in

### ISSUE THREAD

**Issue by AngelaKabari** [opensrp/opensrp-client-anc#826]
### Affected App or Server Version

v 1.6.15 BS_date_picker_changes

### What kind of support do you need?

App crashes after we get past the site characteristics.

See Slack thread: https://opensrp.slack.com/archives/C02V60H2KN1/p1651751801068349 for further details

### What is the acceptance criteria for your support request?

The app should not crash upon login

**Comment by AngelaKabari** [comment]
@sanjit7 Please confirm that the [debug apk](https://drive.google.com/file/d/1ocKHXJCgsvQLPy1nxf0jn2we2WT-Md3U/view?usp=sharing) that Kigamba has shared satisfactorily the crash upon log in issue?

**Comment by uzumakirex0000** [comment]
this issue also has been solved by E.kigamba so we can close this issue
