### ISSUE TITLE
[Ona Support Request]: Generate Task

### ISSUE THREAD

**Issue by elwinameylentia** [opensrp/opensrp-client-anc#828]
### Affected App or Server Version

Indonesia local apk

### What kind of support do you need?

Our team couldn't generate the Task tab on the mother's profile in the client app. Please help check and debug the source code here https://github.com/dhanangap/opensrp-client-anc/tree/form-bug

### What is the acceptance criteria for your support request?

The Task tab can be generated

**Comment by SebaMutuku** [comment]
@elwinameylentia did the web set up happen end-to-end?

**Comment by AngelaKabari** [comment]
Prama and Elwina have [confirmed](https://opensrp.slack.com/archives/C02FPRBPWCU/p1652695286386389?thread_ts=1652178621.761719&cid=C02FPRBPWCU) that this issue is now resolved
