### ISSUE TITLE
[Ona Support Request]: Login to OpenSRP Web form results in an error 

### ISSUE THREAD

**Issue by AngelaKabari** [opensrp/opensrp-client-anc#829]
### Affected App or Server Version

https://web.ancs.dev.sid-indonesia.org/

### What kind of support do you need?

See: https://github.com/opensrp/web/issues/998

### What is the acceptance criteria for your support request?

One should be able to log into the web form

### Relevant Information

See [Slack thread](https://opensrp.slack.com/archives/C02FPRBPWCU/p1649333596903299)

**Comment by SebaMutuku** [comment]
@elwinameylentia  did server web setup happen? I remember a fresh setup of your local instance of server web was to happen.

**Comment by AngelaKabari** [comment]
Levi has [confirmed](https://opensrp.slack.com/archives/C02FPRBPWCU/p1652748543542259?thread_ts=1649333596.903299&cid=C02FPRBPWCU) that this issue is now resolved.
