### ISSUE TITLE
[Ona Support Request]: OptiBP calibration integrated into the WHO-ANC app

### ISSUE THREAD

**Issue by elwinameylentia** [opensrp/opensrp-client-anc#830]
### Affected App or Server Version

WHO-ANC x OptiBP

### What kind of support do you need?

As of right now, clicking the OptiBP widget inside the client app would direct the user to the measurement function straight away, skipping the calibration function. Calibration function is necessary in order to collect an accurate blood pressure of the client/mother. So we hope that the ONA team can develop an apk that has the OptiBP calibration function integrated inside the app for new mothers. 

### What is the acceptance criteria for your support request?

There is an OptiBP calibration function integrated inside the WHO-ANC app for new mothers

**Comment by madrinekariuki** [comment]
Tested on Samsung A12 android 11
user demo


steps:

- install ANC and optiBP apks
- open ANC,register a client and start a contact.
- on the Bp measure select OptiBP
- calibrate the measurements (all 4)
- confirm data is sent back to ANC
- finish contact and sync data.
- wait one day and do contact 2. 
- confirm on contact 2 (<30 days). only one BP measurement is required by the optBP app (not all 4 steps)

observations:

- Both apps install successfully
- login on both was successful (on optiBP signed with email)
- 1st time calibration needed 4 steps and data was successfully sent to OptiBP app. (contact 1)
- taken measurements are correct.
- 2nd measurements BO is only taken once and data sent back to ANC app

**Comment by Naima-Bashir** [comment]
Closing this with client approval
