### ISSUE TITLE
[Ona Support Request]: Checkbox values are being displayed in sentence case in the summary

### ISSUE THREAD

**Issue by AngelaKabari** [opensrp/opensrp-client-anc#831]
### Affected App or Server Version

WHO-ANC Reference App

### What kind of support do you need?

Where there are checkboxes, the text values in the summary are being displayed in sentence case. For example in the contact form, one of the family planning options available is a Copper IUD. On the form, this checkbox option is displayed  as **Cu IUD**. However upon completing the contact, it is displayed on the summary as **Cu iud** which is medically inaccurate and could cause confusion for the health workers.

### What is the acceptance criteria for your support request?

The capitalisation on the contact summary should match that on the contact form.

**Comment by SebaMutuku** [comment]
This issue has been resolved.

**Comment by dubdabasoduba** [comment]
Is it using the translation fix on the app? The fix that shows that field text from the form?

**Comment by SebaMutuku** [comment]
@dubdabasoduba the team is not using any translations. The stuck with english and haven't added any translation changed.

**Comment by dubdabasoduba** [comment]
So how was this fixed?

**Comment by SebaMutuku** [comment]
They amended function keyToValueConverter and cleanValue under class ANCFormUtils to capitalize first and second words.We realized checkboxex array values go through that function.

**Comment by dubdabasoduba** [comment]
> They amended function keyToValueConverter and cleanValue under class ANCFormUtils to capitalize first and second words.We realized checkboxex array values go through that function.

But if they used the latest changes we have on native forms. These are the changes we have to add the translation work would they need a custom implementation?

**Comment by dubdabasoduba** [comment]
> > They amended function keyToValueConverter and cleanValue under class ANCFormUtils to capitalize first and second words.We realized checkboxex array values go through that function.
> 
> But if they used the latest changes we have on native forms. These are the changes we have to add the translation work would they need a custom implementation?

Correct me if I am wrong but the translation fix meant an update on the ANC module to use the form text on the summary displays. It would do this for all languages including the default language.

**Comment by SebaMutuku** [comment]
That is. However, a logic for words that weren't english i. medical words e.g calcium, haemoglobin still exists which was saving the key as the value, reading it and autocapitalizing it to be used at the text. However, like I mentioned the team ins't using the newly added translations native form and ANC

**Comment by AngelaKabari** [comment]
@tobiasmakai has [confirmed](https://opensrp.slack.com/archives/C02BJB1CCU8/p1654640445427229?thread_ts=1652802164.063479&cid=C02BJB1CCU8) that this has been resolved satisfactorily and can therefore be closed.
