### ISSUE TITLE
[Ona Support Request]: Subforms under diagnostic tests allow the user to proceed regardless of whether a required field is left blank

### ISSUE THREAD

**Issue by MwambaK** [opensrp/opensrp-client-anc#832]
### Affected App or Server Version

v1.6.8

### What kind of support do you need?

To be able to prevent the user from proceeding or saving data if a sub form has been opened but not all fields that are set as required have been filled.

### What is the acceptance criteria for your support request?

Sub forms preventing the user from proceeding if required field left blank.

**Comment by SebaMutuku** [comment]
Hi @MwambaK  would you please share a sample tests subform you are testing with?

**Comment by SebaMutuku** [comment]
@dubdabasoduba , after checking, all tests don't have a submit button. The button name is called Save button. The validate_on_submit works only on submit. The team wants to validate_on_save logic which I believe sits on NativeForm. Would you kindly guide what's the best way to handle this.

**Comment by dubdabasoduba** [comment]
> @dubdabasoduba , after checking, all tests don't have a submit button. The button name is called Save button. The validate_on_submit works only on submit. The team wants to validate_on_save logic which I believe sits on NativeForm. Would you kindly guide what's the best way to handle this.

Save and submit are using the same form technology. So validation should work the same on the sub forms as on the main forms. 

Have you tested that validation fails on all subforms? If yes then that's a bug that needs to be fixed

**Comment by SebaMutuku** [comment]
Not all subforms. But allow me to see.

**Comment by SebaMutuku** [comment]
@dubdabasoduba it happens on all forms and also on older versions of native form. Seems it's an existing issue

**Comment by dubdabasoduba** [comment]
> @dubdabasoduba it happens on all forms and also on older versions of native form. Seems it's an existing issue

Please troubleshoot why this does not trigger the validation for the subform. It should use the same validation method used by the main form.

**Comment by SebaMutuku** [comment]
Hi @MwambaK follow these details to test the subforms issue on your end.
1. Use Native form version 2.1.18-PREVIEW-SNAPSHOT
2. Add validate_on_submit:true property on all forms
3. Add err messages to keys that don't have error messages. See the PR

**Comment by AngelaKabari** [comment]
@MwambaK has confirmed that this issue has been [satisfactorily resolved](https://opensrp.slack.com/archives/C02BJB1CCU8/p1653929356332629?thread_ts=1652783805.215389&cid=C02BJB1CCU8).
