### ISSUE TITLE
Pre-populating data

### ISSUE THREAD

**Issue by joyce-x-chen** [opensrp/opensrp-client-anc#833]
SID is having trouble pre-populating data for client contacts. Context:

> I'm writing this email to ask two questions to the ONA team related to pre-populating the data on the client app. Since the app can only record visits from the first contact, Ben suggested we pre-populate the data first for mothers who come to the clinic for their second contact onwards. However, this will cause the date of actual contact and the date of contact recorded in the app to become different. The app also doesn't allow data entry for more than once a day for the same mother. 
> 
> As SID is planning to recruit mothers in the 2nd and 3rd trimesters to the study and record their contacts into the client app, we might need to create some changes in the local app to support pre-populating data, such as a specific question asking for the client's (actual) date of contact and allowing consecutive data entry. 
> 
> Therefore what I would like to ask are:
> 
> 1. What functions/features of the app will be affected/depended on the date of contact? An example that I notice is the expected date for future contacts and gestational age during contact
> 
> 2. What are the processes that need to be followed to make this change happen? 

They are following @dubdabasoduba's instructions:

> 1. Log in to the app as a certain user. Preferably the users on the teams you intend to use
> 2. Sync all the data you need on the app and log out.
> 3. Disable all your internet connections i.e mobile data and wifi
> 4. Change your device date to the contact was done.  
> 5. Log in to the app.
> 6. Record the contact on the said date.
> 7. Logout and then update your device date to the correct date.
> 8. Sync the app to make sure the new records are pushed to the server. 

However, Elwina is getting stuck on step 5. Even after enabling WiFi again, the app continues to display the following error message when attempting to log back in: 
"No internet connection. Please ensure data connectivity." 

Please see attached recording:
https://user-images.githubusercontent.com/81920452/169262181-5ccadf15-0306-4cc3-955a-0cdefe4d0776.mp4

**Build**: 1.6.15 apk ver (built 31 Mar 2022)
**Device**: Samsung A21s device 

@madrinekariuki can you please check if this can be replicated? Thank you

**Comment by madrinekariuki** [comment]
@joyce-x-chen 
tested this on `1.6.15 apk ver`
user : `demo`

steps:
- followed the steps highlighted [here](https://github.com/opensrp/opensrp-client-anc/issues/833#issue-1241496252)
- nb// used an emulated device Android Version 10. due t errors installing on a physical device.
    if you use the emulated device switch off data and wifi from both the laptop and the device 

Observation:

- One cannot  log back into the app without internet. 
- there are challenges installing the apk on various android versions 

screenshot
![image](https://user-images.githubusercontent.com/84722169/169299592-26cbc466-4efa-4991-8836-a1dfbe4cef9e.png)

**Comment by dubdabasoduba** [comment]
@SebaMutuku @junaidwarsivd  Please change the `true` in these lines to `false` https://github.com/opensrp/opensrp-client-anc/blob/8e1d921621ee70f1c52acc9a463c2377e4b7399c/reference-app/src/main/java/org/smartregister/anc/application/AncApplication.java#L190-L202 then perform the following actions. 

1. Uninstall any current app. 
2. Build and install a new one with the change. 
3. Log in to the app as a certain user.
4. Sync all the data you need on the app and log out.
5. Disable all your internet connections i.e mobile data and wifi
6. Change your device date to the contact was done.
7. Log in to the app while offline.

If the login works then bundle an APK for @madrinekariuki to test. If it still passes QA then we can share the same change to the SID team. 

**NB:-** This must be changed back to `true` after prepopulation. We do not want users adding backdated data.

**Comment by madrinekariuki** [comment]
@dubdabasoduba @SebaMutuku @joyce-x-chen 
This has been Retested  on the new release `reference-app-release-changedtimezone` shared [here](https://onaio.slack.com/archives/CETQ18XL3/p1653032593538629?thread_ts=1652952986.194319&cid=CETQ18XL3)
user: `demo`
device: Samsung A12 android 11

Steps:
- Followed the steps shared [here](https://github.com/opensrp/opensrp-client-anc/issues/833#issue-1241496252)
- Changed the device date to 04/01/2022 and registered client `Alex Rose `and did a first contact, changed the date back to current date, logged in and synced data, searched for the client and it shows their contact 2 should be on 27th May.

- synced data and logged out again and switched off data and wifi.
- Changed the device date to 19/02/2022 registered client` Ruchi Ana` and did first contact, changed the date back to current date, logged in and synced data, searched for the client and it shows they are due for contact 2 on 16/04/2022. I recorded contact 2 for `Ruchi Ana` successfully.

Observations:
- One is able to login back to the app when the date has been manually changed and record a contact and log out.
- When you switch on the internet with the backdated date you are unable to sync as the connection to internet shows connected but you cannot access internet. you have to change date to the correct one.
- when you change the date to the correct date, one can sync data, and record contact 2 (or next scheduled contact) 

Screenshots:
![image](https://user-images.githubusercontent.com/84722169/169492034-865b19d7-2b40-475b-8aed-1781ff3fd927.png)

**Comment by dubdabasoduba** [comment]
@madrinekariuki the keycloak and opensrp server will reject syncing with a backdated date. The security certificates view that as a security breach. 

Changing your date to the correct one is the right thing to do.

**Comment by elwinameylentia** [comment]
this particular issue is closed, but it triggered another issue https://github.com/opensrp/opensrp-client-anc/issues/839
