### ISSUE TITLE
[Bug Report]: DOB age not calculating at first time when DOB is Selected

### ISSUE THREAD

**Issue by junaidwarsivd** [opensrp/opensrp-client-anc#837]
### How do we replicate the bug?

on register new user the DOB age is not calculating when its selected on first time i.e (Age : 20 yrs)

### How is this feature expected to work?

Age should calculate whenever the DoB or date is selected on register

**Comment by dubdabasoduba** [comment]
@junaidwarsivd please add the appropriate title for this
