### ISSUE TITLE
[Ona Support Request]: Profile form not completed on second visit onwards

### ISSUE THREAD

**Issue by elwinameylentia** [opensrp/opensrp-client-anc#840]
### Affected App or Server Version

Indonesia local apk

### What kind of support do you need?

The profile form is supposed to already be completed with no empty fields on the client's second visit. However although all fields have been filled in, the profile box/container doesn't have a checkmark and showed that there are still empty fields. The user has to manually go through all the pages for the form to be completed. 

Attached is a screen recording of the issue.

https://user-images.githubusercontent.com/93704986/170233326-0128f3f6-5fa6-4172-975d-aab8df41cad4.mp4

Please help check and debug our source code.

### What is the acceptance criteria for your support request?

The profile form can be completed with no empty fields from the client's second visit onwards.

**Comment by AngelaKabari** [comment]
@elwinameylentia could you grant @SebaMutuku access to your repository or share your local apk so that we can try to replicate this issue and thereafter provide guidance on how to resolve this issue?

**Comment by SebaMutuku** [comment]
@elwinameylentia advise your team to check the following classes
ContactWizardJsonFormFragment
ContactJsonFormActivity
to see which form is showing as incomplete
