### ISSUE TITLE
Misaligned values

### ISSUE THREAD

**Issue by madrinekariuki** [opensrp/opensrp-client-anc#846]
### How do we replicate the bug?

@SebaMutuku @AngelaKabari 
Steps:

- login to the app and start a contact
- ensure to put values e.g HIV +ve,syphillis +ve,RH factor -ve , ASB infection,tobacco user
- complete the contact and save
- click on overview and scroll to RISKS AND DIAGNOSES
- observe how the values of the items above are placed in a wrong place. Key and Value on the same place e.g HIV Positive and then full colon after the name.

### How is this feature expected to work?

We should have the Key and the value, separated by the full colon. e.g` HIV : POSITIVE  `instead of `HIV POSITIVE :`

### Please Share other relevant information about the bug

Screenshot
![image](https://user-images.githubusercontent.com/84722169/171180849-add61700-cd6c-46d1-b422-46337ff832af.png)

**Comment by Naima-Bashir** [comment]
I have tested this on the latest apk and the misaligned values aren't there. I will close this ticket and open it incase it reappears
