### ISSUE TITLE
[Ona Support Request]: ANC peer to peer module cannot get the MAC address of devices using android 11

### ISSUE THREAD

**Issue by MwambaK** [opensrp/opensrp-client-anc#847]
### Affected App or Server Version

v.1.6.8

### What kind of support do you need?

To be able to obtain the MAC address from android 11 tablets as this is a necessity for peer to peer sending of data, please not the devices can receive regardless of the android version but cannot send.

### What is the acceptance criteria for your support request?

To be able to send records using the peer to peer sync module on android 11.

**Comment by dubdabasoduba** [comment]
https://developer.android.com/about/versions/11/migration

**Comment by madrinekariuki** [comment]
tested using user `demo`
devices: Redmi Android version 10
               Samsung android version 11

Test steps:

- Login to the apk on both devices.
- sync data on both devices.
- Make a change(s) on one device. (used android 11)
- Switch bluetooth on for both devices and for wifi, forget the current connection  and switch off wifi
- Go to the me section on the bottom right of the app and click on it.
- click on Device-to-device sync.
- observe the sync progress till it shows Transfer successful.
- observe the phone that was receiving data if all the data has been transferred successfully.
- confirm that the data that was being transferred has reflected correctly on the other device.

observation:
- Data transfer via device to device was successful. 
- Noted item on [this](https://onaio.slack.com/archives/C0E2558SH/p1654863370788619) shared apk , that there is no option of recording BP .

**Comment by SebaMutuku** [comment]
HI @MwambaK. A new version of P2P sync has been updated to work with android 11 and 12. The new snapshot version is 0.3.9-SNAPSHOT 
The changes made are available on this PRs
https://github.com/opensrp/android-p2p-sync/pull/85/files
https://github.com/opensrp/opensrp-client-anc/pull/853
