### ISSUE TITLE
[Ona Support Request]: Syncing of partial contacts

### ISSUE THREAD

**Issue by MwambaK** [opensrp/opensrp-client-anc#848]
### Affected App or Server Version

v1.6.8

### What kind of support do you need?

To sync partial contact information and be able to show when synced using peer to peer that a contact is in progress.

### What is the acceptance criteria for your support request?

To be able to sync a partial contact and get information regarding a contact before it is fully completed (e.g. if a user fills in information under profile and physical exams only and saves that information, if synced using peer to peer, that information should be reflected on the receiving tablet and also show it is in progress).

**Comment by Naima-Bashir** [comment]
Waiting to see how Option 1 will go, will remain open for now

**Comment by dubdabasoduba** [comment]
https://docs.google.com/document/d/1PT6Co4Z6Xu2gdLa7Rovri7iQdRUfXLrBU-f7QWWHZug/edit?usp=sharing Closing this because it's not part of the options here.
