### ISSUE TITLE
[Ona Support Request]: How to modify population characteristics using web opensrp

### ISSUE THREAD

**Issue by elwinameylentia** [opensrp/opensrp-client-anc#851]
### Affected App or Server Version

Indonesia local apk

### What kind of support do you need?

SID team needs support on changing population characteristics of users assigned to a location

### What is the acceptance criteria for your support request?

Users assigned to the same location will have the same population characteristics, while users assigned to different locations might have different population characteristics

**Comment by SebaMutuku** [comment]
@elwinameylentia site characteristics are modified from a file called `site_characteristics.json` on` WHO ANC App` files not on `opensr-web`

**Comment by SIDyuni** [comment]
> https://docs.google.com/document/d/1oGY44I0_wMxLXYX_H2fGIjeHu1o6Kzp8/edit?usp=sharing&ouid=101387221137364839003&rtpof=true&sd=true @elwinameylentia Please go through this docuementation

Hi, request access to this file.

**Comment by SebaMutuku** [comment]
@SIDyuni  please share your email on slack `#slab-partners` channel. Also, see my last comment up there. In case on any queries feel free to request for a pairing session

**Comment by Naima-Bashir** [comment]
Closing this with client approval
