### ISSUE TITLE
[Bug Report]: Translation to Portuguese

### ISSUE THREAD

**Issue by AngelaKabari** [opensrp/opensrp-client-anc#855]
### How do we replicate the bug?

1. Install the apk and log in
2. Change the language to Portuguese. (click on the icon at the bottom right of the app to access the settings)
3. Try to register a new client.
4. Some questions still remain untranslated, as well as all the informations available on the info icons. See screenshots below 
![Screenshot_20220622-143557_WHO ANC](https://user-images.githubusercontent.com/8417097/175020628-340b3f9a-5bf0-494b-8463-a14055028dfb.jpg)
![Screenshot_20220622-143629_WHO ANC](https://user-images.githubusercontent.com/8417097/175020607-063d9c48-b371-4c9e-b1bb-b6088b78577b.jpg)
![Screenshot_20220622-144756_WHO ANC](https://user-images.githubusercontent.com/8417097/175022124-9889ea21-724a-472c-887e-d8d709d2e3f1.jpg)

### How is this feature expected to work?

All the app prompts and content should be translated to the language chosen in the app settings

**Comment by SebaMutuku** [comment]
@AngelaKabari ,
this will need full app translation just like we did for teams like SID and Rwanda.
We will also need to have all widgets of checkboxes, native buttons and spinners json files amended to match the translation code.

**Comment by madrinekariuki** [comment]
@SebaMutuku @AngelaKabari 

We still have data not transalating to portuguese when you switch the app language to portuguese. 
see below screenshot on the `planned birth place `

- observe how the whole page is in english yet the app's language is switched to english.

this was observed when testing #877
![image](https://user-images.githubusercontent.com/84722169/187668039-b6595d9e-064b-4b3f-8ff4-0c1e0444dd98.png)

**Comment by AngelaKabari** [comment]
Thanks for this @madrinekariuki  - once we receive the Portuguese translation files from Unicamp, we shall look into it and see if this page has been fully translated. 

Did you note any other instances of this while undertaking your QA?

**Comment by AngelaKabari** [comment]
In the **Symptoms and Follow-up Container**, for the '_Maternal perception of fetal movement_' question, ensure that the Portuguese translation of the first option (_Normal fetal movement_) reads "**_Movimento fetal normal_**" and NOT "_Sem movimento fetal_"

**Comment by madrinekariuki** [comment]
@AngelaKabari Yes there were a couple of instances I shall compile and share

**Comment by madrinekariuki** [comment]
@AngelaKabari @Naima-Bashir 
Another noted translation issue on the profile page -> Immunisation. 
when the app is changed to Portuguese, some tests are not changing to Portuguese. 
`apk reference-app-brazil-v1.6.15.apk`

see below screenshot
![image](https://user-images.githubusercontent.com/84722169/189597000-8dfeb428-cf63-49e1-ae00-bc014f639ec6.png)

**Comment by SebaMutuku** [comment]
@AngelaKabari @Naima-Bashir have we received translated files from Brazil team?

**Comment by AngelaKabari** [comment]
@SebaMutuku not that I have seen. @Naima-Bashir will follow up to get these.

**Comment by Naima-Bashir** [comment]
Closing this for now. We shall reopen if the client still needs support

**Comment by Naima-Bashir** [comment]
Samira has finished translating the ANC module into Portuguese. Ona shall generate a new apk with the complete translations, perform QA and send it to the her.
