### ISSUE TITLE
[Ona Support Request]: Increasing the speed of the application

### ISSUE THREAD

**Issue by MwambaK** [opensrp/opensrp-client-anc#857]
### Affected App or Server Version

v.1.6.8

### What kind of support do you need?

To be able to have the app run faster as the time taken to load certain forms after more information and calculations have been added is taking too long (e.g obstetric history).

### What is the acceptance criteria for your support request?

To have the app run faster on devices with low RAM (e.g 2gb ).

**Comment by dubdabasoduba** [comment]
@MwambaK Please share the forms and relevant files then we can test from our side.

**Comment by MwambaK** [comment]
[Relevant files.zip](https://github.com/opensrp/opensrp-client-anc/files/9038123/Relevant.files.zip)

**Comment by neric1** [comment]
Here in Rwanda, we have faced this problem too.

**Comment by AngelaKabari** [comment]
> 

Noted that this issue is also occurring for the Rwanda team @neric1. Please share the forms forms that are slow, an APK, along with the relevance and calculation yml files tso that we replicate and try to address it from our side.

**Comment by hamza-vd** [comment]
@neric1 please share the latest repository which has this issue for us to replicate this

**Comment by junaidwarsivd** [comment]
@AngelaKabari  @MwambaK  is the link of the repository already shared  for this issue ?

**Comment by AngelaKabari** [comment]
> @AngelaKabari @MwambaK is the link of the repository already shared for this issue ?

Yes, access to the repo had been granted to Hamza and Seb. Let me ask @MwambaK  and @neric1 to add you as well.

**Comment by madrinekariuki** [comment]
@junaidwarsivd 
test device: Samsung A12 android 11
user: `anc`
apk : `zambia-reference-app-v1.0.0.apk
`

Test findings:
- the app is Crashing at `Physical Exam ->fetal assessment` and one can't proceed
- Some instances are still slow eg. on Client profile when moving from` Current pregnancy to obstetric history`
- Note I could not proceed with the contact from Physical Exam as the app is crashing so I am yet to complete testing the other containers if they are still slow

**Comment by madrinekariuki** [comment]
@junaidwarsivd
test device: Samsung A20 android 9
user: anc
apk : reference-app-zambia-fix.apk

Test findings:

- The app performance has improved and It is no longer slow
- The performance of the transition from  Current pregnancy to obstetric history has also improved. 
- The app is no longer crashing
