### ISSUE TITLE
Add maximum and minimum dates to DOB under search page

### ISSUE THREAD

**Issue by SebaMutuku** [opensrp/opensrp-client-anc#860]
### How do we replicate the bug?

- Log in to ANC APP.
- Under bottom top page click on Search tab
- Scroll down to search by dob , edit text and click on it.
- You will observe you can choose search by today's date or any date more than 100 years ago

### How is this feature expected to work?

Set maximum date to same date as today 49 years ago
Set minimum search date to today 10 years ago

**Comment by madrinekariuki** [comment]
Tested on 
Android` 11 Samsung A12`
user `demo`

Steps:
Followed the steps highlighted [here](https://github.com/opensrp/opensrp-client-anc/issues/860#issue-1292823193)

Observations:
- The DOB Max is  49 years ago from the date when you are testing
- The DOB  min is 10 years ago from the date when you are testing


Screenshot:
![image](https://user-images.githubusercontent.com/84722169/177533423-2738e07a-c319-456c-9474-8e2db87282b3.png)
