### ISSUE TITLE
Previous Steps JsonForms not loaded when you press previous or back button during contact visits

### ISSUE THREAD

**Issue by SebaMutuku** [opensrp/opensrp-client-anc#864]
### Affected App or Server Version

v1.6.8

### What kind of support do you need?

How to replicate the bug:
1. Start a contact 
2. Fill in Quick Check age and press proceed to Normal Contact
3. Click on profile page and fill in required fields and press next
4. Press previous button
5. You will notice the previous filled `JSON FORM` is not loaded.
6. Affected Native form version is `2.1.18-SNAPSHOT` and above

![image](https://user-images.githubusercontent.com/36365043/178928300-b0b35004-7fdd-40c7-b979-3779ac91fbca.png)

### What is the acceptance criteria for your support request?

To be able to see filled or skipped` previous steps json form` when one presses back or previous button on contact visit pages e.g Inside `Profile` page

**Comment by madrinekariuki** [comment]
@SebaMutuku @AngelaKabari 

This has been tested on: `reference-app-debug-native-buttons`
user: anc

Steps:

Followed the steps highlighted https://github.com/opensrp/opensrp-client-anc/issues/864#issue-1304388056

Observation:
- the previous page is showing data as expected. (This has passed QA)


concerns:
- The application is very slow
- on obstetric history, Number of previous pregnancies has been put on one page(so they are  many together) is this how it is supposed to be for this apk?... it is really tough trying to select one see screenshot below. 

![image](https://user-images.githubusercontent.com/84722169/179935331-25769514-d78a-4821-8740-6e7c458af371.png)

**Comment by SebaMutuku** [comment]
@MwambaK can you confirm this issue has been resolved and close the ticket from your end?
However, please note this comment from QA : https://github.com/opensrp/opensrp-client-anc/issues/864#issuecomment-1189984340

**Comment by MwambaK** [comment]
@madrinekariuki the issue with the UI is not a hindrance on the devices we have selected for testing, I will be closing this issue now.

**Comment by SebaMutuku** [comment]
@MwambaK you can close it.
