### ISSUE TITLE
User location is null on MeFragment and app crashes when a user clicks on the location button

### ISSUE THREAD

**Issue by SebaMutuku** [opensrp/opensrp-client-anc#869]
### Affected App or Server Version

v1.7.2

### What kind of support do you need?

Fix missing user assigned location and ensure app doesn't crash when the user is assigned a location.

### What is the acceptance criteria for your support request?

See user assigned location on me fragment.
App should not crash when one selects on user location

**Comment by madrinekariuki** [comment]
@SebaMutuku  cc @AngelaKabari 

test device:` samsung A12 android 11`

steps

- install and sync the apk
- click on 'me' section
- click on location


observation.
- the app is not crashing.
- the location being fetched is not the correct one. which location is the app supposed to take?.(Its currently showing `server_settings_are` and` facility_dev`) 

see screenshot below :
![image](https://user-images.githubusercontent.com/84722169/184376392-88a47dad-94d7-45f2-8127-38f7998a1af6.png)

**Comment by madrinekariuki** [comment]
The location showing server-settings   has been fixed. 
Current assigned location is `facility_dev` which is the assigned location to` ORGANISASI SID  `that is the team that the user `userbidan5 `belongs to. (This can be checked on web)
