### ISSUE TITLE
[Bug Report]: Tests container on Brazil app is slow and crashes

### ISSUE THREAD

**Issue by AngelaKabari** [opensrp/opensrp-client-anc#874]
### How do we replicate the bug?

The tests container is slow again. The app suddenly crashes a few times when using the tests container.

### How is this feature expected to work?

The questions in the test container should be responsive when clicked on

**Comment by madrinekariuki** [comment]
Tested on : Samsung A12 Android 11
User: Demo
apk reference-app-brazil-v1.6.14.apk

Test findings
The app is not Crashing, however the test container is still very slow.

**Comment by madrinekariuki** [comment]
Tested on : Samsung A12 Android 11
User: Demo
apk reference-app-brazil-v1.6.15.apk

Test Findings:
- The test containers are no longer slow and the App is not crashing

**Comment by Naima-Bashir** [comment]
Closing this. Awaiting client QA
