### ISSUE TITLE
[Bug Report]: Patient Contact Summary PDF is not stored on a folder accessible on a phone 

### ISSUE THREAD

**Issue by AngelaKabari** [opensrp/opensrp-client-anc#875]
### How do we replicate the bug?

The app is currently saving the Patient Contact Summary PDF to the system folder in the phone’s internal storage. This folder is not directly accessible on the phone file storage system. 

However, if you plug in the phone into a computer, you can find it if you look in the folder called "WHO ANC" which you can access by going into Android>>data>>org.smartregister.anc>>files>>WHO ANC>>contact summary data.pdf.

### How is this feature expected to work?

The Patient Contact Summary PDF should be accessible on a secure folder on the device that can be accessed without having to plug the phone into a computer.

**Comment by madrinekariuki** [comment]
@junaidwarsivd @AngelaKabari 
Tested on : Samsung A12 Android 11
User: Demo
apk reference-app-brazil-v1.6.14.apk

Test findings:
The Patient pdf file is being saved and can be accessed via the mobile phone.
see screenshot below:
![image](https://user-images.githubusercontent.com/84722169/187695716-4ddee773-e6c8-483e-a3f4-29dbe00d6bd4.png)

**Comment by Naima-Bashir** [comment]
[#876](https://github.com/opensrp/opensrp-client-anc/issues/876) - Tests container optional: the test container is only optional in English but not when the app language is changed to Portuguese.

**Comment by Naima-Bashir** [comment]
This has passed QA
