### ISSUE TITLE
[New Feature Request]: Make the Tests container optional

### ISSUE THREAD

**Issue by AngelaKabari** [opensrp/opensrp-client-anc#876]
### Feature Use Case

Make it possible to finalise a patient contact without opening or filling in the Tests container.

### Acceptance criteria

It should be possible to create a new patient contact and finalise it without opening or filling in the Tests container.

### Relevant Information

This is a country specific adaptation that has already been implemented for the ANC app version that will be used in Rwanda. Get the necessary code from the 1,000 Hills Git Repo and include it in the Brazil app then share an updated apk with Brazil.

**Comment by madrinekariuki** [comment]
@junaidwarsivd @AngelaKabari 

Tested on : `Samsung A12 Android 11`
User: `Demo`
apk `reference-app-brazil-v1.6.14.apk`


please see below test findings:
- The Test container can be omitted successfully when the app in English. (All test scenarios passed)

However when the apk is changed to Portuguese language, we have some test scenarios failing  see below

-  one cannot finalize (omit the tests container ) the contact if :
     a)  open the module close it (without filling any test) in pt
     b) open the tests module and you fill in one test and omit the rest. in pt

Tests run:
- Verify that one can omit the test module english and portuguese
- Verify that one can open and close the test module and omit it and finalize a contact english and portuguese
- Verify that one can open the test module, fill in one test, close the module and finalize the contact both in english and portuguese

**Comment by madrinekariuki** [comment]
Tested on : Samsung A12 Android 11
User: Demo
apk reference-app-brazil-v1.6.15.apk

Tests run:

- Verify that one can omit the test module english and portuguese
- Verify that one can open and close the test module and omit it and finalize a contact english and portuguese
- Verify that one can open the test module, fill in one test, close the module and finalize the contact both in english and portuguese


Test Findings:

- One can omit the test module and finalize the contact both in Portuguese and English
- One can open the test container and close it without filling any test and finalize the contact  both in Portuguese and English
- One can open the test container , fill in one test, exit and finalize the contact  both in Portuguese and English

**Comment by Naima-Bashir** [comment]
Closing this, awaiting client QA
