### ISSUE TITLE
[New Feature Request]: Change "Planned birth place" options

### ISSUE THREAD

**Issue by AngelaKabari** [opensrp/opensrp-client-anc#877]
### Feature Use Case

In the Counselling and Treatment container, change the Multiple Choice (select one) options for "Planned birth place" question from: 
1. Facility
2. Facility (elective C-section)
3. Home
4. Other

To a Multiple Choice (select one) with the following 3 options: 
1. Maternidade municipal; 
2. Hospital de referência; 
3. Outro (especifique).

### Acceptance criteria

In the Counselling and Treatment container, the Multiple Choice (select one) options for "Planned birth place" should be: 
1. Maternidade municipal; 
2. Hospital de referência; 
3. Outro (especifique).

If option 3, "other" is selected then a text box should be provided to type in a response.

**Comment by dubdabasoduba** [comment]
@AngelaKabari Please update the Data dictionaries for all the content changes.

**Comment by AngelaKabari** [comment]
Will do @dubdabasoduba. @Naima-Bashir and I have put time aside next week to do this.

**Comment by AngelaKabari** [comment]
Hello,

**Comment by AngelaKabari** [comment]
@junaidwarsivd as discussed earlier today, please use the below translations for the "Planned birth place" options, then we'll have the Portuguese equivalents in the Brazil translated version of the app:
1. Maternidade municipal - Municipal maternity hospital;
2. Hospital de referência - Referral hospital;
3. Outro (especifique) - Other (specify).

**Comment by madrinekariuki** [comment]
@AngelaKabari @junaidwarsivd :
Tested on : `Samsung A12 Android 11`
User: `Demo`

Test observations:
- The planned birth place options have been updated. However the options only appear in English. even when the app's language has been set to Portuguese. 
- This will be raised under translation ticket. This item has passed QA

screenshot.
![image](https://user-images.githubusercontent.com/84722169/187667186-036839ab-23a9-472d-a6ed-8adee9cd2796.png)

**Comment by Naima-Bashir** [comment]
Closing this unless stated otherwise
