### ISSUE TITLE
[New Feature Request]: Update the Partial Contacts to save the Practitioner Details.

### ISSUE THREAD

**Issue by dubdabasoduba** [opensrp/opensrp-client-anc#878]
### Feature Use Case

- We have a use case where multiple practitioners will be responsible for filling out the contact forms.  
- Based on this we would need to know who filled out each form.  
- We can do this by saving the practitioner details on the partial forms. The details in question are `Practitioner Id`, `Practitioner Username`, `Team Id & name` & the `Location Id`
- We will then use these details when processing the partial forms to events.

Test Steps
- Check that a partial contact has a practitioner array with practitioner details (table to check -> `partial_contacts`)
- check  the event generated when completing a contact has the same provider ID, Team ID and team location as partial contact. table to check -> `event_table`
- 

### Acceptance criteria

- [ ] All partial contacts should have an attribute called `practitionerDetails`. This will hold the details mentioned above. 
- [ ] All the contact events should have the same practitioners as those on the partial forms.

**Comment by SebaMutuku** [comment]
- [ Addition of userId in client core]
- [Update Event Class on Client Core to have PractitionerDetails]

**Comment by madrinekariuki** [comment]
@SebaMutuku  cc @Naima-Bashir 
apk `reference-app-release-partial-contacts.apk`
users `demo` and `demo2`

Steps:

have 2 users.

- Open android studio and install the apk. 
- login with one of the users
- sync data. 
- register a client and do a partial contact (fill in some modules and save changes)
- sync data
- download the DB 
- open the db and go to the partial contacts table. 
- confirm it shows the module you are at.
- copy the data on form_json and open it in a json formatter 
- scroll down to the provider/practioner details and confirm they are there i.e `providerBaseEntityId`,`providerId`,`teamId`,`team`,`locationId` and take note of them.
- for partial contact, log out and login with the other user and you will observe the partial contact written contact 1 in progress.
- When you check open the provider/practitioner details it shall be details of the previous user .**AND**  in case you make any changes to the contact e.g fill in another module or complete the contact, the provider details i.e `providerBaseEntityId, providerId ` will change to that of the most recent user to add data in the contact
- complete the contact and save data.
- open the DB
- For **Event** Check  the event generated when after completing a contact has the same provider ID, Team ID and team location as partial contact. table to check -> event_table search the client by BaseEntityId (you can get this from ec_clients table). 


Observation. 

- partial contact show the correct details i.e according the the user who has made changes to the contact
- partial contacts for multiple clients also show. (you can do artial contacts for like 2 or more clients)
- once a contact is complete partial_contact table gets updated. (partial) data is removed from this table.
-There is no Event created when a client contact is not complete  partial should this be the case?.
- @seb what are the conditions to have an event generated?.. should one have to complete a contact?
- in the event, details of` provider ID, Team ID` and `team location` are the same as those of the partial contact

items to address/clarify:
-There is no Event created when a client contact is not complete i.e partial should this be the case?.
- @SebaMutuku  what are the conditions to have an event generated?.. should one have to complete a contact?
- user **cannot** add a new client to this apk. (thus this has been tested with old data)

**Comment by SebaMutuku** [comment]
@madrinekariuki ,as for the apk not creating client, I have shared another apk which works well.

Find below answers to your questions:
1.once a contact is complete partial_contact table gets updated. (partial) data is removed from this table.
-There is no Event created when a client contact is not complete partial should this be the case?.
@seb what are the conditions to have an event generated?.. should one have to complete a contact?-> `Partial Contacts are not Synced from client app to opensrp web (ANC Architecture) hence no event for Partial contact is generated.`

2. `The event generated is for a complete contact which can be found in event table on drisht database. In this table, there exists event jsons for each contact container.`
cc @dubdabasoduba

**Comment by madrinekariuki** [comment]
@SebaMutuku  cc @dubdabasoduba 

see below test findings from the shared apk with the fix. 

steps:
followed steps mentioned above.

observations:
- partial contact show the correct details  according to the user who has made changes to the contact (screenshot below)
- once a contact is complete partial_contact table gets updated and an event is generated. 
- in the event, details of `provider ID`, `Team ID` and `team location` are the same as those of the partial contact.
- events generated from an old client are different from those of new clients there some values missing. e.g `_rev`,`obs`, `identifiers`,`serverVersion` . (screenshots below) @SebaMutuku adviced these are not mandatory values. 
- important to note that partial contact is only possible in one device not multiple devices.


partial contact screenshot 
![image](https://user-images.githubusercontent.com/84722169/192719706-735de2fc-23c4-44cf-89cc-54fdd055a683.png)

event screenshot
![image](https://user-images.githubusercontent.com/84722169/192720741-cfa21b1b-1974-4593-be8d-955d262cab8a.png)

**Comment by Naima-Bashir** [comment]
Apk was shared with the Bluecode team on September 28th. Awaiting client QA

**Comment by Naima-Bashir** [comment]
@tobiasmakai can we close this issue? has it passed QA from your end?

**Comment by Naima-Bashir** [comment]
Closing this after getting the go ahead from the client
