### ISSUE TITLE
[Bug Report]: Change the COVID Immunisation Status label

### ISSUE THREAD

**Issue by AngelaKabari** [opensrp/opensrp-client-anc#880]
### How do we replicate the bug?

COVID Immunisation Status - The label currently reads “Woman is immunised against flu!”

### How is this feature expected to work?

Change the Covid Immunisation Status label “Woman is immunised against flu!” into “Woman is immunised against COVID!”. Correct this and amend the entry in the Supplemental file for the Brazil Data Dictionary.

**Comment by madrinekariuki** [comment]
@AngelaKabari @junaidwarsivd 
Tested on : ` Samsung A12 Android 11`
User: `Demo`

Test observations:

@junaidwarsivd The covid status label has updated. see screenshot  below. 

However @AngelaKabari @Naima-Bashir  we have the `DTPa` immunisation status  label reading as` woman is fully immunised against tetanus.` should it be tetanus or DTPa? (screenshot attached.)

![image](https://user-images.githubusercontent.com/84722169/187652184-82c89215-b105-4f81-986a-546f917cfebc.png)

**Comment by Naima-Bashir** [comment]
Closing this unless stated otherwise
