### ISSUE TITLE
Radio buttons not updating on some forms

### ISSUE THREAD

**Issue by madrinekariuki** [opensrp/opensrp-client-anc#883]
### How do we replicate the bug?

@SebaMutuku  cc @AngelaKabari 
test device: samsung A12 android 11
app:[ reference-app-release-location_issues.apk](https://onaio.slack.com/archives/C0E2558SH/p1660303459232079)

Steps:

- login to the apk
- sync data.
- click on me on bottom right
- open site characteristics
- click on edit and edit the buttons and click on save.
- confirm that the form updates accordingly.
- 

Current observations:
when you click on edit and change some answers on the questions, you will observe that after saving the data is not changing.

### How is this feature expected to work?

Radio buttons on the forms should update according

**Comment by AngelaKabari** [comment]
Re-opening this issue as we found it was still present when resolving issue [#849](https://github.com/opensrp/opensrp-client-anc/issues/849) on site characteristics.

`when you click on edit and change some answers on the questions, you will observe that after saving the data is not changing.`

@SebaMutuku will address this bug when working on issue [#845](https://github.com/opensrp/opensrp-client-anc/issues/845)

**Comment by madrinekariuki** [comment]
How do we replicate the bug?
@junaidwarsivd cc @AngelaKabari
test device: samsung A12 android 11
app: `reference-app-optibp-v1.6.16.apk`

Steps:

- login to the apk
- sync data.
- click on me on bottom right
- open site characteristics
- click on edit and edit the buttons and click on save.
- confirm that the form updates accordingly.


Observations:
Radio buttons on this form  are updating accordingly and correctly
