### ISSUE TITLE
Unresolved : Unable to login to OPENSRP WEB

### ISSUE THREAD

**Issue by chobela** [opensrp/opensrp-client-anc#884]
### Affected App or Server Version

Server server web version : opensrp-server-web:v2.8.31-SNAPSHOT | opensrp web version : web:v1.1.16

### What kind of support do you need?

We need a pairing session that can help us to login to OPENSRP WEB. WEB Freezes each time we try to login.

Here is the unresolved issue : https://github.com/opensrp/opensrp-client-anc/issues/867

The following error is what we get when WEB times out : 2022/08/24 08:16:21 [error] 639706#639706: *157 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 41.90.39.209, server: web.ecap.bluecodeltd.com, request: "GET /oauth/callback/OpenSRP/?state=opensrp&session_state=549e4e54-b2ce-43c3-87a3-19e23d9f2517&code=793641db-b2a2-41bc-8f68-399a3bd7ccfa.549e4e54-b2ce-43c3-87a3-19e23d9f2517.16cc9665-fe2f-49f8-a862-39491a519c14 HTTP/1.1", upstream: "http://127.0.0.1:3000/oauth/callback/OpenSRP/?state=opensrp&session_state=549e4e54-b2ce-43c3-87a3-19e23d9f2517&code=793641db-b2a2-41bc-8f68-399a3bd7ccfa.549e4e54-b2ce-43c3-87a3-19e23d9f2517.16cc9665-fe2f-49f8-a862-39491a519c14", host: "web.ecap.bluecodeltd.com"
(END)

### What is the acceptance criteria for your support request?

All Containers should be running successfully. You Should be able to login to keycloak and create users from keycloak

### Relevant Information

The exact same docker-compose file works perfectly on our other server. We have not removed or added anything to the docker compose file, exept changing the keycloak secret and URLs

**Comment by dubdabasoduba** [comment]
@machariamuguku Please review this

**Comment by machariamuguku** [comment]
closed in favour of this https://github.com/opensrp/web/issues/1067
