### ISSUE TITLE
[Ona Support Request]: Contact details showing the translation keys instead of the literal strings

### ISSUE THREAD

**Issue by dubdabasoduba** [opensrp/opensrp-client-anc#886]
### Affected App or Server Version

v1.6.14

### What kind of support do you need?

Contact details does not display real values. It displays keys from property files.
![image](https://user-images.githubusercontent.com/8068177/190184555-0f439c6c-ff11-47d8-88b7-e2a7891ff806.png)

### What is the acceptance criteria for your support request?

To add the described functionalities in the app working with the docker server.

### Relevant Information

The apk can be found here.
https://github.com/dodosi/opensrp_rw/releases

**Comment by Naima-Bashir** [comment]
Similar to this https://github.com/opensrp/opensrp-client-anc/issues/772

**Comment by Naima-Bashir** [comment]
The Tech Partners to update their repos to match Ona's mater repo.

**Comment by Naima-Bashir** [comment]
Raised by 1000 Hills

**Comment by Naima-Bashir** [comment]
Pairing session was held, a small fix on the code was suggested.

**Comment by Naima-Bashir** [comment]
Issue has been solved by the 1000 Hills team
