### ISSUE TITLE
Average weight gain under contacts keeps showing Zero, while the correct amount of weight gain shows in overview

### ISSUE THREAD

**Issue by madrinekariuki** [opensrp/opensrp-client-anc#894]
### How do we replicate the bug?

Apk: `reference-app-release_android_11_12.apk`
user: `demo`

steps:

- login to the app and add a client
- fill in a contact
- go to  overview page observe `the total weight gain in pregnancy` show the real weight gain e.g 6
- click on contacts tab, `observe the average weight gain per week since last contact` observe it is constantly showing zero

### How is this feature expected to work?

This should show a correct number instead of zero

**Comment by madrinekariuki** [comment]
#879

**Comment by dubdabasoduba** [comment]
This is the calculation definition. https://docs.google.com/spreadsheets/d/1Zh38B873ohVCbmO5R1sUn9OF2SMca4vP/edit#gid=1087871750&range=12:12

LOE is 2 days
