### ISSUE TITLE
missing tests on tasks tab

### ISSUE THREAD

**Issue by madrinekariuki** [opensrp/opensrp-client-anc#896]
### How do we replicate the bug?

Apk: `reference-app-release_android_11_12.apk`
user: `demo`

steps:

- login to the app and add a client
- fill in a contact
- under tests add ultrasound and Hep C as `ordered` or `not done`
- finalize the contact
- click on the tasks tab in overview
- observe that ultrasound does not show.

### How is this feature expected to work?

if tests has been put as ordered or done not, is should show under tasks tab in overview

**Comment by dubdabasoduba** [comment]
LOE 5 hours.

**Comment by dubdabasoduba** [comment]
@SebaMutuku @junaidwarsivd Please check the functionality to save `ordered` and `not done` tests on the contact_tasks table.
