### ISSUE TITLE
Missing Tests in test Container

### ISSUE THREAD

**Issue by madrinekariuki** [opensrp/opensrp-client-anc#897]
### How do we replicate the bug?

Apk: `reference-app-release_android_11_12.apk`
user: `demo`

steps:

login to the app and add a client
fill in a contact
under tests container observe how we have below missing tests` Hep C,partners HIV, taxoplasmosis, covid - 19`

### How is this feature expected to work?

under tests container, we should have all the tests present

**Comment by madrinekariuki** [comment]
bug raised for #879

**Comment by Naima-Bashir** [comment]
LoE: 5 hours

**Comment by dubdabasoduba** [comment]
This might be broken relevance logic.
