### ISSUE TITLE
one can only select one type of syphilis test

### ISSUE THREAD

**Issue by madrinekariuki** [opensrp/opensrp-client-anc#898]
### How do we replicate the bug?

Apk: `reference-app-release_android_11_12.apk`
user: `demo`

steps:

login to the app and add a client
fill in a contact
on the tests tab -> syphilis test click `done today` or `done earlier`
observe the syphilis test type  shows one can only select one syphilis test type

### How is this feature expected to work?

One should be able to select multiple syphilis test type

**Comment by madrinekariuki** [comment]
bug raised for #879

**Comment by dubdabasoduba** [comment]
Update the radio button to the checkbox as defined here. https://docs.google.com/spreadsheets/d/1Zh38B873ohVCbmO5R1sUn9OF2SMca4vP/edit#gid=1147849887&range=161:161 

The LOE is 1 hour
