### ISSUE TITLE
There's No prompt to refer the woman to a penicillin susceptibility test if Syphilis status is Positive (+ve).

### ISSUE THREAD

**Issue by madrinekariuki** [opensrp/opensrp-client-anc#899]
### How do we replicate the bug?

Apk: reference-app-release_android_11_12.apk
user: demo

steps:

- login to the app and add a client
- fill in a contact
- on the tests tab -> syphilis test click done today or done earlier
- select a syphilis test type
- selects test result as Positive
- observe there is no prompt that shows to refer the woman to a penicillin susceptibility test

### How is this feature expected to work?

If the woman's syphilis test is positive, there should be a prompt to refer the woman for a penicillin susceptibility test

**Comment by madrinekariuki** [comment]
bug raised for #879

**Comment by dubdabasoduba** [comment]
This is the toaster message to be shown https://docs.google.com/spreadsheets/d/1Zh38B873ohVCbmO5R1sUn9OF2SMca4vP/edit#gid=1147849887&range=189:189 

The LOE is 1 hour
