### ISSUE TITLE
Implement re-usable login module

### ISSUE THREAD

**Issue by ndegwamartin** [OpenSRP/opensrp-client-anc#9]
Discussions around implementing a plug and play module with login functionality that can be imported as part of a library and customized with minimal coding.

Would be later extended to include other reusable components

**Comment by ndegwamartin** [comment]
Discussions conclusion
   - To convert components to MVP which makes it easier to extend components easily
   - Move code to the OpenSRP client-core-library
   -  Extend core components and override any functions for custom - implementations specific functionality
Objective: To enforce minimal code duplication across OpenSRP implementations

**Comment by cafootitt** [comment]
this is done, closing
