### ISSUE TITLE
Hematocrit Values in Blood hemoglobin test, one can input up to 100 characters

### ISSUE THREAD

**Issue by madrinekariuki** [opensrp/opensrp-client-anc#900]
### How do we replicate the bug?

Apk:` reference-app-release_android_11_12.apk`
user: `demo`

steps:

login to the app and add a client
fill in a contact
on the tests tab -> blood hemoglobin test click done today or done earlier
on the test results observe you can input up to a 100 characters under hematocrit levels

### How is this feature expected to work?

There should be a defined value that is accepted for the hematocrit

**Comment by madrinekariuki** [comment]
bug raised for #879

**Comment by SebaMutuku** [comment]
@Naima-Bashir @dubdabasoduba  I do not see any limit on the number of characters to limit the above mentioned issue to. This is WRT Data dictionary. Kindly clarify.

**Comment by dubdabasoduba** [comment]
@Naima-Bashir Check in with WHO on the max value for the hematocrit levels. The Data Dictionary doesn't provide one. 

This would be a 1-hour fix if the change is just adding the min & max check.

**Comment by Naima-Bashir** [comment]
Moving this to ice- box non priority
