### ISSUE TITLE
[Ona Support Request]: Gradle sync error with kt3k plugin:2.10.2.

### ISSUE THREAD

**Issue by MwambaK** [opensrp/opensrp-client-anc#904]
### Affected App or Server Version

v.1.6.8

### What kind of support do you need?

We need to be able to sync project with gradle files and resolve the following error:
Gradle sync failed: Could not find gradle.plugin.org.kt3k.gradle.plugin:coveralls-gradle-plugin:2.10.2.

### What is the acceptance criteria for your support request?

Ability to sync gradle files

**Comment by neric1** [comment]
Me too I faced this issue when I missed this line  `maven{  url 'https://plugins.gradle.org/m2/' }` in build.gradle file but after adding it is now solved. 

![errorsolved](https://user-images.githubusercontent.com/91191732/193098707-0bc1880b-d66d-41fa-9281-ff17461973aa.PNG)

**Comment by Naima-Bashir** [comment]
Can we close this @neric1 @MwambaK ? Has this been solved?

**Comment by Naima-Bashir** [comment]
@neric1 @MwambaK any updates?
