### ISSUE TITLE
[Ona Support Request]: Empty fields retrieved using SQL Query

### ISSUE THREAD

**Issue by alfiraratnamalinda** [opensrp/opensrp-client-anc#906]
### Affected App or Server Version

v1.6.14 App

### What kind of support do you need?

When we tested using Bunda App Training Scenario, so far we have identified certain fields are empty when retrieved using SQL Query in which after further investigation, the affected fields were not persisted in the local storage of the Android device when the form was filled in (before sync to the server), list of empty fields are including (but not limited to):

For event "**ANC Registration**", the empty formSubmissionField are:
[
  "reminders"
]

For "**Quick Check**", the empty formSubmissionField are:
[
  "contact_reason"
]

For "**Profile**", the empty formSubmissionField are:
[
  "educ_level",
  "marital_status",
  "lmp_known",
  "ultrasound_done",
  "lmp_gest_age_selection",
  "last_live_birth_preterm",
  "covid_vaccine_status",
  "tt_immun_status",
  "tobacco_user",
  "shs_exposure",
  "condom_use",
  "alcohol_substance_enquiry",
  "partner_hiv_status"
]

For "**Physical Exam**", the empty formSubmissionField are:
[
  "pallor",
  "respiratory_exam",
  "cardiac_exam",
  "breast_exam",
  "abdominal_exam",
  "pelvic_exam",
  "cervical_exam",
  "oedema",
  "sfh_measurement",
  "fetal_heartbeat"
]

For "**Counselling and Treatment**", the empty formSubmissionField are:
[
  "caffeine_counsel",
  "eat_exercise_counsel",
  "danger_signs_counsel",
  "anc_contact_counsel",
  "birth_prep_counsel",
  "delivery_place",
  "family_planning_counsel",
  "family_planning_type",
  "ifa_low_prev_prescribe_daily_dose",
  "calcium_supp",
  "vita_supp"
]

Demo video of this issue:
https://drive.google.com/file/d/1-k_yTZBYEevCvscYhYl9fCnAfjSV4cHJ/view?usp=sharing

### What is the acceptance criteria for your support request?

All fields should present value instead of null_value during retrieval of data from server.

**Comment by Naima-Bashir** [comment]
In the registration page, the radio buttons do not update after one selects an option

**Comment by Naima-Bashir** [comment]
@madrinekariuki to test it on our apk first to determine if it breaks.

**Comment by Naima-Bashir** [comment]
Closing this. @alfiraratnamalinda kindly reopen if the issue persists
