### ISSUE TITLE
[Ona Support Request]: Data from OptiBP app cannot be populated in Bunda app.

### ISSUE THREAD

**Issue by alfiraratnamalinda** [opensrp/opensrp-client-anc#907]
### Affected App or Server Version

android-json-form-wizard version 3.0.1-PREVIEW-SNAPSHOT

### What kind of support do you need?

Error message: "No fields defined to populate BP values"

**Debugging process:**

In strings.xml (android-json-form-wizard): "optibp_values_error"
Error toast invoked from: opensrp-client-native-form > android-json-form-wizard > src > main > java > com > vijay > jsonwizard > widgets > OptiBPWidgetFactory.java
In function call: getBPEditTextField() [Line 276]
This function is called on the same file twice in line 72 and 73
Those lines call BPFieldType enumeration defined in line 352, with value DIASTOLIC_BP("bp_diastolic") and SYSTOLIC_BP("bp_systolic")
So, the library cannot detect the fields with "bp_diastolic" and "bp_systolic" inside the form.

**Are those fields available inside the form?**

Related form file: opensrp-anc > assets > json.form > anc_physical_exam.json
Field with "bp_systolic" key is available and defined in line 632
Field with "bp_diastolic" key is available and defined in line 682
So, both fields are available and defined.

**When this issue start happening?**

Since we upgraded to org.smartregister:opensrp-client-native-form version 3.0.1-PREVIEW-SNAPSHOT

Related media: 
https://drive.google.com/file/d/1LmmW7nAnMG9TlH4ELKa5wVPMruiv6A8E/view?usp=sharing

### What is the acceptance criteria for your support request?

In Physical Exam form, using OptiBP as blood pressure assessment method and to receive BP values from OptiBP back to Bunda App Blood Pressure page.

**Comment by Naima-Bashir** [comment]
![image](https://user-images.githubusercontent.com/61143692/192968691-f13a6b52-0993-4b7d-931e-b092bf5d8021.png)

Apk can be found here: https://drive.google.com/file/d/1RJ_ykTkmPRUJ_3i0-euAgdGeN0MuJN17/view

**Comment by Naima-Bashir** [comment]
This has been fixed by the SID team. Closing this
