### ISSUE TITLE
Switching the TeamId method to LocationID to see if the data is fetched

### ISSUE THREAD

**Issue by Naima-Bashir** [opensrp/opensrp-client-anc#909]
### Affected App or Server Version

Latest apk: 1.6.11 rc1

### What kind of support do you need?

Delete the current app (OptiBP) we have on our devices. Update the two methods: 

```
1. build.gradle -> (buildConfigField "String", "SYNC_TYPE") -> to "locationid" and ""locationId" (we tried both)
2. AncSyncConfiguration.java -> getSyncFilterParam() -> SyncFilter.LOCATION_ID
3. AncSyncConfiguration.java -> getEncryptionParam() -> SyncFilter.LOCATION_ID
4.  then run the app to see if the data is fetched and shown on the app.
```

### What is the acceptance criteria for your support request?

The app should switch from sync by team to sync by location. This means that after the app sync, the data should fetch. If it doesn't fetch, then it will be a bug that we can investigate.

**Comment by junaidwarsivd** [comment]
hi @dubdabasoduba i've checked syncing the data by LocationID looks like the syncing is completed successfully but no data is fetched which was being fetched before when syncing with teamId cc @Naima-Bashir

**Comment by junaidwarsivd** [comment]
@dubdabasoduba 
changing fetchDefaultTeamId to FetchDefaultLocalityID in ANCSyncConfiguration file fixes the issue
```
 @Override
    public String getSyncFilterValue() {
        AllSharedPreferences sharedPreferences =
                AncLibrary.getInstance().getContext().userService().getAllSharedPreferences();
        return sharedPreferences.fetchDefaultLocalityId(sharedPreferences.fetchRegisteredANM());
    }
```
cc @Naima-Bashir
