### ISSUE TITLE
Implement Recent Tests section on Contacts tab

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-anc#91]
On the contacts tab (https://github.com/OpenSRP/opensrp-client-anc/issues/84), the last section displays the recent tests that the woman had during pregnancy. This is any test that is listed on the Tests tab in the data dictionary (https://github.com/OpenSRP/opensrp-client-anc/issues/54).

- [x] The date displayed in the section heading is the date of the most recent test or tests that were recorded for that woman. This can get updated after each contact visit is recorded or when tests are done in the tasks list outside of the contact in the Tasks tab. Each test result has a variable name ending in `_test_date` or something along those lines. So amongst all the tests that are recorded, you'd pick the most recent test date from them and display that here along with the test results below.
- [x] The test results shown are all of the tests and their results that were recorded on that date.
- [x] The "ALL TEST RESULTS" opens to a new dialog where the complete list of all the test results for that woman so far are listed.

**Comment by dubdabasoduba** [comment]
@cagulas  The ALL TEST RESULTS opens a page not a dialog. A dialog would have made things a bit squeezed.
