### ISSUE TITLE
Implement All Test Results from the Contacts tab

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-anc#92]
![clientcard-tests copy](https://user-images.githubusercontent.com/3488986/44733868-2f2b3080-aaf1-11e8-8005-f0ccaea16fed.png)

- [x] Hitting back button in top left or device back button takes user back to the Contacts tab in the woman's profile page.
- [x] Each type of test has its own section. The test sections can be ordered in the exact same order as they are listed in the Tests tab in the data dictionary.
- [x] Only the most recent test result of each type is displayed here. 
- [x] If there are no test results yet for a specific test type, don't show that section for it.
- [ ] To see the complete history of all test results for a certain test type, tap on the "All results" button at the bottom right of each section.
- [ ] If there is only a single test result for a specific test type, the "All results" button doesn't need to be shown.
- [ ] All results - single type of test only (e.g. HIV):

<img width="388" alt="screen shot 2018-08-28 at 7 35 48 pm" src="https://user-images.githubusercontent.com/3488986/44737052-9c42c400-aaf9-11e8-86f3-11b85ca438ca.png">

- [ ] All results - multiple types of tests (e.g. Hep B):

![dialog-hepb-history](https://user-images.githubusercontent.com/3488986/44737166-e9269a80-aaf9-11e8-92b0-3b497f0cbc28.png)

**Comment by dubdabasoduba** [comment]
After a discussion with @cagulas & @ellykits  we decided to this hold this off a bit. Currently it would just show the All Tests page with the popup ability.
