### ISSUE TITLE
[Ona Support Request]: Woman profile picture not displayed in woman profile and take picture of the woman button not clickable in registration form

### ISSUE THREAD

**Issue by neric1** [opensrp/opensrp-client-anc#923]
### Affected App or Server Version

v1.6.15 App

### What kind of support do you need?

We need to have the profile image  displayed as it was before this version or show it placeholder when not available

### What is the acceptance criteria for your support request?

Show a woman's profile image or placeholder and be able to capture an image in the registration form.

### Relevant Information

![Screenshot_1669362359](https://user-images.githubusercontent.com/91191732/203928111-7ee07ebd-5736-4fe2-8a6d-557f5b5e0732.png)

Console error
![Capture111111111e](https://user-images.githubusercontent.com/91191732/203928238-98269407-d08b-449f-b6b7-213377ccd908.PNG)

![Capture2222222222e](https://user-images.githubusercontent.com/91191732/203928288-7e15f11c-621d-4a1b-baa5-5f6129a0e609.PNG)

**Comment by ariadng** [comment]
We also found this issue in the Indonesian build app that rebased from the latest changes of global master branch.

![Screenshot_20221202-154104_Bunda](https://user-images.githubusercontent.com/57926750/205251933-e7a64acc-4e94-400b-9902-76c459aaf6a8.jpg)

**Comment by Naima-Bashir** [comment]
hi @neric1 @ariadng, let me take a look at this

**Comment by Naima-Bashir** [comment]
Hi @neric1 . I'd like to follow up on the priority of this ticket. From the meeting today, Maria had mentioned that it's not a crucial feature. She had also opened a discussion to remove/ deactivate the photo feature so that the health workers don’t have to have trouble with it. Could you discuss this with your team and get back to Ona. Thank you

**Comment by neric1** [comment]
Hi @Naima-Bashir, We should let it stay as it is.

**Comment by Naima-Bashir** [comment]
This is noted
