### ISSUE TITLE
[Ona Support Request]: Need assistance on custom form field

### ISSUE THREAD

**Issue by ariadng** [opensrp/opensrp-client-anc#928]
### Affected App or Server Version

v1.6.8 app

### What kind of support do you need?

Hello @Naima-Bashir @dubdabasoduba ,

We would like to get assistance on getting additional form field value to be used in contact processing.

Let's say in the `anc_quick_contact.json` form, we have additional field like this:

```json
{
    "key": "visit_date",
    "openmrs_entity_parent": "",
    "openmrs_entity": "concept",
    "openmrs_entity_id": "visit_date",
    "type": "date_picker",
    "hint": "{{anc_quick_check.step1.visit_date.hint}}",
    "expanded": false,
    "min_date": "today-320d",
    "max_date": "today",
    "v_required": {
	"value": "true",
	"err": "{{anc_quick_check.step1.visit_date.v_required.err}}"
    }
}
```

How to use the `visit_date` value in contact processing, let's say we want to use it in `finalizeContactForm` method inside `ContactInteractor.java`?

Thank you in advance, we couldn't find a guideline on this..

### What is the acceptance criteria for your support request?

We know how to use custom fields in contact processing.

**Comment by Naima-Bashir** [comment]
This is noted. Allow me to get back to you @ariadng

**Comment by Naima-Bashir** [comment]
This is related to #919 ticket. The main goal is to calculate the GA

**Comment by Naima-Bashir** [comment]
STEPS TO FOLLOW :
1. Add a hidden field that is related to the GA(gestational age) in the [anc_profile_json](https://github.com/opensrp/opensrp-client-anc/pull/910/commits/b558f03045306ac6d321bcd1d363621c13f321cc#diff-23b99860bcb9951a269a1f078ffcb03d99497a0790b685f5ad8adbcd82e6b54d)
2. Update/modify the calculation rules for the profile calculation [yml](https://github.com/opensrp/opensrp-client-anc/pull/910/commits/b558f03045306ac6d321bcd1d363621c13f321cc#diff-af726d9bf1a8032cc07c425a9aad572894694743377aefb87f2598594dc1b94a). 
3. The requested field should then be added to the form

cc @ariadng

**Comment by Naima-Bashir** [comment]
Meeting recording can be found [here](https://drive.google.com/file/d/1a5IQWX_fyDhy1jIAVLv9zGKwSbyI0yVB/view?usp=sharing)

**Comment by ariadng** [comment]
Hello @Naima-Bashir @junaidwarsivd 

Do we have update on how to do the number 2 (Update/modify the calculation rules for the profile calculation)?
As we discussed last week, we need a guide to use the inputted field value on Quick Check form to calculate EDD in profile_calculation.yml file.

Thank you in advance.

**Comment by Naima-Bashir** [comment]
Hi @ariadng . We had demonstrated how to extract values of the date filled in the Quick check page on the Finalize Contact section during the call. Did it solve the problem?

As for accessing the value filed in the Quickcheck in other forms; Here is what is needed for you to access it:

1. Declare the quick check field  key in `contact-globals.yml` file under the desired section of the form (eg anc_Profile)
2. To use the Field in the desired section reference it by adding `global_ prefix` before the key name where needed either in  `calculation.yml ` or in `relevence.yml` of the desired form. 

For reference kindly look at  `contact-globals.yml` and follow the `danger_signs` key  and where it is referenced as `global_danger_signs`

**Comment by Naima-Bashir** [comment]
Meeting recording can be found [here](https://drive.google.com/file/d/1Rko34LQJkPFfSGGjdaXahvtNlaMykw7p/view?usp=sharing) 
@ariadng @mentarisuharto

**Comment by ariadng** [comment]
Hello, thank you for your assistance. The issues related to this are on progress, and our questions regarding the technical guidance have already been solved. This ticket can now be closed.
