### ISSUE TITLE
Generate a new Brazil apk with the translated files

### ISSUE THREAD

**Issue by Naima-Bashir** [OpenSRP/opensrp-client-anc#929]
### Affected App or Server Version

v2.0.1-RELEASE

### What kind of support do you need?

The Brazil team have finished translating the files that we had sent them via Transifex. Next step is to generate a new apk with the complete translation and perform QA. Here are the action items to follow:

- [x] Download translated files from Transifex. Go to the resources section and look for the files that have the suffix **__pt_BR_** .
- [x] Ensure that you have downloaded all the correct Portuguese files
- [x] Add the translated files to the code and ensure you rename them with the suffix _pt_BR. 
- [x] Generate a new apk 
- [x] Share it with @SebaMutuku so that he can request QA
- [x] Request for QA in the qachannel
- [x] Ensure that regression testing is performed on the file. Switch the app to Portuguese and test the entire app. 
- [x] Ensure you test the Spinners, checkbox, Native radio Buttons and Multiselects
- [x] Once it has passed QA, inform @SebaMutuku and Joyce/Benjamin and they can share it with Samira via email

### What is the acceptance criteria for your support request?

Testing the app to ensure that the app is fully translated into Portuguese especially the Spinners, checkbox, Native radio Buttons and Multiselects

**Comment by junaidwarsivd** [comment]
hi @SebaMutuku  i've replaced all the provided transifex files and checked the apk seems like some translations are still missing in anc_test.properties and Profile could you Please make sure the files are the updated ones ?

**Comment by SebaMutuku** [comment]
@junaidwarsivd I have shared the same
