### ISSUE TITLE
Implement Last Contact section in Contacts tab

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client-anc#93]
In the Contacts tab (https://github.com/OpenSRP/opensrp-client-anc/issues/84), the Last Contact section displays the last contact summary information for the woman. 

- [x] {gest_age} weeks · Contact {contact #}
- [x] Hospital referral label if woman was referred to hospital in that contact visit {referred_hosp} = "Yes" on C&T container.
- [x] Date of contact visit
- [x] Summary info from the contact:

- [Any of the attention flags, yellow or red, from that contact]
- Physiological symptoms: {phys_symptoms}
- Average weight gain per week since last contact: {weight_gain} kg

- [x] Previous contacts opens up new page showing the list of all previous contacts.

**Comment by cagulas** [comment]
18 April release QA:

- [ ] Don't need to show number of days, i.e show "22 weeks" not "22 weeks 0 days"
- [ ] The hospital referral icon did not appear when it should have. Please check the logic.
- [ ] Let's add some more padding to the "PREVIOUS CONTACTS" button row. It is a bit easy to skip over and doesn't really stand out as a button right now.
- [ ] Showing "true" for the attention flag items (see below) will be a bit confusing for the user. I'm wondering how we can maybe incorporate the styling of the attention flag logic itself, like you see in the attention flag icon on the main register page? @rowo Can you pls weigh in here?

![Screenshot_20190419-123314](https://user-images.githubusercontent.com/3488986/56418482-b35c3f00-629f-11e9-9cda-5d6b253b55a4.png)
![Screenshot_20190419-123609](https://user-images.githubusercontent.com/3488986/56418512-c969ff80-629f-11e9-854d-5650b27d76ce.png)

**Comment by rowo** [comment]
I agree, "True" is not really a people friendly term unless it's about discerning fact from fiction. 

It would be great if all of the "true's" could be shown together as a list. In the mockups, it shows combining them into a "Risks and Diagnoses" section (items would be comma separated):

<img width="315" alt="Screen Shot 2019-04-19 at 6 33 27 AM" src="https://user-images.githubusercontent.com/1584163/56420730-27312400-626d-11e9-99d2-4b526bd41525.png">

We could call that section "attention flags"

**Comment by cagulas** [comment]
They were changed from True to Yes, which I am happy with for now. We can consider revising this in a future iteration after user testing.
