### ISSUE TITLE
[Ona Support Request]: Encounter related bugs

### ISSUE THREAD

**Issue by mergygayatri** [OpenSRP/opensrp-client-anc#932]
### Affected App or Server Version

v1.6.18 App

### What kind of support do you need?

The encounter date is not working as expected. 

We need your help to fix the encounter date-related issues as written below:
**1. List page:** 
- [GA is -](https://drive.google.com/file/d/1oJwaXuaiU5FFco3OYL-KAuU8_crZ_hgH/view?usp=sharing)
- [Date of the next visit is 26/06/0001](https://drive.google.com/file/d/1oJwaXuaiU5FFco3OYL-KAuU8_crZ_hgH/view?usp=sharing)

**2. Profile form**
- [1st visit_GA using LMP is invalid](https://drive.google.com/file/d/1hOAA8f4SWxFg60kXAC2ZpW1NLEAWOOEP/view?usp=sharing)
- [2nd visit_GA using ultrasound is invalid](https://drive.google.com/file/d/1Y1H-oyyus5Q5xQHkT4LWZi8XwHmREk6l/view?usp=sharing)
- [2nd visit_EDD is also invalid](https://drive.google.com/file/d/1Y1H-oyyus5Q5xQHkT4LWZi8XwHmREk6l/view?usp=sharing)
- [3rd visit_GA using LMP is 0 weeks 0 days](https://drive.google.com/file/d/1eNJ91kGeWo_USP8RRcnPuhmEzVX19JqU/view?usp=sharing) 
- [3rd visit, GA using ultrasound is invalid](https://drive.google.com/file/d/1IwC1P87NpKCetfFxVFJcE8s8V7deZ55a/view?usp=sharing)
- [3rd visit, EDD is 0](https://drive.google.com/file/d/1IwC1P87NpKCetfFxVFJcE8s8V7deZ55a/view?usp=sharing)

**3. Profile page**
- [1st visit_GA is 0 weeks](https://drive.google.com/file/d/1rWItz66dreb7-jQb-y7WX08Nkk7e5nFP/view?usp=sharing)
- [1st visit_Tab 'completed'_GA is 0 weeks](https://drive.google.com/file/d/1sUkmoU7_b5yfbRT83a5QFufmhErwpSli/view?usp=sharing) 
- [2nd visit_the dates of schedule is different from those on the page after the 1st visit was done](https://drive.google.com/file/d/1b2SocLuKiQU6oUrNzVBsAObL_-CbUd6Z/view?usp=sharing)
- [1st visit_Tab 'visit'_GA is 0 weeks](https://drive.google.com/file/d/1fvNTQwgkFEC-helznO6El3KPd8AQ6Loy/view?usp=sharing)
- [2nd visit_ GA in the 1st visit is 0 weeks](https://drive.google.com/file/d/17JUSh70aHkmDLY9raA23izEaYfVELGHN/view?usp=sharing)
- [3rd visit_scheduling and EDD are blank](https://drive.google.com/file/d/1NfLsP3QreL6mibLDX3eOHzg6qCOcn-xF/view?usp=sharing)
- [3rd visit_GA is 0 weeks](https://drive.google.com/file/d/1K2C-MprMEoDkMEc_0tKbaBXhYRrefKci/view?usp=sharing)

**4. Page before 'save and finish'**
- [1st visit_GA on the top is missing](https://drive.google.com/file/d/13f0LGJqE04WQvWfxReOj4oxdWskhsHLV/view?usp=sharing)
- [GA in the current pregnancy tab is 0 weeks 0 days](https://drive.google.com/file/d/13f0LGJqE04WQvWfxReOj4oxdWskhsHLV/view?usp=sharing)
- [1st visit_GA on the top is missing](https://drive.google.com/file/d/1pjNaXqNLBkLKY0EYoSzKJCABb7AWjpcx/view?usp=sharing)
- [2nd visit_GA on the top is 0 weeks](https://drive.google.com/file/d/1XOIM6nDo130hyvnuesMr9HmIex7aNfON/view?usp=sharing)

**5. Summary page after 'save and finish;**
- [1st visit_Incomplete schedule of the next visits](https://drive.google.com/file/d/1pUbTBUfITrqtp9hVoKp-WfOYEmZI_cs4/view?usp=sharing)
- [2nd visit_scheduling is different from the scheduling on the summary page of the 1st visit](https://drive.google.com/file/d/1RWMu9XeO0fGjNHa3ardnvZOUDzCN65Gz/view?usp=sharing)
- [3rd visit_dates of the next visit are behind the LMP](https://drive.google.com/file/d/1CWymDh5_DjY1biCn01yDSQzWEyJTLsCu/view?usp=sharing)
- [3rd visit_year is 0002](https://drive.google.com/file/d/1CWymDh5_DjY1biCn01yDSQzWEyJTLsCu/view?usp=sharing)

Thank you

### What is the acceptance criteria for your support request?

We need your help to fix the encounter date-related issues as written below:
**1. List page:** 
- GA should be shown in numbers, calculated based on the LMP/ultrasound and encounter date
- The date of the next visit should be correct according to the calculation using EDD or GA and the encounter date

**2. Profile form**
- 1st visit_GA using LMP should be 4 Weeks 3 days 
- 2nd visit_GA using ultrasound should be 5 weeks 4 days (these numbers are the same as the number manually inputted to the field of GA using ultrasound)
- 2nd visit_EDD is also invalid
- 3rd visit_GA using LMP is 0 weeks 0 days
- 3rd visit, GA using ultrasound should be 20 weeks 0 days
- 3rd visit, EDD is 03/03/2023

**3. Profile page**
- 1st visit_GA should be 4 weeks
- 1st visit_Tab 'completed'_GA is 4 weeks
- 1st visit_Tab 'visit'_GA is 4 weeks
- 2nd visit_the dates of schedule should be the same as those in the scheduling for the 1st visit (but we have to check the scheduling in advance, whether or not the scheduling is correct, I cannot check the scheduling because the GA is still invalid)
- 2nd visit_GA in the 1st visit should be 4 weeks
- 3rd visit_there should be the date of the next visits, EDD should be 03 March 2023
- 3rd visit_GA should be 20 weeks

**4. Page before 'save and finish'**
- 1st visit_GA should be shown as 4 weeks
- GA in the current pregnancy tab is 0 weeks 0 days
- 1st visit_GA on the top should be shown as 4 weeks
- 2nd visit_GA on the top is 14 weeks

**5. Summary page after 'save and finish;**
- 1st visit_ should have a complete schedule of the next visits
- 2nd visit_scheduling should be as same as the scheduling on the summary page of the 1st visit (but I don't know which scheduling is correct, I still cannot check unless we have fixed the GA)
- 3rd visit_dates of the next visit should be after the LMP
- 3rd visit_year is 2022

**Comment by SebaMutuku** [comment]
@mergygayatri is it possible to attach the apk you used when testing on this issue?

**Comment by Naima-Bashir** [comment]
Proposed solution:
1. Harmonize the code (merge the changes from OptiBP main to SID Dev branch)
2. Check whether the GA is calculated correctly
3. If this doesn't work, we would need to debug and investigate. It may take longer however

**Comment by mergygayatri** [comment]
v1.6.18 App (27 March 2023)

1. **First contact**
- Profile page: [EDD using ultrasound is INVALID. Correct EDD is 06/06/2023](https://drive.google.com/file/d/1p7JKvHUGE_qnu6f71QtgFDuLvG_-_4Vb/view?usp=sharing)

2. **Second contact & third contact**: as same as the first contact

3. **Fourth contact**
- Profile page: [EDD using ultrasound is INVALID. Correct EDD is 06/06/2023](https://drive.google.com/file/d/1Sh-19jqptNEDf0Lp5COnNKVVld57-gLg/view?usp=sharing)
- Summary page: [GA on the top is invalid (0 weeks); Current pregnancy section: GA and EDD (using LMP) are INVALID (0)](https://drive.google.com/file/d/1ZXtHCrB8RtdJcnazUt1k4d-g0vFI7IVP/view?usp=sharing)
- Visit tab_previous visit: [GA is 0](https://drive.google.com/file/d/1lX0Gv4yv9BRB7c5j4PFiA5sWOwHXrVK1/view?usp=sharing); [The list of previous visit summaries is BLANK; EDD is BLANK](https://drive.google.com/file/d/1wYiHVQ1SDHqydOwtEHwtg2BzuCjjYKF0/view?usp=sharing)
- List page:[ GA is – ; Date of next visit: 26/06/0001 (Several mothers have 26/06/0001)](https://drive.google.com/file/d/1k1K47RQYCaVIw5K6qGunsUywI87b5jEQ/view?usp=sharing)

4. **Sixth contact:** Same as the fourth contact, except: [Visit tab_previous visit: GA in the fourth and fifth visits is 0](https://drive.google.com/drive/folders/1402eqE2UB0xDsrbefm0R34SH5sQd2vOY?usp=sharing)

5. **Seventh contact:** same as fourth contact 

6. **Eighth contact**:  [When clicking the physical exam form, the App crashed (minute 3:20)](https://drive.google.com/file/d/1CWQO9qL-5uQRiOsKk_30fGdbsBh2k7-B/view?usp=sharing)

7. **Additional issue:** [field 'weeks' for GA using ultrasound is not working unless the field 'days' is filled out (minute 1:31)](https://drive.google.com/file/d/19TVMVIiCRn4O-kWTuEjTLqLmSXcUkKYO/view?usp=sharing)

**Comment by Naima-Bashir** [comment]
Hi @junaidwarsivd @hilpitome :
I have tested this ticket using this apk: [indonesia-reference-v1.6.8-app-enc-fix.apk]
Find my notes below:
**1. EDD using LMP**

- Manual Encounter Date Selected: 18/04/2023
- Last Menstrual Period Date (HPHT in Bahasa): 18/03/2023 
- EDD expected: 23/12/2023
- EDD shown on device: 23/12/2023  

**This has passed QA**

2. EDD using Ultrasound GA (USG in Bahasa)

- Manual Encounter Date Selected: 18/04/2023
- Date of Ultrasound: 19/02/2023
- GA during Ultrasound: 6 weeks 1 day
- EDD expected: 14/10/2023
- EDD shown on device: 11/12/2023
**This has failed QA**
![image](https://user-images.githubusercontent.com/61143692/233076323-26792999-4347-4291-bd9d-54b3c0564d36.png)

 ![screenshot_20230419-151600_2_720](https://user-images.githubusercontent.com/61143692/233076163-6dc51f63-b53e-4752-a2b6-651983756e3a.jpg)

**Comment by Naima-Bashir** [comment]
Second round of QA:
LMP related issues: 
1. In the 6th visit, the GA using LMP is 0 weeks and 0 days
![image](https://user-images.githubusercontent.com/61143692/234807174-92337dd3-e622-4001-b364-a255ba8878a0.png)
2. GA in summary page: In the 6th visit, GA using LMP is 0 weeks 0 days 
![image](https://user-images.githubusercontent.com/61143692/234807302-b1234008-dc8c-4f92-8a79-e3e915004214.png)

3. GA in overview page:
a.  In the 6th visit, GA uses the K5’s GA, which is 22 Minggu (22 weeks). It should be: 25 weeks 5 days
b.  ‘ikhtisar’ / overview is not completed
![image](https://user-images.githubusercontent.com/61143692/234807545-c022e96e-2c3f-4850-997d-c3515a78a34c.png)

**Comment by Naima-Bashir** [comment]
GA using ultrasound
1.    GA using ultrasound: In the 3rd visit, GA using ultrasound is wrong. The correct GA us 16 weeks 5 days.
![image](https://user-images.githubusercontent.com/61143692/234807751-2f7ced19-d0e4-4604-b248-45da004129b2.png)
2. 2. GA in summary page: In the 3rd visit,
a. It should be “Kunjungan 3”
b. GA shouldn’t be 12 weeks. It should be 16 weeks
c. GA shouldn’t be 7 weeks 6 days. It should be 16 weeks 5 days
![image](https://user-images.githubusercontent.com/61143692/234807881-fcff1c7e-caa6-4065-bab8-e0d6d47cd8ba.png)

3. Three dots in the right corner: In the 3rd visit, It should be third visit and the date is 25-12-2022
![image](https://user-images.githubusercontent.com/61143692/234808024-5b455d38-2b9a-4c57-87ce-3dec84c8a09c.png)
4. a. Scheduling after save and finish and in the contacts page: The schedule is wrong. The encounter date is 25/12/2022, but the next schedule is 29/11/2022
![image](https://user-images.githubusercontent.com/61143692/234808838-e96f3dac-ec8e-4858-a087-3e3fe489c1e9.png)
4 b. Scheduling after save and finish and in the contacts page: It should be 16 weeks
![image](https://user-images.githubusercontent.com/61143692/234808916-86c14940-592b-4171-b334-7c61b3516e6a.png)
4 c. Scheduling after save and finish and in the contacts page: GA should be 16 weeks, Summary is not completed
![image](https://user-images.githubusercontent.com/61143692/234808977-2c4028cc-b270-477b-b7a4-3f1c80ba3eb2.png)

**Comment by Naima-Bashir** [comment]
_1st Contact_
Encounter date: 28/10/2022
LMP: 12/09/2022
GA: 6 weeks 4 days
EDD: 16/06/2023

_2nd Contact_
Encounter date: 26/11/2022
GA using LMP: 10 weeks 5 days
GA using ultrasound: 12 weeks 4 days 

_3rd Contact_
Encounter date: 25/12/2022
GA using LMP: 14 weeks 6 days 
GA using Ultrasound: 16 weeks 5 days

_4th Contact_
Encounter date: 22/01/2023
GA using LMP: 18 weeks 6 days
GA using Ultrasound: 20 weeks 5 days 

_5th Contact_
Encounter date: 19/02/2023
GA using LMP: 22 weeks 6 days 
GA using Ultrasound: 24 weeks 5 days 

_6th Contact_
Encounter date: 11/03/2023
GA using LMP: 25 weeks 5 days 
GA using Ultrasound: 27 weeks 4 days

**Comment by mergygayatri** [comment]
**_Additional information for the 1st contact_**
If using ultrasound, the GA, being entered to field GA as the result of the ultrasound, is 7 weeks 6 days, therefore the GA using ultrasound in the encounter date is 8 weeks 3 days

_7th contact_
Encounter date: 30/03/2023
GA using LMP: 28 weeks 3 days
GA using Ultrasound:  30 weeks 2 days

**Comment by junaidwarsivd** [comment]
following are the the things we found while using encounter date 
1 in first contact it calculates the GA as it should but if we move towards the 2nd and third contact GA is picked from the ultrasound date/ lmp date which was previously selected (using the encounter date of previous contact since GA is supposed to be saved and automatically picked in the ongoing contacts)
2 Scheduled contact dates changes after each contact is being generated imge is attached for the comparision between the schedule contacts dates of the same mother after 2nd and 3rd contact
3 Currently User can Proceed through Quick check form without inputting Encounter date which also causes issues in GA calculations
 
![Screenshot from 2023-04-28 18-36-56](https://user-images.githubusercontent.com/81764603/235601440-fc5971be-c651-4901-9f87-13a1bf032cb0.png)
@Naima-Bashir  @SebaMutuku

**Comment by Naima-Bashir** [comment]
Based on today's lengthy standup; the following decisions have been made with @mergygayatri approval:

- The saved EDD from the first contact should remain constant throughout the entire process

- In the event that the first EDD is not there; we will revert to using the mathematics on the Profile Calculation Data Dictionary

-   @junaidwarsivd will add a check if the contact number is greater than 1, the he goes to the DB to fetch the EDD date for the first contact
cc @mergygayatri @SebaMutuku @junaidwarsivd

**Comment by Naima-Bashir** [comment]
The latest Encounter fix apk has afew incorrect GA calculations. 
The GA should be calculated using the manual encounter dates that are saved during the contact visits. This means that the GA should be calculated after each visit using the manual encounter date that has been entered in that particular visit. 
We have to incorporate the manual encounter date into the GA calculations

cc @mergygayatri @SebaMutuku @junaidwarsivd

**Comment by Naima-Bashir** [comment]
Hi @junaidwarsivd @SebaMutuku Based on the QA done on 5/06/23, here are my findings:

- [x] The GA using LMP calculations are correct 
- [x] The GA using Ultrasound are correct 
- [x] The EDD using LMP calculations are correct 
- [x] The EDD using Ultrasound is also correct 

I did notice that when one tries to proceed to a new contact immediately after finishing the previous contact (without closing the profile page), the GA using Ultrasound is 0. See screenshot below. 

@junaidwarsivd has observed that the contact number is not being updated in the Patient's Details in the profile section. Due to this, the values are not prefilled as they normally are. Normally when one proceeds to the next contact, the values from the GA, LMP, Ultrasound etc are prefilled so that one doesn't have to fill them again. They may edit it should they wish. 
He has updated the patient details in the Profile Page. The correct details are shown but the pre population is still not happening. 
He is investigating the Contact Form Activity and the JSON Form Activity to see if the data is flowing from there. He will provide feedback during standup tomorrow. 
![image](https://github.com/opensrp/opensrp-client-anc/assets/61143692/b950f556-2fb2-4ce3-9e09-20ec898ce7a6)

**Comment by mergygayatri** [comment]
Hi @Naima-Bashir. Thank you. GA from LMP and ultrasound are working now on the profile page. The remained issue is sometimes GA from the ultrasound on the profile page is wrong because we need to reenter GA in .... weeks ..... days manually ([see the video here minute 33:00](https://drive.google.com/file/d/1DJrpvTxtiWHHwgSo2HU3PcUWIxFgmJnC/view?usp=sharing))
Also, the wrong GA was reported on the summary page (see the attachment)
 
![Screenshot_20230608_194525_BUNDA 2](https://github.com/opensrp/opensrp-client-anc/assets/119648701/e174a06a-616d-4c02-bfa6-6eb5430aafcc)

**Comment by mergygayatri** [comment]
Hi @Naima-Bashir
APK: 10 June 2023 (contact)
Issue: crash after 'save and finish'
[See the video](https://drive.google.com/file/d/1V4vji8FyENtLBchs3gWWz7xtgwyWiEZ2/view?usp=sharing)

**Comment by junaidwarsivd** [comment]
hi @mergygayatri i have requested access to the video could you kindly give the access so that i would be able to see the issue

**Comment by mergygayatri** [comment]
Hi @junaidwarsivd, kindly try the link again. I've updated it with access.

**Comment by Naima-Bashir** [comment]
Closing this issue has it has passed QA
