### ISSUE TITLE
[Ona Support Request]: Translation issue and punctuation error

### ISSUE THREAD

**Issue by mergygayatri** [OpenSRP/opensrp-client-anc#934]
### Affected App or Server Version

v1.6.18 App

### What kind of support do you need?

There are issues with the translation

We need your help to fix the translation issues as written below:
1. Overview page
- ['Weeks' should be 'Minggu'](https://drive.google.com/file/d/1_yeYBo08kpwk9TVFGhOIczaPg8v9MZCf/view?usp=sharing)
- ['days' should be 'hari'](https://drive.google.com/file/d/1_yeYBo08kpwk9TVFGhOIczaPg8v9MZCf/view?usp=sharing)
- ['High daily consumption of caffeine' should be 'Asupan kafein harian'](https://drive.google.com/file/d/1r763ylxoN2gqypLNRDKYA54SlseoxMFB/view?usp=sharing)
- ['Tobacco user or recently quit' should be 'Pengguna tembakau atau baru saja berhenti'](https://drive.google.com/file/d/1r763ylxoN2gqypLNRDKYA54SlseoxMFB/view?usp=sharing)

2. Physical exam page
- ['Get Started' should be 'Mulai'](https://drive.google.com/file/d/1KwhxCGPXBk8C8zHLBO9opq6UwIP0oG_I/view?usp=sharing)
-[ 'bpm' should be 'kpm' ](https://drive.google.com/file/d/1sHIgZK8TFbwDA5tmtWju0BDVzjNzwiEf/view?usp=sharing)
- [Put periond (.) between 'kg' and 'Total'](https://drive.google.com/file/d/1pNWG54hy1Vld-DolD5cBVdiztzOeBy-x/view?usp=sharing)

3. Profile page
[- '.....weeks ... days' should be '... minggu ... hari'](https://drive.google.com/file/d/17l8_ZCrM5O6Fb-PDiyv4Kns95NN3JpBK/view?usp=sharing)

4. Summary page
- ['Vitamin A Supplement, Iron & folic acid supplement' should be 'Suplemen vitamin A, suplemen zat besi dan asam folat'](https://drive.google.com/file/d/1dsMVAf44ckCeoFw9dAxvnZZEOWOoyhJD/view?usp=sharing)
- ['....weeks .... day should be '....minggu.....hari'](https://drive.google.com/file/d/1zRTZHgt9L2OQC7owO6eZbFGb2rgOEArT/view?usp=sharing)
- '[Age' should be 'Umur'](https://drive.google.com/file/d/1obM9kmSwMYnsqe2xwN6MTCYc5OYQl3UG/view?usp=sharing)
- ['Sma' should be 'SMA' (capital letters) ](https://drive.google.com/file/d/1v4oa3PE3Y6LSaTvG-0xmlRT2hZXemrI5/view?usp=sharing)
- ['BMI' should be 'IMT'](https://drive.google.com/file/d/10GtfOORc5tTlnI-3-ARd4JtewnN5hap5/view?usp=sharing)
- [bpm should be kpm](https://drive.google.com/file/d/1-KXXNzBt7-P-AaAIV8l1noKqgzXbf_A7/view?usp=sharing)
- ['Ujian' should be 'Pemeriksaan'](https://drive.google.com/file/d/1VA_J5xFx6h787DIU4tTxHAfw1Bj7u6gj/view?usp=sharing)

5. TT Vaccination Status page
- [Put period (.) ](https://drive.google.com/file/d/1s8mqJd_68in-A9Ddb-hbN-Ec8k4xx_1y/view?usp=sharing)

6. Overview (visit tab)
- ['Physiological symptoms' should be 'Gejala fisiologis'](https://drive.google.com/file/d/1_eplDMPI-OS8c_XTE34FmyFQABC-haPH/view?usp=sharing)
- ['Total weight gain in pregnancy' should be 'Total kenaikan berat badan dalam kehamilan'](https://drive.google.com/file/d/1_eplDMPI-OS8c_XTE34FmyFQABC-haPH/view?usp=sharing)
- ['BP' should 'TD' ](https://drive.google.com/file/d/1Lv5Pjau-ikwPgSM0-bXzik7giIgbkGJR/view?usp=sharing)
- ['bpm' should be 'DPM'](https://drive.google.com/file/d/1Lv5Pjau-ikwPgSM0-bXzik7giIgbkGJR/view?usp=sharing)
- ['No' should be 'Tidak'](https://drive.google.com/file/d/1Lv5Pjau-ikwPgSM0-bXzik7giIgbkGJR/view?usp=sharing)
- [Edema: No should be 'Tidak'](https://drive.google.com/file/d/1RjQ8FeGVtSeQpYS8QbGVsYdpdw5P-1Ec/view?usp=sharing)
- [HIV test: 'hiv' should be HIV (capital letters)](https://drive.google.com/file/d/1Omtq3fTy4O6GWc1YKwtyKFni4OEByMbg/view?usp=sharing)
-[ Partner's HIV test: 'Dont know' should be 'Tidak tahu'](https://drive.google.com/file/d/1Omtq3fTy4O6GWc1YKwtyKFni4OEByMbg/view?usp=sharing)
- [Hepatitis B: 'Expired stock' should be 'Persediaan kadaluarsa'](https://drive.google.com/file/d/1Omtq3fTy4O6GWc1YKwtyKFni4OEByMbg/view?usp=sharing)
- ['COMPLETED' should 'TELAH SELESAI'](https://drive.google.com/file/d/1mOlIvqb7h5aKgLcodDiaqPUw1jiZ_6y5/view?usp=sharing)
- ['Physical symptoms' should be 'Gejala fisiologis'](https://drive.google.com/file/d/1mOlIvqb7h5aKgLcodDiaqPUw1jiZ_6y5/view?usp=sharing)
- [UPCOMING CONTACTS should be 'KUNJUNGAN BERIKUTNYA'](https://drive.google.com/file/d/1mOlIvqb7h5aKgLcodDiaqPUw1jiZ_6y5/view?usp=sharing)
- [WEEKS should be 'MINGGU'](https://drive.google.com/file/d/134YFt_N8A5a_S48zZqqZkBaQRG0Y7umx/view?usp=sharing)

7. [Counseling form (information page):  Put period (.) between 'pasti' and 'Selain'](https://drive.google.com/file/d/1Oqowu3OTsrzIwVc2sUqIXUfIlYRBN447/view?usp=sharing)

8. Profile page (habits): 
[Caffein Consumption Information: Put period (.) between 'hari' and 'Masing' ](https://drive.google.com/file/d/1jCThE41LY5VyyASItvKL1qFf4FqVk9A5/view?usp=sharing)

9. [Typos: 'Sipilis' should be 'Sifilis'](https://drive.google.com/file/d/1lCuEE0FXCXwrTjmWy2xad0-Ov5ZwMv2r/view?usp=sharing)

10. Close ANC page
- [ Reason: Live Birth field_wrong translation: 'Modus Persalinan' should be 'Metode Persalinan'](https://drive.google.com/file/d/1e0G7QBVLriI7QMh7CdKj_pTwqAGJTQMs/view?usp=sharing)
- [ Live Birth_'rumah' should be 'Rumah' (R capital)](https://drive.google.com/file/d/1NTD94d6hX5ZPwFwxpKxLtTkGWWbkHKXT/view?usp=sharing)
- [Reason: Still birth field_wrong translation: 'Modus Persalinan' should be 'Metode Persalinan](https://drive.google.com/file/d/1e0G7QBVLriI7QMh7CdKj_pTwqAGJTQMs/view?usp=sharing)']

11. Counselling Form
- [Vitamin C_Put period ( . ) between 'oral' and 'Bukti'](https://drive.google.com/file/d/1d1RA3F13qU4UyRHvlCUuEJWB63dL8sMC/view?usp=sharing)
- [Vitamin C_Put period ( . ) between 'persalinan' and 'Namun'](https://drive.google.com/file/d/1d1RA3F13qU4UyRHvlCUuEJWB63dL8sMC/view?usp=sharing)
- [Vitamin D_Put period ( . ) between 'penting' dan 'Untuk'](https://drive.google.com/file/d/1d1RA3F13qU4UyRHvlCUuEJWB63dL8sMC/view?usp=sharing)
- [Counselling Next ANC Visit_Put periond ( . ) between '...komplikasi)' and 'Jadwal'](https://drive.google.com/file/d/1d1RA3F13qU4UyRHvlCUuEJWB63dL8sMC/view?usp=sharing)

12. [Physical exam form_ preeclampsia counseling: Translation for 'The use of aspirin after 12 weeks gestation is recommended as well as calcium if low dietary intake area. Please also provide counseling' is confusing](https://drive.google.com/file/d/1VtJfqeo78RIHOsl1dYYgbYeJLT9uaUbP/view?usp=sharing)

Thank you

### What are the acceptance criteria for your support request?

There are issues with the translation

We need your help to fix the translation issues as written below:
1. Overview page
- 'Weeks' should be 'Minggu'
- 'days' should be 'hari'
- 'High daily consumption of caffeine' should be 'Asupan kafein harian'
- 'Tobacco user or recently quit' should be 'Pengguna tembakau atau baru saja berhenti'

2. Physical exam page
- 'Get Started' should be 'Mulai'
-'bpm' should be 'kpm' 
- Put period (.) between 'kg' and 'Total'

3. Profile page
- '.....weeks ... days' should be '... minggu ... hari'

4. Summary page
- 'Vitamin A Supplement, Iron & folic acid supplement' should be 'Suplemen vitamin A, suplemen zat besi dan asam folat'
- '....weeks .... day should be '....minggu.....hari'
- 'Age' should be 'Umur'
- 'Sma' should be 'SMA' (capital letters)
- 'BMI' should be 'IMT'
- bpm should be kpm
- 'Ujian' should be 'Pemeriksaan'

5. TT Vaccination Status page
- Put period (.) 

6. Overview (visit tab)
- 'Physiological symptoms' should be 'Gejala fisiologis'
- 'Total weight gain in pregnancy' should be 'Total kenaikan berat badan dalam kehamilan'
- 'BP' should 'TD' 
- 'bpm' should be 'DPM'
- 'No' should be 'Tidak'
- Edema: No should be 'Tidak'
- HIV test: 'hiv' should be HIV (capital letters)
- Partner's HIV test: 'Dont know' should be 'Tidak tahu'
- Hepatitis B: 'Expired stock' should be 'Persediaan kadaluarsa'
- 'COMPLETED' should 'TELAH SELESAI'
- 'Physical symptoms' should be 'Gejala fisiologis'
- 'UPCOMING CONTACTS' should be 'KUNJUNGAN BERIKUTNYA'
- WEEKS should be 'MINGGU'

7. Counseling form (information page):  Put period (.) between 'pasti' and 'Selain'

8. Profile page (habits): 
Caffeine Consumption Information: Put period (.) between 'hari' and 'Masing' 

9. Typos: 'Sipilis' should be 'Sifilis'

10. Close ANC page
- Reason: Live Birth field_wrong translation: 'Modus Persalinan' should be 'Metode Persalinan'
- Live Birth_'rumah' should be 'Rumah' (R capital)
- Reason: Stillbirth field_wrong translation: 'Modus Persalinan' should be 'Metode Persalinan

11. Counselling Form
- Vitamin C_Put period ( . ) between 'oral' and 'Bukti'
- Vitamin C_Put period ( . ) between 'persalinan' and 'Namun'
- Vitamin D_Put period ( . ) between 'penting' dan 'Untuk'
- Counselling Next ANC Visit_Put period ( . ) between '...komplikasi)' and 'Jadwal'

12. The Indonesian translation for 'The use of aspirin after 12 weeks gestation is recommended as well as calcium if low dietary intake area. Please also provide counseling' should be '............'

Thank you

**Comment by Naima-Bashir** [comment]
Hi @mergygayatri , based on the initial investigation, it seems like the untranslated files above are not in the corresponding property files. For example, when you search for `tobacco user/recently quit` in the `profile_overview.property ` , the key is not there. This means that it was not added to the translated files. 
What we can do is:

1. Ona will move the keys and translate using the above words. 
2. Add the translated files to transifex for future use. 
3. Cut an apk for testing

**Comment by junaidwarsivd** [comment]
profile_overview.second_hand_smoke = Second-hand exposure to tobacco smoke
profile_overview.condoms_not_used = Woman and her partner(s) do not use condoms
profile_overview.alcohol_substances = Alcohol / substances currently using
profile_overview.reduced_fetal_movement = Reduced or no fetal movement perceived by woman
profile_overview.pre_eclampsia_risk = Pre-eclampsia risk
profile_overview.pre_hiv_risk = HIV risk
profile_overview.diabetes_risk = Diabetes risk
profile_overview.severe_hypertension = Severe hypertension
profile_overview.pre_eclampsia = Pre-eclampsia
profile_overview.severe_pre_eclampsia = Severe pre-eclampsia
profile_overview.rh_factor_negative = Rh factor negative
profile_overview.hiv_positive = HIV positive
profile_overview.hepatitis_b_positive = Hepatitis B positive
profile_overview.hepatitis_c_positive = Hepatitis C positive
profile_overview.syphilis_positive = Syphilis positive
profile_overview.asb = Asymptomatic bacteriuria (ASB) infection
profile_overview.gbs = Positive for Group B Streptococcus (GBS)
profile_overview.gdm = Gestational Diabetes Mellitus (GDM)
profile_overview.dm = Diabetes Mellitus (DM) na gravidez
profile_overview.anaemia_diagnosis = Anaemia diagnosis
profile_overview.tb_positive = TB screening positive
profile_overview.hypertension = Hypertension

hi @mergygayatri  these strings need translations

**Comment by mergygayatri** [comment]
Hi @junaidwarsivd, please find the translations as written below: 

profile_overview.second_hand_smoke = Second-hand exposure to tobacco smoke  = Perokok pasif

profile_overview.condoms_not_used = Woman and her partner(s) do not use condoms = Ibu dan pasangan (pasangan-pasangan) nya tidak menggunakan kondom

profile_overview.alcohol_substances = Alcohol / substances currently using = Alkohol / zat yang sedang digunakan 

profile_overview.reduced_fetal_movement = Reduced or no fetal movement perceived by woman = Gerakan janin berkurang atau tidak ada gerakan yang dirasakan oleh ibu

profile_overview.pre_eclampsia_risk = Pre-eclampsia risk = Risiko pre-eklampsia

profile_overview.pre_hiv_risk = HIV risk = Risiko HIV

profile_overview.diabetes_risk = Diabetes risk = Risiko diabetes

profile_overview.severe_hypertension = Severe hypertension = Hipertensi berat

profile_overview.pre_eclampsia = Pre-eclampsia = Pre-eklampsia

profile_overview.severe_pre_eclampsia = Severe pre-eclampsia = Pre-eklampsia berat

profile_overview.rh_factor_negative = Rh factor negative = Faktor Rh negatif

profile_overview.hiv_positive = HIV positive = HIV positif

profile_overview.hepatitis_b_positive = Hepatitis B positive = Hepatitis B positif

profile_overview.hepatitis_c_positive = Hepatitis C positive = Hepatitis C positif

profile_overview.syphilis_positive = Syphilis positive = Sifilis positif

profile_overview.asb = Asymptomatic bacteriuria (ASB) infection = Infeksi bakteriuria asimtomatik  (BAS)

profile_overview.gbs = Positive for Group B Streptococcus (GBS) = Positif streptokokus grup B

profile_overview.gdm = Gestational Diabetes Mellitus (GDM) = Diabetes Melitus Gestasional (DMG)

profile_overview.dm = Diabetes Mellitus (DM) na gravidez (Could you please recheck this?, I think it should be ‘Diabetes Mellitus (DM)’? If so, the translation would be Diabetes Melitus (DM)

profile_overview.anaemia_diagnosis = Anaemia diagnosis = Diagnosis anemia

profile_overview.tb_positive = TB screening positive = Positif skrining TB

profile_overview.hypertension = Hypertension

**Comment by Naima-Bashir** [comment]
I have tested this apk: indonesia-reference-app-v1.6.18.apk
Translations that need to be in Bahasa:

PROFILE PAGE:
'Weeks' should be 'Minggu' (two gg)

PHYSICAL EXAM PAGE:
OptiBP get started Page --'Mulai' not Memulai

TEST PAGE:
Syphils test -- "Sifilis" not ""Sipilis"

SUMMARY PAGE:
bpm --kpm
mingu --- minggu
I'll need to confirm if kg, cm and celcius should be translated as I can't find the Bahasa words for them @mergygayatri 
Hadir pucat: Yes -- Ya
HIV : 'hiv' should be HIV (capital letters)
HIV test : Positive -- Positif
tanggal diagnosis- should in capital letter "Tanggal"
Recuded or no fetal movement perceived by woman -- It looks like there is both English and Bahasa there. See screenshot
Ada Edema- Yes --Ya
Jenis edema: Hands feet oedema (We will ask @mergygayatri )
HIV Status, don't know -- @mergygayatri 
Next contact visit dates-- 28th June, August, October, November (All are still in English)
GA and EDD are in English -- should be and HPHT and HPL
Anaemia Diagnosis: Yes (Should be Ya )
Tes USG: Done Today  @mergygayatri )
The date for the Manual Encounter Date is also in English


![Screenshot_20230412-154605](https://user-images.githubusercontent.com/61143692/231465086-7f7acc99-6e44-4ca1-a1d3-8ee95efccba3.jpg)
![Screenshot_20230412-154714](https://user-images.githubusercontent.com/61143692/231465095-ab5af257-ec19-46d8-b239-414bd406ef9e.jpg)
![Screenshot_20230412-153835](https://user-images.githubusercontent.com/61143692/231465100-180b0b9b-9484-4f83-8081-9ee9421747dd.jpg)
![Screenshot_20230412-154213](https://user-images.githubusercontent.com/61143692/231465106-38b72d47-b476-4146-a2d7-2796303b07bf.jpg)
![Screenshot_20230412-153034](https://user-images.githubusercontent.com/61143692/231465113-28ce912c-b1a3-4afd-a61c-3f15b442047f.jpg)
![Screenshot_20230412-153404](https://user-images.githubusercontent.com/61143692/231465117-377e5093-b543-444b-a9e4-c3c902a95ab5.jpg)
![Screenshot_20230412-152302](https://user-images.githubusercontent.com/61143692/231465120-c25c74b7-4084-47ae-95ae-0785daa6a51f.jpg)
![Screenshot_20230412-152827](https://user-images.githubusercontent.com/61143692/231465129-3ab82177-fea3-42ab-b13d-adb0926bf557.jpg)
![Screenshot_20230412-151644](https://user-images.githubusercontent.com/61143692/231465135-6dcd7806-539f-4b6f-a585-b68ff9025d92.jpg)
![Screenshot_20230412-152031](https://user-images.githubusercontent.com/61143692/231465142-830ece9b-bc12-40ef-be12-884305293736.jpg)
![Screenshot_20230412-151534](https://user-images.githubusercontent.com/61143692/231465143-3ad43a1c-08a9-41c5-becf-2c733f0d1d36.jpg)
![Screenshot_20230412-150903](https://user-images.githubusercontent.com/61143692/231465149-73f75918-32c6-402a-af6f-46b56ad096ea.jpg)
![Screenshot_20230412-151037](https://user-images.githubusercontent.com/61143692/231465152-15e7d46f-fb1d-47bd-a5c2-bad46f64bd72.jpg)
![Screenshot_20230412-150150](https://user-images.githubusercontent.com/61143692/231465156-c6fcfc40-8ab0-4dd0-a0c8-4b9c62142f48.jpg)
![Screenshot_20230412-150230](https://user-images.githubusercontent.com/61143692/231465161-995b9385-5139-462a-9af6-086add752c95.jpg)

**Comment by mergygayatri** [comment]
Hi @Naima-Bashir 
PHYSICAL EXAM PAGE:
OptiBP get started Page -- 'Memulai' is also correct

SUMMARY PAGE:
You don't need to translate  kg, cm and celcius because they are Bahasa too
Recuded or no fetal movement perceived by woman -- It looks like there is both English and Bahasa there. See screenshot. You can translate this into 'Gerakan janin yang dirasakan ibu berkurang atau tidak ada'

Ada Edema- Yes --Ya
Jenis edema: Hands feet oedema (Could you please the screenshoot?)

HIV Status, don't know --> tidak tahu
Next contact visit dates-- 28th June, August, October, November (All are still in English)

"GA and EDD are in English -- should be and HPHT and HPL" (Correction: GA is UK, while EDD is HPL). HPHT is LMP

Tes USG: Done Today --> Dilakukan hari ini

"The date for the Manual Encounter Date is also in English"--> Could you please explain more about this question?
Did you mean the translation for 'Encounter Date'? If so, the translation for Encounter Date is Tanggal Kunjungan

Additional issues found from the screenshots @Naima-Bashir sent:
- [Ujian should be 'Pemeriksaan'](https://drive.google.com/file/d/1t1iw7nTuPcPJK0EIJ6Z2XdPbNbwZHTOZ/view?usp=sharing)
- [Diagnosis Anemia should be Diagnosis anemia](https://drive.google.com/file/d/1stnTCl_K_7Y0tvr77FQThcpml4PYz4QT/view?usp=sharing)
- ['Tidak.janin' should be Jumlah janin](https://drive.google.com/file/d/1Fvl9qpwILOufUq7KK2ipVH6gn9DdGLaY/view?usp=sharing)
- ['cairan ketuban' should be Cairan ketuban (C in capital)](https://drive.google.com/file/d/1Fvl9qpwILOufUq7KK2ipVH6gn9DdGLaY/view?usp=sharing)
- ['metode KB diterima' should be 'Metode KB **yang** diterima' (M is in capital letter too)](https://drive.google.com/file/d/1koa-q3BOc1Ic1U6cp1xBAtRngqJzBHm1/view?usp=sharing)
- [Tempat lahir should be Tempat persalinan ](https://drive.google.com/file/d/1koa-q3BOc1Ic1U6cp1xBAtRngqJzBHm1/view?usp=sharing)
- ['Indeks massa tubuh (BMI)' should be Indeks Massa Tubuh (IMT)](https://drive.google.com/file/d/1Axzc7m_wf0oQfiDYL_G57--AXNaPuT7G/view?usp=sharing)
*Please pay attention to capital letters 

Thank you

**Comment by Naima-Bashir** [comment]
Hi @junaidwarsivd 
Kindly find the following translations that need fixing:

SUMMARY PAGE:
1. Jenis edema: Ankle edema (@mergygayatri what should the translation be? See screenshot here)
2. HIV Test: Positive (should be positif). Please note that on the Test Page you have misplelt the word positif to _positf_
3. Hansil tes HIV: Don't know (should be Tidak tahu)
4. Syphilis test: Positive (should be positif)
5. Konseling KB- metode KB diterima [(the word metode should be capital Metode)](https://drive.google.com/file/d/1koa-q3BOc1Ic1U6cp1xBAtRngqJzBHm1/view?usp=sharing)
6.  In the PEMERKSAAN section: the word Ujian should be Pemeriksaan
7.  Hadir pucat: Yes (should be ya)
8. In the KONSELING RENCANA KEHAMILAN section: The word Tempat lahir should be [Tempat Persalinan](https://drive.google.com/file/d/1koa-q3BOc1Ic1U6cp1xBAtRngqJzBHm1/view?usp=sharing)
9.  The next contact dates still shows the dates in English (the months eg 4 June 2023)
10. GA should be [Usia Kehamilan](https://drive.google.com/file/d/1Fvl9qpwILOufUq7KK2ipVH6gn9DdGLaY/view?usp=sharing)
11. EDD should be HPL
12. The dates are reversed on the summary page: One shows 21-04-2023 the other shows 2023-04-24
13. [Tidak janin should be Jumlah janin](https://drive.google.com/file/d/1Fvl9qpwILOufUq7KK2ipVH6gn9DdGLaY/view?usp=sharing)
14. ['cairan ketuban' should be Cairan ketuban (C in capital)](https://drive.google.com/file/d/1Fvl9qpwILOufUq7KK2ipVH6gn9DdGLaY/view?usp=sharing)
15. Done today: Dilakukan hari ini

**Comment by mergygayatri** [comment]
Hi @Naima-Bashir
Ankle edema is Edema pada pergelangan kaki

**Comment by ekigamba** [comment]
@hilpitome Confirm that you can get the site and population characteristics manually using postman on the settings endpoint. 

The response should have each setting with a `description`, `label` and `key` but without a `value`.

**Comment by hilpitome** [comment]
@ekigamba for some wierd reason I am not able to send requests on postman, I am being redirected to the login page. However, the database only has the `site_characteristics` record 
![Screenshot from 2023-06-05 17-12-44](https://github.com/opensrp/opensrp-client-anc/assets/12864384/9f3d2d2d-2847-4e1a-9aa8-e132bc0962d8)

**Comment by ekigamba** [comment]
@hilpitome 
Cool, then kindly upload these using postman. I believe this documentation explains the endpoints https://smartregister.atlassian.net/wiki/spaces/Documentation/pages/1765212165/How+to+interact+with+the+OpenSRP+settings+endpoint .

You should already have these in the app language or English. :disappointed: I have a v1 example of settings that might not serve you

Make sure to make authenticated requests to the WHO ANC server else you will be redirected to the login page. It is always advisable to add data to OpenSRP using the API which runs logic on how to save the data and metadata related to it
