### ISSUE TITLE
[Ona Support Request]: OptiBP recalibration bug

### ISSUE THREAD

**Issue by mergygayatri** [OpenSRP/opensrp-client-anc#935]
### Affected App or Server Version

v1.6.18 App

### What kind of support do you need?

OptiBP is not functioning as expected as written below:

1. Name: Sakmah
- [1th - 6th contact: OptiBP ‘Get started’ was NOT functioning ](https://drive.google.com/file/d/1WWoz1Htbp_nrmwcNyPYuNrDe__dfBUSg/view?usp=sharing)
- [1th visit (video minute 13:21)](https://drive.google.com/file/d/1WWoz1Htbp_nrmwcNyPYuNrDe__dfBUSg/view?usp=sharing)
- [2nd visit (video minute 21:02)](https://drive.google.com/file/d/1WWoz1Htbp_nrmwcNyPYuNrDe__dfBUSg/view?usp=sharing)
- [3rd visit (video minute 26:50)](https://drive.google.com/file/d/1WWoz1Htbp_nrmwcNyPYuNrDe__dfBUSg/view?usp=sharing)
- [4th visit (video minute 31:16)](https://drive.google.com/file/d/1WWoz1Htbp_nrmwcNyPYuNrDe__dfBUSg/view?usp=sharing)
- [5th visit (video minute 38:02)](https://drive.google.com/file/d/1WWoz1Htbp_nrmwcNyPYuNrDe__dfBUSg/view?usp=sharing)
- [6th visit (video minute 42:02)](https://drive.google.com/file/d/1WWoz1Htbp_nrmwcNyPYuNrDe__dfBUSg/view?usp=sharing)
- [7th visit: OptiBP ‘Get started’ was functioning but needed to RECALIBRATION (video minute 48:21)](https://drive.google.com/file/d/1WWoz1Htbp_nrmwcNyPYuNrDe__dfBUSg/view?usp=sharing)
- 8th visit: NO recalibration 

2. Name: Tes Hana Dua
[3rd contact: RECALIBRATION (video from 0:45 to 3:51)](https://drive.google.com/file/d/1Ld12n2XmM4r-CDg6SnBlpKsnJ2IhAaY6/view?usp=sharing )

3. Name: Tes Rara
- [3rd contact: RECALIBRATION (vide from 1:51 to 2:18) ](https://drive.google.com/file/d/1X7MFK9LyV0ibBmwAC88NqbOdyV8IPUVw/view?usp=sharing )
- 2nd, 4th, 5th, 6th, 7th contact: NO recalibration

4. Name: Yuyun Mardiani
- [4th visit, OptiBP ‘Get started’ was NOT functioning (video minute 07:38 - 08:05) ](https://drive.google.com/file/d/1QbFxP9dcy5kzsh2urvbwRecVv5gzRNiJ/view?usp=sharing )
- 3rd and 7th contact: NO recalibration

5. Name: Bidayah
- [2nd visit: OptiBP ‘Get started’ was NOT functioning ](https://drive.google.com/file/d/1Q_KjdXS4fp_B4BBPJW-82uR8EX3qITD-/view?usp=share_link)
- 3rd, 4th, 5th, 6th, 7th, 8th: NO recalibration

6. Tes Tes Hana
2nd - 7th visit: NO recalibration

PS: the pregnant women’s names are fictitious

Thank you

### What is the acceptance criteria for your support request?

- No recalibration in all visits after the 1st visit (calibration is only done in the 1st visit)
- 'Get started' is functioning to use the OptiBP

**Comment by Naima-Bashir** [comment]
Hi @mergygayatri , kindly attach the apk that was used for testing is compatible with the OptiBP App. I have tested on my device (Samung A21s) and it is working. If the Get started button is not functioning, it means that the OptiBP app is not launching on the device

**Comment by Naima-Bashir** [comment]
Hi @mergygayatri can we get access to the app's local database? We want to check if the data has been synched to the server. 
Next step is to initiate the next contact and sync data (do not uninstall the app). Then extract the app local database (drishti.db) and share it with the Ona team. You can consult with the ITIK team (Aria and Levi)

**Comment by Naima-Bashir** [comment]
The GET STARTED button will only work if the midwife ensures that she has selected all the necessary fields in the WHO ANC form. If she skips a field, the GET STARTED button will not work. Please note that this has been removed as a bug as the SID team have confirmed it works once they select all the fields

**Comment by Naima-Bashir** [comment]
How to test the calibration:
steps:

- install ANC and optiBP apks
- open ANC,register a client and start a contact.
- on the Bp measure select OptiBP
- calibrate the measurements (all 4)
- confirm data is sent back to ANC
- finish contact and sync data.
- wait one day and do contact 2.
- confirm on contact 2 (<30 days). only one BP measurement is required by the optBP app (not all 4 steps)

**Comment by Naima-Bashir** [comment]
Hi @mergygayatri can we close this issue?
