### ISSUE TITLE
The Bunda App requests the user to select the Site Characteristics each time they login to the app

### ISSUE THREAD

**Issue by Naima-Bashir** [OpenSRP/opensrp-client-anc#937]
### Affected App or Server Version

Latest Bunda apk

### What kind of support do you need?

We have noted a bug whereby when one logs out of the Bunda App, they are asked to fill in the site characteristics details. 
This is not the case of Ona's WHO ANC App. Once the site characteristics have been filled, even if a user logs out of the app, they should not be asked to fill them again unless they have cleared the app's database and cache. 
You can find more details in the Data Dictionary [here](https://docs.google.com/spreadsheets/d/1Zh38B873ohVCbmO5R1sUn9OF2SMca4vP/edit#gid=2057173193)

### What is the acceptance criteria for your support request?

Once the site characteristics have been filled, even if a user logs out the app and logs in again, they should not be asked to fill them again unless they have cleared the app's database and cache or reinstalled the app. 
Some important classes to look at : [https://github.com/opensrp/opensrp-client-anc/blob/master/opensrp-anc/src/main/jav[…]ister/anc/library/interactor/SiteCharacteristicsInteractor.java](https://github.com/opensrp/opensrp-client-anc/blob/master/opensrp-anc/src/main/java/org/smartregister/anc/library/interactor/SiteCharacteristicsInteractor.java)

and [https://github.com/opensrp/opensrp-client-anc/blob/master/opensrp-anc/src/main/jav[…]tregister/anc/library/interactor/CharacteristicsInteractor.java](https://github.com/opensrp/opensrp-client-anc/blob/master/opensrp-anc/src/main/java/org/smartregister/anc/library/interactor/CharacteristicsInteractor.java)

**Comment by hilpitome** [comment]
The issue could be as a result of the missing template-in folder under assets that has the translated json form that is to be saved to the database cc @Naima-Bashir @SebaMutuku

**Comment by hilpitome** [comment]
This is the PR that should fix the issue https://github.com/sid-indonesia/opensrp-client-anc/pull/26

**Comment by Naima-Bashir** [comment]
This has apssed QA. Below are the test cases I used: 

- A user is asked to fill the site characteristics once they install the app. 
- If they log out and login again, they are not asked to fill the site characteristics.
- When they uninstall and reinstall the app; they are asked to fill in the site characteristics 
- I have noticed some sync issues where the app says Sync Failed however
