### ISSUE TITLE
Implement Previous Contacts from the Contacts tab

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-anc#94]
From the Contacts tab, the user can tap on "Previous Contacts" button to open a new page that shows the summary overview of all previous contacts as well as the schedule of all remaining contacts.

![previous contacts](https://user-images.githubusercontent.com/3488986/44738821-b92dc600-aafe-11e8-82d7-839bacf92b00.png)

- [x] Tapping back button in top left corner or device back button takes user back to the Contacts tab
- [x] All completed contacts are summarized in reverse chronological order in the Completed section.
- [x] Upcoming contacts section shows the schedule of all remaining contacts according to the ANC contact schedule (gest. age at time of contact, due date, and how many days or weeks away), and then EDD is displayed at the bottom with icon.
- [x] Please note there is an 18 weeks Contact 3 and an 18 weeks Hospital Referral in the mockup. This is intentional, as it's meant to display how the summary is displayed for a contact visit that ended in an immediate referral - i.e. danger sign selected in Quick Check and then user chose to "Refer and close contact". If this happens, it doesn't count as an official contact, hence the reason it's shown as just the gest. age, date, and hospital referral without a contact number. Not pictured in the mockups, but please add the "Treatment given before referral" and "Yes" or "No" {danger_signs_treat} from the quick check tab.

**CG: Removing from this last phase of work.**
~~- [ ] Tapping on any contact summary block opens a new page~~
~~- [x] Back button takes user back to Previous Contacts page above.~~
~~- [x] {gest_age} weeks · Contact {contact #} in top page header~~
~~- [ ] Provider name is where we show the first name last name of the provider who was logged in and recorded the contact visit when it was originally done.~~
~~- [ ] Date is the date of the contact.~~
~~- [ ] All of the contact containers are listed in that order~~
~~- [ ] The user can tap into any of these contact containers to view the information submitted in that contact and ability to make edits. See https://github.com/OpenSRP/opensrp-client-anc/issues/51 for what the contact containers would look like when you are reviewing them in this context.~~

**Comment by cagulas** [comment]
18 April release:

Looking good so far!

- [ ] Don't capitalize Weeks in the screenshot below
- [ ] We need to shift the Expected date of delivery text over, as it's getting cut off
- [ ] Remove the extra space between 02 and the comma in the screenshot below
- [ ] Font colors are off for the upcoming contacts.

@rowo Can you specify the color codes for that last point?

![Screenshot_20190419-125203](https://user-images.githubusercontent.com/3488986/56419299-6b8ae700-62a2-11e9-948b-647354097ce8.png)

**Comment by rowo** [comment]
- Is it easy to make the title of the view change to "Upcoming contacts" when you scroll to that section?
- Text color for upcoming contacts is fine as is

**Comment by dubdabasoduba** [comment]
@rowo Yes it can be done. Unfortunately it won't be part of this release as it requires some effort to display alter the toolbar.

**Comment by dubdabasoduba** [comment]
The this has been added but we still having and issue with the contacts arrangement as the referral contacts come first.
