### ISSUE TITLE
Re add the English files to the Bunda App 

### ISSUE THREAD

**Issue by Naima-Bashir** [OpenSRP/opensrp-client-anc#944]
### Affected App or Server Version

Latest apk

### What kind of support do you need?

When one switches the app to English, it still shows most of the files in Bahasa such as the registration form. 

This is what we have found from our investigations: 
From the code we received from ITIK, it seems like  the English files have been removed from the Bunda App. There are some missing English translation files from the ITIK source code; they were removed and replaced with the Bahasa files. This means that the app's main language is Bahasa. The app's default language is Bahasa as it cannot find some English files. I hope this clarifies it  

Our proposition is to read the English files to the Bunda App

### What is the acceptance criteria for your support request?

Re add the English files to the Bunda App so that the app can be switched from Bahasa to English and vice versa

**Comment by hilpitome** [comment]
There were missing translations in both English and Indonesia. This was done in this [commit](https://github.com/sid-indonesia/opensrp-client-anc/pull/30/commits/7fc4b236d8f85f7d958027550be39981f690fc29)

**Comment by Naima-Bashir** [comment]
There are some untranslated Bahasa strings when one switches from Bahasa to English
![image](https://github.com/opensrp/opensrp-client-anc/assets/61143692/46c37898-65a9-4580-8860-dbbbf7e07c32)

**Comment by Naima-Bashir** [comment]
Some untranslated files can be found in the following sections: (all images can be found [here](https://drive.google.com/drive/folders/1vHk1TcSmjo3B35dnmBdRtMwhlLmRpMZf?usp=sharing))
1. Physical Exam section
2. Summary section
3. Contact summary section
