### ISSUE TITLE
When one selects the negative on certain tests, they show up as positive on the Summary Page

### ISSUE THREAD

**Issue by Naima-Bashir** [OpenSRP/opensrp-client-anc#948]
### Affected App or Server Version

Latest apk

### What kind of support do you need?

Login to the Bunda App
Start a contact
In the Profile page, make the following selection:

1. Select negative on HIV Status
2. Select all the vaccinations as done such as Covid 19 and Tetenus
3. In the risk and violence section, select not at risk 
4. Select 1 cup of coffee as the caffeine intake
5. Click finalize contact once you complete the rest of the sections.
6. Observe the summary page

BUG: 

1. Risk of HIV notification appears even though the woman is not at risk. 
2. Tetanus toxoid 1 is asked in the counseling page, while the woman has completed all the vaccination
3. Risk of violence appears even though the woman is not at risk
4. Counseling on caffeine and alcohol appears although the woman doesnt consume them

### What is the acceptance criteria for your support request?

The logic of the app should work as expected e.g if the caffeine intake is less than one, then it should not show up as reduce caffein intake in the Couselling section.
See Data Dictionary [here](https://docs.google.com/spreadsheets/d/1Zh38B873ohVCbmO5R1sUn9OF2SMca4vP/edit#gid=451767701) for more information

**Comment by Naima-Bashir** [comment]
In the Site Charateristics section; if one selects Yes on Gender Based Violence; even if the selections on the profile are no; the Bunda App will advise the user of the GBV risk. 
This is the same for HIV selections in the Site Characteristics. From the Data Dictionary here; you can see that HIV Risk Counselling is triggered when one selects one of the following:

1. Mother is HIV positive OR
2. Partner is HIV positive OR 
3. Site Characteristics -- If the woman lives in a setting with a generalized HIV epidemic

cc @AngelaKabari @hamza-vd 

https://docs.google.com/spreadsheets/d/1Zh38B873ohVCbmO5R1sUn9OF2SMca4vP/edit#gid=1562301016

**Comment by mergygayatri** [comment]
Hi @AngelaKabari please fix the issues as written below:
1. Counseling page: [IPTp-SP 1 and malaria counseling, where the mother is not suspected to have these conditions](https://drive.google.com/file/d/1rXcjPH_VTVE6IRhixN-Xs7LdAyVZHeHl/view?usp=sharing).
2. Symptoms and follow-up page: There is a question: _"adakah gejala lain yang berhubungan dengan nyeri punggung bawah dan panggul?"_, while the mother doesn't have this symptom. Translation for the question: "_Are there any other symptoms associated with low back and pelvic pain?_"
Thank you

**Comment by AngelaKabari** [comment]
Thanks for sharing these @mergygayatri. @junaidwarsivd will look into this today.

**Comment by Naima-Bashir** [comment]
This was a native forms related issue. 
Hamza has removed the multi threading that was causing the Behavior and Counselling to be skipped. E.g if one had selected Yes for Tobacco smoking, the behavior and counselling section should show that smoking should be quit.

**Comment by Naima-Bashir** [comment]
@hamza-vd 
Missing questions
Profile page
1. Pekerjaan ibu hamil (occupation)
2. Adakah masalah pada kehamilan sebelumnya (health problems in the previous pregnancy)
3. Ada alergi (allergy)
4. Pengobatan saat ini (current medication)
5. Asupan kafein (Caffeine intake)
6. Konsumsi alkohol atau obat-obatan terlarang? (alcohol and drugs use)
