### ISSUE TITLE
[Ona Support Request]: App keeps logging out 

### ISSUE THREAD

**Issue by mergygayatri** [OpenSRP/opensrp-client-anc#950]
### Affected App or Server Version

v1.6.29

### What kind of support do you need?

Hi ONA team,
We need you to fix the issue: the app forces to log out after clicking certain buttons:
1.  After clicking 'save'. [See the video minute 57:21](https://drive.google.com/file/d/11UIOZjV-qNyezy5L9ZzUBoofRmIXwhd7/view?usp=sharing)
2. After clicking the physical exam form. [See the video minute 1:12:23](https://drive.google.com/file/d/11UIOZjV-qNyezy5L9ZzUBoofRmIXwhd7/view?usp=sharing)

### What is the acceptance criteria for your support request?

The app does not log out

**Comment by Naima-Bashir** [comment]
The SID team have reported that this issue isn't occurring on apk version 1.6.30
We will put this in the parking lot and pick this up if it occurs again. 

@junaidwarsivd kindly confirm how long it takes to log a user out normally.

**Comment by Naima-Bashir** [comment]
Hi @junaidwarsivd I am reopening this issue as the app has logged a user while filling in GA using ultrasound in the 3rd contact. 
This happened around 1 hour ago. Kindly check Crashlytics.

**Comment by Naima-Bashir** [comment]
Video can be found [here](https://drive.google.com/file/d/12TckoKqiKNQjaHSd1EkCReOEwRaGons4/view?usp=sharing) @junaidwarsivd

**Comment by junaidwarsivd** [comment]
hi @Naima-Bashir  this is noted here i am working on it thanks

**Comment by junaidwarsivd** [comment]
update: this issue is replicated it occurs when the device language and app language is on bahasa currently working on it to add a fix @Naima-Bashir

**Comment by Naima-Bashir** [comment]
Most recent video of the bug can be found [here](https://drive.google.com/file/d/14i-3rkOYljXbWdmKOsQh5I758lnQMfbG/view?usp=drivesdk) cc @junaidwarsivd

**Comment by Naima-Bashir** [comment]
This has passed QA. Closing it for now.

**Comment by AngelaKabari** [comment]
Update on bugs found in [indonesia-reference-app-v1.6.38.apk](https://drive.google.com/file/d/1sQ6avfuL55Fndk6PIUoROVszeQQE5iya/view?usp=drive_link) from Mergy on Friday 21st July: 
<img width="876" alt="Screenshot 2023-07-25 at 13 32 30" src="https://github.com/opensrp/opensrp-client-anc/assets/8417097/a011643f-64ca-4a81-82a7-5807f11c6d21">

**Comment by AngelaKabari** [comment]
Update on bugs found in the [latest apk (indonesia-reference-app-v1.6.39)](https://drive.google.com/file/d/19fhnl6940HPP1OFVGCRg1Sy89TKVe7BQ/view?usp=drive_link) from Mergy on Wednesday 26th July: 

> Logout in the physical exam page using [Samsung A03](https://drive.google.com/file/d/1DgZyL4xmuyYre-4_mRl4GTUr3fIil2IU/view?usp=sharing) and [Samsung S21](https://drive.google.com/file/d/1DYQAWxMFdziIIYJIby5nfLt-FmtE6cdR/view?usp=sharing)

<img width="1058" alt="Screenshot 2023-07-26 at 13 46 18" src="https://github.com/opensrp/opensrp-client-anc/assets/8417097/fdb3d883-644e-410a-8b01-f005e76500a0">
