### ISSUE TITLE
[Ona Support Request]: OptiBP start button is not working 

### ISSUE THREAD

**Issue by mergygayatri** [OpenSRP/opensrp-client-anc#952]
### Affected App or Server Version

v1.6.30

### What kind of support do you need?

We need the OptiBP start button to work. 
I and Naima found a similar issue a few months ago, we should fill in all the previous fields to be able to use the start button. However, today I and my team found that the OptiBP start button is not working even though we have filled in all the fields 
Please see [the video ](https://drive.google.com/file/d/116tpN8g3JcwO5wwO6DcVZ4edoapNM612/view?usp=sharing) minute 1:06:32 to 01:08:00. 
Deadline: July 4, 2023

### What is the acceptance criteria for your support request?

The OptiBP start button works

**Comment by frappereau** [comment]
From your video, we can see that OptiBP does not start. This will happen if the data passed by the Bunda app to OptiBP does not meet our expected format. ([ANC < > OptiBP diagnostic report](https://github.com/opensrp/opensrp-client-anc/issues/601#issuecomment-1165618068)).

How could we get a copy of the data passed to OptiBP when this happens?

**Comment by Naima-Bashir** [comment]
Feedback from QA (Mergy)

1. Samsung S21, Android version 12: Crash while measuring the second calibration step using OptiBP, and the App keeps logging out while clicking finalize
2. Samsung A03, Android version 12 (My android): sync failed but then succeeded (but the screen keeps blinking). I could use the OptiBP but the diastolic value is 24, and I can finalize successfully.

**Comment by Naima-Bashir** [comment]
QA Feedback (Naima)
The OptiBP app keeps crashing during the calibration
![Screenshot_20230712-103145](https://github.com/opensrp/opensrp-client-anc/assets/61143692/bda4f512-ab55-4d3b-9d69-1a9a453ca5e6)

**Comment by frappereau** [comment]
@mergygayatri @Naima-Bashir We need access to the Google Firebase Project & Crashlytics to investigate and debug the issues since.

@Naima-Bashir We need to find a way to get a copy of the data that the Bunda app send OptiBP app, so we can further assist with debugging the issue of the start button.

**Comment by Naima-Bashir** [comment]
Hi @hilpitome The video can be found here https://drive.google.com/file/d/15_N6NMwfhwAtczL_QX-qzBdLfSJ3h7QP/view
From minute 1.59. The user has selected all the prerequisites and the optibp start button is still not working.
