### ISSUE TITLE
Implement Tasks tab in the woman's profile page

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-anc#96]
The Tasks tab in the woman's profile page lists all of the "ordered" and "not done" tasks from the woman's previous contact visits. For e.g. if an HIV test was due in Contact 2, but the user recorded that the HIV test was "ordered" or "not done" in that contact visit, the HIV test gets added to the task list here.

<img width="396" alt="screen shot 2018-08-28 at 9 12 57 pm" src="https://user-images.githubusercontent.com/3488986/44741894-2c3b3a80-ab07-11e8-9bd2-6f18b635e586.png">

- [x] The total number of tasks in the task list is displayed as a red flag next to the Tasks tab name (see red flag with number 4 in the mockup above).
- [x] Tasks are split into two sections - `Tests` and `Counselling & Treatment`
- [x] All tests from the Tests contact container that are due in a contact and the health worker marks them as "ordered" or "not done" would get added to the task list. A test only gets added to the task list if it was due at the time of the contact visit.
- [ ] All counselling and treatments in the C&T tab that are marked as "not done" would show up here in the task list. 
- [x] See the Tasks tab in the data dictionary for a complete list of possible Tasks.
- [x] For tasks that are marked as "Not done" in the contact visit, they show up here as the white circle icon next to it
- [x] For tasks that are marked as "Ordered" in the contact visit, they show up here as the yellow timer icon
- [x] To mark these tasks as complete (no matter if it's a "not done" or "ordered" status), the user taps on the task in the list, which opens a dialog for them to record the test or counseling and treatment done. Refer to https://github.com/OpenSRP/opensrp-client-anc/issues/54 for the test result flows. Refer to https://github.com/OpenSRP/opensrp-client-anc/issues/75 for flows for counseling and treatment.

**Comment by cafootitt** [comment]
QA results, V1.2.11:

- Can we re-order test tasks in the same order you find them in the Tests contact container?
- Once you record one is done, the number of tasks does not tick down by one.
- When do the done tasks disappear from the Tasks list? After how much time?
- Can we not display the UNDO/RECORD buttons and also not display the original not done/ordered inputs from the contact? I.e. display the blank expansion panel widget just like you'd see in the Tests container before you open the expansion panel and enter data. 
- None of the C&T tasks are showing

**Comment by dubdabasoduba** [comment]
@cafootitt Do we need to show the filled content when the user updates the task? This screenshot shows an example of this scenario
![device-2020-02-04-172119](https://user-images.githubusercontent.com/4817531/73752899-caa6e300-4772-11ea-8bb2-c77dccb5d3be.png)

**Comment by dubdabasoduba** [comment]
We might need to discuss this **_None of the C&T tasks are showing_**  a bit before I start working on it.

**Comment by cafootitt** [comment]
@dubdabasoduba Looks great! Yes, we want to show the input after it's filled out.

**Comment by cafootitt** [comment]
@dubdabasoduba Looking good, just one more thing below, but let me know if this is resolved if you wait 24 hours or something for the tasks to save. I wasn't able to forward my device date/time (#459), so I wasn't able to test submitting a new contact in future.

**Comment by dubdabasoduba** [comment]
The above feature request might have performance implications on the the loading of the tests container.  I will work on it starting tomorrow then we can test the performance impact it will have and figure out the way forward on the same.

**Comment by dubdabasoduba** [comment]
@cafootitt What do you mean by tasks saving?

**Comment by dubdabasoduba** [comment]
@cafootitt for the above request. Incase all the tests in the due tests step are not show do we skip and just display the `other` step?

**Comment by cafootitt** [comment]
@dubdabasoduba Let's check in with @rowo on this one.

My concern if they skip the Due tab because it's blank and land on the Other tests tab, they might think that all of the optional tests listed there are due, which we don't want.

In future it might be nice to show the Due tests tab, but have a little icon that shows no tests are due at the moment of something like that. But in the meantime, I don't know if it would be best to show the blank page.

What do you think, Roger?

**Comment by dubdabasoduba** [comment]
@cafootitt Awesome.  When removing the tests do we remove all even if they where marked `ordered` or `not done` on the tasks?

**Comment by cafootitt** [comment]
@dubdabasoduba Thanks for clarifying. I think only if they're marked as "done" would they not show. If they're still pending, i.e. ordered, or still not done at the time the contact is starting, then they'd show up there.

**Comment by rowo** [comment]
I'm not exactly sure where you guys are talking about now, but theoretically an empty state message on the Due tab seems reasonable.

**Comment by cafootitt** [comment]
QA V1.2.13.

Due to the issue where I cannot fast forward the date/time, I won't be able to complete QA on this until tomorrow when the contact visit button resets.

**Comment by cafootitt** [comment]
Closing this issue, as it largely passes QA.

Creating new issues for remaining anomalies:
https://github.com/OpenSRP/opensrp-client-anc/issues/476
https://github.com/OpenSRP/opensrp-client-anc/issues/477
