### ISSUE TITLE
[Ona Support Request]: fix issues on losing data in the BUNDA App

### ISSUE THREAD

**Issue by mergygayatri** [OpenSRP/opensrp-client-anc#962]
### Affected App or Server Version

v1.6.36

### What kind of support do you need?

Please fix the issue of losing data after logging out. 
Kindly find the video [here](https://drive.google.com/file/d/17Qi2a1oNsaFSFs2EoGvv-NUBMUhDrx80/view?usp=sharing). 
In this video, you can see:
1. the  first sync was complete after creating mother 1 (minute 4:48)
2. the second sync was complete too after creating mother 2 (minute 9:23)
3. minute 9:47, we cleared data because we experienced losing data after clearing data before logging in using a different username. In this video, we used the same username, just to make sure we experienced the same as we did using a different username.
4. after logging in, we did sync again and it was complete in the minute 12:13, but the data on two mothers we've just created did not appear. 

### What is the acceptance criteria for your support request?

The data are not lost after syncing even though we log out the app or clear the data

**Comment by SebaMutuku** [comment]
Should be fixed by https://github.com/opensrp/opensrp-client-anc/issues/961. cc @AngelaKabari @Naima-Bashir

**Comment by AngelaKabari** [comment]
The resolution of #945 also has contributed to this fix.

@mergygayatri please confirm that this has been satisfactorily resolved and then close the issue?
