### ISSUE TITLE
Sync by location: Allow users from parent locations to see patients created by child locations

### ISSUE THREAD

**Issue by AngelaKabari** [OpenSRP/opensrp-client-anc#963]
### Affected App or Server Version

Latest apk (indonesia-reference-app-v1.6.38.apk) + OpenSRP Web v2.3.5

### What kind of support do you need?

SID require that users from parent locations can see patients created by users from child locations.
 
Users are assigned to teams and those teams are assigned to locations. When a user creates/updates patient info, then that patient data and info from subsequent contacts are tagged to the location, instead of the team, which is how OpenSRP usually works.

For example, SID have a 2 main levels that come into contact with patients:
- **_Puskesmas_** which is the Community Health Centre level and can be considered the parent location.
- **_Desa_** which is the village level and can be considered the child location.
The Midwives (a.k.a **_Bidans_**) are assigned to a Desa that falls under a Puskesmas.

At the moment, when you look at the location assignment of the team members in Desa Melati and Desa Mawar on the app then they show Puskesmas Bunga and Lombok Barat but not the respective Desas. See below screenshots:
![Bidan Desa Mawar location assigment](https://github.com/opensrp/opensrp-client-anc/assets/8417097/99645646-0b14-49b6-919d-e4829dcc29d0)

![Bidan Desa Melati location assigment](https://github.com/opensrp/opensrp-client-anc/assets/8417097/874b22eb-091c-4080-9abd-c71fe55a269b)

Levi from SID looked at the data on the server and confirmed that at the moment:
- Desa Melati and Desa Mawar are child locations of the parent Puskesmas bunga location.
- Bidan Desa Melati and Bidan Desa Mawar are assigned to the teams Desa Melati, and Desa Mawar respectively.
- The team Desa Melati is assigned to the location Desa Melati, but and Team Desa Mawar are assigned to 2 locations Puskesmas Bunga and Desa Mawar.
- The patients created by Bidan Melati and Bidan Desa Mawar are assigned to locations Desa Melati, and Desa Mawar respectively.

The current issue is manifesting in multiple ways:
1. When we try to remove the Puskesmas Bunga location from Team Desa Mawar, we run into the below 400 error. 
<img width="1551" alt="Team Assignment Error" src="https://github.com/opensrp/opensrp-client-anc/assets/8417097/33a00048-155c-40f4-b8cd-197a4b129e9d">

Find the error stactrace details here: [400 error openSRP website.pdf](https://github.com/opensrp/opensrp-client-anc/files/12160512/400.error.openSRP.website.pdf)

2. The Bidan from Puskesmas Bunga (Bidan Puskesmas Kenanga) (parent location) still cannot see the 2 Desa Mawar patients and 5 Desa Melati patients (child locations) which is what they should be able to see. See below screenshots for Melati and Mawar patient names that you can use to check this:
![Melati Patients](https://github.com/opensrp/opensrp-client-anc/assets/8417097/ab650be1-1c78-4272-9e8e-9fbb26b8208a)

![Mawar Patients](https://github.com/opensrp/opensrp-client-anc/assets/8417097/3c9d3460-368f-4e96-81f9-26b935e9631b)

### What is the acceptance criteria for your support request?

If the sync by location works correctly, then the Bidans in the Puskesmas (parent location) should be able to see patients from multiple Desas (child locations), but the Bidans in a Desa should not be able to see patient data from other Desas. E.g. team members in Puskesmas Bunga should see the patients added by the team members assigned to Desa Melati and Desa Mawar but Bidans in Desa Melati should not be able to see patients in Desa Mawar and vice versa.

### Relevant Information

Nothing further

**Comment by hamza-vd** [comment]
@AngelaKabari cc: @hilpitome 
I'll fix this issue on the client side to sync all the events under the selected facility location. (fetch all the events for child locations under the selected facility location)

**Comment by hilpitome** [comment]
I can confirm that syncing with comma seperated location ids can be used to fetch events and clients for the current location and its children. The sync endpoint works with the following format when we have 3 locations for example, `rest/event/sync?locationId=<uuid1>,<uuid2>, <uuid3>&serverVersion=0&limit=250` cc @AngelaKabari @hamza-vd
