### ISSUE TITLE
The Risks and Diagnoses section in the summary page shows RED Indicators where there are no risks

### ISSUE THREAD

**Issue by Naima-Bashir** [OpenSRP/opensrp-client-anc#967]
### Affected App or Server Version

Latest apk

### What kind of support do you need?

When one selects No in certain sections such as alcohol and tobacco usage,the Risks and Diagnoses section in the summary page shows RED Indicators.

STEPS:
1. Create a new patient 
2. In the Profile page, in the Woman's Behavior section, select No on the Daily Caffeine Intake and No on the tobacco products
3. Finalize the rest of the contact and observe the summary page

 **EXPECTATION:**
The risks and Diagnoses section should not show red unless there is a risk. See [Data Dictionary](https://docs.google.com/spreadsheets/d/1Zh38B873ohVCbmO5R1sUn9OF2SMca4vP/edit#gid=451767701) .
**ACTUAL RESULTS**
Sometimes the risks and diagnoses section shows red. See screenshot below
![image](https://github.com/opensrp/opensrp-client-anc/assets/61143692/a5595086-2938-4f92-918c-25e26820ba08)

### What is the acceptance criteria for your support request?

The risks and Diagnoses section should not show red unless there is a risk. See [Data Dictionary](https://docs.google.com/spreadsheets/d/1Zh38B873ohVCbmO5R1sUn9OF2SMca4vP/edit#gid=451767701) .

**Comment by hilpitome** [comment]
Tasks

- [x] Reproduce the issue
- [ ] Check usage of `isRedFont` property in the yml file in question.
- [ ] Fix

**Comment by hilpitome** [comment]
@Naima-Bashir I was not able to reproduce this on v1.6.48. This is what I got when I filled out  the contact as instructed. The title is `Woman's Behavior `and not `Risks and Diagnosis.`
![Screenshot_2023-09-26-11-45-04-324_org smartregister anc (1)](https://github.com/opensrp/opensrp-client-anc/assets/12864384/4ad414b5-655e-4726-af7e-fcd7f6d06905)

**Comment by Naima-Bashir** [comment]
Hi @hilpitome try a new contact and saying yes to all the risky behaviors. E.g select yes on alcohol use. Then observe if the summary page is loading the selections in red.

**Comment by hilpitome** [comment]
@Naima-Bashir  when I said I could not replicate the issue, I was looking at the contact preview and not the client summary/overview page. I can confirm that this issue exists when you submit a contact and go to the client summary page. Looking into why this is the case.

**Comment by Naima-Bashir** [comment]
The word Tidak Ada: Don't know is shown as red still. See image below:
![Screenshot_20230928-113100_BUNDA](https://github.com/opensrp/opensrp-client-anc/assets/61143692/56ed4ba9-8734-4b88-95d7-1a57dbc4117b)
