### ISSUE TITLE
Next contact date to fall in week days

### ISSUE THREAD

**Issue by dodosi** [OpenSRP/opensrp-client-anc#995]
### Affected App or Server Version

v1.6.14

### What kind of support do you need?

When the next contact date is automatically calculated, sometimes it falls on the weekend, We would like to push the days on the weekend to weekdays in such situations.

In some situations where Next contact date is entered manually, app should also restrict weekends to be the next visit dates.

### What is the acceptance criteria for your support request?

No next visit dates should fall in weekends.

**Comment by murayakarina** [comment]
@dodosi 
After entering a weekend date on the next contact date field manually  the date is pushed to a weekday as requested i.e no next visit dates fall on a weekend.
NB: The next visit date that is displayed on the profile overview does not match  the one displayed on the list of all contact dates. 

This is the profile overview page.
![Screenshot from 2024-04-16 10-54-10](https://github.com/opensrp/opensrp-client-anc/assets/73172427/4f6e77d6-9986-4dc1-9855-c2400be3f17b)

**Comment by hilpitome** [comment]
@dodosi which page do you use to see if the next contact page is falling
 on a weekend. is it the overview page below? cc @Naima-Bashir 
![Screenshot from 2024-04-15 10-25-15](https://github.com/opensrp/opensrp-client-anc/assets/12864384/8539450d-8a14-4387-ae07-0808f3ba085f)

**Comment by dodosi** [comment]
@Naima-Bashir 
It is that. As dates are calculated automatically by the application.

**Comment by Naima-Bashir** [comment]
From today's call with 1000 Hills, here are the updates regarding the different dates shown:
The date shown on the Profile Overview Page was creating for the sole purpose of the prepopulation exercise. It was to aid in recording many contact visits in a short time. It is therefore temporary and will be removed by 1000 team now that the pre population exercise is complete. cc @hilpitome @karina4050

**Comment by Naima-Bashir** [comment]
Hi @dodosi Kindly let us know if you have reviewed this ticket so that we can close it. Thank you
