### ISSUE TITLE
Date of contact to be entered manually instead of considering the today's date

### ISSUE THREAD

**Issue by dodosi** [OpenSRP/opensrp-client-anc#996]
### Affected App or Server Version

v1.6.14

### What kind of support do you need?

In some situations, there is a need to enter the contact date manually and the dates fall in previous dates. Some documentation guides us to change the device's dates which is somehow tiresome to some groups of users.

So we would like to consider that manually entered date as date of contact instead of considering today's date OR changing device's dates.

### What is the acceptance criteria for your support request?

The contact date should be the one entered by the user. and the next contact date should be on it.

**Comment by Naima-Bashir** [comment]
I'll be closing this ticket as we have this other similar ticket open. https://github.com/opensrp/opensrp-client-anc/issues/997
